cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Abstract Blackwork")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Abstract Blackwork Style Brushstroke','Abstract Blackwork Style Negative Space','Abstract Blackwork Style Fluid and Flow','Abstract Blackwork Style Fragmented','Abstract Blackwork Style Bold Shapes','Abstract Blackwork Style Smudge and Texture','Abstract Blackwork Style Figures','Abstract Blackwork Style Wraps and Bands','Abstract Blackwork Style Small','Abstract Blackwork Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Bold black brushstroke swoosh'] = 'The tattoo: bold black brushstroke swoosh. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Brushstroke circle'] = 'The tattoo: brushstroke circle. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Dry brush slash across the arm'] = 'The tattoo: dry brush slash across the arm. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Brushstroke crescent'] = 'The tattoo: brushstroke crescent. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Layered brushstroke waves'] = 'The tattoo: layered brushstroke waves. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Ink brush spiral'] = 'The tattoo: ink brush spiral. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Brushstroke triangle'] = 'The tattoo: brushstroke triangle. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Thick brush band with splatter'] = 'The tattoo: thick brush band with splatter. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Brushstroke wing shape'] = 'The tattoo: brushstroke wing shape. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Calligraphy style brush sweep'] = 'The tattoo: calligraphy style brush sweep. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Wolf face in negative space'] = 'The tattoo: wolf face in negative space. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Moon cut out of solid black'] = 'The tattoo: moon cut out of solid black. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Mountain range in negative space'] = 'The tattoo: mountain range in negative space. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Snake in negative space'] = 'The tattoo: snake in negative space. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Hand silhouette in negative space'] = 'The tattoo: hand silhouette in negative space. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bird flying through solid black'] = 'The tattoo: bird flying through solid black. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Eye cut out of a black shape'] = 'The tattoo: eye cut out of a black shape. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Moth in negative space'] = 'The tattoo: moth in negative space. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Lightning cut through black'] = 'The tattoo: lightning cut through black. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Face profile in negative space'] = 'The tattoo: face profile in negative space. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Flowing black ink ribbons'] = 'The tattoo: flowing black ink ribbons. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black liquid drip shapes'] = 'The tattoo: black liquid drip shapes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Swirling smoke in solid black'] = 'The tattoo: swirling smoke in solid black. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Melting black shapes'] = 'The tattoo: melting black shapes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black wave flowing around the arm'] = 'The tattoo: black wave flowing around the arm. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Ink cloud bursting'] = 'The tattoo: ink cloud bursting. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Black tendrils reaching'] = 'The tattoo: black tendrils reaching. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Liquid black spiral'] = 'The tattoo: liquid black spiral. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pooling black ink'] = 'The tattoo: pooling black ink. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Flowing black flames'] = 'The tattoo: flowing black flames. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Shattered black shapes'] = 'The tattoo: shattered black shapes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Black shard explosion'] = 'The tattoo: black shard explosion. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Broken black circle'] = 'The tattoo: broken black circle. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Fragmented face in black blocks'] = 'The tattoo: fragmented face in black blocks. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Cracked black panel'] = 'The tattoo: cracked black panel. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black shapes scattering into pieces'] = 'The tattoo: black shapes scattering into pieces. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glitched black block pattern'] = 'The tattoo: glitched black block pattern. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Torn black strip'] = 'The tattoo: torn black strip. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black puzzle pieces drifting'] = 'The tattoo: black puzzle pieces drifting. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Fractured black diamond'] = 'The tattoo: fractured black diamond. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Overlapping black circles'] = 'The tattoo: overlapping black circles. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Solid black crescent and dot'] = 'The tattoo: solid black crescent and dot. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black blocks stacked off-balance'] = 'The tattoo: black blocks stacked off-balance. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black arch shapes'] = 'The tattoo: black arch shapes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Bold black stripes of different widths'] = 'The tattoo: bold black stripes of different widths. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Solid black sun shape'] = 'The tattoo: solid black sun shape. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black half circles'] = 'The tattoo: black half circles. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Large black dot cluster'] = 'The tattoo: large black dot cluster. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black rectangles in rhythm'] = 'The tattoo: black rectangles in rhythm. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black orb with a ring'] = 'The tattoo: black orb with a ring. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Charcoal smudge with a fine line'] = 'The tattoo: charcoal smudge with a fine line. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black smear with scratches'] = 'The tattoo: black smear with scratches. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Textured black blot'] = 'The tattoo: textured black blot. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black ink splatter burst'] = 'The tattoo: black ink splatter burst. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Dry brush texture patch'] = 'The tattoo: dry brush texture patch. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Rough black stain with dots'] = 'The tattoo: rough black stain with dots. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black scribble cloud'] = 'The tattoo: black scribble cloud. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black ink bleed shape'] = 'The tattoo: black ink bleed shape. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Grainy black gradient patch'] = 'The tattoo: grainy black gradient patch. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black fingerprint smudge'] = 'The tattoo: black fingerprint smudge. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Abstract human figure in black strokes'] = 'The tattoo: abstract human figure in black strokes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Abstract dancer in black'] = 'The tattoo: abstract dancer in black. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Abstract face in bold black lines'] = 'The tattoo: abstract face in bold black lines. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Abstract eye in black shapes'] = 'The tattoo: abstract eye in black shapes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Abstract hands reaching'] = 'The tattoo: abstract hands reaching. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Abstract woman profile in black'] = 'The tattoo: abstract woman profile in black. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Abstract horse in brushstrokes'] = 'The tattoo: abstract horse in brushstrokes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Abstract bird in black shapes'] = 'The tattoo: abstract bird in black shapes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Abstract skull in bold strokes'] = 'The tattoo: abstract skull in bold strokes. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Abstract heart in black'] = 'The tattoo: abstract heart in black. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Black brushstroke armband'] = 'The tattoo: black brushstroke armband. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Solid black band with a cut out wave'] = 'The tattoo: solid black band with a cut out wave. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black ribbon wrapping the forearm'] = 'The tattoo: black ribbon wrapping the forearm. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Abstract black cuff'] = 'The tattoo: abstract black cuff. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black stripe ankle band'] = 'The tattoo: black stripe ankle band. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Broken black band'] = 'The tattoo: broken black band. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black ink ring around the calf'] = 'The tattoo: black ink ring around the calf. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black spiral wrap'] = 'The tattoo: black spiral wrap. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black drip band'] = 'The tattoo: black drip band. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Black zigzag wrap'] = 'The tattoo: black zigzag wrap. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny black brush dot'] = 'The tattoo: tiny black brush dot. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small black crescent'] = 'The tattoo: small black crescent. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny black splash'] = 'The tattoo: tiny black splash. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small black triangle'] = 'The tattoo: small black triangle. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny black smudge'] = 'The tattoo: tiny black smudge. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small black circle'] = 'The tattoo: small black circle. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny black slash'] = 'The tattoo: tiny black slash. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small black drip'] = 'The tattoo: small black drip. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny negative space star'] = 'The tattoo: tiny negative space star. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small black wave'] = 'The tattoo: small black wave. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Abstract blackwork full sleeve'] = 'The tattoo: abstract blackwork full sleeve. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Abstract brushstroke back piece'] = 'The tattoo: abstract brushstroke back piece. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is across his back, shirtless, seen from behind'
$b['Abstract negative space leg sleeve'] = 'The tattoo: abstract negative space leg sleeve. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['Abstract black flow thigh piece'] = 'The tattoo: abstract black flow thigh piece. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Abstract shards forearm piece'] = 'The tattoo: abstract shards forearm piece. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Abstract black smoke shoulder piece'] = 'The tattoo: abstract black smoke shoulder piece. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Abstract black chest piece'] = 'The tattoo: abstract black chest piece. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Abstract black spine piece'] = 'The tattoo: abstract black spine piece. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is down his spine, shirtless, seen from behind'
$b['Abstract black calf piece'] = 'The tattoo: abstract black calf piece. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Abstract black half sleeve'] = 'The tattoo: abstract black half sleeve. Abstract blackwork tattoo, bold solid black ink only, expressive shapes, brushstrokes, smudges and splatter, strong use of negative space where bare skin forms part of the design, modern art feel, designed like work from a top modern tattoo artist, no colour, no letters, no words, no brand names, no logos. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$sets = [ordered]@{}
$sets['Abstract Blackwork Style Brushstroke'] = @('Bold black brushstroke swoosh','Brushstroke circle','Dry brush slash across the arm','Brushstroke crescent','Layered brushstroke waves','Ink brush spiral','Brushstroke triangle','Thick brush band with splatter','Brushstroke wing shape','Calligraphy style brush sweep')
$sets['Abstract Blackwork Style Negative Space'] = @('Wolf face in negative space','Moon cut out of solid black','Mountain range in negative space','Snake in negative space','Hand silhouette in negative space','Bird flying through solid black','Eye cut out of a black shape','Moth in negative space','Lightning cut through black','Face profile in negative space')
$sets['Abstract Blackwork Style Fluid and Flow'] = @('Flowing black ink ribbons','Black liquid drip shapes','Swirling smoke in solid black','Melting black shapes','Black wave flowing around the arm','Ink cloud bursting','Black tendrils reaching','Liquid black spiral','Pooling black ink','Flowing black flames')
$sets['Abstract Blackwork Style Fragmented'] = @('Shattered black shapes','Black shard explosion','Broken black circle','Fragmented face in black blocks','Cracked black panel','Black shapes scattering into pieces','Glitched black block pattern','Torn black strip','Black puzzle pieces drifting','Fractured black diamond')
$sets['Abstract Blackwork Style Bold Shapes'] = @('Overlapping black circles','Solid black crescent and dot','Black blocks stacked off-balance','Black arch shapes','Bold black stripes of different widths','Solid black sun shape','Black half circles','Large black dot cluster','Black rectangles in rhythm','Black orb with a ring')
$sets['Abstract Blackwork Style Smudge and Texture'] = @('Charcoal smudge with a fine line','Black smear with scratches','Textured black blot','Black ink splatter burst','Dry brush texture patch','Rough black stain with dots','Black scribble cloud','Black ink bleed shape','Grainy black gradient patch','Black fingerprint smudge')
$sets['Abstract Blackwork Style Figures'] = @('Abstract human figure in black strokes','Abstract dancer in black','Abstract face in bold black lines','Abstract eye in black shapes','Abstract hands reaching','Abstract woman profile in black','Abstract horse in brushstrokes','Abstract bird in black shapes','Abstract skull in bold strokes','Abstract heart in black')
$sets['Abstract Blackwork Style Wraps and Bands'] = @('Black brushstroke armband','Solid black band with a cut out wave','Black ribbon wrapping the forearm','Abstract black cuff','Black stripe ankle band','Broken black band','Black ink ring around the calf','Black spiral wrap','Black drip band','Black zigzag wrap')
$sets['Abstract Blackwork Style Small'] = @('Tiny black brush dot','Small black crescent','Tiny black splash','Small black triangle','Tiny black smudge','Small black circle','Tiny black slash','Small black drip','Tiny negative space star','Small black wave')
$sets['Abstract Blackwork Style Large Pieces'] = @('Abstract blackwork full sleeve','Abstract brushstroke back piece','Abstract negative space leg sleeve','Abstract black flow thigh piece','Abstract shards forearm piece','Abstract black smoke shoulder piece','Abstract black chest piece','Abstract black spine piece','Abstract black calf piece','Abstract black half sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Abstract Blackwork Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Abstract Blackwork Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Abstract Blackwork Style$','') -ne 'Wolf face in negative space' })
}
"== drawing " + $all.Count + " Abstract Blackwork split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK Abstract Blackwork"
RUN "SHEET Abstract Blackwork"
}
