cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Bio-Organic")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Bio-Organic Style Alien Flesh','Bio-Organic Style Underwater','Bio-Organic Style Bone and Shell','Bio-Organic Style Plant Hybrids','Bio-Organic Style Insect Forms','Bio-Organic Style Cellular and Micro','Bio-Organic Style Eyes and Faces','Bio-Organic Style Wraps and Bands','Bio-Organic Style Small','Bio-Organic Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Organic alien ridges flowing down the arm'] = 'The tattoo: organic alien ridges flowing down the arm. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bone-like spines growing from the skin'] = 'The tattoo: bone-like spines growing from the skin. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Fleshy pods and tubes'] = 'The tattoo: fleshy pods and tubes. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Alien ribbed tissue panel'] = 'The tattoo: alien ribbed tissue panel. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Organic vents and openings'] = 'The tattoo: organic vents and openings. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Twisting sinew shapes'] = 'The tattoo: twisting sinew shapes. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Smooth alien carapace plates'] = 'The tattoo: smooth alien carapace plates. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Organic tendrils wrapping around'] = 'The tattoo: organic tendrils wrapping around. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Alien vertebrae ridge'] = 'The tattoo: alien vertebrae ridge. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Biological folds and channels'] = 'The tattoo: biological folds and channels. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Coral reef growing from the skin'] = 'The tattoo: coral reef growing from the skin. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Sea anemone tentacles'] = 'The tattoo: sea anemone tentacles. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Nautilus shell spiral structure'] = 'The tattoo: nautilus shell spiral structure. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Deep sea creature textures'] = 'The tattoo: deep sea creature textures. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Barnacle cluster'] = 'The tattoo: barnacle cluster. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Kelp and organic tubes'] = 'The tattoo: kelp and organic tubes. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Bioluminescent sea forms'] = 'The tattoo: bioluminescent sea forms. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Jellyfish tissue layers'] = 'The tattoo: jellyfish tissue layers. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Sea urchin spines'] = 'The tattoo: sea urchin spines. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Seashell chambers opening'] = 'The tattoo: seashell chambers opening. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Bone lattice structure'] = 'The tattoo: bone lattice structure. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Skull fused with shell'] = 'The tattoo: skull fused with shell. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Spiral horn growth'] = 'The tattoo: spiral horn growth. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Organic bone armour plates'] = 'The tattoo: organic bone armour plates. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Fossil ammonite spiral'] = 'The tattoo: fossil ammonite spiral. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Antler-like bone growth'] = 'The tattoo: antler-like bone growth. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Ribbed bone cage shape'] = 'The tattoo: ribbed bone cage shape. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Beetle shell plates'] = 'The tattoo: beetle shell plates. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Bone and cartilage weave'] = 'The tattoo: bone and cartilage weave. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tooth-like ridges'] = 'The tattoo: tooth-like ridges. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Seed pod opening'] = 'The tattoo: seed pod opening. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Organic root system'] = 'The tattoo: organic root system. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Fungus gills'] = 'The tattoo: fungus gills. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Spore cluster'] = 'The tattoo: spore cluster. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Alien fruit pod'] = 'The tattoo: alien fruit pod. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Tendril vine with pods'] = 'The tattoo: tendril vine with pods. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Mushroom tissue layers'] = 'The tattoo: mushroom tissue layers. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Moss and lichen texture'] = 'The tattoo: moss and lichen texture. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Carnivorous plant shape'] = 'The tattoo: carnivorous plant shape. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cactus ribbed growth'] = 'The tattoo: cactus ribbed growth. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Insect wing veins'] = 'The tattoo: insect wing veins. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Beetle carapace texture'] = 'The tattoo: beetle carapace texture. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Mantis arm shapes'] = 'The tattoo: mantis arm shapes. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Cocoon chamber'] = 'The tattoo: cocoon chamber. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Honeycomb cells'] = 'The tattoo: honeycomb cells. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Moth wing scales close up'] = 'The tattoo: moth wing scales close up. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Exoskeleton segments'] = 'The tattoo: exoskeleton segments. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Larva coil'] = 'The tattoo: larva coil. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Insect eye cluster'] = 'The tattoo: insect eye cluster. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Antennae and segmented legs'] = 'The tattoo: antennae and segmented legs. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Cell clusters under a microscope'] = 'The tattoo: cell clusters under a microscope. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Neuron network'] = 'The tattoo: neuron network. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Blood vessel branching'] = 'The tattoo: blood vessel branching. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['DNA twist in organic form'] = 'The tattoo: dna twist in organic form. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Bacteria colony shapes'] = 'The tattoo: bacteria colony shapes. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Pollen grain close up'] = 'The tattoo: pollen grain close up. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Diatom lattice'] = 'The tattoo: diatom lattice. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Virus capsule forms'] = 'The tattoo: virus capsule forms. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Tissue cross section'] = 'The tattoo: tissue cross section. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Spiral cell growth'] = 'The tattoo: spiral cell growth. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Organic eye emerging from tissue'] = 'The tattoo: organic eye emerging from tissue. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Face growing out of roots'] = 'The tattoo: face growing out of roots. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Eye inside a seed pod'] = 'The tattoo: eye inside a seed pod. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Creature face in coral'] = 'The tattoo: creature face in coral. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Alien face with ridges'] = 'The tattoo: alien face with ridges. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Eye cluster in tissue'] = 'The tattoo: eye cluster in tissue. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Face in a shell spiral'] = 'The tattoo: face in a shell spiral. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Organic mask shape'] = 'The tattoo: organic mask shape. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Eye in a cocoon'] = 'The tattoo: eye in a cocoon. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Face of tendrils'] = 'The tattoo: face of tendrils. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Organic ridge armband'] = 'The tattoo: organic ridge armband. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Coral band'] = 'The tattoo: coral band. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Bone ring band'] = 'The tattoo: bone ring band. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Tendril wrap'] = 'The tattoo: tendril wrap. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Shell segment band'] = 'The tattoo: shell segment band. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Vine pod band'] = 'The tattoo: vine pod band. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Spine ridge wrap'] = 'The tattoo: spine ridge wrap. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Organic tube band'] = 'The tattoo: organic tube band. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Fungus ring band'] = 'The tattoo: fungus ring band. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Carapace cuff'] = 'The tattoo: carapace cuff. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny seed pod'] = 'The tattoo: tiny seed pod. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small coral branch'] = 'The tattoo: small coral branch. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny spore'] = 'The tattoo: tiny spore. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small shell spiral'] = 'The tattoo: small shell spiral. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny organic eye'] = 'The tattoo: tiny organic eye. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small bone ring'] = 'The tattoo: small bone ring. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny tendril'] = 'The tattoo: tiny tendril. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small cell cluster'] = 'The tattoo: small cell cluster. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny pod'] = 'The tattoo: tiny pod. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small horn'] = 'The tattoo: small horn. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Bio-organic full sleeve'] = 'The tattoo: bio-organic full sleeve. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Bio-organic back piece'] = 'The tattoo: bio-organic back piece. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across his back, shirtless, seen from behind'
$b['Bio-organic leg sleeve'] = 'The tattoo: bio-organic leg sleeve. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['Organic spine piece'] = 'The tattoo: organic spine piece. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is down his spine, shirtless, seen from behind'
$b['Coral and bone thigh piece'] = 'The tattoo: coral and bone thigh piece. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Alien tissue forearm piece'] = 'The tattoo: alien tissue forearm piece. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Shell and spine calf piece'] = 'The tattoo: shell and spine calf piece. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Organic chest piece'] = 'The tattoo: organic chest piece. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is across his chest, shirtless'
$b['Tendril shoulder piece'] = 'The tattoo: tendril shoulder piece. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Bio-organic half sleeve'] = 'The tattoo: bio-organic half sleeve. Bio-organic tattoo, flowing organic shapes that look like they grow under or out of the skin, smooth 3D depth and soft realistic shading, alien biology, bone, shell and coral textures, muted earthy tones with soft greens and purples, surreal and dimensional, designed like work from a top modern tattoo artist, no gore, no blood, no letters, no words, no brand names, no logos. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$sets = [ordered]@{}
$sets['Bio-Organic Style Alien Flesh'] = @('Organic alien ridges flowing down the arm','Bone-like spines growing from the skin','Fleshy pods and tubes','Alien ribbed tissue panel','Organic vents and openings','Twisting sinew shapes','Smooth alien carapace plates','Organic tendrils wrapping around','Alien vertebrae ridge','Biological folds and channels')
$sets['Bio-Organic Style Underwater'] = @('Coral reef growing from the skin','Sea anemone tentacles','Nautilus shell spiral structure','Deep sea creature textures','Barnacle cluster','Kelp and organic tubes','Bioluminescent sea forms','Jellyfish tissue layers','Sea urchin spines','Seashell chambers opening')
$sets['Bio-Organic Style Bone and Shell'] = @('Bone lattice structure','Skull fused with shell','Spiral horn growth','Organic bone armour plates','Fossil ammonite spiral','Antler-like bone growth','Ribbed bone cage shape','Beetle shell plates','Bone and cartilage weave','Tooth-like ridges')
$sets['Bio-Organic Style Plant Hybrids'] = @('Seed pod opening','Organic root system','Fungus gills','Spore cluster','Alien fruit pod','Tendril vine with pods','Mushroom tissue layers','Moss and lichen texture','Carnivorous plant shape','Cactus ribbed growth')
$sets['Bio-Organic Style Insect Forms'] = @('Insect wing veins','Beetle carapace texture','Mantis arm shapes','Cocoon chamber','Honeycomb cells','Moth wing scales close up','Exoskeleton segments','Larva coil','Insect eye cluster','Antennae and segmented legs')
$sets['Bio-Organic Style Cellular and Micro'] = @('Cell clusters under a microscope','Neuron network','Blood vessel branching','DNA twist in organic form','Bacteria colony shapes','Pollen grain close up','Diatom lattice','Virus capsule forms','Tissue cross section','Spiral cell growth')
$sets['Bio-Organic Style Eyes and Faces'] = @('Organic eye emerging from tissue','Face growing out of roots','Eye inside a seed pod','Creature face in coral','Alien face with ridges','Eye cluster in tissue','Face in a shell spiral','Organic mask shape','Eye in a cocoon','Face of tendrils')
$sets['Bio-Organic Style Wraps and Bands'] = @('Organic ridge armband','Coral band','Bone ring band','Tendril wrap','Shell segment band','Vine pod band','Spine ridge wrap','Organic tube band','Fungus ring band','Carapace cuff')
$sets['Bio-Organic Style Small'] = @('Tiny seed pod','Small coral branch','Tiny spore','Small shell spiral','Tiny organic eye','Small bone ring','Tiny tendril','Small cell cluster','Tiny pod','Small horn')
$sets['Bio-Organic Style Large Pieces'] = @('Bio-organic full sleeve','Bio-organic back piece','Bio-organic leg sleeve','Organic spine piece','Coral and bone thigh piece','Alien tissue forearm piece','Shell and spine calf piece','Organic chest piece','Tendril shoulder piece','Bio-organic half sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Bio-Organic Style" } else { $n } }
"== Bio-Organic before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:bio-organic" --remote 2>$null | Out-Null
RUN "CATEGORY Bio-Organic :: Bio-Organic Style Alien Flesh, Bio-Organic Style Underwater, Bio-Organic Style Bone and Shell, Bio-Organic Style Plant Hybrids, Bio-Organic Style Insect Forms, Bio-Organic Style Cellular and Micro, Bio-Organic Style Eyes and Faces, Bio-Organic Style Wraps and Bands, Bio-Organic Style Small, Bio-Organic Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Bio-Organic Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Bio-Organic Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Coral reef growing from the skin"))
}
}
