cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
RUN "REDO Diamond Body Chain, Pearl Body Draping, Victorian Heirloom Jewelry, Art Nouveau Jewelry, Chandelier Body Jewelry"
RUN "REDO Royal Jewels, Emerald Garden Jewelry, Ruby Lace, Crystal Waterfall, Floating Diamonds"
RUN "REDO Y2K Butterfly Jewelry, Cherry Charm Chain, Pink Rhinestone Princess, Flip-Phone Charm Jewelry, Y2K Lower Back Chain"
RUN "REDO Chrome Starburst Jewelry, Y2K Bow Necklace, Pixel Charm Chain, Pop Princess Charm Bracelet, Chrome Flame Jewelry"
RUN "REDO Rhinestone Tribal Jewelry, Chrome Angel Wings, Cyber Fairy Jewelry, Shooting-Star Body Chain, Neo-Tribal Necklace"
RUN "REDO Neo-Tribal Lower Back Chain, Tribal Gemstone, Tribal Choker, Tribal Shoulder Jewelry, Tribal Thigh Jewelry"
RUN "REDO Tribal Arm Cuff, Tribal Anklet, Tribal Crown Jewelry, Neo-Tribal Pearl Collision, Cyber Sigil Necklace"
RUN "REDO Cyber Crystal Harness, Digital Rosary, Alien Royal Jewelry, Biomechanical Necklace, Cyber Spine Jewelry"
RUN "REDO Circuit Gem Necklace, Glitch Jewelry, Cyber Thorn Choker, Chrome Sigil Pendant, Digital Halo Jewelry"
RUN "REDO Cyber Wing Harness, Alien Gemstone, Techno Lower Back Chain, Future-Goth Rosary, Black Diamond Choker"
RUN "REDO Gothic Cathedral Jewelry, Spiderweb Necklace, Bat-Wing Jewelry, Thorn Necklace, Black Rose Jewelry"
RUN "REDO Gothic Heart Reliquary, Vampire Jewelry, Moonlit Gothic Chain, Gothic Cross Jewelry, Pearl Bow Body Jewelry"
RUN "REDO Ribbon Necklace, Locket Body Chain, Love-Letter Jewelry, Rose-Gold Floral Jewelry, Lace Thigh Jewelry"
RUN "REDO Crystal Butterfly Garden, Heart-Key Jewelry, Birthstone Family Jewelry, Kids Charm Jewelry, Moon Phase Jewelry"
RUN "REDO Sun And Moon Necklace, Constellation Jewelry, Zodiac Body Chain, Planetary Jewelry, Eclipse Pendant"
RUN "REDO Crystal Moon Chandelier, Cosmic Rosary, Aurora Jewelry, Celestial Crown Jewelry, Living Vine Necklace"
RUN "REDO Blossom Link Chain, Orchid Jewelry, Butterfly Link Chain, Snake Jewelry, Dragon Jewelry"
RUN "REDO Hummingbird Pendant, Ocean Jewelry, Coral Necklace, Mushroom Fairy Jewelry, Broken Necklace"
RUN "REDO Floating Jewelry, Tattoo Piercing Illusion, Zipper Jewelry, Barbed-Wire Diamonds, Safety-Pin Jewelry"
RUN "REDO Chainmail Jewelry, Skeleton Hand Jewelry, Impossible Jewelry"
Start-Sleep -Seconds 30
RUN "SHEET Classic Body Jewelry"
RUN "SHEET Y2K Body Jewelry"
RUN "SHEET Neo-Tribal Body Jewelry"
RUN "SHEET Cyber Body Jewelry"
RUN "SHEET Gothic Body Jewelry"
RUN "SHEET Romantic Body Jewelry"
RUN "SHEET Celestial Body Jewelry"
RUN "SHEET Organic Body Jewelry"
RUN "SHEET Wild Body Jewelry"
RUN "BROWSE"