RUN "SETKV shape:classic-coquette-bows 3:2"
RUN "SETKV split:classic-coquette-bows yes"
RUN "SETKV shape:bows-with-flowers 3:2"
RUN "SETKV split:bows-with-flowers yes"
RUN "SETKV shape:bows-with-hearts 3:2"
RUN "SETKV split:bows-with-hearts yes"
RUN "SETKV shape:bows-with-cherries-and-fruit 3:2"
RUN "SETKV split:bows-with-cherries-and-fruit yes"
RUN "SETKV shape:bows-with-daggers 3:2"
RUN "SETKV split:bows-with-daggers yes"
RUN "SETKV shape:bows-with-butterflies-and-birds 3:2"
RUN "SETKV split:bows-with-butterflies-and-birds yes"
RUN "SETKV shape:bows-with-jewelry 3:2"
RUN "SETKV split:bows-with-jewelry yes"
RUN "SETKV shape:body-flow-ribbon-bows 3:2"
RUN "SETKV split:body-flow-ribbon-bows yes"
RUN "SETKV shape:personal-story-bows 3:2"
RUN "SETKV split:personal-story-bows yes"
Start-Sleep -Seconds 60
RUN "REDO Pink Satin Bow, Tiny Fine-Line Bow, Micro Bow, Red Ribbon Bow, Black Satin Bow"
RUN "REDO Baby Pink Bow, Long-Tail Coquette Bow, Loose Hand-Tied Bow, Drooping Ribbon Bow, Oversized Satin Bow"
RUN "REDO Tiny Outline Bow, Delicate Bow, Micro Red Bow, Soft Blue Bow, Black Fine-Line Bow"
RUN "REDO Realistic Silk Bow, Velvet Bow, Black Lace Bow, Sheer Ribbon Bow, Double-Layer Ribbon Bow"
RUN "REDO Bow Tied Around Rose, Bow Tied Around Peony, Bow Tied Around Wildflower Bouquet, Bow Tied Around Tulips, Bow Tied Around Lavender"
RUN "REDO Bow Tied Around Lily Of The Valley, Bow Tied Around Poppies, Bow Tied Around Cherry Blossoms, Bow Tied Around Sunflower Stem, Bow Tied Around Daisies"
RUN "REDO Bow With Flowers Growing Through It, Floral Bow Made From Vines, Rose-Covered Ribbon Bow, Tiny Flower Bouquet With Pink Ribbon, Cascading Flowers From Bow"
RUN "REDO Bow With Hanging Heart Charm, Bow Around Anatomical Heart, Ribbon-Wrapped Heart, Bow-Tied Sacred Heart, Heart-Shaped Ribbon Bow"
RUN "REDO Bow With Tiny Heart Center, Ribbon Forming Heart And Bow, Bow And Heart Locket, Broken Heart Tied With Ribbon, Two Hearts Tied Together With Bow"
RUN "REDO Cherries Tied With Pink Bow, Cherries Tied With Red Ribbon, Strawberry With Ribbon Bow, Two Strawberries Tied With Bow, Peach With Tiny Bow"
RUN "REDO Apple With Ribbon, Lemon Branch Tied With Bow, Cherry Pair With Long Ribbon Tails, Dagger Tied With Pink Bow, Dagger Tied With Red Ribbon"
RUN "REDO Dagger Piercing Satin Bow, Bow Wrapped Around Dagger Handle, Long Ribbon Spiraling Around Dagger, Ornamental Dagger With Bow, Gothic Dagger With Black Lace Bow"
RUN "REDO Sword With Flowing Ribbon Bow, Knife With Tiny Pink Bow, Dagger Through Heart With Bow, Snake And Dagger Tied With Ribbon, Floral Dagger With Ribbon Bow"
RUN "REDO Butterfly Resting On Bow, Butterfly With Ribbon-Tail Bow, Two Butterflies Tied With Ribbon, Moth With Black Bow, Dragonfly And Ribbon"
RUN "REDO Hummingbird Carrying Ribbon Bow, Dove Carrying Flowing Ribbon, Swan With Neck Ribbon Bow, Pearl Strand With Satin Bow, Bow With Hanging Pearl"
RUN "REDO Pearl Necklace Tied With Bow, Jeweled Bow, Heart Jewel Hanging From Bow, Ornamental Bow Pendant, Bow And Victorian Locket"
RUN "REDO Cameo Portrait With Ribbon Bow, Cross Pendant Hanging From Bow, Zodiac Charm Hanging From Bow, Initial Charm Hanging From Bow, Birthstone Charm Hanging From Bow"
RUN "REDO Matching Bows, Garter Bow, Lace Garter With Bow, Ribbon Wrapping Around Thigh Into Bow, Corset Lacing Ending In Bow"
RUN "REDO Corset Ribbon Bow, Under-Bust Ribbon Bow, Hip Ribbon Wrap With Bow, Ankle Ribbon Wrap Ending In Bow, Wrist Ribbon Wrap Ending In Bow"
RUN "REDO Name Written Into Ribbon Tail, Birth Date Written On Ribbon, Two Birth Flowers Tied With Bow, Children's Initials Hanging From Bow, Handwriting Turned Into Flowing Ribbon Bow"
Start-Sleep -Seconds 30
RUN "SHEET Classic Coquette Bows"
RUN "SHEET Bows With Flowers"
RUN "SHEET Bows With Hearts"
RUN "SHEET Bows With Cherries And Fruit"
RUN "SHEET Bows With Daggers"
RUN "SHEET Bows With Butterflies And Birds"
RUN "SHEET Bows With Jewelry"
RUN "SHEET Body-Flow Ribbon Bows"
RUN "SHEET Personal Story Bows"
RUN "SHEET Bows & Ribbons"
RUN "BROWSE"
RUN "BROWSE"
RUN "BROWSE"
