cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Blackwork")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$new = 'Blackwork Abstract and Brutalist','Blackwork Organic','Blackwork Neo-Tribal Flow','Blackwork Cyber Gothic','Blackwork Negative Space Reveals','Blackwork Dark Surrealism','Blackwork Gothic Architecture','Blackwork Modern Ornamental','Blackwork Experimental Nature','Blackwork Statement Pieces','Ink Smear Sleeve','Fractured Black Blocks','Torn Paper Void','Controlled Chaos Splatter','Brutalist Spine Slabs','Shattered Black Glass','Collarbone Brushstroke','Asymmetric Void Panel','Scraped Ink Ribs','Erosion Field','Liquid Black Drip','Root System Forearm','Smoke Mass Ribs','Cellular Growth','Tendril Bloom','Melting Wax Form','Ink In Water','Vein Network','Black Moss Growth','Organic Armour Shell','Sweeping Blade Shoulder','Spinal Blade Column','Flame Rib Flow','Forearm Hook Flow','Chest Crescent Plate','Hip Swoop','Neck Thorn Rise','Calf Wave Blades','Collarbone Wing Sweep','Back Flow Wings','Cyber Thorn Spine','Biomech Forearm Plates','Alien Rib Cage','Chrome Form In Black','Circuit Vine','Cyber Halo','Machine Heart','Antenna Spikes','Glitch Band','Future Gothic Armour','Face In The Black','Wolf From Absence','Cathedral In The Void','Rose Left Bare','Eye From Nothing','Figure Walking Out','Moth Carved Out','Hands From Darkness','Mountain Reveal Band','Skull Hidden In Black','Faceless Cloaked Figure','Hand Of Many Eyes','Melting Portrait','Mouth In A Black Palm','Fragmented Angel','Ribcage Doors','Weeping Black Eyes','Head Of Ravens','Floating Black Hands','Distorted Reflection','Gothic Cathedral Window','Arched Doorway Into Black','Spire Spine','Gargoyle On A Ledge','Ruined Church Arches','Gothic Rose Window','Flying Buttress Ribs','Candlelit Crypt','Gothic Bell Tower','Vaulted Cathedral Ceiling','Barbed Filigree Spine','Hanging Chest Structure','Spilling Shoulder Ornament','Sharp Lace Forearm','Blade Fan Sternum','Black Barbed Garter','Throat Ornament','Chandelier Drop Back','Hand Spikes Ornament','Gothic Ornament Calf','Flower Consumed By Black','Forest Of Black Thorns','Abstract Insect','Raven Dissolving','Warped Botanical','Black Bloom Burst','Serpent Of Roots','Moth Of Smoke','Black Tide Wave','Branches Into Bones','Full Back Black Eclipse','Blackout Sleeve With Bare Lines','Chest Wings Panel','Thigh Panel With Bare Flower','Rib To Hip Flow','Back Of Black Roots','Thorn Leg Sleeve','Spine And Shoulder Cross','Half Torso Blackwork','Neck To Shoulder Flow'
$hits = $new | ? { $tk.ContainsKey((& $slug $_)) } | % { "  CLASH: $_  (already under " + $tk[(& $slug $_)] + ")" }
if ($hits) { $hits; "  STOPPED - nothing written or drawn" } else {
"  no clashes - building Blackwork as split cards"
"== image model the split cards use (before) =="
npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "config:source:redo:model" --remote
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "config:source:redo:model" "gpt-image-2" --remote
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:blackwork" --remote
RUN "CATEGORY Blackwork :: Blackwork Abstract and Brutalist, Blackwork Organic, Blackwork Neo-Tribal Flow, Blackwork Cyber Gothic, Blackwork Negative Space Reveals, Blackwork Dark Surrealism, Blackwork Gothic Architecture, Blackwork Modern Ornamental, Blackwork Experimental Nature, Blackwork Statement Pieces"
RUN "LEAVES Blackwork Abstract and Brutalist :: Ink Smear Sleeve, Fractured Black Blocks, Torn Paper Void, Controlled Chaos Splatter, Brutalist Spine Slabs, Shattered Black Glass, Collarbone Brushstroke, Asymmetric Void Panel, Scraped Ink Ribs, Erosion Field"
RUN "LEAVES Blackwork Organic :: Liquid Black Drip, Root System Forearm, Smoke Mass Ribs, Cellular Growth, Tendril Bloom, Melting Wax Form, Ink In Water, Vein Network, Black Moss Growth, Organic Armour Shell"
RUN "LEAVES Blackwork Neo-Tribal Flow :: Sweeping Blade Shoulder, Spinal Blade Column, Flame Rib Flow, Forearm Hook Flow, Chest Crescent Plate, Hip Swoop, Neck Thorn Rise, Calf Wave Blades, Collarbone Wing Sweep, Back Flow Wings"
RUN "LEAVES Blackwork Cyber Gothic :: Cyber Thorn Spine, Biomech Forearm Plates, Alien Rib Cage, Chrome Form In Black, Circuit Vine, Cyber Halo, Machine Heart, Antenna Spikes, Glitch Band, Future Gothic Armour"
RUN "LEAVES Blackwork Negative Space Reveals :: Face In The Black, Wolf From Absence, Cathedral In The Void, Rose Left Bare, Eye From Nothing, Figure Walking Out, Moth Carved Out, Hands From Darkness, Mountain Reveal Band, Skull Hidden In Black"
RUN "LEAVES Blackwork Dark Surrealism :: Faceless Cloaked Figure, Hand Of Many Eyes, Melting Portrait, Mouth In A Black Palm, Fragmented Angel, Ribcage Doors, Weeping Black Eyes, Head Of Ravens, Floating Black Hands, Distorted Reflection"
RUN "LEAVES Blackwork Gothic Architecture :: Gothic Cathedral Window, Arched Doorway Into Black, Spire Spine, Gargoyle On A Ledge, Ruined Church Arches, Gothic Rose Window, Flying Buttress Ribs, Candlelit Crypt, Gothic Bell Tower, Vaulted Cathedral Ceiling"
RUN "LEAVES Blackwork Modern Ornamental :: Barbed Filigree Spine, Hanging Chest Structure, Spilling Shoulder Ornament, Sharp Lace Forearm, Blade Fan Sternum, Black Barbed Garter, Throat Ornament, Chandelier Drop Back, Hand Spikes Ornament, Gothic Ornament Calf"
RUN "LEAVES Blackwork Experimental Nature :: Flower Consumed By Black, Forest Of Black Thorns, Abstract Insect, Raven Dissolving, Warped Botanical, Black Bloom Burst, Serpent Of Roots, Moth Of Smoke, Black Tide Wave, Branches Into Bones"
RUN "LEAVES Blackwork Statement Pieces :: Full Back Black Eclipse, Blackout Sleeve With Bare Lines, Chest Wings Panel, Thigh Panel With Bare Flower, Rib To Hip Flow, Back Of Black Roots, Thorn Leg Sleeve, Spine And Shoulder Cross, Half Torso Blackwork, Neck To Shoulder Flow"
RUN "SETKV render:blackwork-abstract-and-brutalist Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-abstract-and-brutalist 3:2"
RUN "SETKV split:blackwork-abstract-and-brutalist yes"
RUN "SETKV render:blackwork-organic Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-organic 3:2"
RUN "SETKV split:blackwork-organic yes"
RUN "SETKV render:blackwork-neo-tribal-flow Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-neo-tribal-flow 3:2"
RUN "SETKV split:blackwork-neo-tribal-flow yes"
RUN "SETKV render:blackwork-cyber-gothic Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-cyber-gothic 3:2"
RUN "SETKV split:blackwork-cyber-gothic yes"
RUN "SETKV render:blackwork-negative-space-reveals Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-negative-space-reveals 3:2"
RUN "SETKV split:blackwork-negative-space-reveals yes"
RUN "SETKV render:blackwork-dark-surrealism Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-dark-surrealism 3:2"
RUN "SETKV split:blackwork-dark-surrealism yes"
RUN "SETKV render:blackwork-gothic-architecture Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-gothic-architecture 3:2"
RUN "SETKV split:blackwork-gothic-architecture yes"
RUN "SETKV render:blackwork-modern-ornamental Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-modern-ornamental 3:2"
RUN "SETKV split:blackwork-modern-ornamental yes"
RUN "SETKV render:blackwork-experimental-nature Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-experimental-nature 3:2"
RUN "SETKV split:blackwork-experimental-nature yes"
RUN "SETKV render:blackwork-statement-pieces Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical."
RUN "SETKV shape:blackwork-statement-pieces 3:2"
RUN "SETKV split:blackwork-statement-pieces yes"
RUN "SETKV build:ink-smear-sleeve The tattoo: ink smear sleeve - violent black brush smears wrapping the arm with raw dry-brush edges. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:fractured-black-blocks The tattoo: fractured black blocks - heavy black rectangles cracked and offset like broken concrete. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:torn-paper-void The tattoo: torn paper void - a solid black field with torn ragged edges opening onto bare skin shapes. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:controlled-chaos-splatter The tattoo: controlled chaos splatter - dense black splatter organised into one deliberate falling diagonal. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:brutalist-spine-slabs The tattoo: brutalist spine slabs - stacked heavy black slabs of different widths running down the spine. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:shattered-black-glass The tattoo: shattered black glass - black shards bursting outward from a single point. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:collarbone-brushstroke The tattoo: collarbone brushstroke - one sweeping bold brushstroke that follows the line of the collarbones. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along her collarbones and shoulders, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:asymmetric-void-panel The tattoo: asymmetric void panel - a large black panel with off-centre bare voids cut into it. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:scraped-ink-ribs The tattoo: scraped ink ribs - horizontal scraped black strokes like a palette knife dragged across the ribs. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of her ribs, seen from the side in a simple bandeau top" | Out-Null
RUN "SETKV build:erosion-field The tattoo: erosion field - a black mass eroding into scattered fragments and fine dust. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:liquid-black-drip The tattoo: liquid black drip - thick liquid black melting downward from the top of the shoulder. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:root-system-forearm The tattoo: root system forearm - black roots spreading and branching down the forearm. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:smoke-mass-ribs The tattoo: smoke mass ribs - a dense black smoke form curling up the side of the body. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of her ribs, seen from the side in a simple bandeau top" | Out-Null
RUN "SETKV build:cellular-growth The tattoo: cellular growth - organic black cell clusters growing outward like coral. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tendril-bloom The tattoo: tendril bloom - fine black tendrils unfurling from a solid black core. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:melting-wax-form The tattoo: melting wax form - a heavy black shape slumping and melting like candle wax. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:ink-in-water The tattoo: ink in water - black ink clouds blooming as if dropped into water. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:vein-network The tattoo: vein network - black vein-like branches spreading out from the centre of the chest. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:black-moss-growth The tattoo: black moss growth - thick textured black growth climbing up the leg. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts" | Out-Null
RUN "SETKV build:organic-armour-shell The tattoo: organic armour shell - smooth black organic plates wrapping the shoulder like a shell. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:sweeping-blade-shoulder The tattoo: sweeping blade shoulder - sharp curved black blades sweeping over the shoulder cap. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:spinal-blade-column The tattoo: spinal blade column - symmetrical black blades flowing down the spine. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:flame-rib-flow The tattoo: flame rib flow - flame-like black forms licking up the ribs. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of her ribs, seen from the side in a simple bandeau top" | Out-Null
RUN "SETKV build:forearm-hook-flow The tattoo: forearm hook flow - interlocking hooked black curves wrapping the forearm. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:chest-crescent-plate The tattoo: chest crescent plate - a symmetrical black crescent plate across the chest. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:hip-swoop The tattoo: hip swoop - one long black swoop curving from the hip down the thigh. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:neck-thorn-rise The tattoo: neck thorn rise - sharp black curves rising up the side of the neck. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his neck, wearing a plain crew-neck shirt" | Out-Null
RUN "SETKV build:calf-wave-blades The tattoo: calf wave blades - layered black blades flowing down the calf. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt" | Out-Null
RUN "SETKV build:collarbone-wing-sweep The tattoo: collarbone wing sweep - twin black curves sweeping out from the centre along both collarbones. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:back-flow-wings The tattoo: back flow wings - huge curved black forms spreading across the upper back like wings. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:cyber-thorn-spine The tattoo: cyber thorn spine - mechanical black thorns linked in a chain down the spine. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:biomech-forearm-plates The tattoo: biomech forearm plates - black biomechanical plates and cables that look built into the arm. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:alien-rib-cage The tattoo: alien rib cage - an alien black skeletal structure laid over the ribs. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of his ribs, shirtless, seen from the side" | Out-Null
RUN "SETKV build:chrome-form-in-black The tattoo: chrome form in black - a liquid chrome style form rendered only in black and bare skin. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:circuit-vine The tattoo: circuit vine - black circuit lines growing like a vine around the arm. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:cyber-halo The tattoo: cyber halo - a jagged black halo of spikes and broken rings. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:machine-heart The tattoo: machine heart - a black mechanical heart structure in the centre of the chest. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:antenna-spikes The tattoo: antenna spikes - thin black spikes and antennas radiating up from the shoulder. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:glitch-band The tattoo: glitch band - a black band breaking apart into digital glitch blocks. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:future-gothic-armour The tattoo: future gothic armour - pointed black armour plates over the collarbones and shoulders. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along her collarbones and shoulders, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:face-in-the-black The tattoo: face in the black - a woman's face revealed only by bare skin inside a solid black shape. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:wolf-from-absence The tattoo: wolf from absence - a wolf head formed entirely by untouched skin within a black field. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:cathedral-in-the-void The tattoo: cathedral in the void - a cathedral arch revealed in bare skin inside solid black. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:rose-left-bare The tattoo: rose left bare - a rose made entirely of bare skin in a black panel. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:eye-from-nothing The tattoo: eye from nothing - an eye formed by empty skin within solid black. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:figure-walking-out The tattoo: figure walking out - a small human figure in bare skin walking out of a black mass. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:moth-carved-out The tattoo: moth carved out - a moth carved out of a solid black oval. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:hands-from-darkness The tattoo: hands from darkness - two reaching hands formed by bare skin inside black. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:mountain-reveal-band The tattoo: mountain reveal band - a mountain range revealed in bare skin inside a wide black band. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts" | Out-Null
RUN "SETKV build:skull-hidden-in-black The tattoo: skull hidden in black - a skull that exists only as untouched skin inside black. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt" | Out-Null
RUN "SETKV build:faceless-cloaked-figure The tattoo: faceless cloaked figure - a tall faceless figure in a flowing black cloak. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:hand-of-many-eyes The tattoo: hand of many eyes - a hand covered in open eyes. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:melting-portrait The tattoo: melting portrait - a portrait melting downward into black drips. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:mouth-in-a-black-palm The tattoo: mouth in a black palm - an open mouth with teeth set into a black palm shape. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:fragmented-angel The tattoo: fragmented angel - an angel breaking apart into black fragments. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:ribcage-doors The tattoo: ribcage doors - a ribcage opening like a pair of doors into darkness. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of his ribs, shirtless, seen from the side" | Out-Null
RUN "SETKV build:weeping-black-eyes The tattoo: weeping black eyes - a face crying thick solid black tears. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:head-of-ravens The tattoo: head of ravens - a human head dissolving into a flock of ravens. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:floating-black-hands The tattoo: floating black hands - several black hands floating around an empty void. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:distorted-reflection The tattoo: distorted reflection - a figure staring at its own distorted black reflection. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:gothic-cathedral-window The tattoo: gothic cathedral window - a tall pointed gothic window with black tracery. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:arched-doorway-into-black The tattoo: arched doorway into black - a tall arched doorway opening into darkness. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:spire-spine The tattoo: spire spine - gothic spires rising up along the spine. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:gargoyle-on-a-ledge The tattoo: gargoyle on a ledge - a gargoyle crouching on a stone ledge. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:ruined-church-arches The tattoo: ruined church arches - a ruined church with broken arches and open sky. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:gothic-rose-window The tattoo: gothic rose window - a circular gothic rose window with radiating tracery. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:flying-buttress-ribs The tattoo: flying buttress ribs - flying buttresses arching over the ribs. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of her ribs, seen from the side in a simple bandeau top" | Out-Null
RUN "SETKV build:candlelit-crypt The tattoo: candlelit crypt - a crypt corridor of arches lit by candles. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:gothic-bell-tower The tattoo: gothic bell tower - a narrow bell tower with a steep pointed roof. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:vaulted-cathedral-ceiling The tattoo: vaulted cathedral ceiling - a ribbed vaulted ceiling seen from directly below. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:barbed-filigree-spine The tattoo: barbed filigree spine - sharp barbed filigree flowing down the spine. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:hanging-chest-structure The tattoo: hanging chest structure - a black jewelry-like structure hanging across the chest. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:spilling-shoulder-ornament The tattoo: spilling shoulder ornament - asymmetric ornament spilling off the shoulder down the arm. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:sharp-lace-forearm The tattoo: sharp lace forearm - a sharp pointed lace pattern wrapping the forearm. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:blade-fan-sternum The tattoo: blade fan sternum - blade-like ornament fanning out from the centre of the chest. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:black-barbed-garter The tattoo: black barbed garter - a barbed ornamental band wrapping the thigh like a garter. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:throat-ornament The tattoo: throat ornament - ornament curling up the side of the throat. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his neck, wearing a plain crew-neck shirt" | Out-Null
RUN "SETKV build:chandelier-drop-back The tattoo: chandelier drop back - an ornate chandelier form hanging from the top of the back. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:hand-spikes-ornament The tattoo: hand spikes ornament - pointed ornament radiating across the back of the hand. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his hand, wearing a plain long-sleeve shirt" | Out-Null
RUN "SETKV build:gothic-ornament-calf The tattoo: gothic ornament calf - tall pointed gothic ornament running down the calf. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:flower-consumed-by-black The tattoo: flower consumed by black - a flower being eaten away by spreading black. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:forest-of-black-thorns The tattoo: forest of black thorns - a dense forest of black thorns. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:abstract-insect The tattoo: abstract insect - an insect broken into abstract black shapes. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:raven-dissolving The tattoo: raven dissolving - a raven dissolving into black particles. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:warped-botanical The tattoo: warped botanical - stretched and warped black plant forms. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of her ribs, seen from the side in a simple bandeau top" | Out-Null
RUN "SETKV build:black-bloom-burst The tattoo: black bloom burst - a flower exploding into black shards. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:serpent-of-roots The tattoo: serpent of roots - a snake made entirely of black roots. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:moth-of-smoke The tattoo: moth of smoke - a moth made of curling black smoke. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:black-tide-wave The tattoo: black tide wave - a heavy abstract black wave about to break. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:branches-into-bones The tattoo: branches into bones - tree branches slowly turning into bones. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:full-back-black-eclipse The tattoo: full back black eclipse - a huge black eclipse with radiating forms filling the whole back. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:blackout-sleeve-with-bare-lines The tattoo: blackout sleeve with bare lines - a solid blackout sleeve with thin bare-skin lines cut through it. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:chest-wings-panel The tattoo: chest wings panel - huge black wings spread across the whole chest. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along his collarbones and upper chest, shirtless" | Out-Null
RUN "SETKV build:thigh-panel-with-bare-flower The tattoo: thigh panel with bare flower - a large black thigh panel with one flower left in bare skin. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:rib-to-hip-flow The tattoo: rib to hip flow - one huge flowing black form running from the ribs to the hip. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of her ribs, seen from the side in a simple bandeau top" | Out-Null
RUN "SETKV build:back-of-black-roots The tattoo: back of black roots - roots spreading to cover the whole back. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:thorn-leg-sleeve The tattoo: thorn leg sleeve - black thorns covering the whole leg. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering his whole leg, wearing shorts" | Out-Null
RUN "SETKV build:spine-and-shoulder-cross The tattoo: spine and shoulder cross - a black form running down the spine and across both shoulder blades. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:half-torso-blackwork The tattoo: half torso blackwork - a black composition covering one whole side of the torso. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of his ribs, shirtless, seen from the side" | Out-Null
RUN "SETKV build:neck-to-shoulder-flow The tattoo: neck to shoulder flow - one continuous black form flowing from the neck over the shoulder. Contemporary blackwork tattoo art, experimental and fashion-forward, dramatic tension between saturated black and untouched negative space, modern body-flow composition, expressive organic and architectural forms, sharp intentional silhouettes mixed with intricate detail, designed like work from a contemporary blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his neck, wearing a plain crew-neck shirt" | Out-Null
"  100 builds saved"
RUN "REDO Liquid Black Drip"
}
}
