cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
RUN "REDO Ink Smear Sleeve, Fractured Black Blocks, Torn Paper Void, Controlled Chaos Splatter, Brutalist Spine Slabs"
RUN "REDO Shattered Black Glass, Collarbone Brushstroke, Asymmetric Void Panel, Scraped Ink Ribs, Erosion Field"
RUN "REDO Root System Forearm, Smoke Mass Ribs, Cellular Growth, Tendril Bloom, Melting Wax Form"
RUN "REDO Ink In Water, Vein Network, Black Moss Growth, Organic Armour Shell, Sweeping Blade Shoulder"
RUN "REDO Spinal Blade Column, Flame Rib Flow, Forearm Hook Flow, Chest Crescent Plate, Hip Swoop"
RUN "REDO Neck Thorn Rise, Calf Wave Blades, Collarbone Wing Sweep, Back Flow Wings, Cyber Thorn Spine"
RUN "REDO Biomech Forearm Plates, Alien Rib Cage, Chrome Form In Black, Circuit Vine, Cyber Halo"
RUN "REDO Machine Heart, Antenna Spikes, Glitch Band, Future Gothic Armour, Face In The Black"
RUN "REDO Wolf From Absence, Cathedral In The Void, Rose Left Bare, Eye From Nothing, Figure Walking Out"
RUN "REDO Moth Carved Out, Hands From Darkness, Mountain Reveal Band, Skull Hidden In Black, Faceless Cloaked Figure"
RUN "REDO Hand Of Many Eyes, Melting Portrait, Mouth In A Black Palm, Fragmented Angel, Ribcage Doors"
RUN "REDO Weeping Black Eyes, Head Of Ravens, Floating Black Hands, Distorted Reflection, Gothic Cathedral Window"
RUN "REDO Arched Doorway Into Black, Spire Spine, Gargoyle On A Ledge, Ruined Church Arches, Gothic Rose Window"
RUN "REDO Flying Buttress Ribs, Candlelit Crypt, Gothic Bell Tower, Vaulted Cathedral Ceiling, Barbed Filigree Spine"
RUN "REDO Hanging Chest Structure, Spilling Shoulder Ornament, Sharp Lace Forearm, Blade Fan Sternum, Black Barbed Garter"
RUN "REDO Throat Ornament, Chandelier Drop Back, Hand Spikes Ornament, Gothic Ornament Calf, Flower Consumed By Black"
RUN "REDO Forest Of Black Thorns, Abstract Insect, Raven Dissolving, Warped Botanical, Black Bloom Burst"
RUN "REDO Serpent Of Roots, Moth Of Smoke, Black Tide Wave, Branches Into Bones, Full Back Black Eclipse"
RUN "REDO Blackout Sleeve With Bare Lines, Chest Wings Panel, Thigh Panel With Bare Flower, Rib To Hip Flow, Back Of Black Roots"
RUN "REDO Thorn Leg Sleeve, Spine And Shoulder Cross, Half Torso Blackwork, Neck To Shoulder Flow"
RUN "WALK Blackwork"
RUN "SHEET Blackwork"
