cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Cars")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Cars before (empty = new category) =="
"  " + (@($tt.subjects."Cars") -join ", ")
$kinds = 'Cars Muscle Cars','Cars Lowriders','Cars JDM Legends','Cars Supercars','Cars European Classics','Cars Race Cars','Cars Hot Rods','Cars Off-Road and Trucks','Cars Engines and Parts','Cars Surreal Dream Cars'
$kh = $kinds | ? { $tk.ContainsKey((& $slug $_)) }
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
$sets = [ordered]@{}
$sets['Cars Muscle Cars'] = @('1967 Ford Mustang Fastback black and grey realism aggressive front three-quarter view','1969 Chevrolet Camaro SS emerging through tire smoke','1970 Dodge Challenger RT beneath dramatic storm clouds','1969 Dodge Charger roaring down an empty desert highway','1967 Pontiac GTO head-on chrome grille catching the light','Shelby Cobra with American Traditional flames','Corvette Stingray reflected across wet pavement','Buick Grand National disappearing into black smoke','Plymouth Barracuda with psychedelic 1970s color','Classic Ford Mustang rendered like a vintage racing poster')
$sets['Cars Lowriders'] = @('1964 Chevrolet Impala lowrider in black-and-grey Chicano realism','Candy-red Impala hopping on hydraulics','Lowrider Chevrolet Monte Carlo on gold wire wheels','Cadillac lowrider cruising beneath palm trees at sunset','Lowrider viewed extremely low from the front chrome towering overhead','Purple lowrider surrounded by roses and ornamental filigree','Lowrider cruising through neon-lit Los Angeles streets','Classic Impala reflected in polished chrome lettering','Lowrider with elaborate candy paint rendered in rich color realism','Three-wheel-motion lowrider with smoke curling around the tires')
$sets['Cars JDM Legends'] = @('Nissan Skyline GT-R R34 drifting through neon rain','Toyota Supra Mk4 with glowing city reflections across the body','Mazda RX-7 FD sliding sideways through tire smoke','Honda NSX racing through a mountain tunnel','Datsun 240Z beneath a huge Japanese rising sun','Toyota AE86 drifting down a mountain pass','Mitsubishi Evo blasting through a wet nighttime street','Subaru WRX STI throwing snow through a rally corner','Nissan Silvia S15 surrounded by graffiti and tire smoke','Honda Civic Type R rendered in aggressive manga-panel style')
$sets['Cars Supercars'] = @('Porsche 911 carving through an Alpine switchback','Classic air-cooled Porsche 911 beneath a warm sunset','Porsche 911 GT3 screaming around a racetrack','Ferrari F40 in red-and-black graphic tattoo style','Ferrari Testarossa beneath 1980s Miami neon','Lamborghini Countach in retro airbrush style','Lamborghini Aventador surrounded by shattered-glass geometry','McLaren supercar streaking through abstract watercolor speed','Mercedes AMG emerging through dark architectural shadows','BMW M3 E30 attacking a mountain road')
$sets['Cars European Classics'] = @('Aston Martin DB5 in elegant black-and-grey realism','Jaguar E-Type surrounded by Art Nouveau ornament','Classic Mercedes 300SL with its gullwing doors raised','Porsche 356 driving along the California coast','Vintage Ferrari racing through the Italian countryside','Classic Mini Cooper tearing through a rainy London street','Volkswagen Beetle covered in colorful 1960s psychedelic flowers','Volkswagen bus loaded with surfboards beside an ocean sunset','Vintage Fiat 500 squeezed into a beautiful Italian street','Classic Rolls-Royce rendered like dark luxury Gothic artwork')
$sets['Cars Race Cars'] = @('Formula racing car at full speed beneath exploding track lights','Le Mans prototype racing through nighttime rain','Vintage Formula One car surrounded by checkered flags','NASCAR-style stock car throwing sparks against the wall','Dragster launching with the rear tires wrinkling under power','Funny car engulfed in flames at the starting line','Rally car airborne over a forest road','Drift car sideways with a giant wall of smoke','Porsche endurance racer glowing beneath Le Mans lights','Race car cockpit reflected inside a drivers helmet visor')
$sets['Cars Hot Rods'] = @('1932 Ford hot rod with exposed engine and traditional flames','Chopped Mercury lead sled cruising beneath streetlights','Rat rod with rusty metal texture and exposed mechanical parts','Blown hot rod engine towering through the hood','Flame-painted custom coupe in bold American Traditional style','Slammed vintage pickup with mirror-finish chrome wheels','Custom hot rod rendered in exaggerated New School style','Black hot rod emerging from red smoke','Vintage drag car with hand-painted racing graphics','Chopped custom car beneath a giant desert moon')
$sets['Cars Off-Road and Trucks'] = @('Ford Bronco climbing through rocky desert terrain','Toyota Land Cruiser crossing a river beneath mountains','Jeep crawling over impossible boulders','Baja trophy truck flying through desert dust','Lifted pickup blasting through deep mud','Classic Chevrolet pickup in a dramatic Western desert scene','Ford Raptor jumping across desert terrain','Off-road truck beneath a giant star-filled sky','Slammed custom pickup with brilliant candy paint','Monster truck crushing a tiny row of cars in comic-book style')
$sets['Cars Engines and Parts'] = @('V8 engine rendered like an anatomical heart','Turbocharger surrounded by Japanese clouds and lightning','Supercharger exploding through flames','Chrome wheel reflecting an entire nighttime city','Piston and connecting rod rendered like sacred mechanical ornament','Racing steering wheel surrounded by speed lines and telemetry graphics','Gearshift and tachometer at redline in black-and-grey realism','Engine bay transformed into biomechanical machinery','Brake rotor glowing red with sparks flying outward','Twin turbochargers arranged like mechanical lungs')
$sets['Cars Surreal Dream Cars'] = @('Porsche 911 breaking through a Renaissance painting','Mustang racing alongside a wild horse','Skyline GT-R driving through a cyberpunk city','Lowrider cruising beneath an enormous moon with chrome reflections everywhere','Ferrari exploding out of a stained-glass window','Corvette Stingray surrounded by ocean waves like a Japanese composition','Lamborghini rendered entirely as liquid chrome','Classic muscle car half realistic and half blueprint drawing','Supercar dissolving into speed smoke and geometric fragments','Dream-car garage lineup disappearing into cinematic darkness')
$renamed = @()
foreach ($k in @($sets.Keys)) { $sets[$k] = @($sets[$k] | % { $n = $_; if ($tk.ContainsKey((& $slug $n))) { $r = "$n in Car Style"; $renamed += "  RENAMED: $n  ->  $r  (the first was under " + $tk[(& $slug $n)] + ")"; $r } else { $n } }) }
if ($renamed) { $renamed } else { "  no clashes" }
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:cars" ", imaginative high-end automotive tattoo artwork centered on the car itself as the hero, preserve the recognizable proportions, silhouette, stance, bodywork, headlights, grille, wheels and defining mechanical characteristics of the specific vehicle named; make cars look desirable, powerful and visually dramatic rather than generic; freely vary camera angle including aggressive front three-quarter, rear three-quarter, side profile, head-on, low-angle, racing and motion perspectives; freely vary between photorealism, black-and-grey realism, Chicano automotive art, American Traditional, Neo-Traditional, Japanese influence, New School, blackwork, sketch, watercolor, airbrush, retro poster art, stained glass, cyberpunk, biomechanical, surrealism and experimental contemporary tattoo art according to the concept; use chrome, reflections, candy paint, rust, smoke, flames, rain, neon, asphalt, glass, metal, speed and environmental texture when appropriate; the vehicle must remain visually dominant even when scenery or decorative elements are present; tattoo artwork alone, never worn on skin or a body, complete composition filling the frame, isolated on a clean plain background when the concept does not require an environmental scene, no brand logos, no badges, no watermark" --remote
RUN "CATEGORY Cars :: Cars Muscle Cars, Cars Lowriders, Cars JDM Legends, Cars Supercars, Cars European Classics, Cars Race Cars, Cars Hot Rods, Cars Off-Road and Trucks, Cars Engines and Parts, Cars Surreal Dream Cars"
foreach ($k in $sets.Keys) { RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) | Out-Null; Start-Sleep -Seconds 2 }
"  checking all 10 sets saved..."
Start-Sleep -Seconds 3
$raw2 = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$t2 = $raw2 | ConvertFrom-Json
if ($t2.specific) { foreach ($k in $sets.Keys) { $h = @($t2.specific.$k | ? { $_ }).Count; if ($h -ne 10) { "  REPAIRED " + $k + ": had " + $h; RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) | Out-Null; Start-Sleep -Seconds 2 } } }

RUN "FACE 1964 Chevrolet Impala lowrider in black-and-grey Chicano realism"
}
}
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Motorcycles")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Motorcycles before (empty = new category) =="
"  " + (@($tt.subjects."Motorcycles") -join ", ")
$kinds = 'Motorcycles Harley Davidson','Motorcycles Choppers','Motorcycles Bobbers and Cafe Racers','Motorcycles Superbikes','Motorcycles Vintage Classics','Motorcycles Cruisers','Motorcycles Dirt and Adventure','Motorcycles Trackers and Scramblers','Motorcycles Engines and Parts','Motorcycles Surreal Bikes'
$kh = $kinds | ? { $tk.ContainsKey((& $slug $_)) }
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
$sets = [ordered]@{}
$sets['Motorcycles Harley Davidson'] = @('Harley-Davidson Road Glide head-on sharknose fairing dominating the composition','Harley-Davidson Street Glide cruising through a desert sunset','Harley-Davidson Fat Boy in chrome-heavy black-and-grey realism','Harley-Davidson Sportster beneath a glowing neon motel sign','Harley-Davidson Low Rider leaned aggressively through a mountain curve','Harley-Davidson Breakout with huge rear tire and polished chrome','Vintage Harley Panhead in gritty black-and-grey realism','Vintage Harley Knucklehead rendered as bold American Traditional','Harley Shovelhead surrounded by black smoke and flames','Outrageous custom bagger with candy paint and oversized front wheel')
$sets['Motorcycles Choppers'] = @('Long-fork old-school chopper beneath an enormous desert moon','1970s chopper with tall sissy bar and psychedelic paint','Chrome chopper surrounded by American Traditional roses','Murdered-out chopper emerging through dense black smoke','Gothic chopper surrounded by cathedral architecture','Flame-painted chopper screaming across a desert highway','Chrome chopper surrounded by Japanese clouds and peonies','Chopper reflected in a pool of gasoline and rainbow oil','Vintage chopper rendered as rough woodcut artwork','Futuristic chopper rendered entirely in liquid chrome')
$sets['Motorcycles Bobbers and Cafe Racers'] = @('Stripped-down bobber with fat tires in brutal blackwork','Vintage bobber beneath an abandoned gas-station sign','Black bobber surrounded by blood-red roses','Bobber side profile using dramatic negative space','Rat-bike bobber with rust and distressed-metal texture','Cafe racer speeding through a rainy city at night','Cafe racer beneath glowing neon signs','Vintage cafe racer rendered like a 1960s racing poster','Black-and-gold cafe racer with ornamental mechanical details','Cafe racer exploding through loose watercolor brush strokes')
$sets['Motorcycles Superbikes'] = @('Ducati Panigale leaned impossibly low through a racetrack corner','BMW S1000RR accelerating beneath dramatic track lights','Yamaha R1 racing through nighttime rain','Kawasaki Ninja screaming through a tunnel','Suzuki Hayabusa rendered in hyperreal metallic detail','Honda Fireblade throwing sparks through a corner','Superbike rider fully tucked at extreme speed','Two superbikes fighting side-by-side through a corner','Superbike exploding through shattered geometric fragments','Futuristic superbike surrounded by cyberpunk neon')
$sets['Motorcycles Vintage Classics'] = @('Triumph Bonneville carving through the English countryside','Vintage Norton cafe racer in detailed engraving style','Classic BMW boxer motorcycle beneath Alpine mountains','Vintage Honda CB750 with gorgeous exposed engine detail','Classic Indian motorcycle in rich vintage color','Triumph motorcycle surrounded by faded roses and racing graphics','1960s motorcycle rendered like a weathered screen-printed poster','Vintage Grand Prix motorcycle leaned through a historic circuit','Antique motorcycle engine rendered like luxury jewelry','Barn-find motorcycle with rust peeling paint and wildflowers')
$sets['Motorcycles Cruisers'] = @('Indian Scout in dramatic black-and-grey realism','Indian Chief surrounded by storm clouds and endless highway','Modern muscle cruiser beneath nighttime city lights','Power cruiser doing a massive burnout','Blacked-out muscle bike surrounded by brutalist black shapes','Polished custom cruiser reflecting fire across its chrome','Cruiser photographed from an extreme ground-level front angle','Cruiser riding through heavy rain with headlight blazing','Sinister black cruiser surrounded by ravens and smoke','Touring motorcycle crossing an endless American desert')
$sets['Motorcycles Dirt and Adventure'] = @('Motocross rider flying over an enormous dirt jump','Dirt bike throwing a wall of mud directly toward the viewer','Motocross bike upside down during a huge backflip','Enduro motorcycle climbing an impossible rocky mountain','Adventure motorcycle blasting across a rushing river','Adventure bike beneath enormous snow-covered mountains','Desert rally motorcycle racing through giant dunes','Dirt bike exploding through watercolor splashes of mud','Motocross machine rendered in aggressive graffiti style','Dirt bike jumping through a giant ring of fire')
$sets['Motorcycles Trackers and Scramblers'] = @('Flat-track motorcycle sliding completely sideways around a dirt oval','Street tracker beneath industrial city lights','Vintage board-track racer on an old wooden racing circuit','Speedway motorcycle throwing dirt in stark blackwork','Custom tracker surrounded by bold geometric graphics','Scrambler climbing a rocky hillside','Scrambler crossing a shallow forest stream','Triumph-style scrambler beneath enormous mountain scenery','Desert scrambler surrounded by cactus beneath a blazing sun','Urban scrambler ripping through a graffiti-covered alley')
$sets['Motorcycles Engines and Parts'] = @('V-twin engine rendered like a mechanical anatomical heart','Motorcycle engine exploded into hundreds of floating mechanical pieces','Chrome exhaust pipes twisting into ornamental filigree','Spoked motorcycle wheel transforming into a sacred geometric mandala','Heavy motorcycle chain wrapped around a skull','Fuel tank covered by an elaborate Japanese dragon composition','Piston surrounded by lightning and fire','Motorcycle headlight glowing like an enormous eye','Handlebars tank and gauges viewed from the riders perspective','Polished chrome V-twin reflecting a tiny highway landscape')
$sets['Motorcycles Surreal Bikes'] = @('Harley-style chopper fighting through enormous Japanese ocean waves','Ducati-style superbike smashing through a stained-glass window','Black motorcycle emerging from an enormous Gothic cathedral doorway','Chopper surrounded by giant peonies lightning and black clouds','Cafe racer transitioning from finished motorcycle into loose sketch and blueprint lines','Superbike transformed into biomechanical muscle bone and machinery','Chrome cruiser riding across the surface of the moon','Vintage motorcycle bursting through an ornate tarot-card composition','Black chopper surrounded by flames like a 1980s heavy-metal album cover','Outrageous show bike combining engraved chrome candy paint gold leaf and jeweled mechanical details')
$renamed = @()
foreach ($k in @($sets.Keys)) { $sets[$k] = @($sets[$k] | % { $n = $_; if ($tk.ContainsKey((& $slug $n))) { $r = "$n in Motorcycle Style"; $renamed += "  RENAMED: $n  ->  $r  (the first was under " + $tk[(& $slug $n)] + ")"; $r } else { $n } }) }
if ($renamed) { $renamed } else { "  no clashes" }
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:motorcycles" ", high-end motorcycle tattoo artwork with the motorcycle itself as the visual hero, preserve the recognizable proportions, silhouette, stance, frame geometry, fuel tank, engine configuration, forks, wheels, exhaust, fairings and defining characteristics of the specific motorcycle or build named; make the motorcycle desirable, powerful and unmistakably the focus of the artwork; celebrate motorcycle culture, custom craftsmanship, engines, speed, chrome and attitude; freely vary between photorealism, black-and-grey realism, American Traditional, Neo-Traditional, Japanese tattoo influence, Chicano influence, blackwork, woodcut, engraving, sketch, watercolor, vintage racing graphics, psychedelic art, Gothic, biomechanical, cyberpunk, stained glass, liquid chrome, airbrush and experimental contemporary tattoo art according to the individual concept; freely use polished chrome, brushed metal, blackened steel, candy paint, pinstriping, engraved metal, worn leather, rust, gasoline reflections, smoke, flames, rain, asphalt, dirt, mud, neon and dramatic lighting when appropriate; freely vary perspective between dramatic side profile, aggressive front three-quarter, rear three-quarter, head-on, extreme low-angle, rider point-of-view, leaned cornering and high-speed action; when a rider or environment appears the motorcycle must remain visually dominant; tattoo artwork alone, never worn on skin or a body, complete design filling the frame, clean plain background unless an environmental scene is integral to the concept, no brand logos, no badges, no watermark" --remote
RUN "CATEGORY Motorcycles :: Motorcycles Harley Davidson, Motorcycles Choppers, Motorcycles Bobbers and Cafe Racers, Motorcycles Superbikes, Motorcycles Vintage Classics, Motorcycles Cruisers, Motorcycles Dirt and Adventure, Motorcycles Trackers and Scramblers, Motorcycles Engines and Parts, Motorcycles Surreal Bikes"
foreach ($k in $sets.Keys) { RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) | Out-Null; Start-Sleep -Seconds 2 }
"  checking all 10 sets saved..."
Start-Sleep -Seconds 3
$raw2 = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$t2 = $raw2 | ConvertFrom-Json
if ($t2.specific) { foreach ($k in $sets.Keys) { $h = @($t2.specific.$k | ? { $_ }).Count; if ($h -ne 10) { "  REPAIRED " + $k + ": had " + $h; RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) | Out-Null; Start-Sleep -Seconds 2 } } }

RUN "FACE Long-fork old-school chopper beneath an enormous desert moon"
}
}
