cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
# Read-only: checks that every new set is in the catalog. Changes nothing.
$ns = "9c2ba111589e48c6ba5ad1b924ae8809"
$tree = (npx wrangler kv key get --namespace-id $ns "card:tree" --remote 2>$null | Out-String).Trim() | ConvertFrom-Json
"categories in catalog: " + @($tree.subjects.PSObject.Properties).Count
$have = @($tree.subjects."Dark Ornamental" | ? { $_ }); $want = @('Dark Ornamental II Gothic Architecture','Dark Ornamental II Dark Jewelry','Dark Ornamental II Thorns Blades and Sharp Forms','Dark Ornamental II Black Filigree and Lace','Dark Ornamental II Woodcut Engraving and Ancient Ornament','Dark Ornamental II Dark Botanical Ornament','Dark Ornamental II Symmetry and Body Architecture','Dark Ornamental II Dark Ornament In Motion','Dark Ornamental II Heavy Black and Negative Space','Dark Ornamental II Push Dark Ornamental'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Dark Ornamental - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Dark Ornamental - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Biomechanical" | ? { $_ }); $want = @('Biomechanical Classic Biomechanical','Biomechanical The Human Machine','Biomechanical Bio-Organic Evolution','Biomechanical Cybernetic Future','Biomechanical Alien Anatomy','Biomechanical Beauty','Biomechanical Color Chrome and Energy','Biomechanical Dark Biomechanical','Biomechanical Impossible Transformations','Biomechanical Push Biomechanical'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Biomechanical - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Biomechanical - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Heavy Blackwork" | ? { $_ }); $want = @('Heavy Blackwork Heavy Abstract','Heavy Blackwork Animals Built From Black','Heavy Blackwork Dark Nature','Heavy Blackwork Primal and Ancient','Heavy Blackwork Monsters and Dark Creatures','Heavy Blackwork Black Architecture','Heavy Blackwork Illustrative Heavy Blackwork','Heavy Blackwork Black Body Flow','Heavy Blackwork Black and Skin','Heavy Blackwork Push Heavy Blackwork'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Heavy Blackwork - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Heavy Blackwork - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Blackout" | ? { $_ }); $want = @('Blackout Pure Blackout','Blackout With Windows','Blackout Hidden Images','Blackout Patterns Carved From Black','Blackout In Motion','Blackout Organic Blackout','Blackout Rework And Transformation','Blackout Fade Fragment and Dissolve','Blackout Body Sculpture','Blackout What The Hell Did They Do'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Blackout - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Blackout - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Dark Fantasy" | ? { $_ }); $want = @('Dark Fantasy Dark Warriors','Dark Fantasy Dragons','Dark Fantasy Demons and Creatures','Dark Fantasy Women Of The Dark World','Dark Fantasy Fallen Angels','Dark Fantasy Cursed Nature','Dark Fantasy Kingdoms and Ruins','Dark Fantasy Gods and Mythic Beings','Dark Fantasy In Color','Dark Fantasy Epic Body Worlds'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Dark Fantasy - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Dark Fantasy - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Brutalism" | ? { $_ }); $want = @('Brutalism Concrete Giants','Brutalism Impossible Architecture','Brutalism The Body Becomes Architecture','Brutalism Human Against The Monument','Brutalism Brutalist Abstraction','Brutalism Ruins and Abandoned Worlds','Brutalism Industrial Brutalism','Brutalism Concrete and Color','Brutalism Surreal Human Architecture','Brutalism Push Brutalism'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Brutalism - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Brutalism - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Japanese Fusion" | ? { $_ }); $want = @('Japanese Fusion Black Grey and One Color','Japanese Fusion Japanese Meets Realism','Japanese Fusion Neo-Japanese Color','Japanese Fusion Japanese Meets Blackwork','Japanese Fusion Japanese Meets Surrealism','Japanese Fusion Japanese Meets Modern Illustration','Japanese Fusion Japanese Meets Graphic Art','Japanese Fusion Unexpected Subjects','Japanese Fusion Small and Medium Masterpieces','Japanese Fusion Artists Playground'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Japanese Fusion - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Japanese Fusion - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Mixed Media" | ? { $_ }); $want = @('Mixed Media Realism Collides With Graphic Art','Mixed Media Engraving Meets The Future','Mixed Media Photograph Memory and Art','Mixed Media Typography Becomes Art','Mixed Media Torn Worlds','Mixed Media Material Collisions','Mixed Media Eras Collide','Mixed Media Nature Collides With Design','Mixed Media Controlled Chaos','Mixed Media Artists Playground'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Mixed Media - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Mixed Media - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Neo-Traditional" | ? { $_ }); $want = @('Neo-Traditional II Neo-Traditional Classics Reimagined','Neo-Traditional II Beautiful Women and Powerful Characters','Neo-Traditional II Animals In Motion','Neo-Traditional II Dragons Monsters and Mythical Creatures','Neo-Traditional II Flowers Nature and Flow','Neo-Traditional II Gothic Dark and Macabre','Neo-Traditional II Fantasy and Impossible Worlds','Neo-Traditional II Modern Subjects In Neo-Traditional','Neo-Traditional II Designed Around The Body','Neo-Traditional II Push Neo-Traditional'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Neo-Traditional - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Neo-Traditional - " + $miss.Count + " of 10 new sets missing" }
$have = @($tree.subjects."Metalwork" | ? { $_ }); $want = @('Metalwork Forged Creatures','Metalwork Metal Botanicals','Metalwork Engraved Metal','Metalwork Ancient Metals','Metalwork Armor and Body Architecture','Metalwork Gold Silver and Precious Metal','Metalwork Industrial Metal','Metalwork Color In Metal','Metalwork Impossible Metalwork','Metalwork Masterpieces'); $miss = @($want | ? { $have -notcontains $_ })
if ($miss.Count -eq 0) { "  OK       Metalwork - all 10 new sets there (" + $have.Count + " sets in all)" } else { "  MISSING  Metalwork - " + $miss.Count + " of 10 new sets missing" }
