$t = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote
$j = $t | ConvertFrom-Json
$slug = { param($x) ($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-') }
$all = @{}; foreach ($c in $j.subjects.PSObject.Properties) { $all[(& $slug $c.Name)] = "category $($c.Name)"; foreach ($k in $c.Value) { $all[(& $slug $k)] = "kind $k in $($c.Name)"; foreach ($l in @($j.specific.$k)) { if ($l) { $all[(& $slug $l)] = "design $l in $k" } } } }
$new = 'Liquid Chrome Splash','Melting Chrome Smiley','Melting Chrome Flower','Liquid Chrome Crown','Chrome Water Drop','Chrome Puddle','Chrome Drip Heart','Chrome Splash Crown','Chrome Melting Moon','Chrome Morph','Chrome Cyber Sigil','Chrome Cyber Tribal','Chrome Cyber Heart','Chrome Cyber Butterfly','Chrome Cyber Angel','Chrome Cyber Cross','Chrome Digital Thorns','Chrome Cyber Star','Chrome Alien Glyph','Chrome Portal','Chrome Robot Heart','Chrome Robot Hand','Chrome Cyborg Eye','Chrome Mechanical Spine','Chrome Piston','Chrome Gear Cluster','Chrome Machine Skull','Chrome Mechanical Beetle','Chrome Mechanical Dragonfly','Chrome Mechanical Heart And Flower','Chrome Teddy Bear','Chrome Rubber Duck','Chrome Balloon Dog','Chrome Gummy Bear','Chrome Cherries','Chrome Strawberry','Chrome Mushroom','Chrome Frog','Chrome Ghost','Chrome Dinosaur','Chrome Tiara','Chrome Heart Locket','Chrome Pearl Heart','Chrome Safety Pin','Chrome High Heel','Chrome Perfume Bottle','Chrome Razor Blade','Chrome Key','Chrome Lock','Chrome Charm Cluster','Chrome Peony','Chrome Orchid','Chrome Thorns','Chrome Vine','Chrome Spider','Chrome Scorpion','Chrome Beetle','Chrome Bat','Chrome Shark','Chrome Octopus','Chrome Saturn','Chrome Crescent Moon','Chrome Sun','Chrome Eclipse','Chrome UFO','Chrome Astronaut','Chrome Eye Portal','Chrome Melting Face','Chrome Face And Flower','Chrome Hand Holding Liquid','Chrome Flip Phone','Chrome CD','Chrome Digital Camera','Chrome Headphones','Chrome Dice','Chrome 8-Ball','Chrome Cowboy Boot','Chrome Cowboy Hat','Chrome Lettering','Impossible Chrome Object'
$hits = $new | Where-Object { $all.ContainsKey((& $slug $_)) } | ForEach-Object { "CLASH: $_ -> " + $all[(& $slug $_)] }
if ($hits) { $hits; "STOPPED - nothing saved or drawn" } else {
"no clashes - building"
RUN "LEAVES Chrome Designs :: Chrome Butterfly, Chrome Rose, Chrome Heart, Chrome Skull, Chrome Serpent, Chrome Flame, Chrome Dagger, Chrome Wing, Chrome Orb, Chrome Cross, Chrome Star, Chrome Teardrop, Chrome Chain Link, Chrome Bow, Chrome Angel, Chrome Horse, Chrome Koi, Chrome Moth, Chrome Hand, Chrome Lips, Liquid Chrome Splash, Melting Chrome Smiley, Melting Chrome Flower, Liquid Chrome Crown, Chrome Water Drop, Chrome Puddle, Chrome Drip Heart, Chrome Splash Crown, Chrome Melting Moon, Chrome Morph, Chrome Cyber Sigil, Chrome Cyber Tribal, Chrome Cyber Heart, Chrome Cyber Butterfly, Chrome Cyber Angel, Chrome Cyber Cross, Chrome Digital Thorns, Chrome Cyber Star, Chrome Alien Glyph, Chrome Portal, Chrome Robot Heart, Chrome Robot Hand, Chrome Cyborg Eye, Chrome Mechanical Spine, Chrome Piston, Chrome Gear Cluster, Chrome Machine Skull, Chrome Mechanical Beetle, Chrome Mechanical Dragonfly, Chrome Mechanical Heart And Flower, Chrome Teddy Bear, Chrome Rubber Duck, Chrome Balloon Dog, Chrome Gummy Bear, Chrome Cherries, Chrome Strawberry, Chrome Mushroom, Chrome Frog, Chrome Ghost, Chrome Dinosaur, Chrome Tiara, Chrome Heart Locket, Chrome Pearl Heart, Chrome Safety Pin, Chrome High Heel, Chrome Perfume Bottle, Chrome Razor Blade, Chrome Key, Chrome Lock, Chrome Charm Cluster, Chrome Peony, Chrome Orchid, Chrome Thorns, Chrome Vine, Chrome Spider, Chrome Scorpion, Chrome Beetle, Chrome Bat, Chrome Shark, Chrome Octopus, Chrome Saturn, Chrome Crescent Moon, Chrome Sun, Chrome Eclipse, Chrome UFO, Chrome Astronaut, Chrome Eye Portal, Chrome Melting Face, Chrome Face And Flower, Chrome Hand Holding Liquid, Chrome Flip Phone, Chrome CD, Chrome Digital Camera, Chrome Headphones, Chrome Dice, Chrome 8-Ball, Chrome Cowboy Boot, Chrome Cowboy Hat, Chrome Lettering, Impossible Chrome Object"
RUN "SETKV build:liquid-chrome-splash a liquid chrome splash - free-floating splash of liquid metal frozen in motion"
RUN "SETKV build:melting-chrome-smiley a melting chrome smiley - happy face literally dripping apart"
RUN "SETKV build:melting-chrome-flower a melting chrome flower - flower whose petals dissolve into liquid metal"
RUN "SETKV build:liquid-chrome-crown a liquid chrome crown - crown appearing to melt downward"
RUN "SETKV build:chrome-water-drop a chrome water drop - hyper-reflective suspended droplet"
RUN "SETKV build:chrome-puddle a chrome puddle - abstract mercury-like puddle with impossible reflections"
RUN "SETKV build:chrome-drip-heart a chrome drip heart - rounded heart melting into long metallic drips"
RUN "SETKV build:chrome-splash-crown a chrome splash crown - crown formed entirely from a splash of liquid metal"
RUN "SETKV build:chrome-melting-moon a chrome melting moon - crescent moon becoming liquid"
RUN "SETKV build:chrome-morph a chrome morph - completely abstract metallic object transitioning between solid and liquid"
RUN "SETKV build:chrome-cyber-sigil a chrome cyber sigil - original symmetrical futuristic metallic glyph"
RUN "SETKV build:chrome-cyber-tribal a chrome cyber tribal - sharp liquid-metal neo-tribal form"
RUN "SETKV build:chrome-cyber-heart a chrome cyber heart - mechanical and liquid futuristic heart"
RUN "SETKV build:chrome-cyber-butterfly a chrome cyber butterfly - butterfly reconstructed as sharp metallic cyber forms"
RUN "SETKV build:chrome-cyber-angel a chrome cyber angel - futuristic metallic angel figure"
RUN "SETKV build:chrome-cyber-cross a chrome cyber cross - sharp futuristic metallic cross"
RUN "SETKV build:chrome-digital-thorns a chrome digital thorns - flowing thorn-like metallic structure"
RUN "SETKV build:chrome-cyber-star a chrome cyber star - complex futuristic metallic star"
RUN "SETKV build:chrome-alien-glyph a chrome alien glyph - original unknown-looking metallic symbol"
RUN "SETKV build:chrome-portal a chrome portal - reflective liquid-metal ring opening into darkness"
RUN "SETKV build:chrome-robot-heart a chrome robot heart - mechanical heart with tubes, chambers and polished metal"
RUN "SETKV build:chrome-robot-hand a chrome robot hand - articulated futuristic mechanical hand"
RUN "SETKV build:chrome-cyborg-eye a chrome cyborg eye - mechanical eye surrounded by polished components"
RUN "SETKV build:chrome-mechanical-spine a chrome mechanical spine - segmented futuristic metallic vertebrae"
RUN "SETKV build:chrome-piston a chrome piston - industrial hydraulic piston rendered like polished metal"
RUN "SETKV build:chrome-gear-cluster a chrome gear cluster - interlocking reflective mechanical gears"
RUN "SETKV build:chrome-machine-skull a chrome machine skull - human skull fused with futuristic machinery"
RUN "SETKV build:chrome-mechanical-beetle a chrome mechanical beetle - insect built from polished mechanical components"
RUN "SETKV build:chrome-mechanical-dragonfly a chrome mechanical dragonfly - delicate machine and insect hybrid"
RUN "SETKV build:chrome-mechanical-heart-and-flower a chrome mechanical heart and flower - hard machinery growing into an organic flower"
RUN "SETKV build:chrome-teddy-bear a chrome teddy bear - soft teddy bear impossibly rendered as reflective metal"
RUN "SETKV build:chrome-rubber-duck a chrome rubber duck - cute duck transformed into polished chrome"
RUN "SETKV build:chrome-balloon-dog a chrome balloon dog - inflated balloon-animal form in mirror chrome"
RUN "SETKV build:chrome-gummy-bear a chrome gummy bear - translucent-looking candy form interpreted as reflective metal"
RUN "SETKV build:chrome-cherries a chrome cherries - two rounded dripping metallic cherries"
RUN "SETKV build:chrome-strawberry a chrome strawberry - reflective strawberry with exaggerated metallic seeds"
RUN "SETKV build:chrome-mushroom a chrome mushroom - cute mushroom made from liquid chrome"
RUN "SETKV build:chrome-frog a chrome frog - small polished-metal frog"
RUN "SETKV build:chrome-ghost a chrome ghost - friendly flowing ghost rendered as reflective metal"
RUN "SETKV build:chrome-dinosaur a chrome dinosaur - tiny playful dinosaur transformed into polished chrome"
RUN "SETKV build:chrome-tiara a chrome tiara - highly polished jeweled metallic tiara"
RUN "SETKV build:chrome-heart-locket a chrome heart locket - reflective heart locket with tiny hinge and chain"
RUN "SETKV build:chrome-pearl-heart a chrome pearl heart - metallic pearls arranged into a heart"
RUN "SETKV build:chrome-safety-pin a chrome safety pin - oversized polished safety pin"
RUN "SETKV build:chrome-high-heel a chrome high heel - sculptural futuristic metallic shoe"
RUN "SETKV build:chrome-perfume-bottle a chrome perfume bottle - luxury bottle rendered in reflective chrome"
RUN "SETKV build:chrome-razor-blade a chrome razor blade - classic razor blade transformed into polished sculptural metal"
RUN "SETKV build:chrome-key a chrome key - ornate futuristic reflective key"
RUN "SETKV build:chrome-lock a chrome lock - small reflective padlock with heart-shaped keyhole"
RUN "SETKV build:chrome-charm-cluster a chrome charm cluster - tiny heart, star, key, bow, moon charms hanging together"
RUN "SETKV build:chrome-peony a chrome peony - large flower sculpted entirely from reflective metal"
RUN "SETKV build:chrome-orchid a chrome orchid - elegant metallic orchid"
RUN "SETKV build:chrome-thorns chrome thorns - twisting polished-metal thorn branch"
RUN "SETKV build:chrome-vine a chrome vine - organic climbing vine transformed into flowing metal"
RUN "SETKV build:chrome-spider a chrome spider - highly reflective sculptural spider"
RUN "SETKV build:chrome-scorpion a chrome scorpion - hard polished-metal scorpion"
RUN "SETKV build:chrome-beetle a chrome beetle - mirror-finish beetle shell"
RUN "SETKV build:chrome-bat a chrome bat - spread-wing bat rendered like liquid metal"
RUN "SETKV build:chrome-shark a chrome shark - sleek shark appearing cast from polished chrome"
RUN "SETKV build:chrome-octopus a chrome octopus - flowing reflective tentacles emphasizing liquid-metal effect"
RUN "SETKV build:chrome-saturn a chrome saturn - reflective planet and rings"
RUN "SETKV build:chrome-crescent-moon a chrome crescent moon - mirror-polished crescent"
RUN "SETKV build:chrome-sun a chrome sun - liquid-metal sun with flowing rays"
RUN "SETKV build:chrome-eclipse a chrome eclipse - dark center surrounded by reflective metallic corona"
RUN "SETKV build:chrome-ufo a chrome UFO - retro flying saucer transformed into mirror chrome"
RUN "SETKV build:chrome-astronaut a chrome astronaut - reflective astronaut figure with distorted visor reflections"
RUN "SETKV build:chrome-eye-portal a chrome eye portal - human eye opening into a liquid-metal portal"
RUN "SETKV build:chrome-melting-face a chrome melting face - human face partially dissolving into metallic liquid"
RUN "SETKV build:chrome-face-and-flower a chrome face and flower - classical face morphing into polished metallic flowers"
RUN "SETKV build:chrome-hand-holding-liquid a chrome hand holding liquid - metallic hand with chrome liquid flowing through the fingers"
RUN "SETKV build:chrome-flip-phone a chrome flip phone - early-2000s flip phone rendered as futuristic mirror metal"
RUN "SETKV build:chrome-cd a chrome CD - highly reflective disc with exaggerated light distortion"
RUN "SETKV build:chrome-digital-camera a chrome digital camera - compact retro digital camera transformed into chrome"
RUN "SETKV build:chrome-headphones a chrome headphones - futuristic reflective headphones"
RUN "SETKV build:chrome-dice chrome dice - pair of rounded mirror-metal dice"
RUN "SETKV build:chrome-8-ball a chrome 8-ball - billiard ball interpreted as polished metallic sphere"
RUN "SETKV build:chrome-cowboy-boot a chrome cowboy boot - western boot sculpted from liquid chrome"
RUN "SETKV build:chrome-cowboy-hat a chrome cowboy hat - soft hat shape impossibly formed from polished metal"
RUN "SETKV build:chrome-lettering chrome lettering - one original word rendered as inflated and liquid chrome typography"
RUN "SETKV build:impossible-chrome-object an impossible chrome object - a surreal object that could not physically exist: part flower, part machine, part liquid, part creature, all mirror chrome"
Start-Sleep -Seconds 60
RUN "LEAVES Chrome Designs :: Chrome Butterfly, Chrome Rose, Chrome Heart, Chrome Skull, Chrome Serpent, Chrome Flame, Chrome Dagger, Chrome Wing, Chrome Orb, Chrome Cross, Chrome Star, Chrome Teardrop, Chrome Chain Link, Chrome Bow, Chrome Angel, Chrome Horse, Chrome Koi, Chrome Moth, Chrome Hand, Chrome Lips, Liquid Chrome Splash, Melting Chrome Smiley, Melting Chrome Flower, Liquid Chrome Crown, Chrome Water Drop, Chrome Puddle, Chrome Drip Heart, Chrome Splash Crown, Chrome Melting Moon, Chrome Morph, Chrome Cyber Sigil, Chrome Cyber Tribal, Chrome Cyber Heart, Chrome Cyber Butterfly, Chrome Cyber Angel, Chrome Cyber Cross, Chrome Digital Thorns, Chrome Cyber Star, Chrome Alien Glyph, Chrome Portal, Chrome Robot Heart, Chrome Robot Hand, Chrome Cyborg Eye, Chrome Mechanical Spine, Chrome Piston, Chrome Gear Cluster, Chrome Machine Skull, Chrome Mechanical Beetle, Chrome Mechanical Dragonfly, Chrome Mechanical Heart And Flower, Chrome Teddy Bear, Chrome Rubber Duck, Chrome Balloon Dog, Chrome Gummy Bear, Chrome Cherries, Chrome Strawberry, Chrome Mushroom, Chrome Frog, Chrome Ghost, Chrome Dinosaur, Chrome Tiara, Chrome Heart Locket, Chrome Pearl Heart, Chrome Safety Pin, Chrome High Heel, Chrome Perfume Bottle, Chrome Razor Blade, Chrome Key, Chrome Lock, Chrome Charm Cluster, Chrome Peony, Chrome Orchid, Chrome Thorns, Chrome Vine, Chrome Spider, Chrome Scorpion, Chrome Beetle, Chrome Bat, Chrome Shark, Chrome Octopus, Chrome Saturn, Chrome Crescent Moon, Chrome Sun, Chrome Eclipse, Chrome UFO, Chrome Astronaut, Chrome Eye Portal, Chrome Melting Face, Chrome Face And Flower, Chrome Hand Holding Liquid, Chrome Flip Phone, Chrome CD, Chrome Digital Camera, Chrome Headphones, Chrome Dice, Chrome 8-Ball, Chrome Cowboy Boot, Chrome Cowboy Hat, Chrome Lettering, Impossible Chrome Object"
Start-Sleep -Seconds 60
RUN "LEAVES Chrome Designs"
RUN "GETKV render:chrome-designs"
RUN "REDO Liquid Chrome Splash, Melting Chrome Smiley, Melting Chrome Flower, Liquid Chrome Crown, Chrome Water Drop"
RUN "REDO Chrome Puddle, Chrome Drip Heart, Chrome Splash Crown, Chrome Melting Moon, Chrome Morph"
RUN "REDO Chrome Cyber Sigil, Chrome Cyber Tribal, Chrome Cyber Heart, Chrome Cyber Butterfly, Chrome Cyber Angel"
RUN "REDO Chrome Cyber Cross, Chrome Digital Thorns, Chrome Cyber Star, Chrome Alien Glyph, Chrome Portal"
RUN "REDO Chrome Robot Heart, Chrome Robot Hand, Chrome Cyborg Eye, Chrome Mechanical Spine, Chrome Piston"
RUN "REDO Chrome Gear Cluster, Chrome Machine Skull, Chrome Mechanical Beetle, Chrome Mechanical Dragonfly, Chrome Mechanical Heart And Flower"
RUN "REDO Chrome Teddy Bear, Chrome Rubber Duck, Chrome Balloon Dog, Chrome Gummy Bear, Chrome Cherries"
RUN "REDO Chrome Strawberry, Chrome Mushroom, Chrome Frog, Chrome Ghost, Chrome Dinosaur"
RUN "REDO Chrome Tiara, Chrome Heart Locket, Chrome Pearl Heart, Chrome Safety Pin, Chrome High Heel"
RUN "REDO Chrome Perfume Bottle, Chrome Razor Blade, Chrome Key, Chrome Lock, Chrome Charm Cluster"
RUN "REDO Chrome Peony, Chrome Orchid, Chrome Thorns, Chrome Vine, Chrome Spider"
RUN "REDO Chrome Scorpion, Chrome Beetle, Chrome Bat, Chrome Shark, Chrome Octopus"
RUN "REDO Chrome Saturn, Chrome Crescent Moon, Chrome Sun, Chrome Eclipse, Chrome UFO"
RUN "REDO Chrome Astronaut, Chrome Eye Portal, Chrome Melting Face, Chrome Face And Flower, Chrome Hand Holding Liquid"
RUN "REDO Chrome Flip Phone, Chrome CD, Chrome Digital Camera, Chrome Headphones, Chrome Dice"
RUN "REDO Chrome 8-Ball, Chrome Cowboy Boot, Chrome Cowboy Hat, Chrome Lettering, Impossible Chrome Object"
Start-Sleep -Seconds 30
RUN "SHEET Chrome Designs"
RUN "SHEET Liquid Chrome"
RUN "BROWSE"
}
