cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Cyberpunk")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Cyberpunk Style Characters','Cyberpunk Style Masks and Helmets','Cyberpunk Style Cityscapes','Cyberpunk Style Tech and Weapons','Cyberpunk Style Animals','Cyberpunk Style Glitch','Cyberpunk Style Neon Symbols','Cyberpunk Style Circuits and Bands','Cyberpunk Style Small','Cyberpunk Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Hacker girl with a neon visor'] = 'The tattoo: hacker girl with a neon visor. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Street samurai with a glowing katana'] = 'The tattoo: street samurai with a glowing katana. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Cyborg woman with a chrome jaw'] = 'The tattoo: cyborg woman with a chrome jaw. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Masked runner in a hooded jacket'] = 'The tattoo: masked runner in a hooded jacket. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Android face with circuit tears'] = 'The tattoo: android face with circuit tears. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Netrunner wearing a cable headset'] = 'The tattoo: netrunner wearing a cable headset. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Mercenary with a robotic arm'] = 'The tattoo: mercenary with a robotic arm. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Punk with a glowing mohawk'] = 'The tattoo: punk with a glowing mohawk. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Geisha android with neon fans'] = 'The tattoo: geisha android with neon fans. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Cyber monk with glowing prayer beads'] = 'The tattoo: cyber monk with glowing prayer beads. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Oni mask with neon circuits'] = 'The tattoo: oni mask with neon circuits. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Gas mask with glowing filters'] = 'The tattoo: gas mask with glowing filters. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Chrome skull helmet'] = 'The tattoo: chrome skull helmet. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Visor helmet reflecting a city'] = 'The tattoo: visor helmet reflecting a city. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Respirator mask with LED lines'] = 'The tattoo: respirator mask with led lines. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cracked android face plate'] = 'The tattoo: cracked android face plate. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Samurai helmet with neon trim'] = 'The tattoo: samurai helmet with neon trim. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Biker helmet with a glowing visor'] = 'The tattoo: biker helmet with a glowing visor. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Hannya mask with wires'] = 'The tattoo: hannya mask with wires. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Kitsune mask in neon'] = 'The tattoo: kitsune mask in neon. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Neon city in the rain'] = 'The tattoo: neon city in the rain. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Megatower skyline at night'] = 'The tattoo: megatower skyline at night. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Flying car over a neon street'] = 'The tattoo: flying car over a neon street. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Rainy alley with glowing signs'] = 'The tattoo: rainy alley with glowing signs. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['City inside a circle frame'] = 'The tattoo: city inside a circle frame. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Elevated train through neon towers'] = 'The tattoo: elevated train through neon towers. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Rooftop view of a glowing city'] = 'The tattoo: rooftop view of a glowing city. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Neon bridge over dark water'] = 'The tattoo: neon bridge over dark water. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Street market under neon lights'] = 'The tattoo: street market under neon lights. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['City under a giant moon'] = 'The tattoo: city under a giant moon. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Glowing katana'] = 'The tattoo: glowing katana. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Neon plasma pistol'] = 'The tattoo: neon plasma pistol. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Robotic hand with wires'] = 'The tattoo: robotic hand with wires. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Data chip with glowing traces'] = 'The tattoo: data chip with glowing traces. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Cybernetic eye implant'] = 'The tattoo: cybernetic eye implant. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Drone with red lights'] = 'The tattoo: drone with red lights. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Hover motorcycle'] = 'The tattoo: hover motorcycle. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Mechanical heart with cables'] = 'The tattoo: mechanical heart with cables. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Neural jack port'] = 'The tattoo: neural jack port. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Holographic butterfly'] = 'The tattoo: holographic butterfly. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Robot cat with glowing eyes'] = 'The tattoo: robot cat with glowing eyes. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Cyber koi fish in neon'] = 'The tattoo: cyber koi fish in neon. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Chrome wolf head'] = 'The tattoo: chrome wolf head. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Robotic snake with circuits'] = 'The tattoo: robotic snake with circuits. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Neon jellyfish drone'] = 'The tattoo: neon jellyfish drone. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Mechanical raven'] = 'The tattoo: mechanical raven. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Cyber dragon with LED scales'] = 'The tattoo: cyber dragon with led scales. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Robotic tiger'] = 'The tattoo: robotic tiger. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Holographic fox'] = 'The tattoo: holographic fox. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Mechanical owl with lens eyes'] = 'The tattoo: mechanical owl with lens eyes. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Glitched skull'] = 'The tattoo: glitched skull. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Glitched rose'] = 'The tattoo: glitched rose. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Pixelated heart breaking apart'] = 'The tattoo: pixelated heart breaking apart. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glitched eye'] = 'The tattoo: glitched eye. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glitched butterfly'] = 'The tattoo: glitched butterfly. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Glitched face split in pieces'] = 'The tattoo: glitched face split in pieces. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Glitched moon'] = 'The tattoo: glitched moon. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Glitched snake'] = 'The tattoo: glitched snake. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glitched hand'] = 'The tattoo: glitched hand. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glitched lotus'] = 'The tattoo: glitched lotus. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Neon lotus'] = 'The tattoo: neon lotus. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Neon dagger'] = 'The tattoo: neon dagger. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Neon all-seeing eye'] = 'The tattoo: neon all-seeing eye. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Neon skull and crossbones'] = 'The tattoo: neon skull and crossbones. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Neon lightning bolt'] = 'The tattoo: neon lightning bolt. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Neon heart with wires'] = 'The tattoo: neon heart with wires. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Neon triangle portal'] = 'The tattoo: neon triangle portal. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Neon crescent moon'] = 'The tattoo: neon crescent moon. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Neon rose in a circuit frame'] = 'The tattoo: neon rose in a circuit frame. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Neon hourglass'] = 'The tattoo: neon hourglass. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Circuit board armband'] = 'The tattoo: circuit board armband. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glowing wire band'] = 'The tattoo: glowing wire band. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Circuit traces down the arm'] = 'The tattoo: circuit traces down the arm. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Neon barcode band'] = 'The tattoo: neon barcode band. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Data stream band'] = 'The tattoo: data stream band. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Microchip cuff'] = 'The tattoo: microchip cuff. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Circuit ankle band'] = 'The tattoo: circuit ankle band. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glowing neon ring band'] = 'The tattoo: glowing neon ring band. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Cable wrap band'] = 'The tattoo: cable wrap band. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Pulse line circuit band'] = 'The tattoo: pulse line circuit band. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny neon eye'] = 'The tattoo: tiny neon eye. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small microchip'] = 'The tattoo: small microchip. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny glitched heart'] = 'The tattoo: tiny glitched heart. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small neon katana'] = 'The tattoo: small neon katana. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny robot head'] = 'The tattoo: tiny robot head. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small circuit lotus'] = 'The tattoo: small circuit lotus. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny neon skull'] = 'The tattoo: tiny neon skull. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small cyber eye'] = 'The tattoo: small cyber eye. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny drone'] = 'The tattoo: tiny drone. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small neon moon'] = 'The tattoo: small neon moon. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Neon city back piece'] = 'The tattoo: neon city back piece. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Cyborg woman half sleeve'] = 'The tattoo: cyborg woman half sleeve. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$b['Samurai and katana thigh piece'] = 'The tattoo: samurai and katana thigh piece. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Circuit board full sleeve'] = 'The tattoo: circuit board full sleeve. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Cyber dragon leg sleeve'] = 'The tattoo: cyber dragon leg sleeve. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['Neon oni mask forearm piece'] = 'The tattoo: neon oni mask forearm piece. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Robotic arm armour sleeve'] = 'The tattoo: robotic arm armour sleeve. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Glitched skull chest piece'] = 'The tattoo: glitched skull chest piece. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his chest, shirtless'
$b['Cyber koi calf piece'] = 'The tattoo: cyber koi calf piece. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Neon city spine piece'] = 'The tattoo: neon city spine piece. Cyberpunk tattoo, a neon future city look, bold black linework with glowing neon pink cyan and violet light, dark shadows with electric highlights, chrome and circuit details, gritty high tech low life feel, illustrative tattoo style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is down his spine, shirtless, seen from behind'
$sets = [ordered]@{}
$sets['Cyberpunk Style Characters'] = @('Hacker girl with a neon visor','Street samurai with a glowing katana','Cyborg woman with a chrome jaw','Masked runner in a hooded jacket','Android face with circuit tears','Netrunner wearing a cable headset','Mercenary with a robotic arm','Punk with a glowing mohawk','Geisha android with neon fans','Cyber monk with glowing prayer beads')
$sets['Cyberpunk Style Masks and Helmets'] = @('Oni mask with neon circuits','Gas mask with glowing filters','Chrome skull helmet','Visor helmet reflecting a city','Respirator mask with LED lines','Cracked android face plate','Samurai helmet with neon trim','Biker helmet with a glowing visor','Hannya mask with wires','Kitsune mask in neon')
$sets['Cyberpunk Style Cityscapes'] = @('Neon city in the rain','Megatower skyline at night','Flying car over a neon street','Rainy alley with glowing signs','City inside a circle frame','Elevated train through neon towers','Rooftop view of a glowing city','Neon bridge over dark water','Street market under neon lights','City under a giant moon')
$sets['Cyberpunk Style Tech and Weapons'] = @('Glowing katana','Neon plasma pistol','Robotic hand with wires','Data chip with glowing traces','Cybernetic eye implant','Drone with red lights','Hover motorcycle','Mechanical heart with cables','Neural jack port','Holographic butterfly')
$sets['Cyberpunk Style Animals'] = @('Robot cat with glowing eyes','Cyber koi fish in neon','Chrome wolf head','Robotic snake with circuits','Neon jellyfish drone','Mechanical raven','Cyber dragon with LED scales','Robotic tiger','Holographic fox','Mechanical owl with lens eyes')
$sets['Cyberpunk Style Glitch'] = @('Glitched skull','Glitched rose','Pixelated heart breaking apart','Glitched eye','Glitched butterfly','Glitched face split in pieces','Glitched moon','Glitched snake','Glitched hand','Glitched lotus')
$sets['Cyberpunk Style Neon Symbols'] = @('Neon lotus','Neon dagger','Neon all-seeing eye','Neon skull and crossbones','Neon lightning bolt','Neon heart with wires','Neon triangle portal','Neon crescent moon','Neon rose in a circuit frame','Neon hourglass')
$sets['Cyberpunk Style Circuits and Bands'] = @('Circuit board armband','Glowing wire band','Circuit traces down the arm','Neon barcode band','Data stream band','Microchip cuff','Circuit ankle band','Glowing neon ring band','Cable wrap band','Pulse line circuit band')
$sets['Cyberpunk Style Small'] = @('Tiny neon eye','Small microchip','Tiny glitched heart','Small neon katana','Tiny robot head','Small circuit lotus','Tiny neon skull','Small cyber eye','Tiny drone','Small neon moon')
$sets['Cyberpunk Style Large Pieces'] = @('Neon city back piece','Cyborg woman half sleeve','Samurai and katana thigh piece','Circuit board full sleeve','Cyber dragon leg sleeve','Neon oni mask forearm piece','Robotic arm armour sleeve','Glitched skull chest piece','Cyber koi calf piece','Neon city spine piece')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Cyberpunk Style" } else { $n } }
"== Cyberpunk before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:cyberpunk" --remote 2>$null | Out-Null
RUN "CATEGORY Cyberpunk :: Cyberpunk Style Characters, Cyberpunk Style Masks and Helmets, Cyberpunk Style Cityscapes, Cyberpunk Style Tech and Weapons, Cyberpunk Style Animals, Cyberpunk Style Glitch, Cyberpunk Style Neon Symbols, Cyberpunk Style Circuits and Bands, Cyberpunk Style Small, Cyberpunk Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Cyberpunk Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Cyberpunk Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Oni mask with neon circuits"))
}
}
