cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Cyber-Realism")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Android woman with half her face open'] = 'The tattoo: android woman with half her face open. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cyborg man with an exposed mechanical jaw'] = 'The tattoo: cyborg man with an exposed mechanical jaw. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Robotic eye replacing a human eye'] = 'The tattoo: robotic eye replacing a human eye. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Chrome mask over a face'] = 'The tattoo: chrome mask over a face. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Face splitting to reveal circuitry'] = 'The tattoo: face splitting to reveal circuitry. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Cyborg skull with glowing eyes'] = 'The tattoo: cyborg skull with glowing eyes. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Android with cables for hair'] = 'The tattoo: android with cables for hair. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Porcelain android face'] = 'The tattoo: porcelain android face. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Cybernetic warrior helmet'] = 'The tattoo: cybernetic warrior helmet. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Android with a glowing halo'] = 'The tattoo: android with a glowing halo. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Robotic wolf head'] = 'The tattoo: robotic wolf head. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Mechanical lion'] = 'The tattoo: mechanical lion. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Cyber owl'] = 'The tattoo: cyber owl. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Chrome snake'] = 'The tattoo: chrome snake. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Robotic tiger face'] = 'The tattoo: robotic tiger face. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Mechanical hummingbird'] = 'The tattoo: mechanical hummingbird. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Cyber stag with antenna antlers'] = 'The tattoo: cyber stag with antenna antlers. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Robotic jellyfish'] = 'The tattoo: robotic jellyfish. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Mechanical spider'] = 'The tattoo: mechanical spider. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Chrome eagle'] = 'The tattoo: chrome eagle. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Robotic hand'] = 'The tattoo: robotic hand. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Mechanical heart with pistons'] = 'The tattoo: mechanical heart with pistons. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Chrome spine'] = 'The tattoo: chrome spine. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Cyborg arm with hydraulics'] = 'The tattoo: cyborg arm with hydraulics. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Exposed mechanical knee'] = 'The tattoo: exposed mechanical knee. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Robotic skull'] = 'The tattoo: robotic skull. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Mechanical lungs'] = 'The tattoo: mechanical lungs. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Circuit brain'] = 'The tattoo: circuit brain. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Chrome ribcage'] = 'The tattoo: chrome ribcage. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bionic eye'] = 'The tattoo: bionic eye. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Liquid chrome heart'] = 'The tattoo: liquid chrome heart. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Chrome butterfly'] = 'The tattoo: chrome butterfly. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Melting chrome skull'] = 'The tattoo: melting chrome skull. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Liquid metal rose'] = 'The tattoo: liquid metal rose. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Chrome dagger'] = 'The tattoo: chrome dagger. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Mercury drops'] = 'The tattoo: mercury drops. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Chrome angel wings'] = 'The tattoo: chrome angel wings. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Chrome serpent coil'] = 'The tattoo: chrome serpent coil. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Liquid chrome flame'] = 'The tattoo: liquid chrome flame. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Chrome star'] = 'The tattoo: chrome star. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Circuit board tree'] = 'The tattoo: circuit board tree. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Glowing circuit heart'] = 'The tattoo: glowing circuit heart. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Microchip with roots'] = 'The tattoo: microchip with roots. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Circuit lines forming a face'] = 'The tattoo: circuit lines forming a face. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Motherboard skull'] = 'The tattoo: motherboard skull. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Circuit wolf'] = 'The tattoo: circuit wolf. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Fiber optic flowers'] = 'The tattoo: fiber optic flowers. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Glowing data cables'] = 'The tattoo: glowing data cables. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Circuit moth'] = 'The tattoo: circuit moth. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Circuit lotus'] = 'The tattoo: circuit lotus. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Skin parting to reveal gears'] = 'The tattoo: skin parting to reveal gears. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Skin parting to reveal circuitry'] = 'The tattoo: skin parting to reveal circuitry. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Skin peeling back to chrome muscle'] = 'The tattoo: skin peeling back to chrome muscle. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Zipper opening to machinery'] = 'The tattoo: zipper opening to machinery. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Scales opening to reveal cables'] = 'The tattoo: scales opening to reveal cables. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Crack revealing a glowing core'] = 'The tattoo: crack revealing a glowing core. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Skin opening to reveal a robotic eye'] = 'The tattoo: skin opening to reveal a robotic eye. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Panels sliding open on the arm'] = 'The tattoo: panels sliding open on the arm. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Skin parting to reveal pistons'] = 'The tattoo: skin parting to reveal pistons. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Skin opening onto a glowing reactor'] = 'The tattoo: skin opening onto a glowing reactor. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Retro-futuristic helmet'] = 'The tattoo: retro-futuristic helmet. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['VR headset with reflections'] = 'The tattoo: vr headset with reflections. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Robot hand holding a rose'] = 'The tattoo: robot hand holding a rose. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Glowing power core'] = 'The tattoo: glowing power core. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Hovering drone'] = 'The tattoo: hovering drone. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Holographic cube'] = 'The tattoo: holographic cube. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Mech suit chest plate'] = 'The tattoo: mech suit chest plate. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Futuristic katana'] = 'The tattoo: futuristic katana. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Glowing data crystal'] = 'The tattoo: glowing data crystal. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Orbiting satellite'] = 'The tattoo: orbiting satellite. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Astronaut with a cracked visor reflecting earth'] = 'The tattoo: astronaut with a cracked visor reflecting earth. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Mech warrior'] = 'The tattoo: mech warrior. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Android angel'] = 'The tattoo: android angel. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Cyber samurai'] = 'The tattoo: cyber samurai. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Robot holding a small bird'] = 'The tattoo: robot holding a small bird. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cyber ninja'] = 'The tattoo: cyber ninja. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Bounty hunter helmet'] = 'The tattoo: bounty hunter helmet. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Space marine helmet'] = 'The tattoo: space marine helmet. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Praying android'] = 'The tattoo: praying android. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Cyborg queen'] = 'The tattoo: cyborg queen. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Flower with mechanical petals'] = 'The tattoo: flower with mechanical petals. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Tree with cable roots'] = 'The tattoo: tree with cable roots. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Butterfly with circuit wings'] = 'The tattoo: butterfly with circuit wings. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Heart half flesh half machine'] = 'The tattoo: heart half flesh half machine. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Lion half fur half chrome'] = 'The tattoo: lion half fur half chrome. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Rose with a microchip center'] = 'The tattoo: rose with a microchip center. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Hand half bone half metal'] = 'The tattoo: hand half bone half metal. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Skull with growing wires'] = 'The tattoo: skull with growing wires. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Moth with chrome wings'] = 'The tattoo: moth with chrome wings. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Eye with a gear iris'] = 'The tattoo: eye with a gear iris. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Biomechanical sleeve'] = 'The tattoo: biomechanical sleeve. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Cyborg spine back piece'] = 'The tattoo: cyborg spine back piece. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his back, shirtless, seen from behind'
$b['Chrome chest plate'] = 'The tattoo: chrome chest plate. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Circuit forearm piece'] = 'The tattoo: circuit forearm piece. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Mechanical leg sleeve'] = 'The tattoo: mechanical leg sleeve. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['Android face thigh piece'] = 'The tattoo: android face thigh piece. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Robotic shoulder armour'] = 'The tattoo: robotic shoulder armour. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Gears and pistons calf piece'] = 'The tattoo: gears and pistons calf piece. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Cyber wings back piece'] = 'The tattoo: cyber wings back piece. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Gears and cables half sleeve'] = 'The tattoo: gears and cables half sleeve. Cyber-realism tattoo art, photorealistic rendering of futuristic technology fused with living forms, polished chrome and liquid metal, exposed gears, pistons, cables and glowing circuitry, precise reflections and deep dimensional shadows, cool steel greys with subtle electric blue or cyan glow, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$sets = [ordered]@{}
$sets['Cyber-Realism Style Cyborg Faces'] = @('Android woman with half her face open','Cyborg man with an exposed mechanical jaw','Robotic eye replacing a human eye','Chrome mask over a face','Face splitting to reveal circuitry','Cyborg skull with glowing eyes','Android with cables for hair','Porcelain android face','Cybernetic warrior helmet','Android with a glowing halo')
$sets['Cyber-Realism Style Robotic Animals'] = @('Robotic wolf head','Mechanical lion','Cyber owl','Chrome snake','Robotic tiger face','Mechanical hummingbird','Cyber stag with antenna antlers','Robotic jellyfish','Mechanical spider','Chrome eagle')
$sets['Cyber-Realism Style Mechanical Anatomy'] = @('Robotic hand','Mechanical heart with pistons','Chrome spine','Cyborg arm with hydraulics','Exposed mechanical knee','Robotic skull','Mechanical lungs','Circuit brain','Chrome ribcage','Bionic eye')
$sets['Cyber-Realism Style Liquid Chrome'] = @('Liquid chrome heart','Chrome butterfly','Melting chrome skull','Liquid metal rose','Chrome dagger','Mercury drops','Chrome angel wings','Chrome serpent coil','Liquid chrome flame','Chrome star')
$sets['Cyber-Realism Style Circuitry'] = @('Circuit board tree','Glowing circuit heart','Microchip with roots','Circuit lines forming a face','Motherboard skull','Circuit wolf','Fiber optic flowers','Glowing data cables','Circuit moth','Circuit lotus')
$sets['Cyber-Realism Style Under the Skin'] = @('Skin parting to reveal gears','Skin parting to reveal circuitry','Skin peeling back to chrome muscle','Zipper opening to machinery','Scales opening to reveal cables','Crack revealing a glowing core','Skin opening to reveal a robotic eye','Panels sliding open on the arm','Skin parting to reveal pistons','Skin opening onto a glowing reactor')
$sets['Cyber-Realism Style Tech Objects'] = @('Retro-futuristic helmet','VR headset with reflections','Robot hand holding a rose','Glowing power core','Hovering drone','Holographic cube','Mech suit chest plate','Futuristic katana','Glowing data crystal','Orbiting satellite')
$sets['Cyber-Realism Style Sci-Fi Figures'] = @('Astronaut with a cracked visor reflecting earth','Mech warrior','Android angel','Cyber samurai','Robot holding a small bird','Cyber ninja','Bounty hunter helmet','Space marine helmet','Praying android','Cyborg queen')
$sets['Cyber-Realism Style Organic Tech'] = @('Flower with mechanical petals','Tree with cable roots','Butterfly with circuit wings','Heart half flesh half machine','Lion half fur half chrome','Rose with a microchip center','Hand half bone half metal','Skull with growing wires','Moth with chrome wings','Eye with a gear iris')
$sets['Cyber-Realism Style Large Pieces'] = @('Biomechanical sleeve','Cyborg spine back piece','Chrome chest plate','Circuit forearm piece','Mechanical leg sleeve','Android face thigh piece','Robotic shoulder armour','Gears and pistons calf piece','Cyber wings back piece','Gears and cables half sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Cyber-Realism Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Cyber-Realism Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Cyber-Realism Style$','') -ne 'Robotic wolf head' })
}
"== drawing " + $all.Count + " Cyber-Realism split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK Cyber-Realism"
RUN "SHEET Cyber-Realism"
}
