cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Dark Surrealism")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Head opening like a door to the night sky'] = 'The tattoo: head opening like a door to the night sky. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Face dissolving into birds'] = 'The tattoo: face dissolving into birds. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Face cracked open with a forest inside'] = 'The tattoo: face cracked open with a forest inside. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woman with moths pouring from her hair'] = 'The tattoo: woman with moths pouring from her hair. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Face made of tree roots'] = 'The tattoo: face made of tree roots. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Faceless figure with a moon for a head'] = 'The tattoo: faceless figure with a moon for a head. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Face split like a puzzle'] = 'The tattoo: face split like a puzzle. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Weeping stone face'] = 'The tattoo: weeping stone face. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Face melting into smoke'] = 'The tattoo: face melting into smoke. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Head as a birdcage with a raven inside'] = 'The tattoo: head as a birdcage with a raven inside. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Hand with an eye in the palm'] = 'The tattoo: hand with an eye in the palm. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Hands growing from the ground'] = 'The tattoo: hands growing from the ground. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Eye holding a tiny staircase'] = 'The tattoo: eye holding a tiny staircase. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Eye as a keyhole to a dark room'] = 'The tattoo: eye as a keyhole to a dark room. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Hand made of branches'] = 'The tattoo: hand made of branches. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Hands holding a burning moon'] = 'The tattoo: hands holding a burning moon. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Eye crying a waterfall'] = 'The tattoo: eye crying a waterfall. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Hand reaching from a black ocean'] = 'The tattoo: hand reaching from a black ocean. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Fingers turning into roots'] = 'The tattoo: fingers turning into roots. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Eye inside a seashell'] = 'The tattoo: eye inside a seashell. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Lone tree on a floating island'] = 'The tattoo: lone tree on a floating island. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Staircase into a black void'] = 'The tattoo: staircase into a black void. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Door standing in an empty desert'] = 'The tattoo: door standing in an empty desert. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Moon chained to a mountain'] = 'The tattoo: moon chained to a mountain. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Lighthouse in a sea of clouds'] = 'The tattoo: lighthouse in a sea of clouds. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Ship sailing across the night sky'] = 'The tattoo: ship sailing across the night sky. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Upside-down forest'] = 'The tattoo: upside-down forest. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['City inside a teardrop'] = 'The tattoo: city inside a teardrop. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Clock tower sinking into sand'] = 'The tattoo: clock tower sinking into sand. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bridge to nowhere in fog'] = 'The tattoo: bridge to nowhere in fog. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Whale floating over a forest'] = 'The tattoo: whale floating over a forest. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Wolf made of smoke'] = 'The tattoo: wolf made of smoke. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Deer with antlers full of stars'] = 'The tattoo: deer with antlers full of stars. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Raven with a keyhole chest'] = 'The tattoo: raven with a keyhole chest. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Jellyfish floating in a dark sky'] = 'The tattoo: jellyfish floating in a dark sky. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Owl with clock eyes'] = 'The tattoo: owl with clock eyes. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Snake shedding into a river'] = 'The tattoo: snake shedding into a river. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Moth with a moon in its wings'] = 'The tattoo: moth with a moon in its wings. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Elephant on long thin legs'] = 'The tattoo: elephant on long thin legs. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Horse made of running ink'] = 'The tattoo: horse made of running ink. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Melting pocket watch'] = 'The tattoo: melting pocket watch. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Hourglass draining a city'] = 'The tattoo: hourglass draining a city. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Clock face cracking into moths'] = 'The tattoo: clock face cracking into moths. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Candle burning a forest'] = 'The tattoo: candle burning a forest. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Rotting apple with a galaxy inside'] = 'The tattoo: rotting apple with a galaxy inside. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Wilting rose turning to dust'] = 'The tattoo: wilting rose turning to dust. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Skull with an hourglass inside'] = 'The tattoo: skull with an hourglass inside. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Broken mirror reflecting another face'] = 'The tattoo: broken mirror reflecting another face. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Chess piece casting a giant shadow'] = 'The tattoo: chess piece casting a giant shadow. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Burning match with a city for a flame'] = 'The tattoo: burning match with a city for a flame. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Hooded figure with a lantern in fog'] = 'The tattoo: hooded figure with a lantern in fog. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woman walking on the moon'] = 'The tattoo: woman walking on the moon. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Man with an umbrella in a rain of stars'] = 'The tattoo: man with an umbrella in a rain of stars. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Figure climbing a ladder to the moon'] = 'The tattoo: figure climbing a ladder to the moon. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Small figure holding a moon balloon'] = 'The tattoo: small figure holding a moon balloon. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Astronaut floating in a dark ocean'] = 'The tattoo: astronaut floating in a dark ocean. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Puppet with cut strings'] = 'The tattoo: puppet with cut strings. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Two figures facing across a void'] = 'The tattoo: two figures facing across a void. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Figure with a cage for a body'] = 'The tattoo: figure with a cage for a body. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Silhouette dissolving into ravens'] = 'The tattoo: silhouette dissolving into ravens. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Lightbulb with a storm inside'] = 'The tattoo: lightbulb with a storm inside. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Bottle holding an ocean storm'] = 'The tattoo: bottle holding an ocean storm. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Teacup holding a whirlpool'] = 'The tattoo: teacup holding a whirlpool. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Book opening into a forest'] = 'The tattoo: book opening into a forest. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Birdcage holding the moon'] = 'The tattoo: birdcage holding the moon. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Umbrella raining from inside'] = 'The tattoo: umbrella raining from inside. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Key made of bones'] = 'The tattoo: key made of bones. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Chair floating in the void'] = 'The tattoo: chair floating in the void. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Window open in the sky'] = 'The tattoo: window open in the sky. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Telephone with roots'] = 'The tattoo: telephone with roots. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Sleeping moon face'] = 'The tattoo: sleeping moon face. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Eclipse with an eye'] = 'The tattoo: eclipse with an eye. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Planet cracking open'] = 'The tattoo: planet cracking open. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Stars falling like tears'] = 'The tattoo: stars falling like tears. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Sun with a hole into the void'] = 'The tattoo: sun with a hole into the void. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Moon on a hook'] = 'The tattoo: moon on a hook. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Constellation forming a skull'] = 'The tattoo: constellation forming a skull. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Crescent moon swing'] = 'The tattoo: crescent moon swing. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black hole swallowing a rose'] = 'The tattoo: black hole swallowing a rose. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Night sky inside a skull'] = 'The tattoo: night sky inside a skull. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny floating island'] = 'The tattoo: tiny floating island. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small moon in a jar'] = 'The tattoo: small moon in a jar. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny door in a cloud'] = 'The tattoo: tiny door in a cloud. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small melting clock'] = 'The tattoo: small melting clock. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Little hand with an eye'] = 'The tattoo: little hand with an eye. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Tiny staircase to a star'] = 'The tattoo: tiny staircase to a star. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Small birdcage with a moon'] = 'The tattoo: small birdcage with a moon. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Tiny whale in the sky'] = 'The tattoo: tiny whale in the sky. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Small keyhole eye'] = 'The tattoo: small keyhole eye. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny lightbulb with a moon'] = 'The tattoo: tiny lightbulb with a moon. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Dreamscape back piece'] = 'The tattoo: dreamscape back piece. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Melting city sleeve'] = 'The tattoo: melting city sleeve. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Floating islands thigh piece'] = 'The tattoo: floating islands thigh piece. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Face opening to a forest chest piece'] = 'The tattoo: face opening to a forest chest piece. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is across his chest, shirtless'
$b['Staircase to the moon spine piece'] = 'The tattoo: staircase to the moon spine piece. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is down her spine, seen from behind in a low open-back top'
$b['Whale over a forest forearm piece'] = 'The tattoo: whale over a forest forearm piece. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Clocks and ravens half sleeve'] = 'The tattoo: clocks and ravens half sleeve. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Void doorway calf piece'] = 'The tattoo: void doorway calf piece. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Moth portrait shoulder piece'] = 'The tattoo: moth portrait shoulder piece. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Night ocean leg sleeve'] = 'The tattoo: night ocean leg sleeve. Dark surrealism tattoo art, dreamlike and melancholic impossible scenes, black and grey realism with soft smoky gradients, deep shadows and quiet light, haunting but beautiful, designed like work from a top surrealist blackwork tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Dark Surrealism Style Faces'] = @('Head opening like a door to the night sky','Face dissolving into birds','Face cracked open with a forest inside','Woman with moths pouring from her hair','Face made of tree roots','Faceless figure with a moon for a head','Face split like a puzzle','Weeping stone face','Face melting into smoke','Head as a birdcage with a raven inside')
$sets['Dark Surrealism Style Hands and Eyes'] = @('Hand with an eye in the palm','Hands growing from the ground','Eye holding a tiny staircase','Eye as a keyhole to a dark room','Hand made of branches','Hands holding a burning moon','Eye crying a waterfall','Hand reaching from a black ocean','Fingers turning into roots','Eye inside a seashell')
$sets['Dark Surrealism Style Dreamscapes'] = @('Lone tree on a floating island','Staircase into a black void','Door standing in an empty desert','Moon chained to a mountain','Lighthouse in a sea of clouds','Ship sailing across the night sky','Upside-down forest','City inside a teardrop','Clock tower sinking into sand','Bridge to nowhere in fog')
$sets['Dark Surrealism Style Animals'] = @('Whale floating over a forest','Wolf made of smoke','Deer with antlers full of stars','Raven with a keyhole chest','Jellyfish floating in a dark sky','Owl with clock eyes','Snake shedding into a river','Moth with a moon in its wings','Elephant on long thin legs','Horse made of running ink')
$sets['Dark Surrealism Style Time and Decay'] = @('Melting pocket watch','Hourglass draining a city','Clock face cracking into moths','Candle burning a forest','Rotting apple with a galaxy inside','Wilting rose turning to dust','Skull with an hourglass inside','Broken mirror reflecting another face','Chess piece casting a giant shadow','Burning match with a city for a flame')
$sets['Dark Surrealism Style Figures'] = @('Hooded figure with a lantern in fog','Woman walking on the moon','Man with an umbrella in a rain of stars','Figure climbing a ladder to the moon','Small figure holding a moon balloon','Astronaut floating in a dark ocean','Puppet with cut strings','Two figures facing across a void','Figure with a cage for a body','Silhouette dissolving into ravens')
$sets['Dark Surrealism Style Objects'] = @('Lightbulb with a storm inside','Bottle holding an ocean storm','Teacup holding a whirlpool','Book opening into a forest','Birdcage holding the moon','Umbrella raining from inside','Key made of bones','Chair floating in the void','Window open in the sky','Telephone with roots')
$sets['Dark Surrealism Style Celestial'] = @('Sleeping moon face','Eclipse with an eye','Planet cracking open','Stars falling like tears','Sun with a hole into the void','Moon on a hook','Constellation forming a skull','Crescent moon swing','Black hole swallowing a rose','Night sky inside a skull')
$sets['Dark Surrealism Style Small'] = @('Tiny floating island','Small moon in a jar','Tiny door in a cloud','Small melting clock','Little hand with an eye','Tiny staircase to a star','Small birdcage with a moon','Tiny whale in the sky','Small keyhole eye','Tiny lightbulb with a moon')
$sets['Dark Surrealism Style Large Pieces'] = @('Dreamscape back piece','Melting city sleeve','Floating islands thigh piece','Face opening to a forest chest piece','Staircase to the moon spine piece','Whale over a forest forearm piece','Clocks and ravens half sleeve','Void doorway calf piece','Moth portrait shoulder piece','Night ocean leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Dark Surrealism Style" } else { $n } }
"== Dark Surrealism before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:dark-surrealism" --remote 2>$null | Out-Null
RUN "CATEGORY Dark Surrealism :: Dark Surrealism Style Faces, Dark Surrealism Style Hands and Eyes, Dark Surrealism Style Dreamscapes, Dark Surrealism Style Animals, Dark Surrealism Style Time and Decay, Dark Surrealism Style Figures, Dark Surrealism Style Objects, Dark Surrealism Style Celestial, Dark Surrealism Style Small, Dark Surrealism Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Dark Surrealism Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Dark Surrealism Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Head opening like a door to the night sky"))
}
}
