cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Dark Romantic")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Black rose with thorns'] = 'The tattoo: black rose with thorns. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Oxblood rose dripping'] = 'The tattoo: oxblood rose dripping. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Rose wrapped in barbed thorns'] = 'The tattoo: rose wrapped in barbed thorns. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Wilting rose under a glass dome'] = 'The tattoo: wilting rose under a glass dome. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Rose and dagger'] = 'The tattoo: rose and dagger. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Rose growing from a skull'] = 'The tattoo: rose growing from a skull. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pair of black roses'] = 'The tattoo: pair of black roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Rose tied with a velvet ribbon'] = 'The tattoo: rose tied with a velvet ribbon. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Rose bleeding into lace'] = 'The tattoo: rose bleeding into lace. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Thorned rose vine'] = 'The tattoo: thorned rose vine. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Bleeding sacred heart'] = 'The tattoo: bleeding sacred heart. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Heart pierced by three swords'] = 'The tattoo: heart pierced by three swords. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Anatomical heart with roses'] = 'The tattoo: anatomical heart with roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Heart in a cage'] = 'The tattoo: heart in a cage. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Heart locket hiding a skull'] = 'The tattoo: heart locket hiding a skull. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Heart wrapped in thorns'] = 'The tattoo: heart wrapped in thorns. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Heart with bat wings'] = 'The tattoo: heart with bat wings. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cracked porcelain heart'] = 'The tattoo: cracked porcelain heart. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Heart padlock and key'] = 'The tattoo: heart padlock and key. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Heart in a bell jar'] = 'The tattoo: heart in a bell jar. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Skeleton lovers embracing'] = 'The tattoo: skeleton lovers embracing. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Vampire couple'] = 'The tattoo: vampire couple. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Two hands tied by a red thread'] = 'The tattoo: two hands tied by a red thread. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Kiss beneath a veil'] = 'The tattoo: kiss beneath a veil. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Skeleton bride and groom'] = 'The tattoo: skeleton bride and groom. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Ghost lovers'] = 'The tattoo: ghost lovers. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Two swans with necks entwined'] = 'The tattoo: two swans with necks entwined. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Moth and flame lovers'] = 'The tattoo: moth and flame lovers. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Hands holding through iron bars'] = 'The tattoo: hands holding through iron bars. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Lovers silhouetted in a full moon'] = 'The tattoo: lovers silhouetted in a full moon. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Antique locket'] = 'The tattoo: antique locket. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Poison bottle with a skull'] = 'The tattoo: poison bottle with a skull. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Candelabra with dripping candles'] = 'The tattoo: candelabra with dripping candles. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Ornate hand mirror'] = 'The tattoo: ornate hand mirror. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Victorian skull cameo'] = 'The tattoo: victorian skull cameo. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pocket watch wrapped in roses'] = 'The tattoo: pocket watch wrapped in roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Antique key with a bow'] = 'The tattoo: antique key with a bow. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Raven quill and inkwell'] = 'The tattoo: raven quill and inkwell. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Perfume vial with a ribbon'] = 'The tattoo: perfume vial with a ribbon. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Gothic dagger with a jeweled hilt'] = 'The tattoo: gothic dagger with a jeweled hilt. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Raven perched on a rose'] = 'The tattoo: raven perched on a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Black moth with a skull mark'] = 'The tattoo: black moth with a skull mark. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Bat with lace wings'] = 'The tattoo: bat with lace wings. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black cat with a ribbon'] = 'The tattoo: black cat with a ribbon. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Serpent around a rose'] = 'The tattoo: serpent around a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black swan'] = 'The tattoo: black swan. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Spider in a lace web'] = 'The tattoo: spider in a lace web. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Owl on a candelabra'] = 'The tattoo: owl on a candelabra. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Wolf with a rose in its mouth'] = 'The tattoo: wolf with a rose in its mouth. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Crow carrying a ring'] = 'The tattoo: crow carrying a ring. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Veiled woman crying a red tear'] = 'The tattoo: veiled woman crying a red tear. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Vampire woman with a rose'] = 'The tattoo: vampire woman with a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Widow in a lace veil'] = 'The tattoo: widow in a lace veil. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woman with a raven on her shoulder'] = 'The tattoo: woman with a raven on her shoulder. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Gothic queen with a crown of thorns'] = 'The tattoo: gothic queen with a crown of thorns. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Woman made of lace and bone'] = 'The tattoo: woman made of lace and bone. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Sleeping beauty under thorns'] = 'The tattoo: sleeping beauty under thorns. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woman with moth wings'] = 'The tattoo: woman with moth wings. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Lady holding a candle'] = 'The tattoo: lady holding a candle. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woman with a dagger and a rose'] = 'The tattoo: woman with a dagger and a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Lace choker with a pendant'] = 'The tattoo: lace choker with a pendant. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Velvet bow with a dagger'] = 'The tattoo: velvet bow with a dagger. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Lace butterfly with red veins'] = 'The tattoo: lace butterfly with red veins. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Corset ribbon lacing'] = 'The tattoo: corset ribbon lacing. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Lace veil with roses'] = 'The tattoo: lace veil with roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Velvet ribbon around a rose'] = 'The tattoo: velvet ribbon around a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Lace heart with thorns'] = 'The tattoo: lace heart with thorns. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Lace gloves holding a rose'] = 'The tattoo: lace gloves holding a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Lace cross'] = 'The tattoo: lace cross. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Lace garter with a red rose'] = 'The tattoo: lace garter with a red rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Skull with a crown of roses'] = 'The tattoo: skull with a crown of roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Grim reaper holding a rose'] = 'The tattoo: grim reaper holding a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Tombstone with roses'] = 'The tattoo: tombstone with roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Hourglass with red sand'] = 'The tattoo: hourglass with red sand. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Angel of grief'] = 'The tattoo: angel of grief. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Coffin with a rose on top'] = 'The tattoo: coffin with a rose on top. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Rosary with a bleeding heart'] = 'The tattoo: rosary with a bleeding heart. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Crying angel statue'] = 'The tattoo: crying angel statue. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Skeleton hand holding a rose'] = 'The tattoo: skeleton hand holding a rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Funeral lily bouquet'] = 'The tattoo: funeral lily bouquet. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny black rose'] = 'The tattoo: tiny black rose. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small bleeding heart'] = 'The tattoo: small bleeding heart. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny bat'] = 'The tattoo: tiny bat. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small gothic dagger'] = 'The tattoo: small gothic dagger. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny moth'] = 'The tattoo: tiny moth. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small red bow'] = 'The tattoo: small red bow. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny skull'] = 'The tattoo: tiny skull. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small candle'] = 'The tattoo: small candle. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny cross with roses'] = 'The tattoo: tiny cross with roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small spider'] = 'The tattoo: small spider. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Gothic cathedral back piece with roses'] = 'The tattoo: gothic cathedral back piece with roses. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Vampire queen thigh piece'] = 'The tattoo: vampire queen thigh piece. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Skeleton lovers chest piece'] = 'The tattoo: skeleton lovers chest piece. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Lace and roses sleeve'] = 'The tattoo: lace and roses sleeve. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Raven and moon forearm piece'] = 'The tattoo: raven and moon forearm piece. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bleeding heart sternum piece'] = 'The tattoo: bleeding heart sternum piece. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across his chest, shirtless'
$b['Thorned vine spine piece'] = 'The tattoo: thorned vine spine piece. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is down her spine, seen from behind in a low open-back top'
$b['Victorian portrait half sleeve'] = 'The tattoo: victorian portrait half sleeve. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$b['Black roses leg sleeve'] = 'The tattoo: black roses leg sleeve. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['Bat wings upper back piece'] = 'The tattoo: bat wings upper back piece. Dark romantic tattoo art, gothic Victorian romance, moody black and grey with deep oxblood red accents, roses, lace, velvet and antique details, elegant fine linework and soft smooth shading, beautiful and melancholic, designed like work from a top dark-art tattoo artist, no letters, no words. In the right panel it is across his back, shirtless, seen from behind'
$sets = [ordered]@{}
$sets['Dark Romantic Style Roses and Thorns'] = @('Black rose with thorns','Oxblood rose dripping','Rose wrapped in barbed thorns','Wilting rose under a glass dome','Rose and dagger','Rose growing from a skull','Pair of black roses','Rose tied with a velvet ribbon','Rose bleeding into lace','Thorned rose vine')
$sets['Dark Romantic Style Hearts'] = @('Bleeding sacred heart','Heart pierced by three swords','Anatomical heart with roses','Heart in a cage','Heart locket hiding a skull','Heart wrapped in thorns','Heart with bat wings','Cracked porcelain heart','Heart padlock and key','Heart in a bell jar')
$sets['Dark Romantic Style Lovers'] = @('Skeleton lovers embracing','Vampire couple','Two hands tied by a red thread','Kiss beneath a veil','Skeleton bride and groom','Ghost lovers','Two swans with necks entwined','Moth and flame lovers','Hands holding through iron bars','Lovers silhouetted in a full moon')
$sets['Dark Romantic Style Victorian Objects'] = @('Antique locket','Poison bottle with a skull','Candelabra with dripping candles','Ornate hand mirror','Victorian skull cameo','Pocket watch wrapped in roses','Antique key with a bow','Raven quill and inkwell','Perfume vial with a ribbon','Gothic dagger with a jeweled hilt')
$sets['Dark Romantic Style Creatures'] = @('Raven perched on a rose','Black moth with a skull mark','Bat with lace wings','Black cat with a ribbon','Serpent around a rose','Black swan','Spider in a lace web','Owl on a candelabra','Wolf with a rose in its mouth','Crow carrying a ring')
$sets['Dark Romantic Style Gothic Women'] = @('Veiled woman crying a red tear','Vampire woman with a rose','Widow in a lace veil','Woman with a raven on her shoulder','Gothic queen with a crown of thorns','Woman made of lace and bone','Sleeping beauty under thorns','Woman with moth wings','Lady holding a candle','Woman with a dagger and a rose')
$sets['Dark Romantic Style Lace and Velvet'] = @('Lace choker with a pendant','Velvet bow with a dagger','Lace butterfly with red veins','Corset ribbon lacing','Lace veil with roses','Velvet ribbon around a rose','Lace heart with thorns','Lace gloves holding a rose','Lace cross','Lace garter with a red rose')
$sets['Dark Romantic Style Death and Devotion'] = @('Skull with a crown of roses','Grim reaper holding a rose','Tombstone with roses','Hourglass with red sand','Angel of grief','Coffin with a rose on top','Rosary with a bleeding heart','Crying angel statue','Skeleton hand holding a rose','Funeral lily bouquet')
$sets['Dark Romantic Style Small'] = @('Tiny black rose','Small bleeding heart','Tiny bat','Small gothic dagger','Tiny moth','Small red bow','Tiny skull','Small candle','Tiny cross with roses','Small spider')
$sets['Dark Romantic Style Large Pieces'] = @('Gothic cathedral back piece with roses','Vampire queen thigh piece','Skeleton lovers chest piece','Lace and roses sleeve','Raven and moon forearm piece','Bleeding heart sternum piece','Thorned vine spine piece','Victorian portrait half sleeve','Black roses leg sleeve','Bat wings upper back piece')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Dark Romantic Style" } else { $n } }
"== Dark Romantic before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:dark-romantic" --remote 2>$null | Out-Null
RUN "CATEGORY Dark Romantic :: Dark Romantic Style Roses and Thorns, Dark Romantic Style Hearts, Dark Romantic Style Lovers, Dark Romantic Style Victorian Objects, Dark Romantic Style Creatures, Dark Romantic Style Gothic Women, Dark Romantic Style Lace and Velvet, Dark Romantic Style Death and Devotion, Dark Romantic Style Small, Dark Romantic Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Dark Romantic Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Dark Romantic Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Skeleton lovers embracing"))
}
}
