cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Dark Ornamental")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Black filigree skull'] = 'The tattoo: black filigree skull. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Gothic filigree cross'] = 'The tattoo: gothic filigree cross. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black baroque scroll panel'] = 'The tattoo: black baroque scroll panel. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Filigree bat'] = 'The tattoo: filigree bat. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black filigree crown of thorns'] = 'The tattoo: black filigree crown of thorns. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Filigree coffin'] = 'The tattoo: filigree coffin. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black filigree moth'] = 'The tattoo: black filigree moth. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black filigree serpent'] = 'The tattoo: black filigree serpent. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Filigree dagger'] = 'The tattoo: filigree dagger. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Spiked filigree crescent'] = 'The tattoo: spiked filigree crescent. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Ornamental sigil circle'] = 'The tattoo: ornamental sigil circle. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black sun ornament'] = 'The tattoo: black sun ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Alchemical symbol medallion'] = 'The tattoo: alchemical symbol medallion. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['All-seeing eye in black ornament'] = 'The tattoo: all-seeing eye in black ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Ouroboros ornament'] = 'The tattoo: ouroboros ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Inverted crescent ornament'] = 'The tattoo: inverted crescent ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Moon goddess sigil'] = 'The tattoo: moon goddess sigil. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Ornamental tarot frame'] = 'The tattoo: ornamental tarot frame. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Planetary sigil circle'] = 'The tattoo: planetary sigil circle. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Witch knot ornament'] = 'The tattoo: witch knot ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black skull mandala'] = 'The tattoo: black skull mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Spiked mandala'] = 'The tattoo: spiked mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Moth mandala'] = 'The tattoo: moth mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Bat wing mandala'] = 'The tattoo: bat wing mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Thorn mandala'] = 'The tattoo: thorn mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black sun mandala'] = 'The tattoo: black sun mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Spider web mandala'] = 'The tattoo: spider web mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Eye mandala in black'] = 'The tattoo: eye mandala in black. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black crescent moon mandala'] = 'The tattoo: black crescent moon mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Raven feather mandala'] = 'The tattoo: raven feather mandala. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Gothic arch ornament'] = 'The tattoo: gothic arch ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Black wrought iron gate'] = 'The tattoo: black wrought iron gate. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Black cathedral rose window'] = 'The tattoo: black cathedral rose window. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Gargoyle ornament'] = 'The tattoo: gargoyle ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Black iron chandelier'] = 'The tattoo: black iron chandelier. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Gothic pillar panel'] = 'The tattoo: gothic pillar panel. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Spiked iron crown'] = 'The tattoo: spiked iron crown. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Iron cross ornament'] = 'The tattoo: iron cross ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Church window with bats'] = 'The tattoo: church window with bats. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Gothic tracery band'] = 'The tattoo: gothic tracery band. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Ornamental skull with a crown'] = 'The tattoo: ornamental skull with a crown. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Skull with a filigree jaw'] = 'The tattoo: skull with a filigree jaw. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Bone chandelier'] = 'The tattoo: bone chandelier. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Ribcage ornament'] = 'The tattoo: ribcage ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Skull and moth ornament'] = 'The tattoo: skull and moth ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Horned skull ornament'] = 'The tattoo: horned skull ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Skull draped in black lace'] = 'The tattoo: skull draped in black lace. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Spine of bones ornament'] = 'The tattoo: spine of bones ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Ram skull ornament'] = 'The tattoo: ram skull ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Skull inside a black sun'] = 'The tattoo: skull inside a black sun. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Black dahlia ornament'] = 'The tattoo: black dahlia ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black lotus ornament'] = 'The tattoo: black lotus ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Thorn bouquet'] = 'The tattoo: thorn bouquet. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black chrysanthemum medallion'] = 'The tattoo: black chrysanthemum medallion. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Nightshade ornament'] = 'The tattoo: nightshade ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Spiked black peony'] = 'The tattoo: spiked black peony. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Hemlock ornament'] = 'The tattoo: hemlock ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Belladonna ornament'] = 'The tattoo: belladonna ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black orchid ornament'] = 'The tattoo: black orchid ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Dead roses ornament'] = 'The tattoo: dead roses ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Ornamental bat with spiked wings'] = 'The tattoo: ornamental bat with spiked wings. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black moth with ornament'] = 'The tattoo: black moth with ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Raven ornament'] = 'The tattoo: raven ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Ornamental scorpion'] = 'The tattoo: ornamental scorpion. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black widow spider ornament'] = 'The tattoo: black widow spider ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Serpent coiled in ornament'] = 'The tattoo: serpent coiled in ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black ornamental beetle'] = 'The tattoo: black ornamental beetle. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black swan ornament'] = 'The tattoo: black swan ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Black ornamental octopus'] = 'The tattoo: black ornamental octopus. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Black dragon ornament'] = 'The tattoo: black dragon ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Spiked choker band'] = 'The tattoo: spiked choker band. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black chain drape'] = 'The tattoo: black chain drape. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Thorn armband'] = 'The tattoo: thorn armband. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Spiked cuff'] = 'The tattoo: spiked cuff. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Barbed chain ornament'] = 'The tattoo: barbed chain ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Spiked chandelier drop'] = 'The tattoo: spiked chandelier drop. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Spiked garter band'] = 'The tattoo: spiked garter band. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Chain and padlock ornament'] = 'The tattoo: chain and padlock ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Spiked crown band'] = 'The tattoo: spiked crown band. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Black pendant chain'] = 'The tattoo: black pendant chain. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black onyx pendant'] = 'The tattoo: black onyx pendant. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Obsidian teardrop ornament'] = 'The tattoo: obsidian teardrop ornament. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Garnet blood drop jewel'] = 'The tattoo: garnet blood drop jewel. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black pearl drop'] = 'The tattoo: black pearl drop. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Jet stone cross'] = 'The tattoo: jet stone cross. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Dark amethyst medallion'] = 'The tattoo: dark amethyst medallion. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Black diamond crown'] = 'The tattoo: black diamond crown. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Blood ruby skull pendant'] = 'The tattoo: blood ruby skull pendant. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Smoky quartz drop'] = 'The tattoo: smoky quartz drop. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black opal medallion'] = 'The tattoo: black opal medallion. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Black ornamental back piece'] = 'The tattoo: black ornamental back piece. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Gothic spine piece'] = 'The tattoo: gothic spine piece. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Dark sternum chandelier'] = 'The tattoo: dark sternum chandelier. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Black ornamental sleeve'] = 'The tattoo: black ornamental sleeve. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Dark ornamental thigh piece'] = 'The tattoo: dark ornamental thigh piece. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Spiked shoulder epaulette'] = 'The tattoo: spiked shoulder epaulette. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Black ornamental chest plate'] = 'The tattoo: black ornamental chest plate. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Dark ornamental half sleeve'] = 'The tattoo: dark ornamental half sleeve. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$b['Gothic leg sleeve'] = 'The tattoo: gothic leg sleeve. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['Black cathedral back piece'] = 'The tattoo: black cathedral back piece. Dark ornamental tattoo art, heavy solid black ornamentation with intricate filigree, sharp spikes and gothic symmetry, bold negative space and fine dotwork shading, occult and gothic elegance, mostly pure black ink with rare deep blood red or dark jewel accents where the subject calls for it, composed to flow with the body, designed like work from a top dark ornamental tattoo artist, no letters, no words. In the right panel it is across his back, shirtless, seen from behind'
$sets = [ordered]@{}
$sets['Dark Ornamental Style Gothic Filigree'] = @('Black filigree skull','Gothic filigree cross','Black baroque scroll panel','Filigree bat','Black filigree crown of thorns','Filigree coffin','Black filigree moth','Black filigree serpent','Filigree dagger','Spiked filigree crescent')
$sets['Dark Ornamental Style Occult Symbols'] = @('Ornamental sigil circle','Black sun ornament','Alchemical symbol medallion','All-seeing eye in black ornament','Ouroboros ornament','Inverted crescent ornament','Moon goddess sigil','Ornamental tarot frame','Planetary sigil circle','Witch knot ornament')
$sets['Dark Ornamental Style Dark Mandalas'] = @('Black skull mandala','Spiked mandala','Moth mandala','Bat wing mandala','Thorn mandala','Black sun mandala','Spider web mandala','Eye mandala in black','Black crescent moon mandala','Raven feather mandala')
$sets['Dark Ornamental Style Cathedral and Iron'] = @('Gothic arch ornament','Black wrought iron gate','Black cathedral rose window','Gargoyle ornament','Black iron chandelier','Gothic pillar panel','Spiked iron crown','Iron cross ornament','Church window with bats','Gothic tracery band')
$sets['Dark Ornamental Style Skulls and Bone'] = @('Ornamental skull with a crown','Skull with a filigree jaw','Bone chandelier','Ribcage ornament','Skull and moth ornament','Horned skull ornament','Skull draped in black lace','Spine of bones ornament','Ram skull ornament','Skull inside a black sun')
$sets['Dark Ornamental Style Black Florals'] = @('Black dahlia ornament','Black lotus ornament','Thorn bouquet','Black chrysanthemum medallion','Nightshade ornament','Spiked black peony','Hemlock ornament','Belladonna ornament','Black orchid ornament','Dead roses ornament')
$sets['Dark Ornamental Style Dark Creatures'] = @('Ornamental bat with spiked wings','Black moth with ornament','Raven ornament','Ornamental scorpion','Black widow spider ornament','Serpent coiled in ornament','Black ornamental beetle','Black swan ornament','Black ornamental octopus','Black dragon ornament')
$sets['Dark Ornamental Style Chains and Spikes'] = @('Spiked choker band','Black chain drape','Thorn armband','Spiked cuff','Barbed chain ornament','Spiked chandelier drop','Spiked garter band','Chain and padlock ornament','Spiked crown band','Black pendant chain')
$sets['Dark Ornamental Style Dark Jewels'] = @('Black onyx pendant','Obsidian teardrop ornament','Garnet blood drop jewel','Black pearl drop','Jet stone cross','Dark amethyst medallion','Black diamond crown','Blood ruby skull pendant','Smoky quartz drop','Black opal medallion')
$sets['Dark Ornamental Style Large Pieces'] = @('Black ornamental back piece','Gothic spine piece','Dark sternum chandelier','Black ornamental sleeve','Dark ornamental thigh piece','Spiked shoulder epaulette','Black ornamental chest plate','Dark ornamental half sleeve','Gothic leg sleeve','Black cathedral back piece')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Dark Ornamental Style" } else { $n } }
"== Dark Ornamental before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:dark-ornamental" --remote 2>$null | Out-Null
RUN "CATEGORY Dark Ornamental :: Dark Ornamental Style Gothic Filigree, Dark Ornamental Style Occult Symbols, Dark Ornamental Style Dark Mandalas, Dark Ornamental Style Cathedral and Iron, Dark Ornamental Style Skulls and Bone, Dark Ornamental Style Black Florals, Dark Ornamental Style Dark Creatures, Dark Ornamental Style Chains and Spikes, Dark Ornamental Style Dark Jewels, Dark Ornamental Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Dark Ornamental Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Dark Ornamental Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Black skull mandala"))
}
}
