cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Etching")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Etching Style Botanical Plates','Etching Style Natural History','Etching Style Animals','Etching Style Anatomy','Etching Style Maritime','Etching Style Mythology and Angels','Etching Style Celestial and Science','Etching Style Architecture','Etching Style Small','Etching Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Etched rose with roots'] = 'The tattoo: etched rose with roots. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched poppy seed head'] = 'The tattoo: etched poppy seed head. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched fern frond'] = 'The tattoo: etched fern frond. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched lily of the valley'] = 'The tattoo: etched lily of the valley. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched thistle'] = 'The tattoo: etched thistle. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Etched mushroom specimen'] = 'The tattoo: etched mushroom specimen. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched lavender sprig'] = 'The tattoo: etched lavender sprig. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Etched peony with bud'] = 'The tattoo: etched peony with bud. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched oak leaf and acorn'] = 'The tattoo: etched oak leaf and acorn. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Etched belladonna'] = 'The tattoo: etched belladonna. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched beetle specimen'] = 'The tattoo: etched beetle specimen. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Etched moth with spread wings'] = 'The tattoo: etched moth with spread wings. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched nautilus shell'] = 'The tattoo: etched nautilus shell. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Etched seahorse'] = 'The tattoo: etched seahorse. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Etched crab'] = 'The tattoo: etched crab. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched dragonfly study'] = 'The tattoo: etched dragonfly study. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Etched bird skull'] = 'The tattoo: etched bird skull. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched octopus'] = 'The tattoo: etched octopus. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched coral branch'] = 'The tattoo: etched coral branch. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Etched butterfly specimen'] = 'The tattoo: etched butterfly specimen. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched lion head'] = 'The tattoo: etched lion head. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched wolf portrait'] = 'The tattoo: etched wolf portrait. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched horse head'] = 'The tattoo: etched horse head. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Etched owl'] = 'The tattoo: etched owl. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched stag'] = 'The tattoo: etched stag. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Etched hare'] = 'The tattoo: etched hare. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched tiger'] = 'The tattoo: etched tiger. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Etched bear'] = 'The tattoo: etched bear. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched eagle'] = 'The tattoo: etched eagle. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched fox'] = 'The tattoo: etched fox. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched anatomical heart'] = 'The tattoo: etched anatomical heart. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Etched skull study'] = 'The tattoo: etched skull study. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Etched hand bones'] = 'The tattoo: etched hand bones. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched eye diagram'] = 'The tattoo: etched eye diagram. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Etched ribcage'] = 'The tattoo: etched ribcage. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched brain'] = 'The tattoo: etched brain. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched lungs with branches'] = 'The tattoo: etched lungs with branches. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Etched spine'] = 'The tattoo: etched spine. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched skeletal hand holding a flower'] = 'The tattoo: etched skeletal hand holding a flower. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched anatomical face half skull'] = 'The tattoo: etched anatomical face half skull. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched clipper ship'] = 'The tattoo: etched clipper ship. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Etched lighthouse'] = 'The tattoo: etched lighthouse. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched whale'] = 'The tattoo: etched whale. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Etched kraken attacking a ship'] = 'The tattoo: etched kraken attacking a ship. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched anchor with rope'] = 'The tattoo: etched anchor with rope. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Etched compass'] = 'The tattoo: etched compass. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched diving helmet'] = 'The tattoo: etched diving helmet. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched sea chart with a ship'] = 'The tattoo: etched sea chart with a ship. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched storm at sea'] = 'The tattoo: etched storm at sea. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Etched mermaid on a rock'] = 'The tattoo: etched mermaid on a rock. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched angel with wings'] = 'The tattoo: etched angel with wings. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched Medusa'] = 'The tattoo: etched medusa. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Etched Pegasus'] = 'The tattoo: etched pegasus. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched centaur archer'] = 'The tattoo: etched centaur archer. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched phoenix'] = 'The tattoo: etched phoenix. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Etched fallen angel'] = 'The tattoo: etched fallen angel. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched minotaur'] = 'The tattoo: etched minotaur. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched sphinx'] = 'The tattoo: etched sphinx. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched dragon'] = 'The tattoo: etched dragon. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched cherub with a trumpet'] = 'The tattoo: etched cherub with a trumpet. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched moon with craters'] = 'The tattoo: etched moon with craters. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Etched sun with rays'] = 'The tattoo: etched sun with rays. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched astrolabe'] = 'The tattoo: etched astrolabe. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Etched telescope'] = 'The tattoo: etched telescope. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched solar system'] = 'The tattoo: etched solar system. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched constellation map'] = 'The tattoo: etched constellation map. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched hourglass'] = 'The tattoo: etched hourglass. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Etched antique globe'] = 'The tattoo: etched antique globe. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched comet'] = 'The tattoo: etched comet. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Etched eclipse'] = 'The tattoo: etched eclipse. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Etched cathedral'] = 'The tattoo: etched cathedral. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched ruined arch'] = 'The tattoo: etched ruined arch. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched clock tower'] = 'The tattoo: etched clock tower. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Etched lighthouse on cliffs'] = 'The tattoo: etched lighthouse on cliffs. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Etched castle'] = 'The tattoo: etched castle. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched bridge'] = 'The tattoo: etched bridge. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Etched old windmill'] = 'The tattoo: etched old windmill. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Etched greenhouse'] = 'The tattoo: etched greenhouse. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched temple columns'] = 'The tattoo: etched temple columns. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Etched gothic window'] = 'The tattoo: etched gothic window. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny etched moth'] = 'The tattoo: tiny etched moth. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small etched key'] = 'The tattoo: small etched key. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny etched bee'] = 'The tattoo: tiny etched bee. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small etched moon'] = 'The tattoo: small etched moon. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny etched skull'] = 'The tattoo: tiny etched skull. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small etched feather'] = 'The tattoo: small etched feather. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny etched rose'] = 'The tattoo: tiny etched rose. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small etched eye'] = 'The tattoo: small etched eye. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny etched star'] = 'The tattoo: tiny etched star. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small etched shell'] = 'The tattoo: small etched shell. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Etched botanical back piece'] = 'The tattoo: etched botanical back piece. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Etched ship and storm sleeve'] = 'The tattoo: etched ship and storm sleeve. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Etched anatomical chest piece'] = 'The tattoo: etched anatomical chest piece. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Etched angel thigh piece'] = 'The tattoo: etched angel thigh piece. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Etched lion forearm piece'] = 'The tattoo: etched lion forearm piece. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Etched spine of moths'] = 'The tattoo: etched spine of moths. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Etched natural history half sleeve'] = 'The tattoo: etched natural history half sleeve. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Etched lighthouse calf piece'] = 'The tattoo: etched lighthouse calf piece. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Etched celestial shoulder piece'] = 'The tattoo: etched celestial shoulder piece. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Etched forest leg sleeve'] = 'The tattoo: etched forest leg sleeve. Etching tattoo art in the style of antique copperplate etchings and engravings, fine precise black linework with dense cross-hatching, engraved contour lines and stippled tone, old scientific plate and book illustration feel, black ink only, designed like work from a top engraving tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Etching Style Botanical Plates'] = @('Etched rose with roots','Etched poppy seed head','Etched fern frond','Etched lily of the valley','Etched thistle','Etched mushroom specimen','Etched lavender sprig','Etched peony with bud','Etched oak leaf and acorn','Etched belladonna')
$sets['Etching Style Natural History'] = @('Etched beetle specimen','Etched moth with spread wings','Etched nautilus shell','Etched seahorse','Etched crab','Etched dragonfly study','Etched bird skull','Etched octopus','Etched coral branch','Etched butterfly specimen')
$sets['Etching Style Animals'] = @('Etched lion head','Etched wolf portrait','Etched horse head','Etched owl','Etched stag','Etched hare','Etched tiger','Etched bear','Etched eagle','Etched fox')
$sets['Etching Style Anatomy'] = @('Etched anatomical heart','Etched skull study','Etched hand bones','Etched eye diagram','Etched ribcage','Etched brain','Etched lungs with branches','Etched spine','Etched skeletal hand holding a flower','Etched anatomical face half skull')
$sets['Etching Style Maritime'] = @('Etched clipper ship','Etched lighthouse','Etched whale','Etched kraken attacking a ship','Etched anchor with rope','Etched compass','Etched diving helmet','Etched sea chart with a ship','Etched storm at sea','Etched mermaid on a rock')
$sets['Etching Style Mythology and Angels'] = @('Etched angel with wings','Etched Medusa','Etched Pegasus','Etched centaur archer','Etched phoenix','Etched fallen angel','Etched minotaur','Etched sphinx','Etched dragon','Etched cherub with a trumpet')
$sets['Etching Style Celestial and Science'] = @('Etched moon with craters','Etched sun with rays','Etched astrolabe','Etched telescope','Etched solar system','Etched constellation map','Etched hourglass','Etched antique globe','Etched comet','Etched eclipse')
$sets['Etching Style Architecture'] = @('Etched cathedral','Etched ruined arch','Etched clock tower','Etched lighthouse on cliffs','Etched castle','Etched bridge','Etched old windmill','Etched greenhouse','Etched temple columns','Etched gothic window')
$sets['Etching Style Small'] = @('Tiny etched moth','Small etched key','Tiny etched bee','Small etched moon','Tiny etched skull','Small etched feather','Tiny etched rose','Small etched eye','Tiny etched star','Small etched shell')
$sets['Etching Style Large Pieces'] = @('Etched botanical back piece','Etched ship and storm sleeve','Etched anatomical chest piece','Etched angel thigh piece','Etched lion forearm piece','Etched spine of moths','Etched natural history half sleeve','Etched lighthouse calf piece','Etched celestial shoulder piece','Etched forest leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Etching Style" } else { $n } }
"== Etching before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:etching" --remote 2>$null | Out-Null
RUN "CATEGORY Etching :: Etching Style Botanical Plates, Etching Style Natural History, Etching Style Animals, Etching Style Anatomy, Etching Style Maritime, Etching Style Mythology and Angels, Etching Style Celestial and Science, Etching Style Architecture, Etching Style Small, Etching Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Etching Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Etching Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Etched moth with spread wings"))
}
}
