cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$ns = "9c2ba111589e48c6ba5ad1b924ae8809"
$slug = { param($x) $s = (($x.ToLower() -replace "[^a-z0-9]+","-").Trim("-")); if ($s.Length -gt 70) { $s = $s.Substring(0,70) }; $s }
$tmp = Join-Path $env:TEMP "aura-put.txt"
function Put($k, $v) { [System.IO.File]::WriteAllText($tmp, $v, (New-Object System.Text.UTF8Encoding $false)); npx wrangler kv key put --namespace-id $ns $k --path $tmp --remote 2>$null | Out-Null }
function Bulk($keys, $rx) { $res = @{}; $kf = Join-Path $env:TEMP "aura-fix-keys.json"; for ($i = 0; $i -lt $keys.Count; $i += 100) { $chunk = @($keys[$i..([Math]::Min($i+99,$keys.Count-1))]); ConvertTo-Json $chunk | Set-Content -Path $kf -Encoding utf8; $o = (npx wrangler kv bulk get $kf --namespace-id $ns --remote 2>$null | Out-String); [regex]::Matches($o, $rx) | % { $res[$_.Groups[1].Value] = 1 } }; $res }
$tt = $null; for ($t = 1; $t -le 4 -and -not $tt; $t++) { try { $o = (npx wrangler kv key get --namespace-id $ns "card:tree" --remote 2>$null | Out-String) | ConvertFrom-Json; if ($o.subjects) { $tt = $o } } catch {}; if (-not $tt) { Start-Sleep -Seconds 5 } }
if (-not $tt) { "COULD NOT READ THE CATALOG - run the block again" } else {
"== 1. putting back two style settings my check removed by mistake (they belong to Japanese and Liquid Chrome) =="
Put 'context:japanese' 'a Japanese mythological figure'
Put 'context:chrome-designs' 'a LIQUID CHROME tattoo design - the object is made of molten mirror-polished metal, a perfect reflective surface with sharp specular highlights and dark reflected shadows, smooth flowing liquid form with drips and stretched tendrils of metal, Y2K chrome aesthetic, the surface mirrors its surroundings - no colour except the silver metal, no ornamental filigree, no gemstones, no jewellery, one complete object, centred and isolated on plain white, no background, no scenery, no body, no skin'
"  done"
"== 2. re-checking the split settings on the 7 newest categories (the last check listed them wrong) =="
$sk = New-Object System.Collections.ArrayList
foreach ($c in @('Music','Horror','Neo-Traditional Bold Illustrated','Cannabis Culture','Holidays','Embroidered Tattoos','Ignorant Doodle')) { foreach ($k in @($tt.subjects.$c | ? { $_ })) { $ks = & $slug $k; [void]$sk.Add("render:" + $ks); [void]$sk.Add("shape:" + $ks); [void]$sk.Add("split:" + $ks) } }
$have = Bulk @($sk) '"((?:render|shape|split):[^"]+)":\s*"'
$miss = @($sk | ? { -not $have.ContainsKey($_) })
"  " + $have.Count + " of " + $sk.Count + " found"
foreach ($m in $miss) { "  putting back " + $m; if ($m -like 'render:*') { Put $m 'Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.' } elseif ($m -like 'shape:*') { Put $m '3:2' } else { Put $m 'yes' } }
"== 3. the two Music cards that had no description =="
Put ('build:' + (& $slug 'Disco ball cracking open and releasing an entire nightclub')) 'The tattoo: Disco ball cracking open and releasing an entire nightclub. imaginative high-end contemporary music tattoo artwork treating music as fandom, memory, identity, culture, emotion, history, performance and the soundtrack of a human life rather than merely a collection of instruments and musical symbols; freely draw inspiration from musicians, bands, musical eras, concerts, fan culture, songs, albums, listening technology, nightlife, musical genres, instruments, family memories, relationships and personal life moments; when a famous artist or band is explicitly named in the individual concept, the artist or band name may appear clearly and intentionally as part of an original fan-homage tattoo composition, but create new imagery and composition rather than reproducing an existing album cover, photograph, logo or merchandise design; freely range between rock and roll, pop, punk, metal, hip-hop, rap, country, blues, jazz, soul, funk, disco, electronic, dance, classical, Latin, reggae and other musical worlds according to the concept; freely vary between American Traditional, Neo-Traditional, realism, black and grey, illustrative tattoo art, psychedelic, Gothic, Western, graffiti-influenced, Chicano-influenced, Y2K, fine line, blackwork, surrealism, ornamental, colorful contemporary tattooing and completely unexpected visual languages; show the EXPERIENCE of music through movement, crowds, stage light, rhythm, bass, atmosphere, emotion, memory and visual transformation; instruments and music technology may appear but should become part of a larger idea rather than generic isolated clip art; avoid repetitive guitars, treble clefs, music notes, roses wrapped around microphones, generic headphones and generic vinyl-record compositions; use text only when the individual concept specifically calls for an artist name, band name, date, personal label or other meaningful lettering; THE ART CAN BE IMAGINATIVE BUT SPECIFIC MUSIC-RELATED FACTS PROVIDED BY THE USER MUST REMAIN ACCURATE, preserve supplied artist names, dates, concert details, instrument details, personal handwriting, notation and other meaningful source material rather than inventing or altering it; make each design feel like MUSIC MATTERS TO THIS PERSON. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
Put ('build:' + (& $slug 'Blues guitarist playing in an empty bar while blue smoke becomes memories of people hes loved')) 'The tattoo: Blues guitarist playing in an empty bar while blue smoke becomes memories of people hes loved. imaginative high-end contemporary music tattoo artwork treating music as fandom, memory, identity, culture, emotion, history, performance and the soundtrack of a human life rather than merely a collection of instruments and musical symbols; freely draw inspiration from musicians, bands, musical eras, concerts, fan culture, songs, albums, listening technology, nightlife, musical genres, instruments, family memories, relationships and personal life moments; when a famous artist or band is explicitly named in the individual concept, the artist or band name may appear clearly and intentionally as part of an original fan-homage tattoo composition, but create new imagery and composition rather than reproducing an existing album cover, photograph, logo or merchandise design; freely range between rock and roll, pop, punk, metal, hip-hop, rap, country, blues, jazz, soul, funk, disco, electronic, dance, classical, Latin, reggae and other musical worlds according to the concept; freely vary between American Traditional, Neo-Traditional, realism, black and grey, illustrative tattoo art, psychedelic, Gothic, Western, graffiti-influenced, Chicano-influenced, Y2K, fine line, blackwork, surrealism, ornamental, colorful contemporary tattooing and completely unexpected visual languages; show the EXPERIENCE of music through movement, crowds, stage light, rhythm, bass, atmosphere, emotion, memory and visual transformation; instruments and music technology may appear but should become part of a larger idea rather than generic isolated clip art; avoid repetitive guitars, treble clefs, music notes, roses wrapped around microphones, generic headphones and generic vinyl-record compositions; use text only when the individual concept specifically calls for an artist name, band name, date, personal label or other meaningful lettering; THE ART CAN BE IMAGINATIVE BUT SPECIFIC MUSIC-RELATED FACTS PROVIDED BY THE USER MUST REMAIN ACCURATE, preserve supplied artist names, dates, concert details, instrument details, personal handwriting, notation and other meaningful source material rather than inventing or altering it; make each design feel like MUSIC MATTERS TO THIS PERSON. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
"  written"
"== 4. Neo-Traditional and Black & Grey Realism only have 10 of 100 drawn - checking how they were set up =="
$mode = @{}
foreach ($c in @("Neo-Traditional","Black & Grey Realism")) { $k0 = @($tt.subjects.$c)[0]; $l0 = @($tt.specific.$k0)[0]; $p = Bulk @("frame:category:" + (& $slug $c), "split:" + (& $slug $k0), "build:" + (& $slug $l0)) '"((?:frame|split|build):[^"]+)":\s*"'; "  " + $c + ": frame=" + $p.ContainsKey("frame:category:" + (& $slug $c)) + " split=" + $p.ContainsKey("split:" + (& $slug $k0)) + " description=" + $p.ContainsKey("build:" + (& $slug $l0)); if ($p.ContainsKey("split:" + (& $slug $k0))) { $mode[$c] = "REDO" } elseif ($p.ContainsKey("frame:category:" + (& $slug $c))) { $mode[$c] = "FACE" } else { $mode[$c] = "STOP" } }
"  waiting 70 seconds so every server sees the fixes..."
Start-Sleep -Seconds 70
"== redrawing the two Music cards =="
$r = (RUN ("REDO Disco ball cracking open and releasing an entire nightclub, Blues guitarist playing in an empty bar while blue smoke becomes memories of people hes loved") | Out-String)
[regex]::Matches($r, '"([^"]+)  ->  (https://[^"]+|FAILED[^"]{0,60})"') | % { "  " + $(if ($_.Groups[2].Value -like "FAILED*") { "FAILED" } else { "ok" }) + "  " + $_.Groups[1].Value }
foreach ($c in @("Neo-Traditional","Black & Grey Realism")) {
  if ($mode[$c] -eq "STOP") { "== " + $c + ": no frame and no split setting found - NOT drawing, send me this =="; continue }
  "== " + $c + ": drawing the missing cards with " + $mode[$c] + " =="
  $last = ""
  for ($pass = 1; $pass -le 8; $pass++) {
    $m = $null; for ($try = 1; $try -le 4; $try++) { $o = (RUN ("WALK " + $c) | Out-String); $m = [regex]::Match($o, '"missing":\[(.*?)\]'); if ($m.Success) { break }; Start-Sleep -Seconds 15 }
    if (-not $m.Success) { "  NO ANSWER from WALK - run the block again"; break }
    $names = @([regex]::Matches($m.Groups[1].Value, '"([^"]+)"') | % { $_.Groups[1].Value })
    if ($names.Count -eq 0) { "  nothing missing"; break }
    $now = ($names -join "|"); if ($now -eq $last) { "  these keep failing:"; $names | % { "    " + $_ }; break }; $last = $now
    "  pass " + $pass + " - " + $names.Count + " missing"
    if ($mode[$c] -eq "REDO") { for ($i = 0; $i -lt $names.Count; $i += 5) { $r = (RUN ("REDO " + (($names[$i..([Math]::Min($i+4,$names.Count-1))]) -join ", ")) | Out-String); [regex]::Matches($r, '"([^"]+)  ->  (https://[^"]+|FAILED[^"]{0,60})"') | % { "  " + $(if ($_.Groups[2].Value -like "FAILED*") { "FAILED" } else { "ok" }) + "  " + $_.Groups[1].Value } } }
    else { foreach ($leaf in $names) { $r = (RUN ("FACE " + $leaf) | Out-String); if ($r -match '"img":"img_') { "  ok  " + $leaf } else { "  FAILED  " + $leaf } } }
  }
  RUN ("SHEET " + $c)
}
}
