RUN "SETKV shape:shoulder-and-collarbone-flow 3:2"
RUN "SETKV split:shoulder-and-collarbone-flow yes"
RUN "SETKV shape:upper-arm-flow 3:2"
RUN "SETKV split:upper-arm-flow yes"
RUN "SETKV shape:forearm-and-wrist-flow 3:2"
RUN "SETKV split:forearm-and-wrist-flow yes"
RUN "SETKV shape:spine-and-back-flow 3:2"
RUN "SETKV split:spine-and-back-flow yes"
RUN "SETKV shape:rib-and-side-body-flow 3:2"
RUN "SETKV split:rib-and-side-body-flow yes"
RUN "SETKV shape:chest-and-sternum-flow 3:2"
RUN "SETKV split:chest-and-sternum-flow yes"
RUN "SETKV shape:hip-and-thigh-flow 3:2"
RUN "SETKV split:hip-and-thigh-flow yes"
RUN "SETKV shape:leg-and-ankle-flow 3:2"
RUN "SETKV split:leg-and-ankle-flow yes"
Start-Sleep -Seconds 60
RUN "REDO Shoulder Cap Floral Wrap, Shoulder To Collarbone Floral Sweep, Collarbone Following Floral Vine, Collarbone To Shoulder Botanical Trail, Front Shoulder Floral Curve"
RUN "REDO Back Shoulder Floral Curve, Shoulder Cap Peony Flow, Shoulder Cap Wildflower Flow, Shoulder To Upper Arm Cascading Vine, Shoulder To Chest Floral Sweep"
RUN "REDO Shoulder To Back Floral Sweep, Shoulder Blade Botanical Trail, Double Collarbone Botanical Sweep, Asymmetrical Collarbone Floral Flow, Collarbone Vine With Falling Blossoms"
RUN "REDO Upper Arm Floral Wrap, Loose Bicep Floral Bracelet, Diagonal Bicep Botanical Wrap, Spiral Upper Arm Vine, Shoulder Into Bicep Floral Wrap"
RUN "REDO Outer Bicep Cascading Flowers, Inner Bicep Botanical Curve, Back Of Arm Trailing Floral, Upper Arm Half-Wrap Wildflowers, Upper Arm Full-Wrap Wildflowers"
RUN "REDO Peony And Vine Bicep Wrap, Rose Vine Upper Arm Wrap, Botanical Garland Upper Arm, Asymmetrical Floral Arm Band, Floating Flowers Around Upper Arm"
RUN "REDO Fine-Line Forearm Vine Wrap, Spiral Forearm Botanical Vine, Diagonal Forearm Floral Sweep, Inner Forearm Growing Stem, Outer Forearm Trailing Wildflowers"
RUN "REDO Wrist To Forearm Climbing Vine, Floral Wrist Bracelet, Loose Botanical Wrist Wrap, Forearm Garland Wrap, Wildflowers Circling Forearm"
RUN "REDO Rose Vine Forearm Spiral, Lavender Forearm Wrap, Falling Petals Forearm Flow, Elbow-To-Wrist Botanical Trail, Upper Forearm To Hand Floral Trail"
RUN "REDO Full Spine Floral Vine, Upper Spine Wildflower Trail, Lower Spine Botanical Trail, Neck To Spine Floral Cascade, Spine Vine With Scattered Blossoms"
RUN "REDO Single Stem Following Spine, Asymmetrical Spine Floral Vine, Botanical Vine Crossing Spine, Upper Back Shoulder-To-Shoulder Floral Sweep, One-Sided Back Floral Cascade"
RUN "REDO Shoulder Blade To Spine Botanical Flow, Spine To Hip Floral Cascade, Back Rib Botanical Sweep, Curved Lower Back Floral Vine, Back Of Neck Into Spine Floral Trail"
RUN "REDO Ribcage Floral Vine, Long Rib Wildflower Stem, Side-Rib Botanical Sweep, Underarm To Rib Floral Cascade, Rib To Waist Floral Vine"
RUN "REDO Rib To Hip Botanical Trail, Diagonal Rib Floral Composition, Curved Rib Peony Stem, Wildflower Side-Body Garden, Cascading Flowers Down Side Body"
RUN "REDO Vertical Sternum Floral Stem, Sternum Floral Drop, Center-Chest Botanical Vine, Collarbone To Sternum Floral Trail, Under-Bust Floral Arc"
RUN "REDO Asymmetrical Under-Bust Floral Sweep, Double Under-Bust Botanical Garland, Side-Chest Into Rib Floral Flow, Chest To Shoulder Floral Vine, Sternum To Stomach Botanical Trail"
RUN "REDO Hip-Curve Floral Vine, Waist-To-Hip Botanical Sweep, Hip-Bone Wildflower Trail, Side-Hip Cascading Flowers, Hip To Upper Thigh Floral Flow"
RUN "REDO Front-Thigh Botanical Sweep, Outer-Thigh Floral Curve, Inner-Thigh Floral Vine, Thigh-Wrap Botanical Garland, Diagonal Thigh Wildflower Flow"
RUN "REDO Calf-Wrap Floral Vine, Spiral Calf Botanical Vine, Shin-Climbing Wildflower Stem, Back-Of-Calf Floral Trail, Knee-To-Calf Botanical Cascade"
RUN "REDO Ankle Floral Bracelet, Loose Ankle Vine Wrap, Ankle-To-Calf Climbing Flowers, Ankle-To-Foot Botanical Trail, Floral Vine Circling Lower Leg"
Start-Sleep -Seconds 30
RUN "SHEET Shoulder And Collarbone Flow"
RUN "SHEET Upper Arm Flow"
RUN "SHEET Forearm And Wrist Flow"
RUN "SHEET Spine And Back Flow"
RUN "SHEET Rib And Side Body Flow"
RUN "SHEET Chest And Sternum Flow"
RUN "SHEET Hip And Thigh Flow"
RUN "SHEET Leg And Ankle Flow"
RUN "SHEET Organic Body Flow"
RUN "BROWSE"
RUN "BROWSE"
RUN "BROWSE"
