cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Glass Effect")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Glass Effect Style Animals','Glass Effect Style Hearts and Symbols','Glass Effect Style Crystals and Gems','Glass Effect Style Bottles and Vessels','Glass Effect Style Iridescent','Glass Effect Style Shattered','Glass Effect Style Celestial','Glass Effect Style Water and Ice','Glass Effect Style Small','Glass Effect Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Glass hummingbird'] = 'The tattoo: glass hummingbird. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Glass koi fish'] = 'The tattoo: glass koi fish. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glass butterfly'] = 'The tattoo: glass butterfly. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glass jellyfish'] = 'The tattoo: glass jellyfish. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Glass wolf head'] = 'The tattoo: glass wolf head. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Glass swan'] = 'The tattoo: glass swan. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Glass snake'] = 'The tattoo: glass snake. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Glass fox'] = 'The tattoo: glass fox. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Glass dolphin'] = 'The tattoo: glass dolphin. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Glass owl'] = 'The tattoo: glass owl. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Glass heart'] = 'The tattoo: glass heart. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Glass anatomical heart'] = 'The tattoo: glass anatomical heart. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Glass key'] = 'The tattoo: glass key. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Glass skull'] = 'The tattoo: glass skull. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Glass eye'] = 'The tattoo: glass eye. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Glass crown'] = 'The tattoo: glass crown. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Glass star'] = 'The tattoo: glass star. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glass crescent moon'] = 'The tattoo: glass crescent moon. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glass lock'] = 'The tattoo: glass lock. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Glass dagger'] = 'The tattoo: glass dagger. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Clear quartz crystal'] = 'The tattoo: clear quartz crystal. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Faceted diamond'] = 'The tattoo: faceted diamond. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Amethyst cluster'] = 'The tattoo: amethyst cluster. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Glass prism splitting light'] = 'The tattoo: glass prism splitting light. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Floating gemstone'] = 'The tattoo: floating gemstone. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Crystal point with rainbow refraction'] = 'The tattoo: crystal point with rainbow refraction. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Cut sapphire'] = 'The tattoo: cut sapphire. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Raw crystal shard'] = 'The tattoo: raw crystal shard. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Opal teardrop'] = 'The tattoo: opal teardrop. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Crystal ball'] = 'The tattoo: crystal ball. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Glass bottle with a tiny galaxy inside'] = 'The tattoo: glass bottle with a tiny galaxy inside. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Potion bottle glowing'] = 'The tattoo: potion bottle glowing. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Hourglass in clear glass'] = 'The tattoo: hourglass in clear glass. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Glass jar with fireflies'] = 'The tattoo: glass jar with fireflies. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Message in a bottle'] = 'The tattoo: message in a bottle. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glass terrarium with a tiny forest'] = 'The tattoo: glass terrarium with a tiny forest. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glass snow globe'] = 'The tattoo: glass snow globe. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Perfume bottle'] = 'The tattoo: perfume bottle. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Glass lantern'] = 'The tattoo: glass lantern. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Wine glass with a moon reflection'] = 'The tattoo: wine glass with a moon reflection. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Iridescent bubble'] = 'The tattoo: iridescent bubble. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Holographic butterfly'] = 'The tattoo: holographic butterfly. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Iridescent beetle shell'] = 'The tattoo: iridescent beetle shell. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Rainbow soap bubble cluster'] = 'The tattoo: rainbow soap bubble cluster. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Iridescent seashell'] = 'The tattoo: iridescent seashell. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Holographic heart'] = 'The tattoo: holographic heart. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Iridescent dragonfly wings'] = 'The tattoo: iridescent dragonfly wings. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Oil slick swirl'] = 'The tattoo: oil slick swirl. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Iridescent feather'] = 'The tattoo: iridescent feather. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Pearl with a rainbow sheen'] = 'The tattoo: pearl with a rainbow sheen. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Shattered glass heart'] = 'The tattoo: shattered glass heart. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cracked glass skull'] = 'The tattoo: cracked glass skull. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Breaking glass butterfly'] = 'The tattoo: breaking glass butterfly. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Shards flying apart'] = 'The tattoo: shards flying apart. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Cracked glass moon'] = 'The tattoo: cracked glass moon. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Shattered mirror circle'] = 'The tattoo: shattered mirror circle. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Broken glass rose'] = 'The tattoo: broken glass rose. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cracked glass eye'] = 'The tattoo: cracked glass eye. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Exploding glass orb'] = 'The tattoo: exploding glass orb. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glass wolf shattering'] = 'The tattoo: glass wolf shattering. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Glass planet with rings'] = 'The tattoo: glass planet with rings. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Glass sun'] = 'The tattoo: glass sun. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Glass moon phases'] = 'The tattoo: glass moon phases. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Glass comet'] = 'The tattoo: glass comet. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Glass constellation stars'] = 'The tattoo: glass constellation stars. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Glass galaxy orb'] = 'The tattoo: glass galaxy orb. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Glass shooting star'] = 'The tattoo: glass shooting star. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Glass eclipse'] = 'The tattoo: glass eclipse. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Glass astronaut helmet'] = 'The tattoo: glass astronaut helmet. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Glass solar system'] = 'The tattoo: glass solar system. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Water drop with a reflection'] = 'The tattoo: water drop with a reflection. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Ice crystal'] = 'The tattoo: ice crystal. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Frozen rose'] = 'The tattoo: frozen rose. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Glass wave'] = 'The tattoo: glass wave. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Icicle cluster'] = 'The tattoo: icicle cluster. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Water splash frozen in glass'] = 'The tattoo: water splash frozen in glass. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glass raindrop chain'] = 'The tattoo: glass raindrop chain. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Ice heart'] = 'The tattoo: ice heart. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Frozen butterfly'] = 'The tattoo: frozen butterfly. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Glass water lily'] = 'The tattoo: glass water lily. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny glass heart'] = 'The tattoo: tiny glass heart. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small glass drop'] = 'The tattoo: small glass drop. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny crystal'] = 'The tattoo: tiny crystal. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small glass star'] = 'The tattoo: small glass star. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny glass bubble'] = 'The tattoo: tiny glass bubble. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small glass moon'] = 'The tattoo: small glass moon. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny glass butterfly'] = 'The tattoo: tiny glass butterfly. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small glass key'] = 'The tattoo: small glass key. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny prism'] = 'The tattoo: tiny prism. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small glass eye'] = 'The tattoo: small glass eye. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Glass koi half sleeve'] = 'The tattoo: glass koi half sleeve. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Crystal cluster back piece'] = 'The tattoo: crystal cluster back piece. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his back, shirtless, seen from behind'
$b['Glass butterflies thigh piece'] = 'The tattoo: glass butterflies thigh piece. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Shattered glass full sleeve'] = 'The tattoo: shattered glass full sleeve. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Glass jellyfish leg sleeve'] = 'The tattoo: glass jellyfish leg sleeve. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['Glass snake forearm piece'] = 'The tattoo: glass snake forearm piece. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Glass planets shoulder piece'] = 'The tattoo: glass planets shoulder piece. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Crystal spine piece'] = 'The tattoo: crystal spine piece. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is down his spine, shirtless, seen from behind'
$b['Glass heart chest piece'] = 'The tattoo: glass heart chest piece. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Iridescent calf piece'] = 'The tattoo: iridescent calf piece. Glass effect tattoo, the subject looks like it is made of clear translucent glass, realistic refraction, bright white highlights and reflections, soft see-through edges with subtle rainbow tints, strong clear shading and bold contrast so it reads clearly on skin, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$sets = [ordered]@{}
$sets['Glass Effect Style Animals'] = @('Glass hummingbird','Glass koi fish','Glass butterfly','Glass jellyfish','Glass wolf head','Glass swan','Glass snake','Glass fox','Glass dolphin','Glass owl')
$sets['Glass Effect Style Hearts and Symbols'] = @('Glass heart','Glass anatomical heart','Glass key','Glass skull','Glass eye','Glass crown','Glass star','Glass crescent moon','Glass lock','Glass dagger')
$sets['Glass Effect Style Crystals and Gems'] = @('Clear quartz crystal','Faceted diamond','Amethyst cluster','Glass prism splitting light','Floating gemstone','Crystal point with rainbow refraction','Cut sapphire','Raw crystal shard','Opal teardrop','Crystal ball')
$sets['Glass Effect Style Bottles and Vessels'] = @('Glass bottle with a tiny galaxy inside','Potion bottle glowing','Hourglass in clear glass','Glass jar with fireflies','Message in a bottle','Glass terrarium with a tiny forest','Glass snow globe','Perfume bottle','Glass lantern','Wine glass with a moon reflection')
$sets['Glass Effect Style Iridescent'] = @('Iridescent bubble','Holographic butterfly','Iridescent beetle shell','Rainbow soap bubble cluster','Iridescent seashell','Holographic heart','Iridescent dragonfly wings','Oil slick swirl','Iridescent feather','Pearl with a rainbow sheen')
$sets['Glass Effect Style Shattered'] = @('Shattered glass heart','Cracked glass skull','Breaking glass butterfly','Shards flying apart','Cracked glass moon','Shattered mirror circle','Broken glass rose','Cracked glass eye','Exploding glass orb','Glass wolf shattering')
$sets['Glass Effect Style Celestial'] = @('Glass planet with rings','Glass sun','Glass moon phases','Glass comet','Glass constellation stars','Glass galaxy orb','Glass shooting star','Glass eclipse','Glass astronaut helmet','Glass solar system')
$sets['Glass Effect Style Water and Ice'] = @('Water drop with a reflection','Ice crystal','Frozen rose','Glass wave','Icicle cluster','Water splash frozen in glass','Glass raindrop chain','Ice heart','Frozen butterfly','Glass water lily')
$sets['Glass Effect Style Small'] = @('Tiny glass heart','Small glass drop','Tiny crystal','Small glass star','Tiny glass bubble','Small glass moon','Tiny glass butterfly','Small glass key','Tiny prism','Small glass eye')
$sets['Glass Effect Style Large Pieces'] = @('Glass koi half sleeve','Crystal cluster back piece','Glass butterflies thigh piece','Shattered glass full sleeve','Glass jellyfish leg sleeve','Glass snake forearm piece','Glass planets shoulder piece','Crystal spine piece','Glass heart chest piece','Iridescent calf piece')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Glass Effect Style" } else { $n } }
"== Glass Effect before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:glass-effect" --remote 2>$null | Out-Null
RUN "CATEGORY Glass Effect :: Glass Effect Style Animals, Glass Effect Style Hearts and Symbols, Glass Effect Style Crystals and Gems, Glass Effect Style Bottles and Vessels, Glass Effect Style Iridescent, Glass Effect Style Shattered, Glass Effect Style Celestial, Glass Effect Style Water and Ice, Glass Effect Style Small, Glass Effect Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Glass Effect Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Glass Effect Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Glass hummingbird"))
}
}
