cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Stained Glass")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Stained Glass Style Florals','Stained Glass Style Animals','Stained Glass Style Birds','Stained Glass Style Insects','Stained Glass Style Celestial','Stained Glass Style Sacred','Stained Glass Style Hearts and Symbols','Stained Glass Style Portraits','Stained Glass Style Small','Stained Glass Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Stained glass rose'] = 'The tattoo: stained glass rose. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass lotus'] = 'The tattoo: stained glass lotus. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass iris'] = 'The tattoo: stained glass iris. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass peony'] = 'The tattoo: stained glass peony. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass sunflower'] = 'The tattoo: stained glass sunflower. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Stained glass tulip window'] = 'The tattoo: stained glass tulip window. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass poppy'] = 'The tattoo: stained glass poppy. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Stained glass orchid'] = 'The tattoo: stained glass orchid. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass cherry blossom branch'] = 'The tattoo: stained glass cherry blossom branch. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stained glass wildflower bouquet'] = 'The tattoo: stained glass wildflower bouquet. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass fox'] = 'The tattoo: stained glass fox. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stained glass wolf head'] = 'The tattoo: stained glass wolf head. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass lion'] = 'The tattoo: stained glass lion. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Stained glass deer'] = 'The tattoo: stained glass deer. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Stained glass cat'] = 'The tattoo: stained glass cat. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass koi'] = 'The tattoo: stained glass koi. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Stained glass owl'] = 'The tattoo: stained glass owl. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass snake'] = 'The tattoo: stained glass snake. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass horse'] = 'The tattoo: stained glass horse. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Stained glass jellyfish'] = 'The tattoo: stained glass jellyfish. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass hummingbird'] = 'The tattoo: stained glass hummingbird. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass peacock'] = 'The tattoo: stained glass peacock. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass swallow'] = 'The tattoo: stained glass swallow. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Stained glass phoenix'] = 'The tattoo: stained glass phoenix. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass raven'] = 'The tattoo: stained glass raven. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Stained glass hawk'] = 'The tattoo: stained glass hawk. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass dove'] = 'The tattoo: stained glass dove. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stained glass kingfisher'] = 'The tattoo: stained glass kingfisher. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass flamingo'] = 'The tattoo: stained glass flamingo. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass swan'] = 'The tattoo: stained glass swan. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass butterfly'] = 'The tattoo: stained glass butterfly. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Stained glass moth'] = 'The tattoo: stained glass moth. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Stained glass dragonfly'] = 'The tattoo: stained glass dragonfly. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass beetle'] = 'The tattoo: stained glass beetle. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Stained glass bee'] = 'The tattoo: stained glass bee. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass luna moth'] = 'The tattoo: stained glass luna moth. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass ladybug'] = 'The tattoo: stained glass ladybug. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Stained glass scarab'] = 'The tattoo: stained glass scarab. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass monarch'] = 'The tattoo: stained glass monarch. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass cicada'] = 'The tattoo: stained glass cicada. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass sun'] = 'The tattoo: stained glass sun. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Stained glass crescent moon'] = 'The tattoo: stained glass crescent moon. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass moon phases'] = 'The tattoo: stained glass moon phases. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Stained glass star burst'] = 'The tattoo: stained glass star burst. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass eclipse'] = 'The tattoo: stained glass eclipse. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stained glass galaxy window'] = 'The tattoo: stained glass galaxy window. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass planet'] = 'The tattoo: stained glass planet. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass sun and moon'] = 'The tattoo: stained glass sun and moon. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass comet'] = 'The tattoo: stained glass comet. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stained glass zodiac wheel'] = 'The tattoo: stained glass zodiac wheel. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass angel'] = 'The tattoo: stained glass angel. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass sacred heart'] = 'The tattoo: stained glass sacred heart. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Stained glass dove of peace'] = 'The tattoo: stained glass dove of peace. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass halo saint'] = 'The tattoo: stained glass halo saint. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass cross with roses'] = 'The tattoo: stained glass cross with roses. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Stained glass praying hands'] = 'The tattoo: stained glass praying hands. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass archangel wings'] = 'The tattoo: stained glass archangel wings. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass chalice'] = 'The tattoo: stained glass chalice. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass lamb'] = 'The tattoo: stained glass lamb. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass rose window'] = 'The tattoo: stained glass rose window. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass heart'] = 'The tattoo: stained glass heart. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Stained glass eye'] = 'The tattoo: stained glass eye. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass key'] = 'The tattoo: stained glass key. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stained glass hourglass'] = 'The tattoo: stained glass hourglass. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass anchor'] = 'The tattoo: stained glass anchor. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass skull'] = 'The tattoo: stained glass skull. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass dagger'] = 'The tattoo: stained glass dagger. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stained glass crown'] = 'The tattoo: stained glass crown. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass hand'] = 'The tattoo: stained glass hand. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Stained glass compass'] = 'The tattoo: stained glass compass. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Stained glass woman in profile'] = 'The tattoo: stained glass woman in profile. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass Art Nouveau goddess'] = 'The tattoo: stained glass art nouveau goddess. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass knight'] = 'The tattoo: stained glass knight. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Stained glass mermaid'] = 'The tattoo: stained glass mermaid. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stained glass fairy'] = 'The tattoo: stained glass fairy. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass queen'] = 'The tattoo: stained glass queen. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stained glass dancer'] = 'The tattoo: stained glass dancer. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stained glass moon goddess'] = 'The tattoo: stained glass moon goddess. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass warrior'] = 'The tattoo: stained glass warrior. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Stained glass angel face'] = 'The tattoo: stained glass angel face. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny stained glass heart'] = 'The tattoo: tiny stained glass heart. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small stained glass butterfly'] = 'The tattoo: small stained glass butterfly. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny stained glass moon'] = 'The tattoo: tiny stained glass moon. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small stained glass flower'] = 'The tattoo: small stained glass flower. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny stained glass star'] = 'The tattoo: tiny stained glass star. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small stained glass eye'] = 'The tattoo: small stained glass eye. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny stained glass diamond'] = 'The tattoo: tiny stained glass diamond. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small stained glass leaf'] = 'The tattoo: small stained glass leaf. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny stained glass bee'] = 'The tattoo: tiny stained glass bee. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small stained glass sun'] = 'The tattoo: small stained glass sun. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Cathedral window back piece'] = 'The tattoo: cathedral window back piece. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Stained glass garden sleeve'] = 'The tattoo: stained glass garden sleeve. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Rose window chest piece'] = 'The tattoo: rose window chest piece. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Stained glass phoenix thigh piece'] = 'The tattoo: stained glass phoenix thigh piece. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stained glass koi forearm piece'] = 'The tattoo: stained glass koi forearm piece. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stained glass vine spine piece'] = 'The tattoo: stained glass vine spine piece. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Stained glass birds half sleeve'] = 'The tattoo: stained glass birds half sleeve. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Stained glass flower calf piece'] = 'The tattoo: stained glass flower calf piece. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stained glass sun shoulder piece'] = 'The tattoo: stained glass sun shoulder piece. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Stained glass forest leg sleeve'] = 'The tattoo: stained glass forest leg sleeve. Stained glass tattoo art, bold black leading lines dividing glowing jewel-toned glass panels, luminous saturated colour as if light is shining through, subtle glass texture and gradient within each panel, clean symmetric composition, designed like work from a top stained glass tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Stained Glass Style Florals'] = @('Stained glass rose','Stained glass lotus','Stained glass iris','Stained glass peony','Stained glass sunflower','Stained glass tulip window','Stained glass poppy','Stained glass orchid','Stained glass cherry blossom branch','Stained glass wildflower bouquet')
$sets['Stained Glass Style Animals'] = @('Stained glass fox','Stained glass wolf head','Stained glass lion','Stained glass deer','Stained glass cat','Stained glass koi','Stained glass owl','Stained glass snake','Stained glass horse','Stained glass jellyfish')
$sets['Stained Glass Style Birds'] = @('Stained glass hummingbird','Stained glass peacock','Stained glass swallow','Stained glass phoenix','Stained glass raven','Stained glass hawk','Stained glass dove','Stained glass kingfisher','Stained glass flamingo','Stained glass swan')
$sets['Stained Glass Style Insects'] = @('Stained glass butterfly','Stained glass moth','Stained glass dragonfly','Stained glass beetle','Stained glass bee','Stained glass luna moth','Stained glass ladybug','Stained glass scarab','Stained glass monarch','Stained glass cicada')
$sets['Stained Glass Style Celestial'] = @('Stained glass sun','Stained glass crescent moon','Stained glass moon phases','Stained glass star burst','Stained glass eclipse','Stained glass galaxy window','Stained glass planet','Stained glass sun and moon','Stained glass comet','Stained glass zodiac wheel')
$sets['Stained Glass Style Sacred'] = @('Stained glass angel','Stained glass sacred heart','Stained glass dove of peace','Stained glass halo saint','Stained glass cross with roses','Stained glass praying hands','Stained glass archangel wings','Stained glass chalice','Stained glass lamb','Stained glass rose window')
$sets['Stained Glass Style Hearts and Symbols'] = @('Stained glass heart','Stained glass eye','Stained glass key','Stained glass hourglass','Stained glass anchor','Stained glass skull','Stained glass dagger','Stained glass crown','Stained glass hand','Stained glass compass')
$sets['Stained Glass Style Portraits'] = @('Stained glass woman in profile','Stained glass Art Nouveau goddess','Stained glass knight','Stained glass mermaid','Stained glass fairy','Stained glass queen','Stained glass dancer','Stained glass moon goddess','Stained glass warrior','Stained glass angel face')
$sets['Stained Glass Style Small'] = @('Tiny stained glass heart','Small stained glass butterfly','Tiny stained glass moon','Small stained glass flower','Tiny stained glass star','Small stained glass eye','Tiny stained glass diamond','Small stained glass leaf','Tiny stained glass bee','Small stained glass sun')
$sets['Stained Glass Style Large Pieces'] = @('Cathedral window back piece','Stained glass garden sleeve','Rose window chest piece','Stained glass phoenix thigh piece','Stained glass koi forearm piece','Stained glass vine spine piece','Stained glass birds half sleeve','Stained glass flower calf piece','Stained glass sun shoulder piece','Stained glass forest leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Stained Glass Style" } else { $n } }
"== Stained Glass before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:stained-glass" --remote 2>$null | Out-Null
RUN "CATEGORY Stained Glass :: Stained Glass Style Florals, Stained Glass Style Animals, Stained Glass Style Birds, Stained Glass Style Insects, Stained Glass Style Celestial, Stained Glass Style Sacred, Stained Glass Style Hearts and Symbols, Stained Glass Style Portraits, Stained Glass Style Small, Stained Glass Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Stained Glass Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Stained Glass Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Stained glass hummingbird"))
}
}
