cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$out = @()
"== Neo-Tribal =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: Flowing neo-tribal blackwork that wraps the shoulder and sweeps down the arm in sharp curved blades and hooked tips, bold solid black with clean bare-skin channels cutting through it. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is over his shoulder and down his upper arm, wearing a plain tank top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Neo-Tribal: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Patchwork =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A tight cluster of mismatched old-school mini tattoos fitted together like a collage - a dagger, a swallow, a rose, a moth, a crescent moon and a burning heart - bold black lines with red and gold. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is covering the outside of his forearm, wearing a plain short-sleeve shirt. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Patchwork: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Embroidered Tattoos =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A peony and a hummingbird that look hand-stitched into the skin, every petal and feather made of visible satin-stitch thread with tiny raised highlights and a few loose threads trailing off. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the back of her shoulder, wearing a low-back top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Embroidered Tattoos: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Sticker Tattoos =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A glossy cartoon cherry bomb with a lit fuse and a cheeky grin, drawn like a die-cut vinyl sticker with a thick white border, a soft drop shadow and one corner peeling up. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the front of his thigh, wearing plain shorts. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Sticker Tattoos: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Ignorant Doodle =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A wobbly hand-drawn ghost riding a skateboard and holding a single balloon, thin shaky black lines, naive on purpose and charmingly bad. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is small, about the size of a playing card, on the inside of her wrist, a close-up of the wrist. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Ignorant Doodle: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Micro Tattoos =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A tiny single-needle hot air balloon drifting past a crescent moon and three stars, delicate and precise, the size of a coin. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is small, behind her ear, a close-up of the side of her head with her hair tucked back. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Micro Tattoos: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Fine-Line Florals =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A long trailing stem of wild poppies, lavender and fern unfolding in one graceful line, ultra-fine black linework with soft grey shading. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is down the side of her ribs, wearing a bandeau top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Fine-Line Florals: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Y2K Nostalgia =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A sparkling butterfly with flip-phone antennas and pixel hearts, surrounded by glitter stars and a bubbly chrome halo, early-2000s pink and baby blue. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on her lower back, wearing low-rise jeans and a cropped top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Y2K Nostalgia: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Organic Body Flow =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: Sweeping black ink tendrils and leaves that curve with the muscles, rising like smoke that turns into vines, flowing and asymmetric. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is from her hip up the side of her waist, wearing a bandeau top and low-waist pants. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Organic Body Flow: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Red Ink =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A blood-red koi spiraling around a crimson lotus, done entirely in red ink, deep rich reds and fine red linework with no black at all. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the outside of her thigh, wearing plain shorts. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Red Ink: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Negative Space =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A huge crashing wave with a tiny surfer inside the barrel, carved out of a solid black circle, the wave and surfer formed entirely by bare skin left untouched inside the black. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the outside of his upper arm, wearing a plain short-sleeve shirt. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Negative Space: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Bows & Ribbons =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A satin bow tied at the top of the spine with long silky ribbons trailing down, delicate fine-line shading with a soft pink sheen. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is at the top of her back between the shoulder blades, wearing a low open-back top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Bows & Ribbons: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Birth Month Flowers =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A bouquet of all twelve birth month flowers - carnation, violet, daffodil, daisy, lily of the valley, rose, larkspur, poppy, aster, marigold, chrysanthemum and narcissus - bound with a thin ribbon, fine-line with soft watercolor tints. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the inside of her forearm, wearing a plain short-sleeve top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Birth Month Flowers: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Stained Glass =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A glowing stained-glass phoenix rising with spread wings, jewel-toned panes of ruby, amber and cobalt held in thick black leading lines, light seeming to shine through it. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is across his upper back, seen from behind. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Stained Glass: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Renaissance =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A Renaissance angel in mid-flight reaching out one hand, painted like an old fresco with soft smoky shading, cracked gold leaf and a fragment of classical columns behind. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the back of his calf, wearing plain shorts. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Renaissance: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== all 15 =="
$out
