cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$out = @()
"== Sticker Tattoos 1 of 4"
$r = (RUN 'SHOW_IT {"subject": "Tiny alien cowboy riding a frog inside a holographic sticker whose corner is visibly peeling. Something completely ridiculous that looks physically STUCK ON. The viewer should want to peel it. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Sticker Tattoos 1: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Sticker Tattoos 2 of 4"
$r = (RUN 'SHOW_IT {"subject": "Glossy cherry-red vinyl sticker of a grinning little devil whose pitchfork pokes out through the sticker edge. Something completely ridiculous that looks physically STUCK ON. The viewer should want to peel it. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Sticker Tattoos 2: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Sticker Tattoos 3 of 4"
$r = (RUN 'SHOW_IT {"subject": "Chrome sticker of a koi fish leaping out of its own die-cut border with water droplets flying. Something completely ridiculous that looks physically STUCK ON. The viewer should want to peel it. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Sticker Tattoos 3: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Sticker Tattoos 4 of 4"
$r = (RUN 'SHOW_IT {"subject": "Weathered vintage bumper sticker of a desert motel with one corner curling up to reveal stars underneath. Something completely ridiculous that looks physically STUCK ON. The viewer should want to peel it. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Sticker Tattoos 4: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Cybersigilism 1 of 4"
$r = (RUN 'SHOW_IT {"subject": "Black cybersigil flowing down an invisible spine like alien calligraphy. Aggressive futuristic black sigil flowing like alien calligraphy, cybernetic tribal energy, sharp and elegant simultaneously. It should look dangerous and futuristic. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Cybersigilism 1: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Cybersigilism 2 of 4"
$r = (RUN 'SHOW_IT {"subject": "Cybersigil crown of sharp thorned black lines radiating outward. Aggressive futuristic black sigil flowing like alien calligraphy, cybernetic tribal energy, sharp and elegant simultaneously. It should look dangerous and futuristic. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Cybersigilism 2: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Cybersigilism 3 of 4"
$r = (RUN 'SHOW_IT {"subject": "Pair of cybersigil wings formed from razor-thin black strokes and hooks. Aggressive futuristic black sigil flowing like alien calligraphy, cybernetic tribal energy, sharp and elegant simultaneously. It should look dangerous and futuristic. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Cybersigilism 3: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Cybersigilism 4 of 4"
$r = (RUN 'SHOW_IT {"subject": "Symmetrical cybersigil shaped like a mask, sharp hooks and flowing barbs. Aggressive futuristic black sigil flowing like alien calligraphy, cybernetic tribal energy, sharp and elegant simultaneously. It should look dangerous and futuristic. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Cybersigilism 4: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Horror 1 of 4"
$r = (RUN 'SHOW_IT {"subject": "Pale blank slasher mask emerging from autumn darkness beneath a cold moon. A horror tattoo that makes a horror fan stop scrolling: cinematic atmosphere, dramatic lighting, real dread or dark beauty. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Horror 1: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Horror 2 of 4"
$r = (RUN 'SHOW_IT {"subject": "Vampire castle balanced on a needle-thin mountain beneath a blood-red moon. A horror tattoo that makes a horror fan stop scrolling: cinematic atmosphere, dramatic lighting, real dread or dark beauty. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Horror 2: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Horror 3 of 4"
$r = (RUN 'SHOW_IT {"subject": "Ornate coffin opened to reveal an endless star-filled universe instead of a body. A horror tattoo that makes a horror fan stop scrolling: cinematic atmosphere, dramatic lighting, real dread or dark beauty. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Horror 3: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Horror 4 of 4"
$r = (RUN 'SHOW_IT {"subject": "Werewolf mid-transformation beneath a gigantic full moon, clothing tearing away. A horror tattoo that makes a horror fan stop scrolling: cinematic atmosphere, dramatic lighting, real dread or dark beauty. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point, not excessive tiny detail. Tattoo artwork, no generated text labels, no lettering, no watermark. Keep the hero subject visually dominant with breathing room, no critical elements at the extreme edges.", "raw": true}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Horror 4: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== all 12 =="
$out
