cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$out = @()
"== Cybersigilism =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: Razor-sharp black cybersigil running the full length of the spine and exploding at the top into a winged crown of hooks and thorns, like alien calligraphy forged in obsidian with a cold chrome edge. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is down her spine, seen from behind in a low open-back top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Cybersigilism: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Liquid Chrome =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: Liquid chrome serpent pouring out of a cracked mirror-polished heart, molten metal drips stretching into impossible ribbons that reflect a neon city. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Liquid Chrome: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== Micro Realism =="
$r = (RUN 'SHOW_IT {"subject": "The tattoo: A complete stormy ocean with a lighthouse beam cutting through the rain, contained inside a hand-sized antique pocket watch, every wave hyper-detailed. ONE spectacular tattoo concept, visually readable at small card size: strong silhouette, strong contrast, clear focal point. No generated text labels, no lettering, no watermark. In the right panel it is on the outside of her upper arm, wearing a sleeveless top. Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person''s body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.", "raw": true, "aspect": "3:2"}' | Out-String)
$u = [regex]::Match($r, "https://auras\.guide/image/img_[a-z0-9]+").Value; if ($u) { "  " + $u; $out += ("Micro Realism: " + $u) } else { "  FAILED: " + $r.Substring(0,[Math]::Min(300,$r.Length)) }
"== all 3 =="
$out
