cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Horror Surrealism")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Long-limbed creature in a doorway'] = 'The tattoo: long-limbed creature in a doorway. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Spider with a human face'] = 'The tattoo: spider with a human face. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Moth with eyes on its wings'] = 'The tattoo: moth with eyes on its wings. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Tall thin figure in fog'] = 'The tattoo: tall thin figure in fog. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Deer with too many eyes'] = 'The tattoo: deer with too many eyes. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Crow with a human hand'] = 'The tattoo: crow with a human hand. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Creature made of tangled branches'] = 'The tattoo: creature made of tangled branches. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Faceless figure with long fingers'] = 'The tattoo: faceless figure with long fingers. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Wolf with a mouth of eyes'] = 'The tattoo: wolf with a mouth of eyes. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Octopus with doll heads'] = 'The tattoo: octopus with doll heads. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Face with a second face underneath'] = 'The tattoo: face with a second face underneath. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Smile stretched too wide'] = 'The tattoo: smile stretched too wide. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Face made of crawling moths'] = 'The tattoo: face made of crawling moths. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Eyeless face crying ink'] = 'The tattoo: eyeless face crying ink. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Face sliding off like wax'] = 'The tattoo: face sliding off like wax. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Mouth full of tiny hands'] = 'The tattoo: mouth full of tiny hands. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Head opening like a flower with teeth'] = 'The tattoo: head opening like a flower with teeth. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Face split by a zipper'] = 'The tattoo: face split by a zipper. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Porcelain face cracking'] = 'The tattoo: porcelain face cracking. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Face peeking through skin like a mask'] = 'The tattoo: face peeking through skin like a mask. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Eye with a spider inside'] = 'The tattoo: eye with a spider inside. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cluster of eyes on a vine'] = 'The tattoo: cluster of eyes on a vine. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Teeth growing like flowers'] = 'The tattoo: teeth growing like flowers. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Eye in an open palm'] = 'The tattoo: eye in an open palm. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Jar full of eyes'] = 'The tattoo: jar full of eyes. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Hand with teeth on its fingers'] = 'The tattoo: hand with teeth on its fingers. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Eye peering from a keyhole'] = 'The tattoo: eye peering from a keyhole. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Rose with teeth'] = 'The tattoo: rose with teeth. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Eyeball on spider legs'] = 'The tattoo: eyeball on spider legs. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Moon with teeth'] = 'The tattoo: moon with teeth. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Cracked doll with glowing eyes'] = 'The tattoo: cracked doll with glowing eyes. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Music box with a ballerina skeleton'] = 'The tattoo: music box with a ballerina skeleton. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Rocking chair moving on its own'] = 'The tattoo: rocking chair moving on its own. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Old television showing an eye'] = 'The tattoo: old television showing an eye. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Antique mirror with a figure behind'] = 'The tattoo: antique mirror with a figure behind. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Telephone made of bones'] = 'The tattoo: telephone made of bones. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Teddy bear with stitched mouth'] = 'The tattoo: teddy bear with stitched mouth. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Clock with fingers for hands'] = 'The tattoo: clock with fingers for hands. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Birdcage holding a heart'] = 'The tattoo: birdcage holding a heart. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Candle dripping like flesh'] = 'The tattoo: candle dripping like flesh. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['House with a mouth for a door'] = 'The tattoo: house with a mouth for a door. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Staircase going down into teeth'] = 'The tattoo: staircase going down into teeth. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Forest of hands'] = 'The tattoo: forest of hands. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Lighthouse with an eye for a light'] = 'The tattoo: lighthouse with an eye for a light. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Moon peeling open'] = 'The tattoo: moon peeling open. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Stairs leading into a skull'] = 'The tattoo: stairs leading into a skull. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Door in the woods with light behind'] = 'The tattoo: door in the woods with light behind. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Church with long legs'] = 'The tattoo: church with long legs. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Field of eyes under a red sky'] = 'The tattoo: field of eyes under a red sky. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Hallway that becomes a throat'] = 'The tattoo: hallway that becomes a throat. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Moths pouring from a mouth'] = 'The tattoo: moths pouring from a mouth. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Beetles forming a skull'] = 'The tattoo: beetles forming a skull. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Flowers growing from an eye socket'] = 'The tattoo: flowers growing from an eye socket. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Mushrooms growing from a hand'] = 'The tattoo: mushrooms growing from a hand. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Roots growing through a face'] = 'The tattoo: roots growing through a face. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Centipede wrapped around a heart'] = 'The tattoo: centipede wrapped around a heart. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Bees building a hive in a skull'] = 'The tattoo: bees building a hive in a skull. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Snakes coming from a book'] = 'The tattoo: snakes coming from a book. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Spiders weaving a veil'] = 'The tattoo: spiders weaving a veil. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Rotting rose with beetles'] = 'The tattoo: rotting rose with beetles. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Rabbit mask with human eyes'] = 'The tattoo: rabbit mask with human eyes. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Plague doctor with no face'] = 'The tattoo: plague doctor with no face. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Smiling theatre mask crying'] = 'The tattoo: smiling theatre mask crying. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Porcelain mask with a crack'] = 'The tattoo: porcelain mask with a crack. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Animal skull mask'] = 'The tattoo: animal skull mask. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Mask with stitched eyes'] = 'The tattoo: mask with stitched eyes. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Masked figure holding a balloon'] = 'The tattoo: masked figure holding a balloon. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Deer skull mask with antlers'] = 'The tattoo: deer skull mask with antlers. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Gas mask with flowers'] = 'The tattoo: gas mask with flowers. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Mask hiding a second mask'] = 'The tattoo: mask hiding a second mask. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Melting candle face'] = 'The tattoo: melting candle face. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Stretched figure in a doorway'] = 'The tattoo: stretched figure in a doorway. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Body dissolving into smoke'] = 'The tattoo: body dissolving into smoke. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Hand melting into a puddle of eyes'] = 'The tattoo: hand melting into a puddle of eyes. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Twisted spiral of faces'] = 'The tattoo: twisted spiral of faces. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Skull melting over a clock'] = 'The tattoo: skull melting over a clock. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Upside-down figure on the ceiling'] = 'The tattoo: upside-down figure on the ceiling. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Shadow that does not match'] = 'The tattoo: shadow that does not match. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Face reflected wrong in water'] = 'The tattoo: face reflected wrong in water. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Figure folding into itself'] = 'The tattoo: figure folding into itself. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny eye with legs'] = 'The tattoo: tiny eye with legs. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small smiling moon'] = 'The tattoo: small smiling moon. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny hand with an eye'] = 'The tattoo: tiny hand with an eye. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small cracked doll head'] = 'The tattoo: small cracked doll head. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny moth with a face'] = 'The tattoo: tiny moth with a face. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small key made of teeth'] = 'The tattoo: small key made of teeth. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Little door with an eye'] = 'The tattoo: little door with an eye. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Tiny ghost with a smile'] = 'The tattoo: tiny ghost with a smile. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Small spider with a skull'] = 'The tattoo: small spider with a skull. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny weeping mask'] = 'The tattoo: tiny weeping mask. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Nightmare forest back piece'] = 'The tattoo: nightmare forest back piece. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Creature in fog sleeve'] = 'The tattoo: creature in fog sleeve. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Haunted house chest piece'] = 'The tattoo: haunted house chest piece. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Eyes and moths thigh piece'] = 'The tattoo: eyes and moths thigh piece. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Long-limbed figure forearm piece'] = 'The tattoo: long-limbed figure forearm piece. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Teeth and roses spine piece'] = 'The tattoo: teeth and roses spine piece. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Masked figures half sleeve'] = 'The tattoo: masked figures half sleeve. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Doorway in the woods calf piece'] = 'The tattoo: doorway in the woods calf piece. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Melting faces shoulder piece'] = 'The tattoo: melting faces shoulder piece. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Forest of hands leg sleeve'] = 'The tattoo: forest of hands leg sleeve. Horror surrealism tattoo art, unsettling dreamlike nightmares and impossible creepy imagery, eerie rather than gory, black and grey with deep shadows and a touch of muted red, detailed dark illustrative realism, designed like work from a top horror tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Horror Surrealism Style Creatures'] = @('Long-limbed creature in a doorway','Spider with a human face','Moth with eyes on its wings','Tall thin figure in fog','Deer with too many eyes','Crow with a human hand','Creature made of tangled branches','Faceless figure with long fingers','Wolf with a mouth of eyes','Octopus with doll heads')
$sets['Horror Surrealism Style Faces'] = @('Face with a second face underneath','Smile stretched too wide','Face made of crawling moths','Eyeless face crying ink','Face sliding off like wax','Mouth full of tiny hands','Head opening like a flower with teeth','Face split by a zipper','Porcelain face cracking','Face peeking through skin like a mask')
$sets['Horror Surrealism Style Eyes and Teeth'] = @('Eye with a spider inside','Cluster of eyes on a vine','Teeth growing like flowers','Eye in an open palm','Jar full of eyes','Hand with teeth on its fingers','Eye peering from a keyhole','Rose with teeth','Eyeball on spider legs','Moon with teeth')
$sets['Horror Surrealism Style Haunted Objects'] = @('Cracked doll with glowing eyes','Music box with a ballerina skeleton','Rocking chair moving on its own','Old television showing an eye','Antique mirror with a figure behind','Telephone made of bones','Teddy bear with stitched mouth','Clock with fingers for hands','Birdcage holding a heart','Candle dripping like flesh')
$sets['Horror Surrealism Style Nightmare Scenes'] = @('House with a mouth for a door','Staircase going down into teeth','Forest of hands','Lighthouse with an eye for a light','Moon peeling open','Stairs leading into a skull','Door in the woods with light behind','Church with long legs','Field of eyes under a red sky','Hallway that becomes a throat')
$sets['Horror Surrealism Style Infestation'] = @('Moths pouring from a mouth','Beetles forming a skull','Flowers growing from an eye socket','Mushrooms growing from a hand','Roots growing through a face','Centipede wrapped around a heart','Bees building a hive in a skull','Snakes coming from a book','Spiders weaving a veil','Rotting rose with beetles')
$sets['Horror Surrealism Style Masks'] = @('Rabbit mask with human eyes','Plague doctor with no face','Smiling theatre mask crying','Porcelain mask with a crack','Animal skull mask','Mask with stitched eyes','Masked figure holding a balloon','Deer skull mask with antlers','Gas mask with flowers','Mask hiding a second mask')
$sets['Horror Surrealism Style Melting and Distortion'] = @('Melting candle face','Stretched figure in a doorway','Body dissolving into smoke','Hand melting into a puddle of eyes','Twisted spiral of faces','Skull melting over a clock','Upside-down figure on the ceiling','Shadow that does not match','Face reflected wrong in water','Figure folding into itself')
$sets['Horror Surrealism Style Small'] = @('Tiny eye with legs','Small smiling moon','Tiny hand with an eye','Small cracked doll head','Tiny moth with a face','Small key made of teeth','Little door with an eye','Tiny ghost with a smile','Small spider with a skull','Tiny weeping mask')
$sets['Horror Surrealism Style Large Pieces'] = @('Nightmare forest back piece','Creature in fog sleeve','Haunted house chest piece','Eyes and moths thigh piece','Long-limbed figure forearm piece','Teeth and roses spine piece','Masked figures half sleeve','Doorway in the woods calf piece','Melting faces shoulder piece','Forest of hands leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Horror Surrealism Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Horror Surrealism Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Horror Surrealism Style$','') -ne 'Moth with eyes on its wings' })
}
"== drawing " + $all.Count + " Horror Surrealism split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK Horror Surrealism"
RUN "SHEET Horror Surrealism"
}
