cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Hyperrealism")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Human eye reflecting a sunset'] = 'The tattoo: human eye reflecting a sunset. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Lion eye close-up'] = 'The tattoo: lion eye close-up. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Owl eye macro'] = 'The tattoo: owl eye macro. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Wolf eye with an amber iris'] = 'The tattoo: wolf eye with an amber iris. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Eye with a single tear'] = 'The tattoo: eye with a single tear. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Cat eye with a slit pupil'] = 'The tattoo: cat eye with a slit pupil. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Eagle eye close-up'] = 'The tattoo: eagle eye close-up. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Eye with lashes and a catchlight'] = 'The tattoo: eye with lashes and a catchlight. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Horse eye with long lashes'] = 'The tattoo: horse eye with long lashes. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Snake eye macro'] = 'The tattoo: snake eye macro. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Water droplet on a rose petal'] = 'The tattoo: water droplet on a rose petal. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Glass marble holding a galaxy'] = 'The tattoo: glass marble holding a galaxy. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Water splash frozen in time'] = 'The tattoo: water splash frozen in time. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Wine glass with reflections'] = 'The tattoo: wine glass with reflections. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Melting ice cube'] = 'The tattoo: melting ice cube. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Raindrops on a leaf'] = 'The tattoo: raindrops on a leaf. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Glass bottle with a tiny ship'] = 'The tattoo: glass bottle with a tiny ship. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Crystal ball reflecting a forest'] = 'The tattoo: crystal ball reflecting a forest. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Dew on a spider web'] = 'The tattoo: dew on a spider web. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Soap bubble with a rainbow film'] = 'The tattoo: soap bubble with a rainbow film. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Diamond ring'] = 'The tattoo: diamond ring. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Gold chain links'] = 'The tattoo: gold chain links. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pocket watch with exposed gears'] = 'The tattoo: pocket watch with exposed gears. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Scratched silver key'] = 'The tattoo: scratched silver key. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Chrome skull'] = 'The tattoo: chrome skull. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Pearl necklace'] = 'The tattoo: pearl necklace. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Brass compass macro'] = 'The tattoo: brass compass macro. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Vintage flip lighter'] = 'The tattoo: vintage flip lighter. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Gold coin'] = 'The tattoo: gold coin. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Mechanical heart with gears'] = 'The tattoo: mechanical heart with gears. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Feather macro'] = 'The tattoo: feather macro. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Snake scales close-up'] = 'The tattoo: snake scales close-up. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiger fur texture'] = 'The tattoo: tiger fur texture. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Butterfly wing scales'] = 'The tattoo: butterfly wing scales. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Tree bark with moss'] = 'The tattoo: tree bark with moss. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Peacock feather macro'] = 'The tattoo: peacock feather macro. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Shimmering fish scales'] = 'The tattoo: shimmering fish scales. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Lion mane detail'] = 'The tattoo: lion mane detail. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pine cone macro'] = 'The tattoo: pine cone macro. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Rose petals macro'] = 'The tattoo: rose petals macro. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Hyper-detailed lion face'] = 'The tattoo: hyper-detailed lion face. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Gorilla portrait'] = 'The tattoo: gorilla portrait. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Chameleon on a branch'] = 'The tattoo: chameleon on a branch. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Tree frog with water drops'] = 'The tattoo: tree frog with water drops. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Elephant skin and eye'] = 'The tattoo: elephant skin and eye. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Wolf with snow on its fur'] = 'The tattoo: wolf with snow on its fur. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Horse with a flowing mane'] = 'The tattoo: horse with a flowing mane. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bald eagle feathers'] = 'The tattoo: bald eagle feathers. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiger with water dripping'] = 'The tattoo: tiger with water dripping. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Owl with ruffled feathers'] = 'The tattoo: owl with ruffled feathers. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Split pomegranate'] = 'The tattoo: split pomegranate. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Sliced orange with juice'] = 'The tattoo: sliced orange with juice. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Strawberry with water drops'] = 'The tattoo: strawberry with water drops. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cherries with stems'] = 'The tattoo: cherries with stems. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Honey dripping from a dipper'] = 'The tattoo: honey dripping from a dipper. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Green apple'] = 'The tattoo: green apple. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Coffee beans'] = 'The tattoo: coffee beans. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Dripping chocolate'] = 'The tattoo: dripping chocolate. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Kiwi slice'] = 'The tattoo: kiwi slice. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Grapes with dew'] = 'The tattoo: grapes with dew. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Amethyst geode'] = 'The tattoo: amethyst geode. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Raw emerald crystal'] = 'The tattoo: raw emerald crystal. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Opal stone'] = 'The tattoo: opal stone. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Quartz point'] = 'The tattoo: quartz point. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Cut ruby'] = 'The tattoo: cut ruby. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Blue sapphire'] = 'The tattoo: blue sapphire. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Obsidian shard'] = 'The tattoo: obsidian shard. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Rose quartz heart'] = 'The tattoo: rose quartz heart. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Agate slice'] = 'The tattoo: agate slice. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Brilliant cut diamond'] = 'The tattoo: brilliant cut diamond. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Old man with deep wrinkles'] = 'The tattoo: old man with deep wrinkles. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woman with freckles in sunlight'] = 'The tattoo: woman with freckles in sunlight. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Weathered fisherman'] = 'The tattoo: weathered fisherman. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Woman behind a lace veil'] = 'The tattoo: woman behind a lace veil. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Man with a grey beard'] = 'The tattoo: man with a grey beard. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Ballerina in profile'] = 'The tattoo: ballerina in profile. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Elderly woman smiling'] = 'The tattoo: elderly woman smiling. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Boxer with a bruised face'] = 'The tattoo: boxer with a bruised face. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Warrior with face paint'] = 'The tattoo: warrior with face paint. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Woman with flowers in her hair'] = 'The tattoo: woman with flowers in her hair. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Hand made of water'] = 'The tattoo: hand made of water. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Face cracking like porcelain'] = 'The tattoo: face cracking like porcelain. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Rose made of glass'] = 'The tattoo: rose made of glass. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Eye inside a keyhole'] = 'The tattoo: eye inside a keyhole. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Moon inside a lightbulb'] = 'The tattoo: moon inside a lightbulb. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Whale inside a glass jar'] = 'The tattoo: whale inside a glass jar. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Hourglass with sand dunes'] = 'The tattoo: hourglass with sand dunes. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Skull made of ice'] = 'The tattoo: skull made of ice. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Feather turning into birds'] = 'The tattoo: feather turning into birds. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Clock dissolving into sand'] = 'The tattoo: clock dissolving into sand. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Lion with dripping water sleeve'] = 'The tattoo: lion with dripping water sleeve. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Eye and clock forearm piece'] = 'The tattoo: eye and clock forearm piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Ocean wave back piece'] = 'The tattoo: ocean wave back piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Wolf in a snowstorm chest piece'] = 'The tattoo: wolf in a snowstorm chest piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his chest, shirtless'
$b['Rose and droplets thigh piece'] = 'The tattoo: rose and droplets thigh piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Tiger fur half sleeve'] = 'The tattoo: tiger fur half sleeve. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$b['Geode calf piece'] = 'The tattoo: geode calf piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Portrait and rose forearm piece'] = 'The tattoo: portrait and rose forearm piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Eagle in flight back piece'] = 'The tattoo: eagle in flight back piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Mechanical heart chest piece'] = 'The tattoo: mechanical heart chest piece. Hyperrealism tattoo art, extreme lifelike detail beyond a photograph, visible pores, reflections, catchlights and fine textures, precise light gradients and deep dimensional shadows, rendered in rich natural colour or deep black and grey to suit the subject, designed like work from a top realism tattoo artist, no letters, no words. In the right panel it is across his chest, shirtless'
$sets = [ordered]@{}
$sets['Hyperrealism Style Eyes'] = @('Human eye reflecting a sunset','Lion eye close-up','Owl eye macro','Wolf eye with an amber iris','Eye with a single tear','Cat eye with a slit pupil','Eagle eye close-up','Eye with lashes and a catchlight','Horse eye with long lashes','Snake eye macro')
$sets['Hyperrealism Style Water and Glass'] = @('Water droplet on a rose petal','Glass marble holding a galaxy','Water splash frozen in time','Wine glass with reflections','Melting ice cube','Raindrops on a leaf','Glass bottle with a tiny ship','Crystal ball reflecting a forest','Dew on a spider web','Soap bubble with a rainbow film')
$sets['Hyperrealism Style Metal and Jewelry'] = @('Diamond ring','Gold chain links','Pocket watch with exposed gears','Scratched silver key','Chrome skull','Pearl necklace','Brass compass macro','Vintage flip lighter','Gold coin','Mechanical heart with gears')
$sets['Hyperrealism Style Textures'] = @('Feather macro','Snake scales close-up','Tiger fur texture','Butterfly wing scales','Tree bark with moss','Peacock feather macro','Shimmering fish scales','Lion mane detail','Pine cone macro','Rose petals macro')
$sets['Hyperrealism Style Animals'] = @('Hyper-detailed lion face','Gorilla portrait','Chameleon on a branch','Tree frog with water drops','Elephant skin and eye','Wolf with snow on its fur','Horse with a flowing mane','Bald eagle feathers','Tiger with water dripping','Owl with ruffled feathers')
$sets['Hyperrealism Style Food and Fruit'] = @('Split pomegranate','Sliced orange with juice','Strawberry with water drops','Cherries with stems','Honey dripping from a dipper','Green apple','Coffee beans','Dripping chocolate','Kiwi slice','Grapes with dew')
$sets['Hyperrealism Style Gems and Minerals'] = @('Amethyst geode','Raw emerald crystal','Opal stone','Quartz point','Cut ruby','Blue sapphire','Obsidian shard','Rose quartz heart','Agate slice','Brilliant cut diamond')
$sets['Hyperrealism Style Portraits'] = @('Old man with deep wrinkles','Woman with freckles in sunlight','Weathered fisherman','Woman behind a lace veil','Man with a grey beard','Ballerina in profile','Elderly woman smiling','Boxer with a bruised face','Warrior with face paint','Woman with flowers in her hair')
$sets['Hyperrealism Style Surreal'] = @('Hand made of water','Face cracking like porcelain','Rose made of glass','Eye inside a keyhole','Moon inside a lightbulb','Whale inside a glass jar','Hourglass with sand dunes','Skull made of ice','Feather turning into birds','Clock dissolving into sand')
$sets['Hyperrealism Style Large Pieces'] = @('Lion with dripping water sleeve','Eye and clock forearm piece','Ocean wave back piece','Wolf in a snowstorm chest piece','Rose and droplets thigh piece','Tiger fur half sleeve','Geode calf piece','Portrait and rose forearm piece','Eagle in flight back piece','Mechanical heart chest piece')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Hyperrealism Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Hyperrealism Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Hyperrealism Style$','') -ne 'Human eye reflecting a sunset' })
}
"== drawing " + $all.Count + " Hyperrealism split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK Hyperrealism"
RUN "SHEET Hyperrealism"
}
