cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.specific) { "COULD NOT READ THE CATALOG - nothing started, run the block again" } else {
$sets = [ordered]@{}
$sets['Cars Muscle Cars'] = @('1967 Ford Mustang Fastback black and grey realism aggressive front three-quarter view','1969 Chevrolet Camaro SS emerging through tire smoke','1970 Dodge Challenger RT beneath dramatic storm clouds','1969 Dodge Charger roaring down an empty desert highway','1967 Pontiac GTO head-on chrome grille catching the light','Shelby Cobra with American Traditional flames','Corvette Stingray reflected across wet pavement','Buick Grand National disappearing into black smoke','Plymouth Barracuda with psychedelic 1970s color','Classic Ford Mustang rendered like a vintage racing poster')
$sets['Cars Lowriders'] = @('1964 Chevrolet Impala lowrider in black-and-grey Chicano realism','Candy-red Impala hopping on hydraulics','Lowrider Chevrolet Monte Carlo on gold wire wheels','Cadillac lowrider cruising beneath palm trees at sunset','Lowrider viewed extremely low from the front chrome towering overhead','Purple lowrider surrounded by roses and ornamental filigree','Lowrider cruising through neon-lit Los Angeles streets','Classic Impala reflected in polished chrome lettering','Lowrider with elaborate candy paint rendered in rich color realism','Three-wheel-motion lowrider with smoke curling around the tires')
$sets['Cars JDM Legends'] = @('Nissan Skyline GT-R R34 drifting through neon rain','Toyota Supra Mk4 with glowing city reflections across the body','Mazda RX-7 FD sliding sideways through tire smoke','Honda NSX racing through a mountain tunnel','Datsun 240Z beneath a huge Japanese rising sun','Toyota AE86 drifting down a mountain pass','Mitsubishi Evo blasting through a wet nighttime street','Subaru WRX STI throwing snow through a rally corner','Nissan Silvia S15 surrounded by graffiti and tire smoke','Honda Civic Type R rendered in aggressive manga-panel style')
$sets['Cars Supercars'] = @('Porsche 911 carving through an Alpine switchback','Classic air-cooled Porsche 911 beneath a warm sunset','Porsche 911 GT3 screaming around a racetrack','Ferrari F40 in red-and-black graphic tattoo style','Ferrari Testarossa beneath 1980s Miami neon','Lamborghini Countach in retro airbrush style','Lamborghini Aventador surrounded by shattered-glass geometry','McLaren supercar streaking through abstract watercolor speed','Mercedes AMG emerging through dark architectural shadows','BMW M3 E30 attacking a mountain road')
$sets['Cars European Classics'] = @('Aston Martin DB5 in elegant black-and-grey realism','Jaguar E-Type surrounded by Art Nouveau ornament','Classic Mercedes 300SL with its gullwing doors raised','Porsche 356 driving along the California coast','Vintage Ferrari racing through the Italian countryside','Classic Mini Cooper tearing through a rainy London street','Volkswagen Beetle covered in colorful 1960s psychedelic flowers','Volkswagen bus loaded with surfboards beside an ocean sunset','Vintage Fiat 500 squeezed into a beautiful Italian street','Classic Rolls-Royce rendered like dark luxury Gothic artwork')
$sets['Cars Race Cars'] = @('Formula racing car at full speed beneath exploding track lights','Le Mans prototype racing through nighttime rain','Vintage Formula One car surrounded by checkered flags','NASCAR-style stock car throwing sparks against the wall','Dragster launching with the rear tires wrinkling under power','Funny car engulfed in flames at the starting line','Rally car airborne over a forest road','Drift car sideways with a giant wall of smoke','Porsche endurance racer glowing beneath Le Mans lights','Race car cockpit reflected inside a drivers helmet visor')
$sets['Cars Hot Rods'] = @('1932 Ford hot rod with exposed engine and traditional flames','Chopped Mercury lead sled cruising beneath streetlights','Rat rod with rusty metal texture and exposed mechanical parts','Blown hot rod engine towering through the hood','Flame-painted custom coupe in bold American Traditional style','Slammed vintage pickup with mirror-finish chrome wheels','Custom hot rod rendered in exaggerated New School style','Black hot rod emerging from red smoke','Vintage drag car with hand-painted racing graphics','Chopped custom car beneath a giant desert moon')
$sets['Cars Off-Road and Trucks'] = @('Ford Bronco climbing through rocky desert terrain','Toyota Land Cruiser crossing a river beneath mountains','Jeep crawling over impossible boulders','Baja trophy truck flying through desert dust','Lifted pickup blasting through deep mud','Classic Chevrolet pickup in a dramatic Western desert scene','Ford Raptor jumping across desert terrain','Off-road truck beneath a giant star-filled sky','Slammed custom pickup with brilliant candy paint','Monster truck crushing a tiny row of cars in comic-book style')
$sets['Cars Engines and Parts'] = @('V8 engine rendered like an anatomical heart','Turbocharger surrounded by Japanese clouds and lightning','Supercharger exploding through flames','Chrome wheel reflecting an entire nighttime city','Piston and connecting rod rendered like sacred mechanical ornament','Racing steering wheel surrounded by speed lines and telemetry graphics','Gearshift and tachometer at redline in black-and-grey realism','Engine bay transformed into biomechanical machinery','Brake rotor glowing red with sparks flying outward','Twin turbochargers arranged like mechanical lungs')
$sets['Cars Surreal Dream Cars'] = @('Porsche 911 breaking through a Renaissance painting','Mustang racing alongside a wild horse','Skyline GT-R driving through a cyberpunk city','Lowrider cruising beneath an enormous moon with chrome reflections everywhere','Ferrari exploding out of a stained-glass window','Corvette Stingray surrounded by ocean waves like a Japanese composition','Lamborghini rendered entirely as liquid chrome','Classic muscle car half realistic and half blueprint drawing','Supercar dissolving into speed smoke and geometric fragments','Dream-car garage lineup disappearing into cinematic darkness')
$sets['Motorcycles Harley Davidson'] = @('Harley-Davidson Road Glide head-on sharknose fairing dominating the composition','Harley-Davidson Street Glide cruising through a desert sunset','Harley-Davidson Fat Boy in chrome-heavy black-and-grey realism','Harley-Davidson Sportster beneath a glowing neon motel sign','Harley-Davidson Low Rider leaned aggressively through a mountain curve','Harley-Davidson Breakout with huge rear tire and polished chrome','Vintage Harley Panhead in gritty black-and-grey realism','Vintage Harley Knucklehead rendered as bold American Traditional','Harley Shovelhead surrounded by black smoke and flames','Outrageous custom bagger with candy paint and oversized front wheel')
$sets['Motorcycles Choppers'] = @('Long-fork old-school chopper beneath an enormous desert moon','1970s chopper with tall sissy bar and psychedelic paint','Chrome chopper surrounded by American Traditional roses','Murdered-out chopper emerging through dense black smoke','Gothic chopper surrounded by cathedral architecture','Flame-painted chopper screaming across a desert highway','Chrome chopper surrounded by Japanese clouds and peonies','Chopper reflected in a pool of gasoline and rainbow oil','Vintage chopper rendered as rough woodcut artwork','Futuristic chopper rendered entirely in liquid chrome')
$sets['Motorcycles Bobbers and Cafe Racers'] = @('Stripped-down bobber with fat tires in brutal blackwork','Vintage bobber beneath an abandoned gas-station sign','Black bobber surrounded by blood-red roses','Bobber side profile using dramatic negative space','Rat-bike bobber with rust and distressed-metal texture','Cafe racer speeding through a rainy city at night','Cafe racer beneath glowing neon signs','Vintage cafe racer rendered like a 1960s racing poster','Black-and-gold cafe racer with ornamental mechanical details','Cafe racer exploding through loose watercolor brush strokes')
$sets['Motorcycles Superbikes'] = @('Ducati Panigale leaned impossibly low through a racetrack corner','BMW S1000RR accelerating beneath dramatic track lights','Yamaha R1 racing through nighttime rain','Kawasaki Ninja screaming through a tunnel','Suzuki Hayabusa rendered in hyperreal metallic detail','Honda Fireblade throwing sparks through a corner','Superbike rider fully tucked at extreme speed','Two superbikes fighting side-by-side through a corner','Superbike exploding through shattered geometric fragments','Futuristic superbike surrounded by cyberpunk neon')
$sets['Motorcycles Vintage Classics'] = @('Triumph Bonneville carving through the English countryside','Vintage Norton cafe racer in detailed engraving style','Classic BMW boxer motorcycle beneath Alpine mountains','Vintage Honda CB750 with gorgeous exposed engine detail','Classic Indian motorcycle in rich vintage color','Triumph motorcycle surrounded by faded roses and racing graphics','1960s motorcycle rendered like a weathered screen-printed poster','Vintage Grand Prix motorcycle leaned through a historic circuit','Antique motorcycle engine rendered like luxury jewelry','Barn-find motorcycle with rust peeling paint and wildflowers')
$sets['Motorcycles Cruisers'] = @('Indian Scout in dramatic black-and-grey realism','Indian Chief surrounded by storm clouds and endless highway','Modern muscle cruiser beneath nighttime city lights','Power cruiser doing a massive burnout','Blacked-out muscle bike surrounded by brutalist black shapes','Polished custom cruiser reflecting fire across its chrome','Cruiser photographed from an extreme ground-level front angle','Cruiser riding through heavy rain with headlight blazing','Sinister black cruiser surrounded by ravens and smoke','Touring motorcycle crossing an endless American desert')
$sets['Motorcycles Dirt and Adventure'] = @('Motocross rider flying over an enormous dirt jump','Dirt bike throwing a wall of mud directly toward the viewer','Motocross bike upside down during a huge backflip','Enduro motorcycle climbing an impossible rocky mountain','Adventure motorcycle blasting across a rushing river','Adventure bike beneath enormous snow-covered mountains','Desert rally motorcycle racing through giant dunes','Dirt bike exploding through watercolor splashes of mud','Motocross machine rendered in aggressive graffiti style','Dirt bike jumping through a giant ring of fire')
$sets['Motorcycles Trackers and Scramblers'] = @('Flat-track motorcycle sliding completely sideways around a dirt oval','Street tracker beneath industrial city lights','Vintage board-track racer on an old wooden racing circuit','Speedway motorcycle throwing dirt in stark blackwork','Custom tracker surrounded by bold geometric graphics','Scrambler climbing a rocky hillside','Scrambler crossing a shallow forest stream','Triumph-style scrambler beneath enormous mountain scenery','Desert scrambler surrounded by cactus beneath a blazing sun','Urban scrambler ripping through a graffiti-covered alley')
$sets['Motorcycles Engines and Parts'] = @('V-twin engine rendered like a mechanical anatomical heart','Motorcycle engine exploded into hundreds of floating mechanical pieces','Chrome exhaust pipes twisting into ornamental filigree','Spoked motorcycle wheel transforming into a sacred geometric mandala','Heavy motorcycle chain wrapped around a skull','Fuel tank covered by an elaborate Japanese dragon composition','Piston surrounded by lightning and fire','Motorcycle headlight glowing like an enormous eye','Handlebars tank and gauges viewed from the riders perspective','Polished chrome V-twin reflecting a tiny highway landscape')
$sets['Motorcycles Surreal Bikes'] = @('Harley-style chopper fighting through enormous Japanese ocean waves','Ducati-style superbike smashing through a stained-glass window','Black motorcycle emerging from an enormous Gothic cathedral doorway','Chopper surrounded by giant peonies lightning and black clouds','Cafe racer transitioning from finished motorcycle into loose sketch and blueprint lines','Superbike transformed into biomechanical muscle bone and machinery','Chrome cruiser riding across the surface of the moon','Vintage motorcycle bursting through an ornate tarot-card composition','Black chopper surrounded by flames like a 1980s heavy-metal album cover','Outrageous show bike combining engraved chrome candy paint gold leaf and jeweled mechanical details')
$sets['Sports Big Moments'] = @('Basketball hoop on a neighborhood street beneath dramatic city lights','Baseball exploding apart with red stitching turning into roses','Boxer sitting exhausted in the corner between rounds','Soccer goal on a childhood field beneath a huge sunset','Surfer dropping into an enormous curling wave','Vintage football helmet surrounded by lightning','Basketball player flying toward the rim with angel wings','Baseball glove holding a bouquet of wildflowers','Hockey goalie mask covered in Gothic ornament','Skateboarder jumping over a city skyline')
$sets['Sports Epic Scenes'] = @('Championship ring floating above the city where it was won','Basketball net hanging from a crescent moon','Baseball stadium beneath a star-filled summer sky','Female boxer surrounded by roses and broken chains','Soccer ball designed like planet Earth','Golfer walking alone toward the eighteenth green at sunset','Hockey player skating through shattered ice','Football player emerging from storm clouds','Tennis player serving beneath enormous stadium lights','Dirt-bike rider jumping over desert mountains')
$sets['Sports Memories and Gear'] = @('Kids first baseball glove with the year stitched into it','Dad and child walking toward a stadium holding hands','Old neighborhood basketball hoop with weeds growing underneath','Pair of worn boxing gloves hanging from a nail','Soccer cleats covered in mud and wildflowers','Baseball breaking through a stained-glass window','Basketball on fire going through the hoop','Hockey puck cracking through frozen lake ice','Football surrounded by American Traditional roses','Tennis racket with flowers growing through the strings')
$sets['Sports Action and Adventure'] = @('Surfer sitting on board watching enormous moon rise','Skateboard with entire city landscape painted underneath it','Snowboarder flying through a forest of giant pine trees','Skier dropping from a mountain into clouds','Motocross rider jumping through a ring of fire','BMX rider flying over the moon','Rock climber hanging from an impossible floating mountain','Marathon runner following a road disappearing into sunrise','Cyclist climbing a mountain road surrounded by clouds','Wakeboarder jumping through a giant wave shaped like a dragon')
$sets['Sports Numbers and Jerseys'] = @('Basketball jersey hanging alone inside an old locker','Baseball jersey number formed from stadium lights','Football number made from cracked concrete','Soccer jersey number surrounded by hometown flowers','Hockey number frozen inside a block of ice','Athletes number formed from flames','Championship year built into a city skyline','Lucky number designed like vintage varsity lettering','Retired jersey hanging from the clouds','Athletes number surrounded by objects from their entire playing career')
$sets['Sports Legends and Warriors'] = @('Basketball court floating in outer space','Astronaut playing golf on the moon','Skeleton playing basketball','Grim Reaper skateboarding down a handrail','Skeleton surfer riding an enormous wave','Knight in full armor playing hockey','Medieval knight dunking a basketball','Samurai standing in a baseball batters box','Viking playing football with a flaming ball','Cowboy riding a motocross bike instead of a horse')
$sets['Sports Animal Athletes'] = @('Octopus boxing with eight gloves','Bear playing ice hockey','Gorilla hanging from a basketball rim','Alligator playing golf in plaid pants','Frog skateboarding down a giant staircase','Raccoon stealing a championship trophy','Pigeon wearing boxing gloves','Shark wearing a football helmet','Golden Retriever catching a baseball in midair','Black cat sitting inside a basketball hoop')
$sets['Sports Surreal Gear'] = @('Baseball turned into the moon above a city','Basketball splitting open with flowers growing from inside','Soccer ball transforming into a globe of city streets','Football containing a mountain landscape','Hockey mask with an entire frozen forest reflected inside it','Tennis ball leaving a trail of wildflowers','Golf ball sitting on top of planet Earth like a tee','Boxing glove breaking through a marble statue','Skateboard deck becoming a stained-glass cathedral window','Surfboard covered in Japanese waves and koi')
$sets['Sports Home Field'] = @('Stadium rising from inside an anatomical heart','Childhood ball field inside a Polaroid-style frame','Neighborhood court with apartment buildings surrounding it','Empty stadium seat with a ticket and date from a legendary game','Stadium lights emerging from a city map','Hometown skyline wrapped around a basketball','Baseball stitching turning into the street grid of a hometown','Football field disappearing into the horizon','Hockey rink surrounded by hometown architecture','Soccer stadium inside a snow globe')
$sets['Sports Funny and Crazy'] = @('Championship trophy being abducted by a UFO','Skeleton fan screaming from the front row','Grim Reaper holding a giant foam finger','Angel and devil arguing over opposing teams','Baseball player batting away a meteor','Basketball player dunking through Saturns rings','Surfer riding a wave through downtown skyscrapers','Golfer hitting a ball directly into outer space','Boxer fighting their own shadow','Athlete walking from a childhood playground into a giant professional stadium')
$sets['Hometown Lettering'] = @('NYC in huge Gothic lettering with Manhattan rising through the letters','LA script beneath palm trees and a glowing sunset','212 built from New York skyscrapers','310 surrounded by ocean waves and California palms','415 disappearing into Golden Gate fog','BROOKLYN lettering built from brownstone buildings','CHICAGO lettering beneath an elevated train','305 surrounded by Miami palms and Art Deco neon','ATL emerging through peaches skyline and flames','Hometown ZIP code designed like an old tattoo flash emblem')
$sets['Hometown Landmarks'] = @('Statue of Liberty wearing sunglasses','Golden Gate Bridge disappearing into giant clouds','Los Angeles freeway interchange transformed into ornamental linework','Chicago L train winding around skyscrapers','Miami Art Deco hotel surrounded by flamingos','Seattle Space Needle rising through storm clouds','New Orleans balcony at night surrounded by music notes and flowers','Boston brownstones beneath falling autumn leaves','Detroit muscle car beneath old industrial architecture','Las Vegas neon signs stacked into a giant glowing tower')
$sets['Hometown Street Life'] = @('Brooklyn brownstone stoop with sneakers sitting on the steps','New York bodega glowing at 2 a.m.','LA taco truck beneath palm trees','San Francisco cable car climbing an absurdly steep hill','Chicago neighborhood corner during winter','Miami lifeguard tower beneath giant tropical clouds','New Orleans streetcar surrounded by magnolias','Philadelphia row houses beneath dramatic evening sky','Seattle coffee cup with city reflected in the steam','Honolulu surfboard overlooking Diamond Head')
$sets['Hometown Area Codes'] = @('213 designed like chrome lowrider lettering','718 surrounded by Brooklyn street imagery','312 incorporated into Chicago architecture','404 made from Atlanta highway signs','702 built from Las Vegas neon tubing','617 surrounded by Boston brick and ivy','504 wrapped in New Orleans wrought iron','808 surrounded by waves and hibiscus','313 designed from Detroit automotive chrome','Persons ZIP code printed like an old postage stamp from home')
$sets['Hometown Childhood Places'] = @('Childhood street sign surrounded by flowers','Exact intersection where somebody grew up','Highway exit sign leading home','Childhood house beneath a huge moon','Apartment building where the family grew up','Local corner store turned into beautiful tattoo flash','Neighborhood basketball court beneath city lights','Hometown water tower surrounded by wildflowers','Local diner glowing alone at night','Streetlight and front stoop from childhood')
$sets['Hometown Skylines Inside Things'] = @('Manhattan skyline contained inside an anatomical heart','Los Angeles skyline reflected inside sunglasses','San Francisco inside a snow globe filled with fog','Chicago skyline growing from a deep-dish pizza','Miami skyline inside a flamingo silhouette','Seattle skyline rising from a coffee cup','New Orleans street scene inside a trumpet','Nashville skyline growing from a guitar','Detroit skyline reflected in a chrome wheel','Honolulu landscape inside a breaking wave')
$sets['Hometown Local Icons'] = @('New York subway entrance rendered as American Traditional flash','Los Angeles freeway sign surrounded by roses','San Francisco Victorian house inside an ornate frame','Chicago hot dog rendered like sacred religious iconography','Philadelphia cheesesteak presented like royal treasure','Miami cafecito cup surrounded by tropical ornament','New Orleans crawfish wearing a crown','Texas cowboy boot containing an entire hometown landscape','Seattle umbrella raining tiny Space Needles','Las Vegas slot machine filled with hometown landmarks')
$sets['Hometown Maps and Roots'] = @('City street map becoming human veins','Hometown map folded into an origami heart','City skyline growing from someones roots','Coordinates surrounded by the flowers native to home','Street grid forming a fingerprint','City map forming the shape of a heart','Hometown landscape inside the outline of the state','Road from childhood home leading into city skyline','City streets flowing out of an old Polaroid','Hometown landmarks stacked like a surreal tower')
$sets['Hometown Inside Jokes'] = @('NYC pigeon wearing a tiny gold chain','LA palm tree wearing sunglasses','San Francisco fog portrayed as a giant monster swallowing the bridge','Chicago wind literally blowing buildings sideways','Miami flamingo driving a convertible','New Orleans alligator playing trumpet','Boston lobster riding the subway','Seattle Sasquatch drinking coffee beneath the Space Needle','Las Vegas skeleton hitting a jackpot','Philadelphia cheesesteak running up famous museum steps')
$sets['Hometown Crazy Ideas'] = @('Statue of Liberty skateboarding through Manhattan','Golden Gate Bridge being abducted by a UFO','Hollywood sign surrounded by dinosaurs','Empire State Building turned into a giant rocket','Chicago train circling Saturn','Miami beach scene inside a giant martini glass','New Orleans jazz band made entirely of skeletons','Persons area code floating above their childhood street like a giant neon sign','Childhood house with hometown skyline growing impossibly behind it','Entire life journey from childhood street to hometown skyline flowing through one continuous tattoo composition')
$bad = 0
foreach ($k in $sets.Keys) { $h = @($tt.specific.$k | ? { $_ }).Count; if ($h -ne 10) { "  REPAIRED " + $k + ": had " + $h; RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) | Out-Null; $bad++; Start-Sleep -Seconds 3 } }
if ($bad) { "== " + $bad + " sets were short and are re-saved - run this block once more to confirm before drawing ==" } else {
"== all 40 sets have their 10 designs - starting Cars and Motorcycles in two new windows =="
Start-Process powershell -WorkingDirectory (Get-Location) -ArgumentList '-NoExit','-Command','Get-Content .\draw-cars.ps1 -Raw | Invoke-Expression'
Start-Process powershell -WorkingDirectory (Get-Location) -ArgumentList '-NoExit','-Command','Get-Content .\draw-moto.ps1 -Raw | Invoke-Expression'
}
}
