cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Medieval Marginalia")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Rabbit knight with a sword'] = 'The tattoo: rabbit knight with a sword. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Rabbit riding a snail into battle'] = 'The tattoo: rabbit riding a snail into battle. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Rabbit hunting a hunter'] = 'The tattoo: rabbit hunting a hunter. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Rabbit with a longbow'] = 'The tattoo: rabbit with a longbow. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Rabbit defeating a dragon'] = 'The tattoo: rabbit defeating a dragon. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Rabbit on horseback with a lance'] = 'The tattoo: rabbit on horseback with a lance. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Rabbit pope with a staff'] = 'The tattoo: rabbit pope with a staff. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Rabbit playing bagpipes'] = 'The tattoo: rabbit playing bagpipes. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Rabbit storming a castle'] = 'The tattoo: rabbit storming a castle. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Rabbit and fox duel'] = 'The tattoo: rabbit and fox duel. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Knight fighting a giant snail'] = 'The tattoo: knight fighting a giant snail. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Knight kneeling to a snail'] = 'The tattoo: knight kneeling to a snail. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Snail with a castle shell'] = 'The tattoo: snail with a castle shell. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Snail with a lance'] = 'The tattoo: snail with a lance. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Two snails jousting'] = 'The tattoo: two snails jousting. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Snail with a crown'] = 'The tattoo: snail with a crown. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Archer aiming at a snail'] = 'The tattoo: archer aiming at a snail. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Snail guarding a gate'] = 'The tattoo: snail guarding a gate. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Snail army on the march'] = 'The tattoo: snail army on the march. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Knight fleeing a snail'] = 'The tattoo: knight fleeing a snail. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Cat playing a lute'] = 'The tattoo: cat playing a lute. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cat in a monk robe'] = 'The tattoo: cat in a monk robe. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Cat chasing mice with a sword'] = 'The tattoo: cat chasing mice with a sword. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Cat on a throne'] = 'The tattoo: cat on a throne. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Dog in armor'] = 'The tattoo: dog in armor. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Cat licking its paw in the margin'] = 'The tattoo: cat licking its paw in the margin. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Cat and mouse knights'] = 'The tattoo: cat and mouse knights. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Hound chasing a hare'] = 'The tattoo: hound chasing a hare. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Cat with a book'] = 'The tattoo: cat with a book. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Dog playing a trumpet'] = 'The tattoo: dog playing a trumpet. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Human head on snail legs'] = 'The tattoo: human head on snail legs. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Bird with a human face'] = 'The tattoo: bird with a human face. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Knight with a fish tail'] = 'The tattoo: knight with a fish tail. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Monk with a dragon body'] = 'The tattoo: monk with a dragon body. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Lion with a human head'] = 'The tattoo: lion with a human head. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Musician with bird legs'] = 'The tattoo: musician with bird legs. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Fish with arms'] = 'The tattoo: fish with arms. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Owl with a bishop hat'] = 'The tattoo: owl with a bishop hat. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Grotesque blowing a horn'] = 'The tattoo: grotesque blowing a horn. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Two-headed beast'] = 'The tattoo: two-headed beast. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Monk sleeping on a book'] = 'The tattoo: monk sleeping on a book. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Nun climbing a tree'] = 'The tattoo: nun climbing a tree. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Monk fighting a demon'] = 'The tattoo: monk fighting a demon. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Monk brewing in a cauldron'] = 'The tattoo: monk brewing in a cauldron. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Monk with a lantern'] = 'The tattoo: monk with a lantern. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Monk playing a harp'] = 'The tattoo: monk playing a harp. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Nun with a cat'] = 'The tattoo: nun with a cat. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Monk riding a goose'] = 'The tattoo: monk riding a goose. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Monk reading upside down'] = 'The tattoo: monk reading upside down. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Monk chasing a pig'] = 'The tattoo: monk chasing a pig. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Bear playing a harp'] = 'The tattoo: bear playing a harp. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Monkey with a drum'] = 'The tattoo: monkey with a drum. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Goat with a flute'] = 'The tattoo: goat with a flute. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Fox playing a fiddle'] = 'The tattoo: fox playing a fiddle. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Donkey playing an organ'] = 'The tattoo: donkey playing an organ. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Lion with a horn'] = 'The tattoo: lion with a horn. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Bird with bagpipes'] = 'The tattoo: bird with bagpipes. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Dancing bear'] = 'The tattoo: dancing bear. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Frog with a lute'] = 'The tattoo: frog with a lute. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pig playing a horn'] = 'The tattoo: pig playing a horn. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Dragon in the margin'] = 'The tattoo: dragon in the margin. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Unicorn in a vine'] = 'The tattoo: unicorn in a vine. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Sea monster swallowing a ship'] = 'The tattoo: sea monster swallowing a ship. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Basilisk in the corner'] = 'The tattoo: basilisk in the corner. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Dragon biting its own tail'] = 'The tattoo: dragon biting its own tail. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Griffin with a scroll border'] = 'The tattoo: griffin with a scroll border. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Demon with bat wings'] = 'The tattoo: demon with bat wings. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Mermaid with a mirror'] = 'The tattoo: mermaid with a mirror. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Manticore'] = 'The tattoo: manticore. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Wyvern on a letter'] = 'The tattoo: wyvern on a letter. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Woman spinning thread'] = 'The tattoo: woman spinning thread. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Farmer with a plough'] = 'The tattoo: farmer with a plough. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Man in a barrel'] = 'The tattoo: man in a barrel. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Baker with bread'] = 'The tattoo: baker with bread. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Juggler'] = 'The tattoo: juggler. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Man riding backwards on a goat'] = 'The tattoo: man riding backwards on a goat. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Women dancing in a ring'] = 'The tattoo: women dancing in a ring. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Fisherman with a net'] = 'The tattoo: fisherman with a net. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Hunter with a falcon'] = 'The tattoo: hunter with a falcon. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Man shooting an arrow at a bird'] = 'The tattoo: man shooting an arrow at a bird. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny snail knight'] = 'The tattoo: tiny snail knight. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small rabbit with a sword'] = 'The tattoo: small rabbit with a sword. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Little grotesque face'] = 'The tattoo: little grotesque face. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny dragon in a vine'] = 'The tattoo: tiny dragon in a vine. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Small cat with a lute'] = 'The tattoo: small cat with a lute. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Tiny monk'] = 'The tattoo: tiny monk. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Small owl bishop'] = 'The tattoo: small owl bishop. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Tiny fish with legs'] = 'The tattoo: tiny fish with legs. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Small gold leaf vine'] = 'The tattoo: small gold leaf vine. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny unicorn'] = 'The tattoo: tiny unicorn. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Illuminated border back piece'] = 'The tattoo: illuminated border back piece. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Rabbit war sleeve'] = 'The tattoo: rabbit war sleeve. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Snail siege chest piece'] = 'The tattoo: snail siege chest piece. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Grotesque parade thigh piece'] = 'The tattoo: grotesque parade thigh piece. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Monk and demon forearm piece'] = 'The tattoo: monk and demon forearm piece. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Vine border spine piece'] = 'The tattoo: vine border spine piece. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Musician animals half sleeve'] = 'The tattoo: musician animals half sleeve. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Dragon in the margins calf piece'] = 'The tattoo: dragon in the margins calf piece. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Gold leaf vine shoulder piece'] = 'The tattoo: gold leaf vine shoulder piece. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Manuscript page leg sleeve'] = 'The tattoo: manuscript page leg sleeve. Medieval marginalia tattoo art, whimsical strange drawings from the margins of an illuminated manuscript, fine brown-black ink linework with flat muted colour, touches of gold leaf, vines and border flourishes, absurd and charming, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Marginalia Style Killer Rabbits'] = @('Rabbit knight with a sword','Rabbit riding a snail into battle','Rabbit hunting a hunter','Rabbit with a longbow','Rabbit defeating a dragon','Rabbit on horseback with a lance','Rabbit pope with a staff','Rabbit playing bagpipes','Rabbit storming a castle','Rabbit and fox duel')
$sets['Marginalia Style Snail Battles'] = @('Knight fighting a giant snail','Knight kneeling to a snail','Snail with a castle shell','Snail with a lance','Two snails jousting','Snail with a crown','Archer aiming at a snail','Snail guarding a gate','Snail army on the march','Knight fleeing a snail')
$sets['Marginalia Style Cats and Dogs'] = @('Cat playing a lute','Cat in a monk robe','Cat chasing mice with a sword','Cat on a throne','Dog in armor','Cat licking its paw in the margin','Cat and mouse knights','Hound chasing a hare','Cat with a book','Dog playing a trumpet')
$sets['Marginalia Style Hybrid Grotesques'] = @('Human head on snail legs','Bird with a human face','Knight with a fish tail','Monk with a dragon body','Lion with a human head','Musician with bird legs','Fish with arms','Owl with a bishop hat','Grotesque blowing a horn','Two-headed beast')
$sets['Marginalia Style Monks and Nuns'] = @('Monk sleeping on a book','Nun climbing a tree','Monk fighting a demon','Monk brewing in a cauldron','Monk with a lantern','Monk playing a harp','Nun with a cat','Monk riding a goose','Monk reading upside down','Monk chasing a pig')
$sets['Marginalia Style Musicians'] = @('Bear playing a harp','Monkey with a drum','Goat with a flute','Fox playing a fiddle','Donkey playing an organ','Lion with a horn','Bird with bagpipes','Dancing bear','Frog with a lute','Pig playing a horn')
$sets['Marginalia Style Monsters'] = @('Dragon in the margin','Unicorn in a vine','Sea monster swallowing a ship','Basilisk in the corner','Dragon biting its own tail','Griffin with a scroll border','Demon with bat wings','Mermaid with a mirror','Manticore','Wyvern on a letter')
$sets['Marginalia Style Daily Life'] = @('Woman spinning thread','Farmer with a plough','Man in a barrel','Baker with bread','Juggler','Man riding backwards on a goat','Women dancing in a ring','Fisherman with a net','Hunter with a falcon','Man shooting an arrow at a bird')
$sets['Marginalia Style Small'] = @('Tiny snail knight','Small rabbit with a sword','Little grotesque face','Tiny dragon in a vine','Small cat with a lute','Tiny monk','Small owl bishop','Tiny fish with legs','Small gold leaf vine','Tiny unicorn')
$sets['Marginalia Style Large Pieces'] = @('Illuminated border back piece','Rabbit war sleeve','Snail siege chest piece','Grotesque parade thigh piece','Monk and demon forearm piece','Vine border spine piece','Musician animals half sleeve','Dragon in the margins calf piece','Gold leaf vine shoulder piece','Manuscript page leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Marginalia Style" } else { $n } }
"== Medieval Marginalia before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:medieval-marginalia" --remote 2>$null | Out-Null
RUN "CATEGORY Medieval Marginalia :: Marginalia Style Killer Rabbits, Marginalia Style Snail Battles, Marginalia Style Cats and Dogs, Marginalia Style Hybrid Grotesques, Marginalia Style Monks and Nuns, Marginalia Style Musicians, Marginalia Style Monsters, Marginalia Style Daily Life, Marginalia Style Small, Marginalia Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Marginalia Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Marginalia Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Rabbit riding a snail into battle"))
}
}
