cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Medieval")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Knight on horseback with a lance'] = 'The tattoo: knight on horseback with a lance. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Kneeling knight with a sword'] = 'The tattoo: kneeling knight with a sword. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Knight fighting a dragon'] = 'The tattoo: knight fighting a dragon. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Knight in prayer before battle'] = 'The tattoo: knight in prayer before battle. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Knight with a shield and banner'] = 'The tattoo: knight with a shield and banner. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Fallen knight under a tree'] = 'The tattoo: fallen knight under a tree. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Knight holding a rose'] = 'The tattoo: knight holding a rose. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Two knights jousting'] = 'The tattoo: two knights jousting. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Knight with a hawk on his arm'] = 'The tattoo: knight with a hawk on his arm. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Lady knight in armor'] = 'The tattoo: lady knight in armor. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Great helm with a plume'] = 'The tattoo: great helm with a plume. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Visored helmet with a crown'] = 'The tattoo: visored helmet with a crown. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Gauntlet holding a sword'] = 'The tattoo: gauntlet holding a sword. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Breastplate with a lion engraving'] = 'The tattoo: breastplate with a lion engraving. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Horned helmet'] = 'The tattoo: horned helmet. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Chainmail hood'] = 'The tattoo: chainmail hood. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Armored skull'] = 'The tattoo: armored skull. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Helmet with a dragon crest'] = 'The tattoo: helmet with a dragon crest. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Knight helmet with a laurel wreath'] = 'The tattoo: knight helmet with a laurel wreath. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Shield and crossed swords'] = 'The tattoo: shield and crossed swords. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Longsword with a jeweled hilt'] = 'The tattoo: longsword with a jeweled hilt. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Sword in a stone'] = 'The tattoo: sword in a stone. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Sword wrapped in thorns'] = 'The tattoo: sword wrapped in thorns. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Battle axe with ornament'] = 'The tattoo: battle axe with ornament. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Mace and shield'] = 'The tattoo: mace and shield. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Dagger with a rose'] = 'The tattoo: dagger with a rose. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Broken sword'] = 'The tattoo: broken sword. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Sword through a crown'] = 'The tattoo: sword through a crown. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Bow and quiver of arrows'] = 'The tattoo: bow and quiver of arrows. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Flail and helmet'] = 'The tattoo: flail and helmet. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Wyvern coiled around a tower'] = 'The tattoo: wyvern coiled around a tower. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Griffin rampant'] = 'The tattoo: griffin rampant. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Unicorn in a garden'] = 'The tattoo: unicorn in a garden. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Basilisk with a crown'] = 'The tattoo: basilisk with a crown. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Dragon guarding treasure'] = 'The tattoo: dragon guarding treasure. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Sea serpent attacking a ship'] = 'The tattoo: sea serpent attacking a ship. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Two-headed eagle'] = 'The tattoo: two-headed eagle. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Lion rampant'] = 'The tattoo: lion rampant. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Stag with a cross between its antlers'] = 'The tattoo: stag with a cross between its antlers. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Phoenix rising from a cauldron'] = 'The tattoo: phoenix rising from a cauldron. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Castle on a hill'] = 'The tattoo: castle on a hill. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Tower with a dragon'] = 'The tattoo: tower with a dragon. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Castle gate with a drawbridge'] = 'The tattoo: castle gate with a drawbridge. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Ruined castle under a moon'] = 'The tattoo: ruined castle under a moon. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Castle in the clouds'] = 'The tattoo: castle in the clouds. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Watchtower by the sea'] = 'The tattoo: watchtower by the sea. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Castle with banners'] = 'The tattoo: castle with banners. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Fortress in the mountains'] = 'The tattoo: fortress in the mountains. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Castle reflected in a lake'] = 'The tattoo: castle reflected in a lake. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Keep surrounded by roses'] = 'The tattoo: keep surrounded by roses. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Shield with a lion and fleur-de-lis'] = 'The tattoo: shield with a lion and fleur-de-lis. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Crest with two griffins'] = 'The tattoo: crest with two griffins. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Shield with a wolf'] = 'The tattoo: shield with a wolf. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Heraldic eagle'] = 'The tattoo: heraldic eagle. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Coat of arms with a dragon'] = 'The tattoo: coat of arms with a dragon. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Shield with three stars'] = 'The tattoo: shield with three stars. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Crest with a stag'] = 'The tattoo: crest with a stag. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Shield with a tower'] = 'The tattoo: shield with a tower. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Heraldic bear'] = 'The tattoo: heraldic bear. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Crest with a crown and swords'] = 'The tattoo: crest with a crown and swords. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['King on a throne'] = 'The tattoo: king on a throne. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Queen with a scepter'] = 'The tattoo: queen with a scepter. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Crown on a velvet pillow'] = 'The tattoo: crown on a velvet pillow. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Jester with bells'] = 'The tattoo: jester with bells. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Princess in a tower window'] = 'The tattoo: princess in a tower window. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['King and queen chess pieces'] = 'The tattoo: king and queen chess pieces. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Royal falcon'] = 'The tattoo: royal falcon. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Crown with roses'] = 'The tattoo: crown with roses. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Orb and scepter'] = 'The tattoo: orb and scepter. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Queen in a veil'] = 'The tattoo: queen in a veil. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Archangel with a flaming sword'] = 'The tattoo: archangel with a flaming sword. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Angel blowing a trumpet'] = 'The tattoo: angel blowing a trumpet. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Saint with a halo and lamb'] = 'The tattoo: saint with a halo and lamb. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Angel slaying a dragon'] = 'The tattoo: angel slaying a dragon. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Praying monk'] = 'The tattoo: praying monk. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Guardian angel with a shield'] = 'The tattoo: guardian angel with a shield. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pilgrim with a staff'] = 'The tattoo: pilgrim with a staff. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Winged lion'] = 'The tattoo: winged lion. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Angel with a lantern'] = 'The tattoo: angel with a lantern. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Chalice with light'] = 'The tattoo: chalice with light. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Skeleton knight'] = 'The tattoo: skeleton knight. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Dance of death skeletons'] = 'The tattoo: dance of death skeletons. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Skull with a crown and roses'] = 'The tattoo: skull with a crown and roses. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Death on a pale horse'] = 'The tattoo: death on a pale horse. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Hourglass with wings'] = 'The tattoo: hourglass with wings. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Skeleton king on a throne'] = 'The tattoo: skeleton king on a throne. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Reaper with a scythe in a field'] = 'The tattoo: reaper with a scythe in a field. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Skull and candle'] = 'The tattoo: skull and candle. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Plague doctor'] = 'The tattoo: plague doctor. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Skeleton playing a lute'] = 'The tattoo: skeleton playing a lute. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Knight and dragon back piece'] = 'The tattoo: knight and dragon back piece. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Castle siege sleeve'] = 'The tattoo: castle siege sleeve. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Archangel chest piece'] = 'The tattoo: archangel chest piece. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Heraldic beasts thigh piece'] = 'The tattoo: heraldic beasts thigh piece. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Knight on horseback forearm piece'] = 'The tattoo: knight on horseback forearm piece. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Sword spine piece'] = 'The tattoo: sword spine piece. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Dance of death half sleeve'] = 'The tattoo: dance of death half sleeve. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Dragon and castle calf piece'] = 'The tattoo: dragon and castle calf piece. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Armored shoulder piece'] = 'The tattoo: armored shoulder piece. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Tapestry battle leg sleeve'] = 'The tattoo: tapestry battle leg sleeve. Medieval tattoo art inspired by medieval tapestries, heraldry and old engravings, bold black linework with muted earthy red, ochre, deep blue and gold accents, flat ornate composition, designed like work from a top medieval-style tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Medieval Style Knights'] = @('Knight on horseback with a lance','Kneeling knight with a sword','Knight fighting a dragon','Knight in prayer before battle','Knight with a shield and banner','Fallen knight under a tree','Knight holding a rose','Two knights jousting','Knight with a hawk on his arm','Lady knight in armor')
$sets['Medieval Style Armor and Helmets'] = @('Great helm with a plume','Visored helmet with a crown','Gauntlet holding a sword','Breastplate with a lion engraving','Horned helmet','Chainmail hood','Armored skull','Helmet with a dragon crest','Knight helmet with a laurel wreath','Shield and crossed swords')
$sets['Medieval Style Swords and Weapons'] = @('Longsword with a jeweled hilt','Sword in a stone','Sword wrapped in thorns','Battle axe with ornament','Mace and shield','Dagger with a rose','Broken sword','Sword through a crown','Bow and quiver of arrows','Flail and helmet')
$sets['Medieval Style Dragons and Beasts'] = @('Wyvern coiled around a tower','Griffin rampant','Unicorn in a garden','Basilisk with a crown','Dragon guarding treasure','Sea serpent attacking a ship','Two-headed eagle','Lion rampant','Stag with a cross between its antlers','Phoenix rising from a cauldron')
$sets['Medieval Style Castles'] = @('Castle on a hill','Tower with a dragon','Castle gate with a drawbridge','Ruined castle under a moon','Castle in the clouds','Watchtower by the sea','Castle with banners','Fortress in the mountains','Castle reflected in a lake','Keep surrounded by roses')
$sets['Medieval Style Heraldry'] = @('Shield with a lion and fleur-de-lis','Crest with two griffins','Shield with a wolf','Heraldic eagle','Coat of arms with a dragon','Shield with three stars','Crest with a stag','Shield with a tower','Heraldic bear','Crest with a crown and swords')
$sets['Medieval Style Royalty'] = @('King on a throne','Queen with a scepter','Crown on a velvet pillow','Jester with bells','Princess in a tower window','King and queen chess pieces','Royal falcon','Crown with roses','Orb and scepter','Queen in a veil')
$sets['Medieval Style Saints and Angels'] = @('Archangel with a flaming sword','Angel blowing a trumpet','Saint with a halo and lamb','Angel slaying a dragon','Praying monk','Guardian angel with a shield','Pilgrim with a staff','Winged lion','Angel with a lantern','Chalice with light')
$sets['Medieval Style Memento Mori'] = @('Skeleton knight','Dance of death skeletons','Skull with a crown and roses','Death on a pale horse','Hourglass with wings','Skeleton king on a throne','Reaper with a scythe in a field','Skull and candle','Plague doctor','Skeleton playing a lute')
$sets['Medieval Style Large Pieces'] = @('Knight and dragon back piece','Castle siege sleeve','Archangel chest piece','Heraldic beasts thigh piece','Knight on horseback forearm piece','Sword spine piece','Dance of death half sleeve','Dragon and castle calf piece','Armored shoulder piece','Tapestry battle leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Medieval Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Medieval Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Medieval Style$','') -ne 'Knight fighting a dragon' })
}
"== drawing " + $all.Count + " Medieval split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK Medieval"
RUN "SHEET Medieval"
}
