cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Meme Tattoos")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Meme Tattoos before (empty = new category) =="
"  " + (@($tt.subjects."Meme Tattoos") -join ", ")
$kinds = 'Meme Unhinged Animals','Meme Cats Have Taken Over','Meme Food Has Problems','Meme Medieval Internet','Meme Skeleton Life','Meme Tiny Disasters','Meme Internet Archaeology','Meme Absolutely Wrong Mashups','Meme Existential Nonsense','Meme What Is That'
$kh = $kinds | ? { $tk.ContainsKey((& $slug $_)) }
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
$sets = [ordered]@{}
$sets['Meme Unhinged Animals'] = @('Possum knight with tiny sword','Raccoon stealing a diamond','Frog riding a snail into battle','Pigeon wearing a business suit','Rat king eating pizza','Goose carrying a switchblade','Chihuahua dressed as an angel','Capybara in cowboy hat','Squirrel dragging enormous sword','Goldfish wearing ski goggles')
$sets['Meme Cats Have Taken Over'] = @('Cat screaming into microphone','Cat working behind convenience-store counter','Cowboy cat riding a Roomba','Cat staring at burning toaster','Cat wearing medieval armor','Cat abducted by tiny UFO','Cat smoking at computer','Cat sitting inside ramen bowl','Cat as exhausted office worker','Cat summoning a demon')
$sets['Meme Food Has Problems'] = @('Hot dog riding a horse','Cigarette-smoking croissant','Pizza slice crying in bathtub','Banana dressed as cowboy','Angry chicken nugget with sword','Taco being abducted by UFO','Donut with existential crisis','Shrimp drinking martini','Egg running away from frying pan','Sandwich attending its own funeral')
$sets['Meme Medieval Internet'] = @('Knight using laptop','Knight ordering at drive-through','Medieval monk taking selfie','Knight fighting giant chicken','Wizard working tech support','Skeleton knight riding skateboard','Medieval executioner walking tiny dog','Knight protecting last slice of pizza','Plague doctor at vending machine','King sitting on plastic lawn chair')
$sets['Meme Skeleton Life'] = @('Skeleton waiting for text reply','Skeleton doing laundry','Skeleton doomscrolling in bed','Skeleton drinking gas-station coffee','Skeleton mowing lawn','Skeleton at office cubicle','Skeleton riding shopping cart','Skeleton watering dead plant','Skeleton sitting at DMV','Skeleton dancing alone under disco ball')
$sets['Meme Tiny Disasters'] = @('Frog whose house is on fire','Little devil stuck in traffic','Crying cloud smoking cigarette','Tiny ghost missing the bus','Alien whose UFO has flat tire','Angel dropping halo down drain','Grim Reaper stepping on Lego','Sad moon holding empty wallet','Devil doing taxes','Ghost accidentally haunting wrong house')
$sets['Meme Internet Archaeology'] = @('Pixelated broken heart','Cursor chasing butterfly','Error window with tiny demon inside','Computer folder leaking flowers','Old desktop computer growing mushrooms','Loading bar stuck at 99 percent','Floppy disk with angel wings','Pixel skeleton crawling from monitor','Computer mouse caught in mousetrap','Dial-up modem summoning portal')
$sets['Meme Absolutely Wrong Mashups'] = @('Shark wearing cowboy boots','Crocodile driving tiny convertible','Frog bodybuilder lifting strawberry','Moth operating tattoo machine','Octopus playing eight keyboards','Pigeon riding shark','Snail with monster-truck shell','Goldfish driving getaway car','Chicken riding motorcycle through flames','Lobster dressed as Victorian gentleman')
$sets['Meme Existential Nonsense'] = @('Frog staring into black void','Smiley face slowly melting','Birthday cake attending funeral','Tombstone for Monday morning','Happy little sun having nervous breakdown','Balloon carrying person away','Tiny house falling through space','Man calmly drinking coffee inside tornado','Flower growing from dead phone','Door standing alone in middle of ocean')
$sets['Meme What Is That'] = @('Two-headed cowboy frog dueling itself','Biblically accurate fuzzy toy creature','Renaissance cherub stealing french fries','Giant eyeball walking tiny dog','Skeleton mermaid smoking underwater','Angel and devil sharing cigarette','UFO abducting another UFO','Grim Reaper riding inflatable flamingo','Three raccoons inside trench coat','Horse standing on balcony looking suspicious')
$renamed = @()
foreach ($k in @($sets.Keys)) { $sets[$k] = @($sets[$k] | % { $n = $_; if ($tk.ContainsKey((& $slug $n))) { $r = "$n in Meme Style"; $renamed += "  RENAMED: $n  ->  $r  (the first was under " + $tk[(& $slug $n)] + ")"; $r } else { $n } }) }
if ($renamed) { $renamed } else { "  no clashes" }
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:meme-tattoos" ", contemporary meme tattoo and internet-humor tattoo artwork, weird, absurd, unexpected, irreverent and highly shareable, drawing from internet culture, post-ironic humor, shitposting, nostalgic web culture and deliberately ridiculous tattoo ideas; freely vary between ignorant-style doodle, crude hand-drawn linework, bold tattoo flash, clean illustrative tattooing, retro cartoon, pixel-art influence and unexpectedly beautiful detailed rendering depending on the subject; embrace strange proportions, visual jokes and deadpan absurdity; color may range naturally from simple black ink to limited flash colors to deliberately loud color when appropriate; make each design feel like something a real person might get because it is funny, strange or strangely brilliant, not generic clip art; tattoo artwork alone, never worn on skin or a body, isolated on a clean plain background, no watermark" --remote
RUN "CATEGORY Meme Tattoos :: Meme Unhinged Animals, Meme Cats Have Taken Over, Meme Food Has Problems, Meme Medieval Internet, Meme Skeleton Life, Meme Tiny Disasters, Meme Internet Archaeology, Meme Absolutely Wrong Mashups, Meme Existential Nonsense, Meme What Is That"
foreach ($k in $sets.Keys) { RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) }
RUN "FACE Grim Reaper riding inflatable flamingo"
}
}$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Animals & Pets")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Animals & Pets sets today - they all stay, the 10 pet sets are added =="
"  " + (@($tt.subjects."Animals & Pets") -join ", ")
$kinds = 'Pets Dressed Up','Pets on Adventures','Pets Up to Mischief','Magic Pets','Dreamy Pets','Glam Pets','Retro Flash Pets','Edgy and Elegant Pets','Psychedelic and Floral Pets','Pets in Everyday Life'
$kh = $kinds | ? { $tk.ContainsKey((& $slug $_)) }
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
$sets = [ordered]@{}
$sets['Pets Dressed Up'] = @('Sphynx cat dressed as an Egyptian pharaoh','Maine Coon dressed as a giant Viking','Chihuahua as a furious little medieval king','Persian cat as an overdressed Victorian aristocrat','Tuxedo cat working as a tiny maitre d','Doberman in black leather jacket','Pug as exhausted office worker','Shih Tzu as glamorous 1980s rock star','German Shepherd dressed as medieval knight','Greyhound dressed like an Art Deco socialite')
$sets['Pets on Adventures'] = @('Corgi astronaut floating through space with tennis balls','English Bulldog driving a tiny convertible','Golden Retriever surfing in sunglasses','French Bulldog riding a Vespa','Great Dane squeezed onto a tiny skateboard','Orange tabby cowboy riding a Roomba','Jack Russell riding a motorcycle','Husky riding a rocket through space','Corgi flying an old-fashioned airplane','Golden Retriever and tuxedo cat riding a motorcycle together')
$sets['Pets Up to Mischief'] = @('Dachshund stretched into a limousine','Orange tabby stealing an entire roast chicken','Siamese cat drinking a martini','Saint Bernard bartender with barrel collar','Boxer playing poker with other dogs','Calico cat sleeping inside a pizza box','Labrador stealing a giant slice of pizza','Golden Retriever carrying an absurdly enormous stick','Dachshund dressed like a hot dog at a barbecue','Orange tabby chef making ramen')
$sets['Magic Pets'] = @('Black cat magician pulling a mouse from a hat','Black cat riding a broom through stars','Maine Coon wizard surrounded by mushrooms','Tuxedo cat in top hat performing stage magic','Black cat sitting inside a crystal ball','Sphynx cat surrounded by planets and occult stars','Maine Coon as majestic tarot-card character','Black cat with tiny devil horns sitting in flames','Orange tabby as mischievous little vampire','Orange tabby being abducted by a UFO')
$sets['Dreamy Pets'] = @('Dalmatian with spots turning into stars and planets','Scottish Fold sitting inside a teacup','Ragdoll cat floating through clouds with balloons','Ragdoll cat sleeping on a crescent moon','Samoyed floating inside a fluffy cloud','Maine Coon with tiny angel wings','Border Collie herding tiny clouds','Chihuahua as tiny angel with ridiculously large wings','Corgi and Maine Coon having tea on the moon','Husky howling beneath a neon-colored moon')
$sets['Glam Pets'] = @('Sphynx cat covered in ornamental jewelry','Pit Bull wearing a jeweled crown','Persian cat reclining on velvet cushion with pearls','Siamese cat tangled in a strand of pearls','Persian cat inside ornate jeweled picture frame','Siamese cat perched inside a crescent moon chandelier','Cavalier King Charles Spaniel inside a jeweled heart locket','Sphynx cat inside jeweled scarab composition','British Shorthair in bow tie drinking espresso','Poodle as 1960s fashion icon')
$sets['Retro Flash Pets'] = @('Poodle beneath a tiny disco ball','Chihuahua wearing enormous cowboy hat','French Bulldog wearing Hawaiian shirt with cocktail','Dalmatian as retro roller-skating disco dog','Black cat as embroidered patch with flames','German Shepherd emerging through tattoo-flash roses','Saint Bernard mountain-rescue scene turned into vintage tattoo flash','Golden Retriever as embroidered souvenir patch','French Bulldog as vintage matchbox illustration','Black cat with hearts and flames and dice and lucky symbols')
$sets['Edgy and Elegant Pets'] = @('Doberman surrounded by black roses and silver chains','Sphynx cat as tattooed punk rocker','Maine Coon inside a Gothic stained-glass window','English Bulldog as tattooed biker','Doberman inside Gothic cathedral arch','Persian cat as vintage perfume-label illustration','Siamese cat inside Art Nouveau floral window','Rottweiler wearing flower crown','Rottweiler with butterfly sitting on nose','Corgi dressed as royal guard')
$sets['Psychedelic and Floral Pets'] = @('Bengal cat disappearing into psychedelic jungle patterns','Australian Shepherd surrounded by wildflowers and butterflies','Bengal cat stalking through oversized tropical flowers','Calico cat surrounded by cherries and bows','Bengal cat with coat pattern transforming into flowers','Calico cat made from quilt-like floral patterns','Australian Shepherd jumping through psychedelic flowers','Bengal cat melting into colorful liquid patterns','Dachshund surrounded by retro smiley flowers','Calico cat surrounded by strawberries and daisies')
$sets['Pets in Everyday Life'] = @('Beagle detective following a trail of paw prints','Tuxedo cat playing piano in a jazz club','Bernese Mountain Dog camping beside a tiny tent','Schnauzer as old sea captain','Great Dane having tea at a ridiculously tiny table','Pug wrapped like a burrito in a blanket','Scottish Fold hiding inside a cowboy boot','Beagle fishing from a tiny boat','Orange tabby wearing sunglasses in a kiddie pool','Tuxedo cat playing cards with three mice')
$renamed = @()
foreach ($k in @($sets.Keys)) { $sets[$k] = @($sets[$k] | % { $n = $_; if ($tk.ContainsKey((& $slug $n))) { $r = "$n in Pet Style"; $renamed += "  RENAMED: $n  ->  $r  (the first was under " + $tk[(& $slug $n)] + ")"; $r } else { $n } }) }
if ($renamed) { $renamed } else { "  no clashes" }
"== the old Animals & Pets ending (being replaced) =="
npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:animals-pets" --remote 2>$null | Select-Object -Last 1
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:animals-pets" ", creative contemporary pet tattoo artwork, playful, stylish, expressive and full of personality, preserve the recognizable physical characteristics, proportions, coat patterns and personality of the specific dog or cat breed named in the concept while creatively transforming the situation around it, ranging naturally between bold tattoo flash, colorful illustrative tattooing, funky retro art, cute hand-drawn work, decorative tattoo art, embroidered-patch influence, psychedelic color, graphic black ink, Art Nouveau, ornamental influences and whimsical surrealism depending on the idea, favor imaginative compositions and visual storytelling rather than realistic pet portraiture, no micro-realism, fun and surprising but still desirable as a real tattoo, use color freely when it improves the design, tattoo artwork alone, never worn on skin or a body, complete design filling the frame, isolated on a clean plain white background, no watermark" --remote
$newK = @('Pets Dressed Up','Pets on Adventures','Pets Up to Mischief','Magic Pets','Dreamy Pets','Glam Pets','Retro Flash Pets','Edgy and Elegant Pets','Psychedelic and Floral Pets','Pets in Everyday Life')
RUN ("CATEGORY Animals & Pets :: " + ((@($mineK | ? { $newK -notcontains $_ }) + $newK) -join ", "))
foreach ($k in $sets.Keys) { RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) }
RUN "FACE Dachshund stretched into a limousine"
}
}