RUN "SETKV shape:micro-realism-family 3:2"
RUN "SETKV split:micro-realism-family yes"
RUN "SETKV shape:micro-realism-legacy 3:2"
RUN "SETKV split:micro-realism-legacy yes"
RUN "SETKV shape:micro-realism-pets-and-animals 3:2"
RUN "SETKV split:micro-realism-pets-and-animals yes"
RUN "SETKV shape:micro-realism-nature 3:2"
RUN "SETKV split:micro-realism-nature yes"
RUN "SETKV shape:micro-realism-keepsakes 3:2"
RUN "SETKV split:micro-realism-keepsakes yes"
RUN "SETKV shape:micro-realism-nostalgia-and-travel 3:2"
RUN "SETKV split:micro-realism-nostalgia-and-travel yes"
Start-Sleep -Seconds 60
RUN "REDO Micro-Real Baby Portrait, Micro-Real Child Portrait, Micro-Real Two Children Portrait, Micro-Real Mother And Baby, Micro-Real Father And Child"
RUN "REDO Micro-Real Mother And Daughter, Micro-Real Father And Son, Micro-Real Siblings From Childhood Photo, Micro-Real Child Holding Parent's Hand, Micro-Real Parent Holding Baby Hand"
RUN "REDO Micro-Real Baby Hand, Micro-Real Baby Foot, Micro-Real Child Handprint, Micro-Real Baby Footprint, Micro-Real Child's Eye"
RUN "REDO Micro-Real Child's Smile, Micro-Real Baby Shoes, Micro-Real Child's Favorite Teddy Bear, Micro-Real Childhood Toy, Micro-Real Family Home"
RUN "REDO Micro-Real Grandmother Portrait, Micro-Real Grandfather Portrait, Micro-Real Grandparent Couple Portrait, Micro-Real Old Family Photograph, Micro-Real Wedding Portrait"
RUN "REDO Micro-Real Parent's Hand, Micro-Real Grandparent's Hand, Micro-Real Handwritten Note, Micro-Real Signature, Micro-Real Handwritten Recipe Card"
RUN "REDO Micro-Real Old House Key, Micro-Real Family Heirloom Ring, Micro-Real Pocket Watch, Micro-Real Grandmother's Brooch, Micro-Real Father's Work Boots"
RUN "REDO Micro-Real Golden Retriever Portrait, Micro-Real French Bulldog Portrait, Micro-Real Dachshund Portrait, Micro-Real Chihuahua Portrait, Micro-Real German Shepherd Portrait"
RUN "REDO Micro-Real Pit Bull Portrait, Micro-Real Cat Portrait, Micro-Real Sleeping Cat, Micro-Real Dog Nose, Micro-Real Cat Eye"
RUN "REDO Micro-Real Dog Paw, Micro-Real Pet Collar And Tag, Micro-Real Rabbit, Micro-Real Horse Portrait, Micro-Real Hummingbird"
RUN "REDO Micro-Real Swallow, Micro-Real Owl, Micro-Real Fox, Micro-Real Wolf, Micro-Real Elephant"
RUN "REDO Micro-Real Peony, Micro-Real Sunflower, Micro-Real Orchid, Micro-Real Poppy, Micro-Real Birth Flower"
RUN "REDO Micro-Real Two Birth Flowers, Micro-Real Family Birth-Flower Bouquet, Micro-Real Monarch Butterfly, Micro-Real Moth, Micro-Real Honeybee"
RUN "REDO Micro-Real Dragonfly, Micro-Real Ladybug, Micro-Real Seashell, Micro-Real Ocean Wave, Micro-Real Moon"
RUN "REDO Micro-Real Teddy Bear, Micro-Real Sneakers, Micro-Real Cowboy Boots, Micro-Real Baseball Glove, Micro-Real Baseball"
RUN "REDO Micro-Real Football, Micro-Real Surfboard, Micro-Real Skateboard, Micro-Real Guitar, Micro-Real Piano"
RUN "REDO Micro-Real Vinyl Record, Micro-Real Headphones, Micro-Real Book, Micro-Real Typewriter, Micro-Real Perfume Bottle"
RUN "REDO Micro-Real Polaroid Camera, Micro-Real Polaroid Photograph, Micro-Real Cassette Tape, Micro-Real Game Controller, Micro-Real Roller Skate"
RUN "REDO Micro-Real Bicycle, Micro-Real Matchbook, Micro-Real Lighter, Micro-Real Coffee Cup, Micro-Real Champagne Glass"
RUN "REDO Micro-Real Childhood Home, Micro-Real Favorite Building, Micro-Real City Skyline, Micro-Real Vacation Landmark, Micro-Real Airplane"
Start-Sleep -Seconds 30
RUN "SHEET Micro Realism Family"
RUN "SHEET Micro Realism Legacy"
RUN "SHEET Micro Realism Pets And Animals"
RUN "SHEET Micro Realism Nature"
RUN "SHEET Micro Realism Keepsakes"
RUN "SHEET Micro Realism Nostalgia And Travel"
RUN "SHEET Micro Realism"
RUN "BROWSE"
RUN "BROWSE"
RUN "BROWSE"
