RUN "SETKV shape:micro-clever-objects 3:2"
RUN "SETKV split:micro-clever-objects yes"
RUN "SETKV shape:micro-little-worlds 3:2"
RUN "SETKV split:micro-little-worlds yes"
RUN "SETKV shape:micro-funny-and-playful 3:2"
RUN "SETKV split:micro-funny-and-playful yes"
RUN "SETKV shape:micro-personal-and-family 3:2"
RUN "SETKV split:micro-personal-and-family yes"
RUN "SETKV shape:micro-body-interaction 3:2"
RUN "SETKV split:micro-body-interaction yes"
RUN "SETKV shape:micro-collections 3:2"
RUN "SETKV split:micro-collections yes"
Start-Sleep -Seconds 60
RUN "REDO Matchbook With One Match Missing, Tiny Polaroid With A Sunset Inside, Cowboy Boot With A Flower Growing Out, Champagne Bottle Popping Its Cork, Half-Full Martini With Falling Olive"
RUN "REDO Tiny Open Book With A Star Escaping, Key With A Heart-Shaped Keyhole, Envelope With One Flower Coming Out, Tiny Perfume Bottle With Flower Stopper, Pocket Watch With A Flower Growing Through It"
RUN "REDO Tiny Camera With A Heart In The Lens, Lighter With A Tiny Flower Instead Of Flame, Teacup With A Tiny Storm Cloud Above It, Espresso Cup With A Tiny Planet As The Foam, Sunglasses Reflecting Two Palm Trees"
RUN "REDO Tiny Suitcase Covered In Travel Stickers, Compass With A Tiny House At North, Tiny Record Player With One Music Note, Cassette With Tape Forming A Heart, Tiny Bicycle With Flowers In The Basket"
RUN "REDO Two Chairs Facing The Ocean, Tiny Campfire With Two Empty Chairs, House With One Lit Window, Person Sitting On A Crescent Moon, Ladder Disappearing Into A Cloud"
RUN "REDO Open Door With A Star Beyond It, Surfboard Leaning Against A Palm Tree, Tiny Van Parked Beside The Ocean, Tent Under Three Stars, Tiny Sailboat On A Single Wave"
RUN "REDO Person Fishing From A Crescent Moon, Little House Under A Huge Moon, Mountains Inside A Postage Stamp, Beach Sunset Inside A Polaroid, Tiny City Skyline Inside A Matchbox"
RUN "REDO Tiny Cabin With Smoke From The Chimney, Person In A Rowboat Under The Moon, Tiny Car Driving Toward Mountains, Little Lighthouse With One Beam, Astronaut Floating Above A Tiny Earth"
RUN "REDO UFO Abducting A Cow, Ghost Carrying Flowers, Skeleton Watering A Flower, Frog Sitting Under A Mushroom, Snail Carrying A Little House"
RUN "REDO Cat Sitting In A Cardboard Box, Dinosaur Holding A Balloon, Tiny Crocodile Wearing A Party Hat, Duck Wearing Cowboy Boots, Frog Drinking An Espresso"
RUN "REDO Ghost Walking A Tiny Dog, Skeleton Relaxing In A Beach Chair, Alien Holding A Flower, Tiny Shark With Party Hat, Mouse Carrying An Oversized Flower"
RUN "REDO Raccoon Holding A Slice Of Pizza, Pigeon Wearing A Tiny Crown, Tiny Cowboy Riding A Snail, Little Devil Watering A Daisy, Tiny Angel And Devil Sharing A Drink"
RUN "REDO Child Holding Parent's Finger, Two Hands Making A Pinky Promise, Three Children's Birth Flowers From One Stem, Child's Actual Stick-Figure Drawing, Child's Handwritten Love You"
RUN "REDO Tiny Family House From A Photo, Child's Favorite Teddy Bear, Dad's Old Work Boot, Mom's Favorite Coffee Cup, Grandma's Recipe Card Detail"
RUN "REDO Parent's Signature With One Tiny Flower, Family Pet's Ear Outline From Photo, Child's First Shoes, Parents' Wedding Cake Topper, Childhood Home With One Tree"
RUN "REDO Shark Fin Circling The Ankle, Spider Crawling From Behind Ear, Little Person Sitting On Kneecap, Diver Diving Toward Navel, Paper Airplane Flying Along Collarbone"
RUN "REDO Little Climber Using A Freckle As A Boulder, Tiny Person Fishing Into The Navel, Mouse Peeking Over Waistband, Flower Growing From A Scar, Tiny Swing Hanging From Collarbone Line"
RUN "REDO Little Skier Descending The Shin, Tiny Surfer Riding An Ankle Curve, Little Astronaut Floating Around Shoulder, Tiny Cat Peeking From Behind The Wrist, Tiny Person Climbing Up The Spine"
RUN "REDO Travel Life, Beach Life, My Kids, My Dog, Night Out"
RUN "REDO Music Life, Little Western World, Little Garden, My Story, Completely Random Little Life"
Start-Sleep -Seconds 30
RUN "SHEET Micro Clever Objects"
RUN "SHEET Micro Little Worlds"
RUN "SHEET Micro Funny And Playful"
RUN "SHEET Micro Personal And Family"
RUN "SHEET Micro Body Interaction"
RUN "SHEET Micro Collections"
RUN "SHEET Micro Tattoos"
RUN "BROWSE"
RUN "BROWSE"
RUN "BROWSE"
