cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
RUN "REDO Small Heart On The Finger, Small Arrow On The Forearm, Tiny Triangle Behind The Ear, Open Circle On The Wrist, Tiny Cross On The Finger"
RUN "REDO Lightning Bolt On The Ankle, Tiny Star On The Collarbone, Small Infinity On The Wrist, Tiny Eye On The Neck, One-Line Face Profile"
RUN "REDO One-Line Cat On The Wrist, One-Line Mountains, One-Line Wave, One-Line Hands Touching, One-Line Flower On The Ankle"
RUN "REDO One-Line Bird In Flight, One-Line Heartbeat Mountain, One-Line Couple Embracing, One-Line Dog Portrait, Wildflower Stem On The Ribs"
RUN "REDO Olive Sprig Behind The Ear, Tiny Fern On The Ankle, Tiny Rose On The Finger, Eucalyptus Sprig On The Collarbone, Small Leaf On The Wrist"
RUN "REDO Lavender Stem On The Inner Arm, Tiny Daisy On The Hip, Pine Branch On The Forearm, Tiny Tulip On The Shoulder Blade, Moon Phases Down The Spine"
RUN "REDO Crescent Moon Behind The Ear, Constellation On The Shoulder Blade, Tiny Ringed Planet, Shooting Star On The Finger, Sun And Moon On The Wrist"
RUN "REDO Three Stars On The Collarbone, Small North Star On The Chest, Tiny Comet On The Forearm, Orbit Lines On The Ankle, Tiny Swallow On The Hand"
RUN "REDO Whale Tail On The Ankle, Tiny Butterfly On The Shoulder Blade, Small Bee On The Finger, Tiny Fox Outline, Small Elephant On The Inner Arm"
RUN "REDO Tiny Paw Print On The Wrist, Small Wolf Outline, Tiny Fish On The Ankle, Small Bird On The Collarbone, Triangle Trio On The Forearm"
RUN "REDO Tiny Diamond On The Finger, Circle And Line On The Inner Arm, Small Hexagon On The Wrist, Square Frame On The Ankle, Mountain Triangle On The Forearm"
RUN "REDO Half Circles On The Shoulder, Minimal Compass On The Forearm, Tiny Cube On The Hand, Golden Ratio Spiral, Three Dots On The Finger"
RUN "REDO Dot Trail Behind The Ear, Single Line Around The Wrist, Two Parallel Arm Bands, Dotted Line Along The Collarbone, Dot Constellation On The Hand"
RUN "REDO Line Ring On The Finger, Dot Circle On The Ankle, Thin Line Down The Arm, Dash Line Around The Ankle, Semicolon On The Wrist"
RUN "REDO Unalome On The Sternum, Small Anchor On The Finger, Tiny Lotus On The Neck, Small Key On The Wrist, Tiny Hourglass On The Forearm"
RUN "REDO Origami Crane On The Wrist, Tiny Feather On The Ankle, Crossed Arrows On The Forearm, Puzzle Piece On The Finger, Ornament Drop On The Sternum"
RUN "REDO Ear Curve Ornament, Filigree On The Finger, Ornamental Wrist Line, Tiny Bow On The Arm, Ornamental Spine Accent"
RUN "REDO Dainty Ankle Ornament, Small Ornamental Band, Ornamental Hand Accent, Tiny Ornamental Chest Mark, Tiny Flower On The Earlobe"
RUN "REDO Wave On The Side Of The Finger, Sun On The Back Of The Neck, Mountain On The Inner Wrist, Moon On The Ankle Bone, Spark Behind The Ear"
RUN "REDO Heart On The Hip, Small Arrow Behind The Ear, Tiny Cloud On The Wrist, Small Snake Around The Finger"
RUN "WALK Minimalist"
RUN "SHEET Minimalist"
