RUN "LEAVES Negative Space On Him :: Forest Hides Two Faces, Waves Hide A Whale, Mountains Hide A Wolf, Tree Hides A Child, Smoke Hides A Face, Collarbone Becomes Horizon, Ribs Become Sunbeams, Elbow Becomes Eclipse, Navel Becomes Black Hole, Pec Becomes Sunrise, Window Into The Ocean, Keyhole With A Landscape, Broken Wall And Flowers Behind It, Polaroid Window, Cave Opening, Lighthouse Beam, Sunbeams Through Forest, Car Headlights In Fog, UFO Beam, Sun Through Clouds, Missing Person, Erased Flower, Disappearing Bird, Missing Heart, The One Who Isn't There, Tiger Stripes Without Tiger, Octopus From Empty Water, Owl Eyes From Moonlight, Hummingbird Between Flowers, Snake Made From Empty Space, Face Opening Into Space, Person Falling Through Themselves, Skull Containing A City, Human Profile Containing Ocean, Body With A Doorway, Impossible Cube, Broken Circle, Optical Tunnel, Mobius Void, Fractured Sun, Child's Profile In Flowers, Family Of Four, Dad's Profile In Mountains, Child's Handprint As Empty Space, Handwriting Cutout, Woman Made Of Nothing, Two People About To Kiss, Person Walking Into Light, Skin River, Portrait Inside The Absence, The Tattoo That Isn't There"
RUN "LEAVES Negative Space On Her :: Flowers Hide A Woman, Roses Hide A Skull, Butterfly Hides Two Faces, Flowers Hide A Butterfly, Snakes Hide A Heart, Spine Becomes Lightning, Shoulder Becomes Moon, Knee Becomes An Eye, Hip Curve Becomes Wave, Shoulder Blade Becomes Wing Gap, Window Into The Forest, Open Door Into Space, Portal With A Person Inside, Archway To The Moon, Tear In Reality, Flashlight Beam, Moonlight On Water, Angelic Light, Open Door Light, Candle Glow, Missing Portrait, Missing Puzzle Piece, Half-Erased Skull, Unfinished Statue, Forgotten Face, Zebra Disappearing Into Skin, Shark Under The Surface, Deer Between Trees, Fox In Autumn Leaves, Koi Made From Water, Head Full Of Butterflies, Hand Holding A Heart Made Of Nothing, Eye Containing A Forest, Flower Blooming Into A Face, The Void Looking Back, Negative-Space Spiral, Skin Maze, Shattered Mirror, Negative Diamond, Geometric Face, Two Children In A Tree, Mom's Profile In Her Favorite Flower, Pet Profile In Forest, Child's Drawing As Empty Space, Family Home In The Void, Man Made Of Nothing, Hand Reaching Through A Wall, Black Ocean And Empty Moon, Butterflies Made From Gaps"
RUN "SETKV shape:negative-space-on-him 3:2"
RUN "SETKV split:negative-space-on-him yes"
RUN "SETKV shape:negative-space-on-her 3:2"
RUN "SETKV split:negative-space-on-her yes"
Start-Sleep -Seconds 60
RUN "LEAVES Negative Space On Him"
RUN "LEAVES Negative Space On Her"
RUN "REDO Forest Hides Two Faces, Flowers Hide A Woman, Waves Hide A Whale, Roses Hide A Skull, Mountains Hide A Wolf"
RUN "REDO Butterfly Hides Two Faces, Tree Hides A Child, Flowers Hide A Butterfly, Smoke Hides A Face, Snakes Hide A Heart"
RUN "REDO Collarbone Becomes Horizon, Spine Becomes Lightning, Ribs Become Sunbeams, Shoulder Becomes Moon, Elbow Becomes Eclipse"
RUN "REDO Knee Becomes An Eye, Navel Becomes Black Hole, Hip Curve Becomes Wave, Pec Becomes Sunrise, Shoulder Blade Becomes Wing Gap"
RUN "REDO Window Into The Ocean, Window Into The Forest, Keyhole With A Landscape, Open Door Into Space, Broken Wall And Flowers Behind It"
RUN "REDO Portal With A Person Inside, Polaroid Window, Archway To The Moon, Cave Opening, Tear In Reality"
RUN "REDO Lighthouse Beam, Flashlight Beam, Sunbeams Through Forest, Moonlight On Water, Car Headlights In Fog"
RUN "REDO Angelic Light, UFO Beam, Open Door Light, Sun Through Clouds, Candle Glow"
RUN "REDO Missing Portrait, Missing Person, Missing Puzzle Piece, Erased Flower, Half-Erased Skull"
RUN "REDO Disappearing Bird, Unfinished Statue, Missing Heart, Forgotten Face, The One Who Isn't There"
RUN "REDO Tiger Stripes Without Tiger, Zebra Disappearing Into Skin, Octopus From Empty Water, Shark Under The Surface, Owl Eyes From Moonlight"
RUN "REDO Deer Between Trees, Hummingbird Between Flowers, Fox In Autumn Leaves, Snake Made From Empty Space, Koi Made From Water"
RUN "REDO Face Opening Into Space, Head Full Of Butterflies, Person Falling Through Themselves, Hand Holding A Heart Made Of Nothing, Skull Containing A City"
RUN "REDO Eye Containing A Forest, Human Profile Containing Ocean, Flower Blooming Into A Face, Body With A Doorway, The Void Looking Back"
RUN "REDO Impossible Cube, Negative-Space Spiral, Broken Circle, Skin Maze, Optical Tunnel"
RUN "REDO Shattered Mirror, Mobius Void, Negative Diamond, Fractured Sun, Geometric Face"
RUN "REDO Child's Profile In Flowers, Two Children In A Tree, Family Of Four, Mom's Profile In Her Favorite Flower, Dad's Profile In Mountains"
RUN "REDO Pet Profile In Forest, Child's Handprint As Empty Space, Child's Drawing As Empty Space, Handwriting Cutout, Family Home In The Void"
RUN "REDO Woman Made Of Nothing, Man Made Of Nothing, Two People About To Kiss, Hand Reaching Through A Wall, Person Walking Into Light"
RUN "REDO Black Ocean And Empty Moon, Skin River, Butterflies Made From Gaps, Portrait Inside The Absence, The Tattoo That Isn't There"
Start-Sleep -Seconds 30
RUN "SHEET Negative Space On Him"
RUN "SHEET Negative Space On Her"
RUN "SHEET Negative Space"
RUN "BROWSE"
