cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."1990s Nostalgia")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('1990s Nostalgia Style Tech','1990s Nostalgia Style Toys and Games','1990s Nostalgia Style Flash','1990s Nostalgia Style Y2K Butterflies and Stars','1990s Nostalgia Style Snacks and Things','1990s Nostalgia Style Cartoon Style','1990s Nostalgia Style Grunge','1990s Nostalgia Style Bands and Cuffs','1990s Nostalgia Style Small','1990s Nostalgia Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Cassette tape with a pencil in the reel'] = 'The tattoo: cassette tape with a pencil in the reel. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Chunky handheld game console'] = 'The tattoo: chunky handheld game console. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Portable CD player with headphones'] = 'The tattoo: portable cd player with headphones. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Flip phone with an antenna'] = 'The tattoo: flip phone with an antenna. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pager clipped to a belt'] = 'The tattoo: pager clipped to a belt. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Floppy disk'] = 'The tattoo: floppy disk. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Boxy CRT television'] = 'The tattoo: boxy crt television. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['VHS tape'] = 'The tattoo: vhs tape. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Virtual pet keychain egg'] = 'The tattoo: virtual pet keychain egg. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Old desktop computer with a mouse'] = 'The tattoo: old desktop computer with a mouse. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Yo-yo mid spin'] = 'The tattoo: yo-yo mid spin. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Slap bracelet'] = 'The tattoo: slap bracelet. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Rubik cube half solved'] = 'The tattoo: rubik cube half solved. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Pogs stack with a slammer'] = 'The tattoo: pogs stack with a slammer. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Glow in the dark stars'] = 'The tattoo: glow in the dark stars. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bubble wand with bubbles'] = 'The tattoo: bubble wand with bubbles. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Inline skate'] = 'The tattoo: inline skate. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Skateboard with flame graphics'] = 'The tattoo: skateboard with flame graphics. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Stuffed bear with a heart'] = 'The tattoo: stuffed bear with a heart. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Magic eight ball'] = 'The tattoo: magic eight ball. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tribal sun'] = 'The tattoo: tribal sun. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Yin yang with flames'] = 'The tattoo: yin yang with flames. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Barbed wire heart'] = 'The tattoo: barbed wire heart. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Dolphin jumping over a wave'] = 'The tattoo: dolphin jumping over a wave. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Celtic knot armband'] = 'The tattoo: celtic knot armband. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Tribal butterfly'] = 'The tattoo: tribal butterfly. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Sun and moon kissing'] = 'The tattoo: sun and moon kissing. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Nautical star'] = 'The tattoo: nautical star. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Rose with a dagger through it'] = 'The tattoo: rose with a dagger through it. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tribal scorpion'] = 'The tattoo: tribal scorpion. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Butterfly with sparkles'] = 'The tattoo: butterfly with sparkles. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Shooting star trail'] = 'The tattoo: shooting star trail. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Cluster of tiny stars'] = 'The tattoo: cluster of tiny stars. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Butterfly hair clip'] = 'The tattoo: butterfly hair clip. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Heart with angel wings'] = 'The tattoo: heart with angel wings. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Sparkly crescent moon'] = 'The tattoo: sparkly crescent moon. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Glitter star'] = 'The tattoo: glitter star. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Butterfly with swirls'] = 'The tattoo: butterfly with swirls. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Fairy sitting on a crescent moon'] = 'The tattoo: fairy sitting on a crescent moon. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Flaming heart'] = 'The tattoo: flaming heart. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Lava lamp'] = 'The tattoo: lava lamp. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Smiley face with a drip'] = 'The tattoo: smiley face with a drip. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Alien head'] = 'The tattoo: alien head. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Mood ring'] = 'The tattoo: mood ring. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Disposable camera'] = 'The tattoo: disposable camera. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Choker necklace with a charm'] = 'The tattoo: choker necklace with a charm. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Bucket hat'] = 'The tattoo: bucket hat. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Jelly sandals'] = 'The tattoo: jelly sandals. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Gel pen set'] = 'The tattoo: gel pen set. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Lunchbox with stickers'] = 'The tattoo: lunchbox with stickers. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Cartoon alien with big eyes'] = 'The tattoo: cartoon alien with big eyes. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cartoon dinosaur in sneakers'] = 'The tattoo: cartoon dinosaur in sneakers. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Cartoon cat in sunglasses'] = 'The tattoo: cartoon cat in sunglasses. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cartoon slime monster'] = 'The tattoo: cartoon slime monster. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Cartoon skateboarding frog'] = 'The tattoo: cartoon skateboarding frog. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Cartoon cyclops monster'] = 'The tattoo: cartoon cyclops monster. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Cartoon gremlin with headphones'] = 'The tattoo: cartoon gremlin with headphones. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cartoon rubber duck in shades'] = 'The tattoo: cartoon rubber duck in shades. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Cartoon flying saucer'] = 'The tattoo: cartoon flying saucer. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cartoon pizza slice with sunglasses'] = 'The tattoo: cartoon pizza slice with sunglasses. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Melting smiley'] = 'The tattoo: melting smiley. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Safety pin through a heart'] = 'The tattoo: safety pin through a heart. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Flannel heart patch'] = 'The tattoo: flannel heart patch. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Daisy with a smiley centre'] = 'The tattoo: daisy with a smiley centre. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Broken guitar'] = 'The tattoo: broken guitar. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Combat boot with daisies'] = 'The tattoo: combat boot with daisies. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Crying eye with a star'] = 'The tattoo: crying eye with a star. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Peace sign with roses'] = 'The tattoo: peace sign with roses. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Grunge rose with drips'] = 'The tattoo: grunge rose with drips. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Mixtape heart'] = 'The tattoo: mixtape heart. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Barbed wire armband'] = 'The tattoo: barbed wire armband. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Tribal armband'] = 'The tattoo: tribal armband. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Celtic band'] = 'The tattoo: celtic band. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Flame armband'] = 'The tattoo: flame armband. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Chain link armband'] = 'The tattoo: chain link armband. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Star cuff'] = 'The tattoo: star cuff. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Butterfly ankle band'] = 'The tattoo: butterfly ankle band. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Daisy chain band'] = 'The tattoo: daisy chain band. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Dolphin ankle band'] = 'The tattoo: dolphin ankle band. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Heartbeat line band'] = 'The tattoo: heartbeat line band. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny smiley face'] = 'The tattoo: tiny smiley face. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small yin yang'] = 'The tattoo: small yin yang. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny alien head'] = 'The tattoo: tiny alien head. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small butterfly'] = 'The tattoo: small butterfly. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny daisy'] = 'The tattoo: tiny daisy. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small flame'] = 'The tattoo: small flame. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny star'] = 'The tattoo: tiny star. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small cassette'] = 'The tattoo: small cassette. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny heart with wings'] = 'The tattoo: tiny heart with wings. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small peace sign'] = 'The tattoo: small peace sign. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Nineties tech half sleeve'] = 'The tattoo: nineties tech half sleeve. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Tribal flames back piece'] = 'The tattoo: tribal flames back piece. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his back, shirtless, seen from behind'
$b['Butterflies and stars thigh piece'] = 'The tattoo: butterflies and stars thigh piece. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Cartoon monsters leg sleeve'] = 'The tattoo: cartoon monsters leg sleeve. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his whole leg, wearing shorts'
$b['Barbed wire and roses forearm piece'] = 'The tattoo: barbed wire and roses forearm piece. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Dolphins and sun calf piece'] = 'The tattoo: dolphins and sun calf piece. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Grunge flash sleeve'] = 'The tattoo: grunge flash sleeve. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Y2K sparkle shoulder piece'] = 'The tattoo: y2k sparkle shoulder piece. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Alien and saucer chest piece'] = 'The tattoo: alien and saucer chest piece. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Lava lamps and flames spine piece'] = 'The tattoo: lava lamps and flames spine piece. 1990s nostalgia tattoo, a retro nineties throwback, bold clean black outlines, bright saturated nineties colours like teal purple hot pink and lime, smooth flat colour with simple shading, playful fun flash style, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is down his spine, shirtless, seen from behind'
$sets = [ordered]@{}
$sets['1990s Nostalgia Style Tech'] = @('Cassette tape with a pencil in the reel','Chunky handheld game console','Portable CD player with headphones','Flip phone with an antenna','Pager clipped to a belt','Floppy disk','Boxy CRT television','VHS tape','Virtual pet keychain egg','Old desktop computer with a mouse')
$sets['1990s Nostalgia Style Toys and Games'] = @('Yo-yo mid spin','Slap bracelet','Rubik cube half solved','Pogs stack with a slammer','Glow in the dark stars','Bubble wand with bubbles','Inline skate','Skateboard with flame graphics','Stuffed bear with a heart','Magic eight ball')
$sets['1990s Nostalgia Style Flash'] = @('Tribal sun','Yin yang with flames','Barbed wire heart','Dolphin jumping over a wave','Celtic knot armband','Tribal butterfly','Sun and moon kissing','Nautical star','Rose with a dagger through it','Tribal scorpion')
$sets['1990s Nostalgia Style Y2K Butterflies and Stars'] = @('Butterfly with sparkles','Shooting star trail','Cluster of tiny stars','Butterfly hair clip','Heart with angel wings','Sparkly crescent moon','Glitter star','Butterfly with swirls','Fairy sitting on a crescent moon','Flaming heart')
$sets['1990s Nostalgia Style Snacks and Things'] = @('Lava lamp','Smiley face with a drip','Alien head','Mood ring','Disposable camera','Choker necklace with a charm','Bucket hat','Jelly sandals','Gel pen set','Lunchbox with stickers')
$sets['1990s Nostalgia Style Cartoon Style'] = @('Cartoon alien with big eyes','Cartoon dinosaur in sneakers','Cartoon cat in sunglasses','Cartoon slime monster','Cartoon skateboarding frog','Cartoon cyclops monster','Cartoon gremlin with headphones','Cartoon rubber duck in shades','Cartoon flying saucer','Cartoon pizza slice with sunglasses')
$sets['1990s Nostalgia Style Grunge'] = @('Melting smiley','Safety pin through a heart','Flannel heart patch','Daisy with a smiley centre','Broken guitar','Combat boot with daisies','Crying eye with a star','Peace sign with roses','Grunge rose with drips','Mixtape heart')
$sets['1990s Nostalgia Style Bands and Cuffs'] = @('Barbed wire armband','Tribal armband','Celtic band','Flame armband','Chain link armband','Star cuff','Butterfly ankle band','Daisy chain band','Dolphin ankle band','Heartbeat line band')
$sets['1990s Nostalgia Style Small'] = @('Tiny smiley face','Small yin yang','Tiny alien head','Small butterfly','Tiny daisy','Small flame','Tiny star','Small cassette','Tiny heart with wings','Small peace sign')
$sets['1990s Nostalgia Style Large Pieces'] = @('Nineties tech half sleeve','Tribal flames back piece','Butterflies and stars thigh piece','Cartoon monsters leg sleeve','Barbed wire and roses forearm piece','Dolphins and sun calf piece','Grunge flash sleeve','Y2K sparkle shoulder piece','Alien and saucer chest piece','Lava lamps and flames spine piece')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Nineties Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Nineties Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Nineties Style$','') -ne 'Cassette tape with a pencil in the reel' })
}
"== drawing " + $all.Count + " 1990s Nostalgia split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK 1990s Nostalgia"
RUN "SHEET 1990s Nostalgia"
}
