cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."3D / Optical")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('3D Optical Style Illusions','3D Optical Style Skin Rips','3D Optical Style Objects on Skin','3D Optical Style Geometric Depth','3D Optical Style Op Art','3D Optical Style Portals and Holes','3D Optical Style Mechanical','3D Optical Style Water and Glass','3D Optical Style Small','3D Optical Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Impossible triangle'] = 'The tattoo: impossible triangle. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Endless staircase'] = 'The tattoo: endless staircase. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Impossible cube'] = 'The tattoo: impossible cube. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Spiral tunnel into the skin'] = 'The tattoo: spiral tunnel into the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Rotating circles illusion'] = 'The tattoo: rotating circles illusion. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Warped checkerboard sphere'] = 'The tattoo: warped checkerboard sphere. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Infinite loop ribbon'] = 'The tattoo: infinite loop ribbon. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Impossible fork'] = 'The tattoo: impossible fork. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Twisted ring illusion'] = 'The tattoo: twisted ring illusion. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Penrose square'] = 'The tattoo: penrose square. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Torn skin showing gears'] = 'The tattoo: torn skin showing gears. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Skin rip showing a galaxy'] = 'The tattoo: skin rip showing a galaxy. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Zipper opening in the skin'] = 'The tattoo: zipper opening in the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Torn skin showing robot parts'] = 'The tattoo: torn skin showing robot parts. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Skin peeling to reveal circuits'] = 'The tattoo: skin peeling to reveal circuits. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Skin rip showing an eye'] = 'The tattoo: skin rip showing an eye. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Skin torn open showing ocean waves'] = 'The tattoo: skin torn open showing ocean waves. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Skin rip showing a clock'] = 'The tattoo: skin rip showing a clock. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Torn skin with a butterfly emerging'] = 'The tattoo: torn skin with a butterfly emerging. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Skin rip showing a forest'] = 'The tattoo: skin rip showing a forest. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Butterfly resting on the skin with a shadow'] = 'The tattoo: butterfly resting on the skin with a shadow. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Spider crawling with a cast shadow'] = 'The tattoo: spider crawling with a cast shadow. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Ladybug sitting on the skin'] = 'The tattoo: ladybug sitting on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Dragonfly resting with a shadow'] = 'The tattoo: dragonfly resting with a shadow. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Bee landing on the skin'] = 'The tattoo: bee landing on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Moth sitting on the skin'] = 'The tattoo: moth sitting on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Dice that look real'] = 'The tattoo: dice that look real. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Key lying on the skin'] = 'The tattoo: key lying on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Feather lying on the skin with a shadow'] = 'The tattoo: feather lying on the skin with a shadow. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Beetle crawling with a shadow'] = 'The tattoo: beetle crawling with a shadow. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['3D cube stack'] = 'The tattoo: 3d cube stack. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Floating 3D pyramid'] = 'The tattoo: floating 3d pyramid. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['3D hexagon tunnel'] = 'The tattoo: 3d hexagon tunnel. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Stacked 3D blocks'] = 'The tattoo: stacked 3d blocks. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['3D sphere made of lines'] = 'The tattoo: 3d sphere made of lines. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Floating geometric shards'] = 'The tattoo: floating geometric shards. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['3D star tetrahedron'] = 'The tattoo: 3d star tetrahedron. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['3D wireframe globe'] = 'The tattoo: 3d wireframe globe. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['3D stairs into a hole'] = 'The tattoo: 3d stairs into a hole. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Cubes floating off the skin'] = 'The tattoo: cubes floating off the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Wavy lines bulging out'] = 'The tattoo: wavy lines bulging out. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Concentric circles that pulse'] = 'The tattoo: concentric circles that pulse. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and white wave pattern'] = 'The tattoo: black and white wave pattern. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Bulging grid'] = 'The tattoo: bulging grid. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Moire circles'] = 'The tattoo: moire circles. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Spiral op art disc'] = 'The tattoo: spiral op art disc. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Stripes bending around a sphere'] = 'The tattoo: stripes bending around a sphere. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Op art eye'] = 'The tattoo: op art eye. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Op art zebra lines'] = 'The tattoo: op art zebra lines. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Op art diamond bulge'] = 'The tattoo: op art diamond bulge. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Hole in the skin with a mini world inside'] = 'The tattoo: hole in the skin with a mini world inside. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Portal with stars inside'] = 'The tattoo: portal with stars inside. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Keyhole into another world'] = 'The tattoo: keyhole into another world. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Window into the sea'] = 'The tattoo: window into the sea. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Hole with a ladder going down'] = 'The tattoo: hole with a ladder going down. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Portal with a waterfall'] = 'The tattoo: portal with a waterfall. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Door opening in the skin'] = 'The tattoo: door opening in the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Well into a galaxy'] = 'The tattoo: well into a galaxy. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Crack showing glowing lava'] = 'The tattoo: crack showing glowing lava. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Manhole cover opening'] = 'The tattoo: manhole cover opening. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Biomechanical gears under the skin'] = 'The tattoo: biomechanical gears under the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Pistons in the forearm'] = 'The tattoo: pistons in the forearm. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Clockwork heart'] = 'The tattoo: clockwork heart. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Robotic joint in the elbow'] = 'The tattoo: robotic joint in the elbow. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Gears in a spiral'] = 'The tattoo: gears in a spiral. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Mechanical eye'] = 'The tattoo: mechanical eye. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Cables under the skin'] = 'The tattoo: cables under the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Hydraulic arm'] = 'The tattoo: hydraulic arm. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Spinning cog stack'] = 'The tattoo: spinning cog stack. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Mechanical spine'] = 'The tattoo: mechanical spine. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Water drop sitting on the skin'] = 'The tattoo: water drop sitting on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Glass marble on the skin'] = 'The tattoo: glass marble on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Bubble sitting on the skin'] = 'The tattoo: bubble sitting on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Ice cube on the skin'] = 'The tattoo: ice cube on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Water splash rising off the skin'] = 'The tattoo: water splash rising off the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Droplets running down the arm'] = 'The tattoo: droplets running down the arm. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Crystal sitting on the skin'] = 'The tattoo: crystal sitting on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Magnifying lens on the skin'] = 'The tattoo: magnifying lens on the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Soap bubble with a reflection'] = 'The tattoo: soap bubble with a reflection. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Glass orb with a reflection'] = 'The tattoo: glass orb with a reflection. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny 3D cube'] = 'The tattoo: tiny 3d cube. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small impossible triangle'] = 'The tattoo: small impossible triangle. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny ladybug with a shadow'] = 'The tattoo: tiny ladybug with a shadow. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small 3D sphere'] = 'The tattoo: small 3d sphere. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny hole in the skin'] = 'The tattoo: tiny hole in the skin. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small 3D star'] = 'The tattoo: small 3d star. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny water drop'] = 'The tattoo: tiny water drop. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small 3D pyramid'] = 'The tattoo: small 3d pyramid. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny gear'] = 'The tattoo: tiny gear. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small op art circle'] = 'The tattoo: small op art circle. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['3D biomechanical full sleeve'] = 'The tattoo: 3d biomechanical full sleeve. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Skin rip back piece with gears'] = 'The tattoo: skin rip back piece with gears. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his back, shirtless, seen from behind'
$b['Op art leg sleeve'] = 'The tattoo: op art leg sleeve. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole leg, wearing mid-length shorts'
$b['3D geometric thigh piece'] = 'The tattoo: 3d geometric thigh piece. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Optical illusion forearm piece'] = 'The tattoo: optical illusion forearm piece. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Portal calf piece'] = 'The tattoo: portal calf piece. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['3D cube shoulder piece'] = 'The tattoo: 3d cube shoulder piece. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Skin rip chest piece'] = 'The tattoo: skin rip chest piece. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his chest, shirtless'
$b['3D spiral spine piece'] = 'The tattoo: 3d spiral spine piece. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is down her spine, seen from behind in a low open-back top'
$b['Op art half sleeve'] = 'The tattoo: op art half sleeve. 3D optical illusion tattoo, strong realistic depth and shading so it looks like it pops out of or sinks into the skin, cast shadows and highlights, mind bending perspective, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$sets = [ordered]@{}
$sets['3D Optical Style Illusions'] = @('Impossible triangle','Endless staircase','Impossible cube','Spiral tunnel into the skin','Rotating circles illusion','Warped checkerboard sphere','Infinite loop ribbon','Impossible fork','Twisted ring illusion','Penrose square')
$sets['3D Optical Style Skin Rips'] = @('Torn skin showing gears','Skin rip showing a galaxy','Zipper opening in the skin','Torn skin showing robot parts','Skin peeling to reveal circuits','Skin rip showing an eye','Skin torn open showing ocean waves','Skin rip showing a clock','Torn skin with a butterfly emerging','Skin rip showing a forest')
$sets['3D Optical Style Objects on Skin'] = @('Butterfly resting on the skin with a shadow','Spider crawling with a cast shadow','Ladybug sitting on the skin','Dragonfly resting with a shadow','Bee landing on the skin','Moth sitting on the skin','Dice that look real','Key lying on the skin','Feather lying on the skin with a shadow','Beetle crawling with a shadow')
$sets['3D Optical Style Geometric Depth'] = @('3D cube stack','Floating 3D pyramid','3D hexagon tunnel','Stacked 3D blocks','3D sphere made of lines','Floating geometric shards','3D star tetrahedron','3D wireframe globe','3D stairs into a hole','Cubes floating off the skin')
$sets['3D Optical Style Op Art'] = @('Wavy lines bulging out','Concentric circles that pulse','Black and white wave pattern','Bulging grid','Moire circles','Spiral op art disc','Stripes bending around a sphere','Op art eye','Op art zebra lines','Op art diamond bulge')
$sets['3D Optical Style Portals and Holes'] = @('Hole in the skin with a mini world inside','Portal with stars inside','Keyhole into another world','Window into the sea','Hole with a ladder going down','Portal with a waterfall','Door opening in the skin','Well into a galaxy','Crack showing glowing lava','Manhole cover opening')
$sets['3D Optical Style Mechanical'] = @('Biomechanical gears under the skin','Pistons in the forearm','Clockwork heart','Robotic joint in the elbow','Gears in a spiral','Mechanical eye','Cables under the skin','Hydraulic arm','Spinning cog stack','Mechanical spine')
$sets['3D Optical Style Water and Glass'] = @('Water drop sitting on the skin','Glass marble on the skin','Bubble sitting on the skin','Ice cube on the skin','Water splash rising off the skin','Droplets running down the arm','Crystal sitting on the skin','Magnifying lens on the skin','Soap bubble with a reflection','Glass orb with a reflection')
$sets['3D Optical Style Small'] = @('Tiny 3D cube','Small impossible triangle','Tiny ladybug with a shadow','Small 3D sphere','Tiny hole in the skin','Small 3D star','Tiny water drop','Small 3D pyramid','Tiny gear','Small op art circle')
$sets['3D Optical Style Large Pieces'] = @('3D biomechanical full sleeve','Skin rip back piece with gears','Op art leg sleeve','3D geometric thigh piece','Optical illusion forearm piece','Portal calf piece','3D cube shoulder piece','Skin rip chest piece','3D spiral spine piece','Op art half sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in 3D Optical Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in 3D Optical Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in 3D Optical Style$','') -ne 'Impossible triangle' })
}
"== drawing " + $all.Count + " 3D / Optical split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK 3D / Optical"
RUN "SHEET 3D / Optical"
}
