cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
RUN "REDO Ruby heart pendant with dangling chains, Sapphire chandelier ornament, Amethyst crescent pendant, Opal sunburst medallion, Black diamond filigree pendant"
RUN "REDO Pearl and chain cascade, Emerald eye pendant, Ruby dagger brooch, Sapphire moth jewel, Baroque filigree heart"
RUN "REDO Ornate filigree butterfly, Filigree crescent moon, Filigree ornamental cross, Rococo shell ornament, Filigree serpent"
RUN "REDO Ornate antique key, Filigree scarab, Baroque sun ornament, Filigree anatomical heart, Peony inside an ornamental frame"
RUN "REDO Wildflowers growing through filigree, Lotus jewel ornament, Poppy with dangling chains, Iris framed by Art Nouveau curves, Chrysanthemum ornamental medallion"
RUN "REDO Magnolia with pearl drops, Rose with emerald leaves, Wisteria chandelier ornament, Fern and gemstone composition, Woman with flowing ornamental hair"
RUN "REDO Peacock inside an Art Nouveau arch, Dragonfly stained-glass ornament, Butterfly with flowing Nouveau wings, Moon woman inside a floral arch, Swan surrounded by iris curves"
RUN "REDO Serpent winding through Nouveau flowers, Poppy stained-glass panel, Sun and moon Nouveau medallion, Two koi inside a flowing floral frame, Jeweled crescent moon chandelier"
RUN "REDO Ornamental sun with an amber center, Moon phases with hanging gemstones, Celestial eye with sapphire tears, Crystal star pendant, Ornamental eclipse"
RUN "REDO Saturn surrounded by filigree rings, Crystal ball framed in ornament, Jeweled constellation ornament, Sun and crescent hanging together, Gothic rose window with ruby glass"
RUN "REDO Cathedral arch with a dangling jewel, Ornamental cathedral window, Gothic doorway surrounded by roses, Stained-glass moth window, Baroque palace gate ornament"
RUN "REDO Gothic spire chandelier, Ornamental flying buttress composition, Renaissance window with flowers, Cathedral window with the moon behind it, Lace butterfly with pearl drops"
RUN "REDO Black lace heart with a ruby center, Ornamental bow with a hanging jewel, Draped chains with crescent charms, Lace fan with a floral center, Pearl garland with filigree drops"
RUN "REDO Lace rose medallion, Chain chandelier with emerald drops, Velvet ribbon ornament with a jewel, Lace crescent with dangling stars, Moth with jeweled wings"
RUN "REDO Butterfly with a sapphire body, Peacock feather with an emerald eye, Snake wrapped around a gemstone pendant, Beetle with a ruby shell, Cicada with Art Nouveau wings"
RUN "REDO Hummingbird surrounded by filigree, Seahorse with a pearl ornament, Black swan with a jeweled crown, Bee with golden ornamental wings, Black filigree exploding into red flowers"
RUN "REDO Ornamental eye dripping gemstones, Broken pearl necklace with a thorn ornament, Dagger suspended from jeweled chains, Anatomical heart wrapped in gold ornament, Snake passing through ornamental rings"
RUN "REDO Two hands holding an emerald pendant, Ornamental mirror reflecting a moon, Black rose inside jeweled architecture, Crystal heart surrounded by thorns, Sternum chandelier with a ruby center"
RUN "REDO Spine ornament with cascading gemstones, Symmetrical back chandelier with pearls, Shoulder ornament with floral chains, Ornamental chest necklace with an emerald center, Thigh ornament with peonies and jewels"
RUN "REDO Hip ornament with draped chains and flowers, Large Art Nouveau back panel, Ornamental half-sleeve with flowers and gemstones, Full back jewelry composition with a celestial centerpiece"
RUN "WALK Ornamental"
RUN "SHEET Ornamental"
