cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Pastel")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Pastel Style Celestial','Pastel Style Cute Animals','Pastel Style Butterflies and Wings','Pastel Style Crystals and Magic','Pastel Style Pastel Goth','Pastel Style Sweets','Pastel Style Ocean','Pastel Style Hearts and Symbols','Pastel Style Small','Pastel Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Pastel crescent moon with stars'] = 'The tattoo: pastel crescent moon with stars. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Sleeping moon in clouds'] = 'The tattoo: sleeping moon in clouds. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pastel planet with rings'] = 'The tattoo: pastel planet with rings. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pastel sun and moon'] = 'The tattoo: pastel sun and moon. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Shooting star with a soft trail'] = 'The tattoo: shooting star with a soft trail. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Moon phases in pastel'] = 'The tattoo: moon phases in pastel. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel comet'] = 'The tattoo: pastel comet. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Cloud with a rainbow'] = 'The tattoo: cloud with a rainbow. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Pastel constellation'] = 'The tattoo: pastel constellation. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Pastel galaxy swirl'] = 'The tattoo: pastel galaxy swirl. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pastel bunny with a flower crown'] = 'The tattoo: pastel bunny with a flower crown. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Sleepy cat on a cloud'] = 'The tattoo: sleepy cat on a cloud. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Pastel whale with bubbles'] = 'The tattoo: pastel whale with bubbles. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Baby fox curled up'] = 'The tattoo: baby fox curled up. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Pastel axolotl'] = 'The tattoo: pastel axolotl. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Little bear holding a balloon'] = 'The tattoo: little bear holding a balloon. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Pastel jellyfish'] = 'The tattoo: pastel jellyfish. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pastel snail with a swirl shell'] = 'The tattoo: pastel snail with a swirl shell. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Bunny riding a moon'] = 'The tattoo: bunny riding a moon. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Pastel penguin'] = 'The tattoo: pastel penguin. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel butterfly'] = 'The tattoo: pastel butterfly. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pastel moth with soft wings'] = 'The tattoo: pastel moth with soft wings. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pair of fairy wings'] = 'The tattoo: pair of fairy wings. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Butterfly with gradient wings'] = 'The tattoo: butterfly with gradient wings. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Angel wings in pastel'] = 'The tattoo: angel wings in pastel. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Pastel dragonfly'] = 'The tattoo: pastel dragonfly. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Butterfly on a crescent moon'] = 'The tattoo: butterfly on a crescent moon. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Heart with butterfly wings'] = 'The tattoo: heart with butterfly wings. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pastel bee'] = 'The tattoo: pastel bee. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Swallowtail butterfly in pastel'] = 'The tattoo: swallowtail butterfly in pastel. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel crystal cluster'] = 'The tattoo: pastel crystal cluster. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Magic wand with sparkles'] = 'The tattoo: magic wand with sparkles. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Pastel crystal ball'] = 'The tattoo: pastel crystal ball. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Floating gem with sparkles'] = 'The tattoo: floating gem with sparkles. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Pastel potion bottle'] = 'The tattoo: pastel potion bottle. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Unicorn horn in pastel'] = 'The tattoo: unicorn horn in pastel. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pastel tarot sun card'] = 'The tattoo: pastel tarot sun card. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Magic mirror in pastel'] = 'The tattoo: magic mirror in pastel. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel hourglass with stars'] = 'The tattoo: pastel hourglass with stars. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Pastel crown'] = 'The tattoo: pastel crown. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pastel skull with a bow'] = 'The tattoo: pastel skull with a bow. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Pastel bat'] = 'The tattoo: pastel bat. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel ghost'] = 'The tattoo: pastel ghost. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Pastel coffin with stars'] = 'The tattoo: pastel coffin with stars. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Pastel spider with a heart'] = 'The tattoo: pastel spider with a heart. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Pastel heart with a dagger'] = 'The tattoo: pastel heart with a dagger. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pastel eyeball with lashes'] = 'The tattoo: pastel eyeball with lashes. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Pastel candle with a moon'] = 'The tattoo: pastel candle with a moon. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel black cat'] = 'The tattoo: pastel black cat. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Pastel snake around a heart'] = 'The tattoo: pastel snake around a heart. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Pastel ice cream cone'] = 'The tattoo: pastel ice cream cone. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Pastel macarons'] = 'The tattoo: pastel macarons. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Pastel cupcake with a cherry'] = 'The tattoo: pastel cupcake with a cherry. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pastel donut with sprinkles'] = 'The tattoo: pastel donut with sprinkles. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pastel milkshake'] = 'The tattoo: pastel milkshake. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Pastel lollipop'] = 'The tattoo: pastel lollipop. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel cake slice'] = 'The tattoo: pastel cake slice. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Pastel bubble tea'] = 'The tattoo: pastel bubble tea. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pastel cotton candy'] = 'The tattoo: pastel cotton candy. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pastel strawberry'] = 'The tattoo: pastel strawberry. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pastel seashell'] = 'The tattoo: pastel seashell. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Pastel mermaid tail'] = 'The tattoo: pastel mermaid tail. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Pastel wave'] = 'The tattoo: pastel wave. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Pastel seahorse'] = 'The tattoo: pastel seahorse. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pastel starfish'] = 'The tattoo: pastel starfish. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Pastel pearl in a shell'] = 'The tattoo: pastel pearl in a shell. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel koi fish'] = 'The tattoo: pastel koi fish. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Pastel turtle'] = 'The tattoo: pastel turtle. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Pastel coral'] = 'The tattoo: pastel coral. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Pastel narwhal'] = 'The tattoo: pastel narwhal. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Pastel heart with sparkles'] = 'The tattoo: pastel heart with sparkles. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pastel rainbow'] = 'The tattoo: pastel rainbow. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pastel cloud'] = 'The tattoo: pastel cloud. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Pastel lightning bolt'] = 'The tattoo: pastel lightning bolt. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pastel key'] = 'The tattoo: pastel key. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Pastel lock with a heart'] = 'The tattoo: pastel lock with a heart. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pastel eye with lashes'] = 'The tattoo: pastel eye with lashes. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pastel yin yang'] = 'The tattoo: pastel yin yang. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Pastel smiley'] = 'The tattoo: pastel smiley. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Pastel star'] = 'The tattoo: pastel star. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny pastel heart'] = 'The tattoo: tiny pastel heart. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small pastel moon'] = 'The tattoo: small pastel moon. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny pastel star'] = 'The tattoo: tiny pastel star. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small pastel cloud'] = 'The tattoo: small pastel cloud. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny pastel butterfly'] = 'The tattoo: tiny pastel butterfly. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small pastel rainbow'] = 'The tattoo: small pastel rainbow. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny pastel bunny'] = 'The tattoo: tiny pastel bunny. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small pastel crystal'] = 'The tattoo: small pastel crystal. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny pastel shell'] = 'The tattoo: tiny pastel shell. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small pastel ghost'] = 'The tattoo: small pastel ghost. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Pastel celestial back piece'] = 'The tattoo: pastel celestial back piece. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Pastel butterflies half sleeve'] = 'The tattoo: pastel butterflies half sleeve. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt'
$b['Pastel ocean thigh piece'] = 'The tattoo: pastel ocean thigh piece. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Pastel dreamscape leg sleeve'] = 'The tattoo: pastel dreamscape leg sleeve. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his whole leg, wearing shorts'
$b['Pastel moon and clouds forearm piece'] = 'The tattoo: pastel moon and clouds forearm piece. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Pastel crystals calf piece'] = 'The tattoo: pastel crystals calf piece. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Pastel fairy wings shoulder piece'] = 'The tattoo: pastel fairy wings shoulder piece. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Pastel galaxy spine piece'] = 'The tattoo: pastel galaxy spine piece. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is down his spine, shirtless, seen from behind'
$b['Pastel magic sleeve'] = 'The tattoo: pastel magic sleeve. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Pastel goth chest piece'] = 'The tattoo: pastel goth chest piece. Pastel tattoo, soft dreamy pastel colours like baby pink lavender mint baby blue and peach, delicate black outlines with smooth soft colour fills and gentle gradients, cute light airy feel, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his chest, shirtless'
$sets = [ordered]@{}
$sets['Pastel Style Celestial'] = @('Pastel crescent moon with stars','Sleeping moon in clouds','Pastel planet with rings','Pastel sun and moon','Shooting star with a soft trail','Moon phases in pastel','Pastel comet','Cloud with a rainbow','Pastel constellation','Pastel galaxy swirl')
$sets['Pastel Style Cute Animals'] = @('Pastel bunny with a flower crown','Sleepy cat on a cloud','Pastel whale with bubbles','Baby fox curled up','Pastel axolotl','Little bear holding a balloon','Pastel jellyfish','Pastel snail with a swirl shell','Bunny riding a moon','Pastel penguin')
$sets['Pastel Style Butterflies and Wings'] = @('Pastel butterfly','Pastel moth with soft wings','Pair of fairy wings','Butterfly with gradient wings','Angel wings in pastel','Pastel dragonfly','Butterfly on a crescent moon','Heart with butterfly wings','Pastel bee','Swallowtail butterfly in pastel')
$sets['Pastel Style Crystals and Magic'] = @('Pastel crystal cluster','Magic wand with sparkles','Pastel crystal ball','Floating gem with sparkles','Pastel potion bottle','Unicorn horn in pastel','Pastel tarot sun card','Magic mirror in pastel','Pastel hourglass with stars','Pastel crown')
$sets['Pastel Style Pastel Goth'] = @('Pastel skull with a bow','Pastel bat','Pastel ghost','Pastel coffin with stars','Pastel spider with a heart','Pastel heart with a dagger','Pastel eyeball with lashes','Pastel candle with a moon','Pastel black cat','Pastel snake around a heart')
$sets['Pastel Style Sweets'] = @('Pastel ice cream cone','Pastel macarons','Pastel cupcake with a cherry','Pastel donut with sprinkles','Pastel milkshake','Pastel lollipop','Pastel cake slice','Pastel bubble tea','Pastel cotton candy','Pastel strawberry')
$sets['Pastel Style Ocean'] = @('Pastel seashell','Pastel mermaid tail','Pastel wave','Pastel seahorse','Pastel starfish','Pastel pearl in a shell','Pastel koi fish','Pastel turtle','Pastel coral','Pastel narwhal')
$sets['Pastel Style Hearts and Symbols'] = @('Pastel heart with sparkles','Pastel rainbow','Pastel cloud','Pastel lightning bolt','Pastel key','Pastel lock with a heart','Pastel eye with lashes','Pastel yin yang','Pastel smiley','Pastel star')
$sets['Pastel Style Small'] = @('Tiny pastel heart','Small pastel moon','Tiny pastel star','Small pastel cloud','Tiny pastel butterfly','Small pastel rainbow','Tiny pastel bunny','Small pastel crystal','Tiny pastel shell','Small pastel ghost')
$sets['Pastel Style Large Pieces'] = @('Pastel celestial back piece','Pastel butterflies half sleeve','Pastel ocean thigh piece','Pastel dreamscape leg sleeve','Pastel moon and clouds forearm piece','Pastel crystals calf piece','Pastel fairy wings shoulder piece','Pastel galaxy spine piece','Pastel magic sleeve','Pastel goth chest piece')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Pastel Style" } else { $n } }
"== Pastel before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:pastel" --remote 2>$null | Out-Null
RUN "CATEGORY Pastel :: Pastel Style Celestial, Pastel Style Cute Animals, Pastel Style Butterflies and Wings, Pastel Style Crystals and Magic, Pastel Style Pastel Goth, Pastel Style Sweets, Pastel Style Ocean, Pastel Style Hearts and Symbols, Pastel Style Small, Pastel Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Pastel Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Pastel Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Sleeping moon in clouds"))
}
}
