RUN "SETKV shape:patchwork-looks 3:2"
RUN "SETKV split:patchwork-looks yes"
RUN "SETKV shape:patchwork-life-stories 3:2"
RUN "SETKV split:patchwork-life-stories yes"
RUN "SETKV shape:patchwork-growth 3:2"
RUN "SETKV split:patchwork-growth yes"
RUN "SETKV shape:patchwork-wild-cards 3:2"
RUN "SETKV split:patchwork-wild-cards yes"
Start-Sleep -Seconds 60
RUN "REDO Classic American Patchwork, Black American Traditional, Fine-Line Patchwork, Micro Realism Patchwork, Blackwork Patchwork"
RUN "REDO Red Ink Patchwork Collection, Doodle Patchwork Collection, Ignorant-Style Patchwork, Y2K Patchwork Collection, Dark Gothic Patchwork Collection"
RUN "REDO Botanical Patchwork, Ornamental Patchwork, Engraving Patchwork, Cute Patchwork, Colorful Sticker Patchwork"
RUN "REDO Western Patchwork, Japanese-Inspired Patchwork, Ocean Patchwork Collection, Celestial Patchwork Collection, Animal Kingdom Patchwork Collection"
RUN "REDO Mythology Patchwork Collection, Surreal Patchwork, Minimal Patchwork, Bold And Delicate Patchwork, Black And Color Patchwork"
RUN "REDO Floral And Dark Patchwork, Vintage Patchwork, Abstract Patchwork, Mixed-Artist Patchwork, Beautiful Chaos"
RUN "REDO My Children Patchwork, My Family, Mom, Dad, Grandma"
RUN "REDO Grandpa, People I Love, People I've Lost, My Dogs, My Pets"
RUN "REDO My Childhood, My Travels, Places I've Lived, My California, My Italy"
RUN "REDO My Beach Life, My Music, My Movies, My Books, My Sports"
RUN "REDO My Work, Things I've Built, Things I've Survived, My Milestones, Love Story"
RUN "REDO My Favorite Things, Things That Make Me Laugh, My Weird Stuff, Things I Never Want To Forget, My Whole Life Story"
RUN "REDO Just Starting - Three Pieces, Just Starting - Five Small Pieces, First Anchor, Two Anchors And Small Pieces, Building Around An Old Tattoo"
RUN "REDO Five Years Of Collecting, Different Artists, Big And Medium And Tiny, All Small, One Giant Anchor And Satellites"
RUN "REDO No Filler, Light Filler, Intentional Negative Space, Tight Sticker Patchwork, Full Arm - Still Breathing"
RUN "REDO Forearm Only, Upper Arm Only, Shoulder Downward Growth, Wrist Upward Growth, Patchwork Leg - Starting"
RUN "REDO Patchwork Leg - Developed, Thigh Patchwork, Back Patchwork, Chest Patchwork, Torso Collection"
RUN "REDO Grandma And Punk Rock, Cowboy In Space, Family And Stupid Little Jokes, Ancient And Future, Heaven And Hell"
RUN "REDO Pretty And Dangerous, Nature And Technology, Beach And Gothic, Fancy And Trashy, Childhood And Adult Life"
RUN "REDO Love And Chaos, Sweet And Creepy, Old World And Modern Life, Everything I Love But None Of It Matches, My Life - Collected Over 20 Years"
Start-Sleep -Seconds 30
RUN "SHEET Patchwork Looks"
RUN "SHEET Patchwork Life Stories"
RUN "SHEET Patchwork Growth"
RUN "SHEET Patchwork Wild Cards"
RUN "SHEET Patchwork"
RUN "BROWSE"
RUN "BROWSE"
RUN "BROWSE"
