cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Animals & Pets")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Animals & Pets sets today - the animal sets stay, the first 10 pet sets are swapped for the new 10 =="
"  " + (@($tt.subjects."Animals & Pets") -join ", ")
$kinds = 'Pets in Landscapes','Pets in Flower Fields','Pets at Night','Pets Transformed','Dark and Ornamental Pets','Decorative Pets','Enchanted Pets','Pets in Sun and Water','Pet Characters','Funny Pet Situations'
$kh = $kinds | ? { $tk.ContainsKey((& $slug $_)) }
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
$sets = [ordered]@{}
$sets['Pets in Landscapes'] = @('Husky beneath the northern lights in a snowy landscape','German Shepherd standing in pine forest with mountains behind it','Golden Retriever sitting at the end of a wooden dock at sunset','Australian Shepherd beneath a mountain waterfall','Saint Bernard crossing an alpine landscape','Labrador running through ocean surf at sunset','Border Collie standing beneath dramatic storm clouds in open countryside','Bernese Mountain Dog beside an alpine lake surrounded by wildflowers','German Shepherd reflected in a mountain lake','Border Collie leaping across a stream in a mountain landscape')
$sets['Pets in Flower Fields'] = @('Golden Retriever walking through waist-high sunflowers','Australian Shepherd running through lavender with butterflies','Black Labrador bursting through wildflowers carrying its favorite ball','Calico cat surrounded by colorful wildflowers','German Shepherd surrounded by poppies and wheat','Dachshund walking through oversized wildflowers','Corgi running through a field of daisies','Black Labrador surrounded by magnolia blossoms','Calico cat sleeping beneath hanging wisteria','Siamese cat beneath falling cherry blossoms')
$sets['Pets at Night'] = @('Maine Coon walking through a moonlit snowy forest','Black cat sitting among enormous moonlit lilies','Black cat curled inside a crescent moon surrounded by stars','Black cat watching glowing fireflies in a dark garden','Labrador curled beside a campfire beneath the stars','Husky walking through a forest beneath a huge full moon','Great Dane standing beneath a star-filled night sky','Ragdoll cat sleeping among clouds beneath hanging stars','German Shepherd walking through a field where flowers gradually become stars','Doberman framed by red spider lilies and a crescent moon')
$sets['Pets Transformed'] = @('Dalmatian with spots gradually becoming stars and planets','Bengal cat whose markings dissolve into tropical flowers','Husky with mountain landscape flowing through its silhouette','Dalmatian whose spots transform into butterflies','Calico cat with coat patches transforming into flowers','Australian Shepherd with colorful landscape flowing through its fur','Dalmatian with colorful flowers growing from selected spots','Golden Retriever walking through a landscape that gradually dissolves into watercolor and flowers','Golden Retriever emerging through watercolor wildflowers','Doberman with butterflies emerging from its shadow')
$sets['Dark and Ornamental Pets'] = @('Doberman surrounded by deep red roses and ornamental gold details','Rottweiler emerging through dark peonies and foliage','Doberman standing beneath a black sun with crimson flowers','Rottweiler surrounded by ornamental chains and roses','Rottweiler standing among ruined Gothic arches and roses','Maine Coon sitting inside a Gothic cathedral window','Doberman emerging from geometric architectural shapes','Doberman and black cat posed together inside a dark ornamental composition','Maine Coon surrounded by moths and forest ferns','Persian cat surrounded by pearls and roses and jeweled ornament')
$sets['Decorative Pets'] = @('Sphynx cat surrounded by Egyptian jewelry and celestial ornament','Great Dane beneath an elegant Art Deco arch','Greyhound running through sweeping Art Deco shapes','Tuxedo cat beneath an elegant chandelier','Siamese cat framed by Art Nouveau irises','Sphynx cat inside an ornate jeweled scarab composition','Australian Shepherd surrounded by blue and purple botanical ornament','Husky surrounded by icy blue botanical patterns and snowflakes','Bengal cat emerging through dense tropical foliage','Bengal cat disappearing halfway into psychedelic foliage')
$sets['Enchanted Pets'] = @('Maine Coon wizard surrounded by mushrooms and glowing plants','Maine Coon sitting among giant mushrooms in an enchanted forest','Black cat sitting inside a glowing crystal ball','Bengal cat walking through a surreal jungle of giant flowers','Ragdoll cat floating among clouds and wildflowers','Corgi astronaut floating through space with tennis balls','Corgi and Maine Coon having tea on the moon','Orange tabby being abducted by a tiny UFO','Chihuahua as tiny angel with ridiculously enormous wings','Border Collie running through tall grass as birds explode upward')
$sets['Pets in Sun and Water'] = @('Golden Retriever swimming underwater toward a tennis ball','Orange tabby stretched in a sunny window surrounded by houseplants','Golden Retriever lying beneath a tree with sunlight breaking through leaves','Siamese cat watching koi beneath a garden pond','Two Labradors swimming together above and below the waterline','Golden Retriever looking through an open car window with coastline reflected in the glass','Golden Retriever walking along a beach with pawprints behind it','Black cat staring into a pond filled with colorful koi','Corgi standing in autumn leaves with monarch butterflies','Golden Retriever surrounded by monarch butterflies and warm autumn leaves')
$sets['Pet Characters'] = @('Chihuahua as a furious little medieval king','Maine Coon dressed as a giant Viking','Pug as exhausted office worker surrounded by paperwork','Persian cat as overdressed Victorian aristocrat','Sphynx cat as tattooed punk rocker','Tuxedo cat playing piano in a tiny jazz club','Orange tabby chef making ramen','Saint Bernard bartender wearing its classic barrel collar','Chihuahua wearing enormous cowboy hat','French Bulldog wearing Hawaiian shirt and holding a cocktail')
$sets['Funny Pet Situations'] = @('Dachshund stretched into a black limousine arriving on a red carpet','English Bulldog driving a tiny vintage convertible','French Bulldog riding a Vespa through Paris','Orange tabby cowboy riding a Roomba','Orange tabby stealing an entire roast chicken','Great Dane squeezed onto a ridiculously tiny skateboard','Dachshund dressed like a hot dog at a backyard barbecue','Scottish Fold hiding inside a cowboy boot','Golden Retriever carrying an absurdly enormous stick through the woods','Golden Retriever and tuxedo cat sitting together beneath a flowering tree')
$renamed = @()
foreach ($k in @($sets.Keys)) { $sets[$k] = @($sets[$k] | % { $n = $_; if ($tk.ContainsKey((& $slug $n))) { $r = "$n in Pet Style"; $renamed += "  RENAMED: $n  ->  $r  (the first was under " + $tk[(& $slug $n)] + ")"; $r } else { $n } }) }
if ($renamed) { $renamed } else { "  no clashes" }
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:animals-pets" ", imaginative contemporary pet tattoo artwork, featuring a recognizable naturally proportioned dog or cat with convincing animal anatomy, fur, markings and breed characteristics while placing the animal into beautiful, artistic, unusual or playful compositions; freely range between detailed illustrative tattoo art, painterly color, black and grey, botanical compositions, landscapes, decorative tattoo art, bold tattoo flash, Art Nouveau, ornamental influences, surrealism, fantasy, psychedelic art and occasional humorous illustration depending on the concept; the animal does not need to be a portrait or headshot and may be shown full-body, moving, interacting with its environment or incorporated into a larger composition; favor beautiful visual storytelling and creative tattoo design, allowing humor when the concept calls for it without automatically turning the animal into a cartoon character; use rich color when appropriate and monochrome when stronger, no micro-realistic portrait style, tattoo artwork alone, never worn on skin or a body, complete design filling the frame, isolated on a clean plain white background, no watermark, no letters, no words" --remote
$newK = @('Pets in Landscapes','Pets in Flower Fields','Pets at Night','Pets Transformed','Dark and Ornamental Pets','Decorative Pets','Enchanted Pets','Pets in Sun and Water','Pet Characters','Funny Pet Situations')
$oldPets = @('Pets Dressed Up','Pets on Adventures','Pets Up to Mischief','Magic Pets','Dreamy Pets','Glam Pets','Retro Flash Pets','Edgy and Elegant Pets','Psychedelic and Floral Pets','Pets in Everyday Life')
RUN ("CATEGORY Animals & Pets :: " + ((@($mineK | ? { ($newK -notcontains $_) -and ($oldPets -notcontains $_) }) + $newK) -join ", "))
foreach ($k in $sets.Keys) { RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) }
RUN "FACE Golden Retriever walking through waist-high sunflowers"
}
}