cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Pop of Colour")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Pop of Colour Style Animals','Pop of Colour Style Portraits','Pop of Colour Style Skulls and Dark','Pop of Colour Style Hearts and Symbols','Pop of Colour Style Nature','Pop of Colour Style Objects','Pop of Colour Style Mythical','Pop of Colour Style Celestial','Pop of Colour Style Small','Pop of Colour Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Black and grey wolf with blue eyes'] = 'The tattoo: black and grey wolf with blue eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black and grey lion with golden eyes'] = 'The tattoo: black and grey lion with golden eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black and grey tiger with green eyes'] = 'The tattoo: black and grey tiger with green eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black and grey owl with amber eyes'] = 'The tattoo: black and grey owl with amber eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black and grey fox with an orange tail tip'] = 'The tattoo: black and grey fox with an orange tail tip. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Black and grey snake with a red tongue'] = 'The tattoo: black and grey snake with a red tongue. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and grey raven with a red berry'] = 'The tattoo: black and grey raven with a red berry. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black and grey cat with yellow eyes'] = 'The tattoo: black and grey cat with yellow eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Black and grey hummingbird with a turquoise throat'] = 'The tattoo: black and grey hummingbird with a turquoise throat. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black and grey koi with one orange fin'] = 'The tattoo: black and grey koi with one orange fin. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woman portrait with red lips'] = 'The tattoo: woman portrait with red lips. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woman with violet eyes'] = 'The tattoo: woman with violet eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Greek statue with a gold leaf crown'] = 'The tattoo: greek statue with a gold leaf crown. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Woman with a red flower in her hair'] = 'The tattoo: woman with a red flower in her hair. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Praying hands with a red rosary'] = 'The tattoo: praying hands with a red rosary. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woman with a blue tear'] = 'The tattoo: woman with a blue tear. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Lady face with pink blush'] = 'The tattoo: lady face with pink blush. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Statue with a red blindfold'] = 'The tattoo: statue with a red blindfold. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woman with a gold earring'] = 'The tattoo: woman with a gold earring. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Girl with a red bow'] = 'The tattoo: girl with a red bow. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and grey skull with a red rose'] = 'The tattoo: black and grey skull with a red rose. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Skull with glowing blue eyes'] = 'The tattoo: skull with glowing blue eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Grim reaper with a red hourglass'] = 'The tattoo: grim reaper with a red hourglass. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Skull with a gold tooth'] = 'The tattoo: skull with a gold tooth. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Raven skull with a purple gem'] = 'The tattoo: raven skull with a purple gem. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Dagger through a skull with red drips'] = 'The tattoo: dagger through a skull with red drips. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Skull with a yellow candle flame'] = 'The tattoo: skull with a yellow candle flame. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Skull and snake with green eyes'] = 'The tattoo: skull and snake with green eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Hourglass with red sand'] = 'The tattoo: hourglass with red sand. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Coffin with a red heart'] = 'The tattoo: coffin with a red heart. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Anatomical heart with red arteries'] = 'The tattoo: anatomical heart with red arteries. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Black and grey eye with a blue iris'] = 'The tattoo: black and grey eye with a blue iris. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Compass with a red needle'] = 'The tattoo: compass with a red needle. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Key with a red ribbon'] = 'The tattoo: key with a red ribbon. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Crown with a blue jewel'] = 'The tattoo: crown with a blue jewel. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Hand holding a red apple'] = 'The tattoo: hand holding a red apple. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Lock with a gold keyhole'] = 'The tattoo: lock with a gold keyhole. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Dagger with a red gem hilt'] = 'The tattoo: dagger with a red gem hilt. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pocket watch with a gold face'] = 'The tattoo: pocket watch with a gold face. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Anchor with a red rope'] = 'The tattoo: anchor with a red rope. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black and grey butterfly with blue wings'] = 'The tattoo: black and grey butterfly with blue wings. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Black and grey moth with orange eyespots'] = 'The tattoo: black and grey moth with orange eyespots. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and grey mountain with a red sun'] = 'The tattoo: black and grey mountain with a red sun. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black and grey moon with a purple glow'] = 'The tattoo: black and grey moon with a purple glow. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Black and grey forest with a red bird'] = 'The tattoo: black and grey forest with a red bird. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black and grey wave with a turquoise crest'] = 'The tattoo: black and grey wave with a turquoise crest. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black and grey jellyfish with pink glow'] = 'The tattoo: black and grey jellyfish with pink glow. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black and grey beetle with a green shell'] = 'The tattoo: black and grey beetle with a green shell. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and grey mushroom with a red cap'] = 'The tattoo: black and grey mushroom with a red cap. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black and grey ladybug in red'] = 'The tattoo: black and grey ladybug in red. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Black and grey camera with a red lens'] = 'The tattoo: black and grey camera with a red lens. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black and grey lantern with an orange flame'] = 'The tattoo: black and grey lantern with an orange flame. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Black and grey teacup with pink steam'] = 'The tattoo: black and grey teacup with pink steam. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black and grey bottle with a blue potion'] = 'The tattoo: black and grey bottle with a blue potion. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black and grey record player with a gold record'] = 'The tattoo: black and grey record player with a gold record. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Black and grey balloon in red'] = 'The tattoo: black and grey balloon in red. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and grey paper boat in yellow'] = 'The tattoo: black and grey paper boat in yellow. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black and grey umbrella in red'] = 'The tattoo: black and grey umbrella in red. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black and grey kite in blue'] = 'The tattoo: black and grey kite in blue. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black and grey match with a flame'] = 'The tattoo: black and grey match with a flame. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black and grey dragon with red eyes'] = 'The tattoo: black and grey dragon with red eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Black and grey phoenix with orange fire'] = 'The tattoo: black and grey phoenix with orange fire. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Black and grey angel with a gold halo'] = 'The tattoo: black and grey angel with a gold halo. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black and grey mermaid with a teal tail'] = 'The tattoo: black and grey mermaid with a teal tail. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black and grey Medusa with green eyes'] = 'The tattoo: black and grey medusa with green eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black and grey unicorn with a gold horn'] = 'The tattoo: black and grey unicorn with a gold horn. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and grey kitsune with blue flames'] = 'The tattoo: black and grey kitsune with blue flames. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Black and grey griffin with gold wings'] = 'The tattoo: black and grey griffin with gold wings. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Black and grey devil with red horns'] = 'The tattoo: black and grey devil with red horns. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Black and grey fairy with pink wings'] = 'The tattoo: black and grey fairy with pink wings. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Black and grey sun with gold rays'] = 'The tattoo: black and grey sun with gold rays. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black and grey eclipse with a red ring'] = 'The tattoo: black and grey eclipse with a red ring. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black and grey planet with blue rings'] = 'The tattoo: black and grey planet with blue rings. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Black and grey comet with a purple tail'] = 'The tattoo: black and grey comet with a purple tail. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Black and grey moon with a red star'] = 'The tattoo: black and grey moon with a red star. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black and grey constellation with gold stars'] = 'The tattoo: black and grey constellation with gold stars. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Black and grey galaxy with a pink core'] = 'The tattoo: black and grey galaxy with a pink core. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Black and grey hand holding a gold star'] = 'The tattoo: black and grey hand holding a gold star. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Black and grey astronaut with a gold visor'] = 'The tattoo: black and grey astronaut with a gold visor. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Black and grey crescent with a blue jewel'] = 'The tattoo: black and grey crescent with a blue jewel. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny black and grey heart in red'] = 'The tattoo: tiny black and grey heart in red. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small black and grey eye with blue'] = 'The tattoo: small black and grey eye with blue. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny black and grey star in gold'] = 'The tattoo: tiny black and grey star in gold. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small black and grey cherry in red'] = 'The tattoo: small black and grey cherry in red. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny black and grey moon in purple'] = 'The tattoo: tiny black and grey moon in purple. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small black and grey key in gold'] = 'The tattoo: small black and grey key in gold. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny black and grey bee in yellow'] = 'The tattoo: tiny black and grey bee in yellow. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small black and grey drop in red'] = 'The tattoo: small black and grey drop in red. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny black and grey leaf in green'] = 'The tattoo: tiny black and grey leaf in green. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small black and grey flame in orange'] = 'The tattoo: small black and grey flame in orange. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Black and grey wolf half sleeve with blue eyes'] = 'The tattoo: black and grey wolf half sleeve with blue eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Black and grey dragon back piece with red eyes'] = 'The tattoo: black and grey dragon back piece with red eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his back, shirtless, seen from behind'
$b['Black and grey portrait thigh piece with red lips'] = 'The tattoo: black and grey portrait thigh piece with red lips. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Black and grey phoenix leg sleeve with orange fire'] = 'The tattoo: black and grey phoenix leg sleeve with orange fire. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering his whole leg, wearing shorts'
$b['Black and grey tiger forearm piece with green eyes'] = 'The tattoo: black and grey tiger forearm piece with green eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Black and grey skull calf piece with a red rose'] = 'The tattoo: black and grey skull calf piece with a red rose. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on the back of his calf, wearing shorts'
$b['Black and grey angel shoulder piece with a gold halo'] = 'The tattoo: black and grey angel shoulder piece with a gold halo. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Black and grey snake spine piece with red eyes'] = 'The tattoo: black and grey snake spine piece with red eyes. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is down his spine, shirtless, seen from behind'
$b['Black and grey ocean sleeve with turquoise waves'] = 'The tattoo: black and grey ocean sleeve with turquoise waves. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top'
$b['Black and grey heart chest piece with red arteries'] = 'The tattoo: black and grey heart chest piece with red arteries. Pop of colour tattoo, the whole design in smooth black and grey realism shading, with only one small part in a single bright colour as a striking accent, everything else stays black and grey, high contrast, designed like work from a top modern tattoo artist, no letters, no words, no brand names, no logos. In the right panel it is across his chest, shirtless'
$sets = [ordered]@{}
$sets['Pop of Colour Style Animals'] = @('Black and grey wolf with blue eyes','Black and grey lion with golden eyes','Black and grey tiger with green eyes','Black and grey owl with amber eyes','Black and grey fox with an orange tail tip','Black and grey snake with a red tongue','Black and grey raven with a red berry','Black and grey cat with yellow eyes','Black and grey hummingbird with a turquoise throat','Black and grey koi with one orange fin')
$sets['Pop of Colour Style Portraits'] = @('Woman portrait with red lips','Woman with violet eyes','Greek statue with a gold leaf crown','Woman with a red flower in her hair','Praying hands with a red rosary','Woman with a blue tear','Lady face with pink blush','Statue with a red blindfold','Woman with a gold earring','Girl with a red bow')
$sets['Pop of Colour Style Skulls and Dark'] = @('Black and grey skull with a red rose','Skull with glowing blue eyes','Grim reaper with a red hourglass','Skull with a gold tooth','Raven skull with a purple gem','Dagger through a skull with red drips','Skull with a yellow candle flame','Skull and snake with green eyes','Hourglass with red sand','Coffin with a red heart')
$sets['Pop of Colour Style Hearts and Symbols'] = @('Anatomical heart with red arteries','Black and grey eye with a blue iris','Compass with a red needle','Key with a red ribbon','Crown with a blue jewel','Hand holding a red apple','Lock with a gold keyhole','Dagger with a red gem hilt','Pocket watch with a gold face','Anchor with a red rope')
$sets['Pop of Colour Style Nature'] = @('Black and grey butterfly with blue wings','Black and grey moth with orange eyespots','Black and grey mountain with a red sun','Black and grey moon with a purple glow','Black and grey forest with a red bird','Black and grey wave with a turquoise crest','Black and grey jellyfish with pink glow','Black and grey beetle with a green shell','Black and grey mushroom with a red cap','Black and grey ladybug in red')
$sets['Pop of Colour Style Objects'] = @('Black and grey camera with a red lens','Black and grey lantern with an orange flame','Black and grey teacup with pink steam','Black and grey bottle with a blue potion','Black and grey record player with a gold record','Black and grey balloon in red','Black and grey paper boat in yellow','Black and grey umbrella in red','Black and grey kite in blue','Black and grey match with a flame')
$sets['Pop of Colour Style Mythical'] = @('Black and grey dragon with red eyes','Black and grey phoenix with orange fire','Black and grey angel with a gold halo','Black and grey mermaid with a teal tail','Black and grey Medusa with green eyes','Black and grey unicorn with a gold horn','Black and grey kitsune with blue flames','Black and grey griffin with gold wings','Black and grey devil with red horns','Black and grey fairy with pink wings')
$sets['Pop of Colour Style Celestial'] = @('Black and grey sun with gold rays','Black and grey eclipse with a red ring','Black and grey planet with blue rings','Black and grey comet with a purple tail','Black and grey moon with a red star','Black and grey constellation with gold stars','Black and grey galaxy with a pink core','Black and grey hand holding a gold star','Black and grey astronaut with a gold visor','Black and grey crescent with a blue jewel')
$sets['Pop of Colour Style Small'] = @('Tiny black and grey heart in red','Small black and grey eye with blue','Tiny black and grey star in gold','Small black and grey cherry in red','Tiny black and grey moon in purple','Small black and grey key in gold','Tiny black and grey bee in yellow','Small black and grey drop in red','Tiny black and grey leaf in green','Small black and grey flame in orange')
$sets['Pop of Colour Style Large Pieces'] = @('Black and grey wolf half sleeve with blue eyes','Black and grey dragon back piece with red eyes','Black and grey portrait thigh piece with red lips','Black and grey phoenix leg sleeve with orange fire','Black and grey tiger forearm piece with green eyes','Black and grey skull calf piece with a red rose','Black and grey angel shoulder piece with a gold halo','Black and grey snake spine piece with red eyes','Black and grey ocean sleeve with turquoise waves','Black and grey heart chest piece with red arteries')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Pop of Colour Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Pop of Colour Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Pop of Colour Style$','') -ne 'Black and grey wolf with blue eyes' })
}
"== drawing " + $all.Count + " Pop of Colour split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK Pop of Colour"
RUN "SHEET Pop of Colour"
}
