cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."1970s Horror Poster")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Swamp creature rising from the bog'] = 'The tattoo: swamp creature rising from the bog. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Giant spider looming over a town'] = 'The tattoo: giant spider looming over a town. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Werewolf howling at a red moon'] = 'The tattoo: werewolf howling at a red moon. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Lizard man in the jungle'] = 'The tattoo: lizard man in the jungle. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Sea monster grabbing a boat'] = 'The tattoo: sea monster grabbing a boat. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Hairy beast in the woods'] = 'The tattoo: hairy beast in the woods. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Creature emerging from a black lagoon'] = 'The tattoo: creature emerging from a black lagoon. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Giant bat over a castle'] = 'The tattoo: giant bat over a castle. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Mutant crab on the beach'] = 'The tattoo: mutant crab on the beach. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Yeti in a blizzard'] = 'The tattoo: yeti in a blizzard. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Haunted mansion with one lit window'] = 'The tattoo: haunted mansion with one lit window. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Crooked house on a hill under lightning'] = 'The tattoo: crooked house on a hill under lightning. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Ghost in an attic window'] = 'The tattoo: ghost in an attic window. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Haunted lighthouse in a storm'] = 'The tattoo: haunted lighthouse in a storm. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Abandoned motel at night'] = 'The tattoo: abandoned motel at night. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Possessed doll in a nursery'] = 'The tattoo: possessed doll in a nursery. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Ghost bride on a staircase'] = 'The tattoo: ghost bride on a staircase. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Haunted carousel in fog'] = 'The tattoo: haunted carousel in fog. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Old church with glowing eyes'] = 'The tattoo: old church with glowing eyes. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Cabin in the woods with a full moon'] = 'The tattoo: cabin in the woods with a full moon. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Witch in a hooded cloak with a candle'] = 'The tattoo: witch in a hooded cloak with a candle. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Coven circle around a fire'] = 'The tattoo: coven circle around a fire. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Goat-headed figure in the woods'] = 'The tattoo: goat-headed figure in the woods. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Witch on a broom across a red moon'] = 'The tattoo: witch on a broom across a red moon. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Robed cult figures in a forest'] = 'The tattoo: robed cult figures in a forest. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Witch with a black cat familiar'] = 'The tattoo: witch with a black cat familiar. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Fortune teller with a skull'] = 'The tattoo: fortune teller with a skull. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Ritual mask on an altar'] = 'The tattoo: ritual mask on an altar. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Witch emerging from smoke'] = 'The tattoo: witch emerging from smoke. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Crone stirring a bubbling cauldron'] = 'The tattoo: crone stirring a bubbling cauldron. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Vampire countess with a goblet'] = 'The tattoo: vampire countess with a goblet. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Vampire rising from a coffin'] = 'The tattoo: vampire rising from a coffin. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Vampire with a cape over a castle'] = 'The tattoo: vampire with a cape over a castle. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Vampire bat transforming into a man'] = 'The tattoo: vampire bat transforming into a man. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Vampire bride in a nightgown'] = 'The tattoo: vampire bride in a nightgown. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Fangs under a blood red moon'] = 'The tattoo: fangs under a blood red moon. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Vampire hunter with a stake and crossbow'] = 'The tattoo: vampire hunter with a stake and crossbow. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Vampire at a candlelit feast'] = 'The tattoo: vampire at a candlelit feast. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Vampire lord on a throne'] = 'The tattoo: vampire lord on a throne. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Vampire kiss in moonlight'] = 'The tattoo: vampire kiss in moonlight. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Zombie hands rising from a graveyard'] = 'The tattoo: zombie hands rising from a graveyard. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Ghoul peeking over a tombstone'] = 'The tattoo: ghoul peeking over a tombstone. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Zombie walking out of fog'] = 'The tattoo: zombie walking out of fog. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Mummy shambling from a tomb'] = 'The tattoo: mummy shambling from a tomb. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Skeleton army marching'] = 'The tattoo: skeleton army marching. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Zombie in a drive-in'] = 'The tattoo: zombie in a drive-in. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Ghoul with lantern eyes'] = 'The tattoo: ghoul with lantern eyes. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Corpse bride in a swamp'] = 'The tattoo: corpse bride in a swamp. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Zombie dog at the cemetery gate'] = 'The tattoo: zombie dog at the cemetery gate. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Crypt keeper with a candle'] = 'The tattoo: crypt keeper with a candle. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Flying saucer abducting a cow'] = 'The tattoo: flying saucer abducting a cow. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Alien with a huge brain'] = 'The tattoo: alien with a huge brain. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Giant ant attacking a city'] = 'The tattoo: giant ant attacking a city. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Blob swallowing a diner'] = 'The tattoo: blob swallowing a diner. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Robot with glowing eyes carrying a woman'] = 'The tattoo: robot with glowing eyes carrying a woman. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Alien pod hatching'] = 'The tattoo: alien pod hatching. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Space astronaut with a cracked helmet and a creature'] = 'The tattoo: space astronaut with a cracked helmet and a creature. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Brain in a jar with tentacles'] = 'The tattoo: brain in a jar with tentacles. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Mutant plant eating a car'] = 'The tattoo: mutant plant eating a car. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Radioactive lizard on a skyline'] = 'The tattoo: radioactive lizard on a skyline. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Scream queen in a red dress'] = 'The tattoo: scream queen in a red dress. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Woman with a candelabra in a dark hall'] = 'The tattoo: woman with a candelabra in a dark hall. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Final girl with a flashlight'] = 'The tattoo: final girl with a flashlight. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woman screaming in a shower of shadows'] = 'The tattoo: woman screaming in a shower of shadows. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woman fleeing through the woods'] = 'The tattoo: woman fleeing through the woods. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woman in a nightgown holding a lantern'] = 'The tattoo: woman in a nightgown holding a lantern. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woman behind a cracked mirror'] = 'The tattoo: woman behind a cracked mirror. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woman with a knife and a smirk'] = 'The tattoo: woman with a knife and a smirk. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Woman in a veil with glowing eyes'] = 'The tattoo: woman in a veil with glowing eyes. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Woman on a staircase under lightning'] = 'The tattoo: woman on a staircase under lightning. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Masked figure in a doorway'] = 'The tattoo: masked figure in a doorway. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cracked white mask on a skull'] = 'The tattoo: cracked white mask on a skull. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Hooded figure with a lantern'] = 'The tattoo: hooded figure with a lantern. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Killer clown face'] = 'The tattoo: killer clown face. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Figure with a burlap sack mask'] = 'The tattoo: figure with a burlap sack mask. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Shadow on a wall holding an axe'] = 'The tattoo: shadow on a wall holding an axe. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Masked figure in a cornfield'] = 'The tattoo: masked figure in a cornfield. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Porcelain mask in the dark'] = 'The tattoo: porcelain mask in the dark. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Silhouette in a window'] = 'The tattoo: silhouette in a window. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Figure with glowing eyes behind trees'] = 'The tattoo: figure with glowing eyes behind trees. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny skull with candles'] = 'The tattoo: tiny skull with candles. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small red moon with a bat'] = 'The tattoo: small red moon with a bat. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Little haunted house'] = 'The tattoo: little haunted house. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small eyeball with veins'] = 'The tattoo: small eyeball with veins. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny coffin'] = 'The tattoo: tiny coffin. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small claw hand'] = 'The tattoo: small claw hand. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny ghost'] = 'The tattoo: tiny ghost. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small dagger with a drip'] = 'The tattoo: small dagger with a drip. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Little black cat'] = 'The tattoo: little black cat. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny tombstone with a hand'] = 'The tattoo: tiny tombstone with a hand. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Monster movie collage back piece'] = 'The tattoo: monster movie collage back piece. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Vampire castle sleeve'] = 'The tattoo: vampire castle sleeve. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Swamp creature chest piece'] = 'The tattoo: swamp creature chest piece. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Haunted house thigh piece'] = 'The tattoo: haunted house thigh piece. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the side of his thigh, wearing shorts'
$b['Werewolf moon forearm piece'] = 'The tattoo: werewolf moon forearm piece. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Witch coven spine piece'] = 'The tattoo: witch coven spine piece. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is down his spine, shirtless, seen from behind'
$b['Zombie graveyard half sleeve'] = 'The tattoo: zombie graveyard half sleeve. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Alien invasion calf piece'] = 'The tattoo: alien invasion calf piece. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on the back of his calf, wearing shorts'
$b['Scream queen shoulder piece'] = 'The tattoo: scream queen shoulder piece. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Creature feature leg sleeve'] = 'The tattoo: creature feature leg sleeve. 1970s horror movie poster tattoo art, painted grindhouse illustration, bold dramatic composition, saturated orange, blood red and sickly green against deep black, grainy retro print texture, original characters, spooky and campy rather than gory, designed like work from a top horror tattoo artist, no letters, no words, no title. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['1970s Horror Poster Style Monsters'] = @('Swamp creature rising from the bog','Giant spider looming over a town','Werewolf howling at a red moon','Lizard man in the jungle','Sea monster grabbing a boat','Hairy beast in the woods','Creature emerging from a black lagoon','Giant bat over a castle','Mutant crab on the beach','Yeti in a blizzard')
$sets['1970s Horror Poster Style Haunted Houses'] = @('Haunted mansion with one lit window','Crooked house on a hill under lightning','Ghost in an attic window','Haunted lighthouse in a storm','Abandoned motel at night','Possessed doll in a nursery','Ghost bride on a staircase','Haunted carousel in fog','Old church with glowing eyes','Cabin in the woods with a full moon')
$sets['1970s Horror Poster Style Witches and Cults'] = @('Witch in a hooded cloak with a candle','Coven circle around a fire','Goat-headed figure in the woods','Witch on a broom across a red moon','Robed cult figures in a forest','Witch with a black cat familiar','Fortune teller with a skull','Ritual mask on an altar','Witch emerging from smoke','Crone stirring a bubbling cauldron')
$sets['1970s Horror Poster Style Vampires'] = @('Vampire countess with a goblet','Vampire rising from a coffin','Vampire with a cape over a castle','Vampire bat transforming into a man','Vampire bride in a nightgown','Fangs under a blood red moon','Vampire hunter with a stake and crossbow','Vampire at a candlelit feast','Vampire lord on a throne','Vampire kiss in moonlight')
$sets['1970s Horror Poster Style Zombies and Ghouls'] = @('Zombie hands rising from a graveyard','Ghoul peeking over a tombstone','Zombie walking out of fog','Mummy shambling from a tomb','Skeleton army marching','Zombie in a drive-in','Ghoul with lantern eyes','Corpse bride in a swamp','Zombie dog at the cemetery gate','Crypt keeper with a candle')
$sets['1970s Horror Poster Style Sci-Fi Horror'] = @('Flying saucer abducting a cow','Alien with a huge brain','Giant ant attacking a city','Blob swallowing a diner','Robot with glowing eyes carrying a woman','Alien pod hatching','Space astronaut with a cracked helmet and a creature','Brain in a jar with tentacles','Mutant plant eating a car','Radioactive lizard on a skyline')
$sets['1970s Horror Poster Style Scream Queens'] = @('Scream queen in a red dress','Woman with a candelabra in a dark hall','Final girl with a flashlight','Woman screaming in a shower of shadows','Woman fleeing through the woods','Woman in a nightgown holding a lantern','Woman behind a cracked mirror','Woman with a knife and a smirk','Woman in a veil with glowing eyes','Woman on a staircase under lightning')
$sets['1970s Horror Poster Style Killers and Masks'] = @('Masked figure in a doorway','Cracked white mask on a skull','Hooded figure with a lantern','Killer clown face','Figure with a burlap sack mask','Shadow on a wall holding an axe','Masked figure in a cornfield','Porcelain mask in the dark','Silhouette in a window','Figure with glowing eyes behind trees')
$sets['1970s Horror Poster Style Small'] = @('Tiny skull with candles','Small red moon with a bat','Little haunted house','Small eyeball with veins','Tiny coffin','Small claw hand','Tiny ghost','Small dagger with a drip','Little black cat','Tiny tombstone with a hand')
$sets['1970s Horror Poster Style Large Pieces'] = @('Monster movie collage back piece','Vampire castle sleeve','Swamp creature chest piece','Haunted house thigh piece','Werewolf moon forearm piece','Witch coven spine piece','Zombie graveyard half sleeve','Alien invasion calf piece','Scream queen shoulder piece','Creature feature leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Horror Poster Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Horror Poster Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Horror Poster Style$','') -ne 'Werewolf howling at a red moon' })
}
"== drawing " + $all.Count + " 1970s Horror Poster split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK 1970s Horror Poster"
RUN "SHEET 1970s Horror Poster"
}
