$t = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote
$j = $t | ConvertFrom-Json
$slug = { param($x) ($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-') }
$all = @{}; foreach ($c in $j.subjects.PSObject.Properties) { $all[(& $slug $c.Name)] = "category $($c.Name)"; foreach ($k in $c.Value) { $all[(& $slug $k)] = "kind $k in $($c.Name)"; foreach ($l in @($j.specific.$k)) { if ($l) { $all[(& $slug $l)] = "design $l in $k" } } } }
$new = 'Red Cherries','Red Satin Bow','Red Heart Locket','Red Sacred Heart','Red Anatomical Heart','Red Broken Heart','Red Cupid','Red Kiss','Red Love Letter','Red Hands','Red Swallow','Red Hummingbird','Red Raven','Red Swan','Red Crane','Red Moth','Red Dragonfly','Red Bee','Red Beetle','Red Centipede','Red Panther','Red Wolf','Red Fox','Red Leopard','Red Horse','Red Rabbit','Red Bat','Red Shark','Red Octopus','Red Jellyfish','Red Chrysanthemum','Red Spider Lily','Red Poppy','Red Orchid','Red Wildflowers','Red Botanical Branch','Red Thorns','Red Strawberry','Red Pomegranate','Red Mushroom','Red Crescent Moon','Red Sun','Red Saturn','Red Eclipse','Red Constellation','Red Comet','Red Astronaut','Red Ufo','Red Medusa','Red Angel','Red Fallen Angel','Red Devil','Red Cherub','Red Siren','Red Griffin','Red Cerberus','Red Samurai Mask','Red Oni Mask','Red Hannya Mask','Red Fan','Red Katana','Red Cowboy Boot','Red Cowboy Hat','Red Longhorn Skull','Red Horseshoe','Red Playing Cards','Red Dice','Red Eight Ball','Red Matchbook','Red Martini','Red Perfume Bottle','Red Pocket Watch','Red Camera','Red Vinyl Record','Red Cassette','Red Cyber Heart','Red Cyber Tribal','Red Barbed-Wire Heart','Red Ornamental Cross','Red Surreal Face'
$hits = $new | Where-Object { $all.ContainsKey((& $slug $_)) } | ForEach-Object { "CLASH: $_ -> " + $all[(& $slug $_)] }
if ($hits) { $hits; "STOPPED - nothing saved or drawn" } else {
"no clashes - building"
RUN "LEAVES Red Ink Ideas :: Red Rose, Red Snake, Red Dragon, Red Butterfly, Red Tiger, Red Skull, Red Heart, Red Dagger, Red Koi, Red Phoenix, Red Lotus, Red Peony, Red Spider, Red Scorpion, Red Eye, Red Flame, Red Fine-Line Portrait, Red Ornamental Design, Red Script Lettering, Abstract Red Linework, Red Cherries, Red Satin Bow, Red Heart Locket, Red Sacred Heart, Red Anatomical Heart, Red Broken Heart, Red Cupid, Red Kiss, Red Love Letter, Red Hands, Red Swallow, Red Hummingbird, Red Raven, Red Swan, Red Crane, Red Moth, Red Dragonfly, Red Bee, Red Beetle, Red Centipede, Red Panther, Red Wolf, Red Fox, Red Leopard, Red Horse, Red Rabbit, Red Bat, Red Shark, Red Octopus, Red Jellyfish, Red Chrysanthemum, Red Spider Lily, Red Poppy, Red Orchid, Red Wildflowers, Red Botanical Branch, Red Thorns, Red Strawberry, Red Pomegranate, Red Mushroom, Red Crescent Moon, Red Sun, Red Saturn, Red Eclipse, Red Constellation, Red Comet, Red Astronaut, Red Ufo, Red Medusa, Red Angel, Red Fallen Angel, Red Devil, Red Cherub, Red Siren, Red Griffin, Red Cerberus, Red Samurai Mask, Red Oni Mask, Red Hannya Mask, Red Fan, Red Katana, Red Cowboy Boot, Red Cowboy Hat, Red Longhorn Skull, Red Horseshoe, Red Playing Cards, Red Dice, Red Eight Ball, Red Matchbook, Red Martini, Red Perfume Bottle, Red Pocket Watch, Red Camera, Red Vinyl Record, Red Cassette, Red Cyber Heart, Red Cyber Tribal, Red Barbed-Wire Heart, Red Ornamental Cross, Red Surreal Face"
RUN "SETKV render:red-ink-ideas Red ink tattoo artwork only - every line and every bit of shading in red ink, no black, grey or any other colour in the design - isolated and centred on a solid pure black background, no skin, no body, no words."
RUN "SETKV build:red-cherries two glossy cherries with leaves, bold red tattoo illustration"
RUN "SETKV build:red-satin-bow flowing ribbon bow with long tails and dimensional folds, drawn as a bold traditional red tattoo"
RUN "SETKV build:red-heart-locket vintage heart-shaped locket with ornate detailing, drawn in red engraving linework"
RUN "SETKV build:red-sacred-heart flaming anatomical-inspired sacred heart with rays, drawn as a red illustrative tattoo"
RUN "SETKV build:red-anatomical-heart detailed anatomical heart rendered entirely in red, drawn as an ornamental red tattoo"
RUN "SETKV build:red-broken-heart split heart with expressive cracks and small fragments, drawn with realistic red shading"
RUN "SETKV build:red-cupid small classical cupid drawing a bow, in red ink"
RUN "SETKV build:red-kiss expressive lipstick kiss impression, drawn as a graphic red tattoo"
RUN "SETKV build:red-love-letter envelope with heart seal and letter emerging, drawn in fine delicate red line"
RUN "SETKV build:red-hands two elegant hands almost touching, drawn as a bold traditional red tattoo"
RUN "SETKV build:red-swallow classic flying swallow with sweeping wings, drawn in red engraving linework"
RUN "SETKV build:red-hummingbird detailed hovering hummingbird, drawn as a red illustrative tattoo"
RUN "SETKV build:red-raven dark dramatic raven rendered with red engraving lines"
RUN "SETKV build:red-swan elegant curved-neck swan, drawn with realistic red shading"
RUN "SETKV build:red-crane japanese-inspired flying crane, drawn as a loose red sketch-style tattoo"
RUN "SETKV build:red-moth large detailed moth with ornamental wing markings, in red ink"
RUN "SETKV build:red-dragonfly delicate symmetrical dragonfly, drawn in fine delicate red line"
RUN "SETKV build:red-bee detailed honeybee, drawn as a bold traditional red tattoo"
RUN "SETKV build:red-beetle ornamental scarab and beetle illustration, in red ink"
RUN "SETKV build:red-centipede long curling centipede with graphic movement, in red ink"
RUN "SETKV build:red-panther classic crawling panther rendered entirely in red, drawn as an ornamental red tattoo"
RUN "SETKV build:red-wolf expressive wolf head with strong linework, in red ink"
RUN "SETKV build:red-fox elegant fox head with flowing fur, drawn as a loose red sketch-style tattoo"
RUN "SETKV build:red-leopard leopard head with graphic spots and intense expression, in red ink"
RUN "SETKV build:red-horse running horse with flowing mane, drawn in fine delicate red line"
RUN "SETKV build:red-rabbit detailed rabbit with botanical and illustrative character, in red ink"
RUN "SETKV build:red-bat spread-wing bat with gothic character, in red ink"
RUN "SETKV build:red-shark dynamic shark silhouette with illustrative detail, in red ink"
RUN "SETKV build:red-octopus flowing octopus with curling tentacles, drawn as an ornamental red tattoo"
RUN "SETKV build:red-jellyfish ethereal jellyfish with long flowing tentacles, drawn with realistic red shading"
RUN "SETKV build:red-chrysanthemum large intricate chrysanthemum bloom, drawn as a loose red sketch-style tattoo"
RUN "SETKV build:red-spider-lily fine-line red spider lily with dramatic curling petals"
RUN "SETKV build:red-poppy open poppy bloom with delicate stem, drawn in fine delicate red line"
RUN "SETKV build:red-orchid elegant orchid branch, drawn as a bold traditional red tattoo"
RUN "SETKV build:red-wildflowers loose mixed wildflower bouquet, drawn in red engraving linework"
RUN "SETKV build:red-botanical-branch fine-line leafy botanical branch, in red ink"
RUN "SETKV build:red-thorns twisting thorn branch forming an organic shape, drawn as an ornamental red tattoo"
RUN "SETKV build:red-strawberry detailed strawberry with leaves, drawn with realistic red shading"
RUN "SETKV build:red-pomegranate cut-open pomegranate showing seeds, drawn as a loose red sketch-style tattoo"
RUN "SETKV build:red-mushroom detailed woodland mushroom cluster, drawn as a graphic red tattoo"
RUN "SETKV build:red-crescent-moon ornamental crescent moon, in red ink"
RUN "SETKV build:red-sun graphic radiant sun with expressive rays, in red ink"
RUN "SETKV build:red-saturn detailed Saturn with rings and small stars, drawn in red engraving linework"
RUN "SETKV build:red-eclipse sun and moon eclipse with dramatic rays, drawn as a red illustrative tattoo"
RUN "SETKV build:red-constellation elegant celestial constellation composition, drawn as an ornamental red tattoo"
RUN "SETKV build:red-comet fast-moving comet with long flowing tail, drawn with realistic red shading"
RUN "SETKV build:red-astronaut floating astronaut rendered in red linework"
RUN "SETKV build:red-ufo retro flying saucer with beam beneath it, drawn as a graphic red tattoo"
RUN "SETKV build:red-medusa classical Medusa head with flowing snakes, in red ink"
RUN "SETKV build:red-angel classical angel figure with sweeping wings, in red ink"
RUN "SETKV build:red-fallen-angel seated winged figure with darker dramatic character, drawn in red engraving linework"
RUN "SETKV build:red-devil elegant vintage devil illustration, drawn as a red illustrative tattoo"
RUN "SETKV build:red-cherub classical cherub with clouds, in red ink"
RUN "SETKV build:red-siren mythological siren and mermaid with flowing hair, drawn with realistic red shading"
RUN "SETKV build:red-griffin detailed mythological griffin, drawn as a loose red sketch-style tattoo"
RUN "SETKV build:red-cerberus three-headed mythological dog, drawn as a graphic red tattoo"
RUN "SETKV build:red-samurai-mask detailed warrior mask rendered in red, drawn in fine delicate red line"
RUN "SETKV build:red-oni-mask aggressive Japanese-inspired oni mask, drawn as a bold traditional red tattoo"
RUN "SETKV build:red-hannya-mask expressive theatrical demon mask, drawn in red engraving linework"
RUN "SETKV build:red-fan decorative folding fan with floral detailing, drawn as a red illustrative tattoo"
RUN "SETKV build:red-katana elegant sword with ribbon or botanical accent, drawn as an ornamental red tattoo"
RUN "SETKV build:red-cowboy-boot detailed Western boot with decorative stitching, drawn with realistic red shading"
RUN "SETKV build:red-cowboy-hat classic Western hat with expressive linework, in red ink"
RUN "SETKV build:red-longhorn-skull western cattle skull with decorative details, drawn as a graphic red tattoo"
RUN "SETKV build:red-horseshoe ornamental horseshoe with small decorative accents, in red ink"
RUN "SETKV build:red-playing-cards dramatic pair of playing cards with graphic red treatment"
RUN "SETKV build:red-dice pair of dimensional rolling dice, drawn in red engraving linework"
RUN "SETKV build:red-eight-ball classic billiard ball reinterpreted entirely in red, drawn as a red illustrative tattoo"
RUN "SETKV build:red-matchbook open vintage matchbook with burning match, drawn as an ornamental red tattoo"
RUN "SETKV build:red-martini elegant cocktail glass with olive, drawn with realistic red shading"
RUN "SETKV build:red-perfume-bottle vintage ornate perfume bottle, drawn as a loose red sketch-style tattoo"
RUN "SETKV build:red-pocket-watch detailed antique pocket watch, drawn as a graphic red tattoo"
RUN "SETKV build:red-camera vintage camera with detailed linework, in red ink"
RUN "SETKV build:red-vinyl-record record with stylized label and motion lines, drawn as a bold traditional red tattoo"
RUN "SETKV build:red-cassette retro cassette with loose tape curling outward, drawn in red engraving linework"
RUN "SETKV build:red-cyber-heart chrome and Y2K-inspired heart translated into red linework"
RUN "SETKV build:red-cyber-tribal sharp symmetrical cyber-tribal composition, in red ink"
RUN "SETKV build:red-barbed-wire-heart barbed wire twisted into a heart shape, drawn with realistic red shading"
RUN "SETKV build:red-ornamental-cross highly decorative gothic and ornamental cross, in red ink"
RUN "SETKV build:red-surreal-face fine-line human face dissolving into flowers, smoke, abstract lines or fragmented forms, in red ink"
Start-Sleep -Seconds 60
RUN "LEAVES Red Ink Ideas :: Red Rose, Red Snake, Red Dragon, Red Butterfly, Red Tiger, Red Skull, Red Heart, Red Dagger, Red Koi, Red Phoenix, Red Lotus, Red Peony, Red Spider, Red Scorpion, Red Eye, Red Flame, Red Fine-Line Portrait, Red Ornamental Design, Red Script Lettering, Abstract Red Linework, Red Cherries, Red Satin Bow, Red Heart Locket, Red Sacred Heart, Red Anatomical Heart, Red Broken Heart, Red Cupid, Red Kiss, Red Love Letter, Red Hands, Red Swallow, Red Hummingbird, Red Raven, Red Swan, Red Crane, Red Moth, Red Dragonfly, Red Bee, Red Beetle, Red Centipede, Red Panther, Red Wolf, Red Fox, Red Leopard, Red Horse, Red Rabbit, Red Bat, Red Shark, Red Octopus, Red Jellyfish, Red Chrysanthemum, Red Spider Lily, Red Poppy, Red Orchid, Red Wildflowers, Red Botanical Branch, Red Thorns, Red Strawberry, Red Pomegranate, Red Mushroom, Red Crescent Moon, Red Sun, Red Saturn, Red Eclipse, Red Constellation, Red Comet, Red Astronaut, Red Ufo, Red Medusa, Red Angel, Red Fallen Angel, Red Devil, Red Cherub, Red Siren, Red Griffin, Red Cerberus, Red Samurai Mask, Red Oni Mask, Red Hannya Mask, Red Fan, Red Katana, Red Cowboy Boot, Red Cowboy Hat, Red Longhorn Skull, Red Horseshoe, Red Playing Cards, Red Dice, Red Eight Ball, Red Matchbook, Red Martini, Red Perfume Bottle, Red Pocket Watch, Red Camera, Red Vinyl Record, Red Cassette, Red Cyber Heart, Red Cyber Tribal, Red Barbed-Wire Heart, Red Ornamental Cross, Red Surreal Face"
Start-Sleep -Seconds 60
RUN "LEAVES Red Ink Ideas"
RUN "REDO Red Cherries, Red Satin Bow, Red Heart Locket, Red Sacred Heart, Red Anatomical Heart"
RUN "REDO Red Broken Heart, Red Cupid, Red Kiss, Red Love Letter, Red Hands"
RUN "REDO Red Swallow, Red Hummingbird, Red Raven, Red Swan, Red Crane"
RUN "REDO Red Moth, Red Dragonfly, Red Bee, Red Beetle, Red Centipede"
RUN "REDO Red Panther, Red Wolf, Red Fox, Red Leopard, Red Horse"
RUN "REDO Red Rabbit, Red Bat, Red Shark, Red Octopus, Red Jellyfish"
RUN "REDO Red Chrysanthemum, Red Spider Lily, Red Poppy, Red Orchid, Red Wildflowers"
RUN "REDO Red Botanical Branch, Red Thorns, Red Strawberry, Red Pomegranate, Red Mushroom"
RUN "REDO Red Crescent Moon, Red Sun, Red Saturn, Red Eclipse, Red Constellation"
RUN "REDO Red Comet, Red Astronaut, Red Ufo, Red Medusa, Red Angel"
RUN "REDO Red Fallen Angel, Red Devil, Red Cherub, Red Siren, Red Griffin"
RUN "REDO Red Cerberus, Red Samurai Mask, Red Oni Mask, Red Hannya Mask, Red Fan"
RUN "REDO Red Katana, Red Cowboy Boot, Red Cowboy Hat, Red Longhorn Skull, Red Horseshoe"
RUN "REDO Red Playing Cards, Red Dice, Red Eight Ball, Red Matchbook, Red Martini"
RUN "REDO Red Perfume Bottle, Red Pocket Watch, Red Camera, Red Vinyl Record, Red Cassette"
RUN "REDO Red Cyber Heart, Red Cyber Tribal, Red Barbed-Wire Heart, Red Ornamental Cross, Red Surreal Face"
Start-Sleep -Seconds 30
RUN "SHEET Red Ink Ideas"
RUN "SHEET Red Ink"
RUN "BROWSE"
}
