cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Renaissance")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Renaissance Style Portraits','Renaissance Style Angels and Cherubs','Renaissance Style Classical Sculpture','Renaissance Style Mythology','Renaissance Style Anatomy Studies','Renaissance Style Sacred Art','Renaissance Style Still Life','Renaissance Style Architecture','Renaissance Style Small','Renaissance Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Renaissance noblewoman in profile'] = 'The tattoo: renaissance noblewoman in profile. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Young man with a laurel wreath'] = 'The tattoo: young man with a laurel wreath. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Lady with a pearl headdress'] = 'The tattoo: lady with a pearl headdress. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Scholar with a book'] = 'The tattoo: scholar with a book. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woman with braided hair and veil'] = 'The tattoo: woman with braided hair and veil. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Bearded philosopher'] = 'The tattoo: bearded philosopher. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Noble girl holding a flower'] = 'The tattoo: noble girl holding a flower. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Merchant in a velvet hat'] = 'The tattoo: merchant in a velvet hat. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woman with a lute'] = 'The tattoo: woman with a lute. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Old man in candlelight'] = 'The tattoo: old man in candlelight. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Cherub resting on a cloud'] = 'The tattoo: cherub resting on a cloud. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Two cherubs looking up'] = 'The tattoo: two cherubs looking up. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Angel with a trumpet'] = 'The tattoo: angel with a trumpet. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Archangel with a sword'] = 'The tattoo: archangel with a sword. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Cherub with a bow'] = 'The tattoo: cherub with a bow. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Angel playing a viol'] = 'The tattoo: angel playing a viol. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Weeping angel'] = 'The tattoo: weeping angel. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Angel holding a lantern'] = 'The tattoo: angel holding a lantern. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Cherub with a scroll'] = 'The tattoo: cherub with a scroll. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Angel with spread wings'] = 'The tattoo: angel with spread wings. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Marble statue of a youth in drapery'] = 'The tattoo: marble statue of a youth in drapery. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Statue head of a goddess'] = 'The tattoo: statue head of a goddess. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Bust of a philosopher'] = 'The tattoo: bust of a philosopher. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Marble hand holding a rose'] = 'The tattoo: marble hand holding a rose. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Statue with a broken arm'] = 'The tattoo: statue with a broken arm. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Marble horse head'] = 'The tattoo: marble horse head. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Sculpted torso in drapery'] = 'The tattoo: sculpted torso in drapery. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Statue of a warrior'] = 'The tattoo: statue of a warrior. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Marble lion'] = 'The tattoo: marble lion. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Statue of a dancer'] = 'The tattoo: statue of a dancer. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Goddess rising from a seashell in flowing drapery'] = 'The tattoo: goddess rising from a seashell in flowing drapery. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Mercury with winged helmet'] = 'The tattoo: mercury with winged helmet. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Medusa head'] = 'The tattoo: medusa head. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Diana the huntress with a bow'] = 'The tattoo: diana the huntress with a bow. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Apollo with a lyre'] = 'The tattoo: apollo with a lyre. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cupid and Psyche'] = 'The tattoo: cupid and psyche. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Neptune with a trident'] = 'The tattoo: neptune with a trident. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Pegasus'] = 'The tattoo: pegasus. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Minerva with an owl'] = 'The tattoo: minerva with an owl. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bacchus with grapes'] = 'The tattoo: bacchus with grapes. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Hand study in sepia'] = 'The tattoo: hand study in sepia. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Skull study in sepia'] = 'The tattoo: skull study in sepia. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Anatomical heart drawing'] = 'The tattoo: anatomical heart drawing. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Study of an eye'] = 'The tattoo: study of an eye. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Proportion figure in a circle'] = 'The tattoo: proportion figure in a circle. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Study of a horse'] = 'The tattoo: study of a horse. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Flying machine sketch in sepia'] = 'The tattoo: flying machine sketch in sepia. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Muscle study of an arm'] = 'The tattoo: muscle study of an arm. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Study of hands praying'] = 'The tattoo: study of hands praying. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Profile study of a face'] = 'The tattoo: profile study of a face. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Madonna and child'] = 'The tattoo: madonna and child. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Praying saint'] = 'The tattoo: praying saint. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Hands reaching toward each other'] = 'The tattoo: hands reaching toward each other. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Halo angel portrait'] = 'The tattoo: halo angel portrait. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Saint with a lily'] = 'The tattoo: saint with a lily. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Dove descending in light'] = 'The tattoo: dove descending in light. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Pieta sculpture'] = 'The tattoo: pieta sculpture. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Saint holding a key'] = 'The tattoo: saint holding a key. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Monk in prayer'] = 'The tattoo: monk in prayer. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cathedral light rays'] = 'The tattoo: cathedral light rays. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Skull with an hourglass and candle'] = 'The tattoo: skull with an hourglass and candle. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Bowl of fruit with a fly'] = 'The tattoo: bowl of fruit with a fly. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Wilting flowers in a vase'] = 'The tattoo: wilting flowers in a vase. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Pocket watch and lemon'] = 'The tattoo: pocket watch and lemon. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Goblet and grapes'] = 'The tattoo: goblet and grapes. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Books and a quill'] = 'The tattoo: books and a quill. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Snuffed candle'] = 'The tattoo: snuffed candle. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Shell and pearls'] = 'The tattoo: shell and pearls. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Dead bird on a table'] = 'The tattoo: dead bird on a table. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Bread and wine'] = 'The tattoo: bread and wine. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Domed cathedral'] = 'The tattoo: domed cathedral. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Classical arch with columns'] = 'The tattoo: classical arch with columns. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Ruined temple'] = 'The tattoo: ruined temple. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Bell tower'] = 'The tattoo: bell tower. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Fountain with statues'] = 'The tattoo: fountain with statues. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Venetian gondola'] = 'The tattoo: venetian gondola. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Marble staircase'] = 'The tattoo: marble staircase. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Corinthian column'] = 'The tattoo: corinthian column. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Florence skyline'] = 'The tattoo: florence skyline. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Garden with a statue'] = 'The tattoo: garden with a statue. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny cherub'] = 'The tattoo: tiny cherub. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small marble hand'] = 'The tattoo: small marble hand. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Little laurel wreath'] = 'The tattoo: little laurel wreath. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny anatomical eye'] = 'The tattoo: tiny anatomical eye. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Small Medusa head'] = 'The tattoo: small medusa head. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Tiny winged helmet'] = 'The tattoo: tiny winged helmet. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Small dove in light'] = 'The tattoo: small dove in light. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Tiny statue head'] = 'The tattoo: tiny statue head. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Small quill and book'] = 'The tattoo: small quill and book. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny angel wing'] = 'The tattoo: tiny angel wing. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Sistine ceiling back piece'] = 'The tattoo: sistine ceiling back piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Angels and clouds sleeve'] = 'The tattoo: angels and clouds sleeve. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Draped statue chest piece'] = 'The tattoo: draped statue chest piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Goddess on a seashell thigh piece'] = 'The tattoo: goddess on a seashell thigh piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Hands reaching forearm piece'] = 'The tattoo: hands reaching forearm piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Column and vine spine piece'] = 'The tattoo: column and vine spine piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Mythology half sleeve'] = 'The tattoo: mythology half sleeve. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Statue with drapery calf piece'] = 'The tattoo: statue with drapery calf piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Cherub shoulder piece'] = 'The tattoo: cherub shoulder piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Classical sculpture leg sleeve'] = 'The tattoo: classical sculpture leg sleeve. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia, ochre and soft flesh, classical beauty and graceful anatomy, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Renaissance Style Portraits'] = @('Renaissance noblewoman in profile','Young man with a laurel wreath','Lady with a pearl headdress','Scholar with a book','Woman with braided hair and veil','Bearded philosopher','Noble girl holding a flower','Merchant in a velvet hat','Woman with a lute','Old man in candlelight')
$sets['Renaissance Style Angels and Cherubs'] = @('Cherub resting on a cloud','Two cherubs looking up','Angel with a trumpet','Archangel with a sword','Cherub with a bow','Angel playing a viol','Weeping angel','Angel holding a lantern','Cherub with a scroll','Angel with spread wings')
$sets['Renaissance Style Classical Sculpture'] = @('Marble statue of a youth in drapery','Statue head of a goddess','Bust of a philosopher','Marble hand holding a rose','Statue with a broken arm','Marble horse head','Sculpted torso in drapery','Statue of a warrior','Marble lion','Statue of a dancer')
$sets['Renaissance Style Mythology'] = @('Goddess rising from a seashell in flowing drapery','Mercury with winged helmet','Medusa head','Diana the huntress with a bow','Apollo with a lyre','Cupid and Psyche','Neptune with a trident','Pegasus','Minerva with an owl','Bacchus with grapes')
$sets['Renaissance Style Anatomy Studies'] = @('Hand study in sepia','Skull study in sepia','Anatomical heart drawing','Study of an eye','Proportion figure in a circle','Study of a horse','Flying machine sketch in sepia','Muscle study of an arm','Study of hands praying','Profile study of a face')
$sets['Renaissance Style Sacred Art'] = @('Madonna and child','Praying saint','Hands reaching toward each other','Halo angel portrait','Saint with a lily','Dove descending in light','Pieta sculpture','Saint holding a key','Monk in prayer','Cathedral light rays')
$sets['Renaissance Style Still Life'] = @('Skull with an hourglass and candle','Bowl of fruit with a fly','Wilting flowers in a vase','Pocket watch and lemon','Goblet and grapes','Books and a quill','Snuffed candle','Shell and pearls','Dead bird on a table','Bread and wine')
$sets['Renaissance Style Architecture'] = @('Domed cathedral','Classical arch with columns','Ruined temple','Bell tower','Fountain with statues','Venetian gondola','Marble staircase','Corinthian column','Florence skyline','Garden with a statue')
$sets['Renaissance Style Small'] = @('Tiny cherub','Small marble hand','Little laurel wreath','Tiny anatomical eye','Small Medusa head','Tiny winged helmet','Small dove in light','Tiny statue head','Small quill and book','Tiny angel wing')
$sets['Renaissance Style Large Pieces'] = @('Sistine ceiling back piece','Angels and clouds sleeve','Draped statue chest piece','Goddess on a seashell thigh piece','Hands reaching forearm piece','Column and vine spine piece','Mythology half sleeve','Statue with drapery calf piece','Cherub shoulder piece','Classical sculpture leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Renaissance Style" } else { $n } }
$all = @()
foreach ($k in $sets.Keys) {
  $have = @($tt.specific.$k)
  if ($have.Count -ne $sets[$k].Count) {
    $names = @($sets[$k] | % { & $fix $_ })
    "  REPAIRED " + $k + ": had " + $have.Count + " of " + $names.Count
    RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
    foreach ($leaf in $names) { $base = $leaf -replace ' in Renaissance Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null }
    $have = $names
  }
  $all += @($have | ? { ($_ -replace ' in Renaissance Style$','') -ne 'Cherub resting on a cloud' })
}
"== drawing " + $all.Count + " Renaissance split cards, 5 at a time =="
for ($i = 0; $i -lt $all.Count; $i += 5) { RUN ("REDO " + (($all[$i..([Math]::Min($i+4,$all.Count-1))]) -join ", ")) }
RUN "WALK Renaissance"
RUN "SHEET Renaissance"
}
