cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.specific) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$sw = [ordered]@{}
$bd = @{}
$sw['Two cherubs looking up'] = @('Renaissance Style Angels and Cherubs','Two winged angel heads looking up')
$bd['Two winged angel heads looking up'] = 'The tattoo: two winged angel heads looking up. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$sw['Cherub with a bow'] = @('Renaissance Style Angels and Cherubs','Bow and arrow with angel wings')
$bd['Bow and arrow with angel wings'] = 'The tattoo: bow and arrow with angel wings. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$sw['Angel playing a viol'] = @('Renaissance Style Angels and Cherubs','Robed angel playing a viol')
$bd['Robed angel playing a viol'] = 'The tattoo: robed angel playing a viol. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$sw['Statue with a broken arm'] = @('Renaissance Style Classical Sculpture','Robed marble statue with a broken arm')
$bd['Robed marble statue with a broken arm'] = 'The tattoo: robed marble statue with a broken arm. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$sw['Goddess rising from a seashell in flowing drapery'] = @('Renaissance Style Mythology','Goddess in a long gown standing on a seashell')
$bd['Goddess in a long gown standing on a seashell'] = 'The tattoo: goddess in a long gown standing on a seashell. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$sw['Cupid and Psyche'] = @('Renaissance Style Mythology','Two robed lovers in marble')
$bd['Two robed lovers in marble'] = 'The tattoo: two robed lovers in marble. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$sw['Proportion figure in a circle'] = @('Renaissance Style Anatomy Studies','Compass and circle proportion study')
$bd['Compass and circle proportion study'] = 'The tattoo: compass and circle proportion study. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$sw['Madonna and child'] = @('Renaissance Style Sacred Art','Robed Madonna with a halo')
$bd['Robed Madonna with a halo'] = 'The tattoo: robed madonna with a halo. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$sw['Dove descending in light'] = @('Renaissance Style Sacred Art','Dove descending in light')
$bd['Dove descending in light'] = 'The tattoo: dove descending in light. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$sw['Ruined temple'] = @('Renaissance Style Architecture','Ruined temple')
$bd['Ruined temple'] = 'The tattoo: ruined temple. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$sw['Fountain with statues'] = @('Renaissance Style Architecture','Fountain with statues')
$bd['Fountain with statues'] = 'The tattoo: fountain with statues. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$sw['Sistine ceiling back piece'] = @('Renaissance Style Large Pieces','Two hands reaching back piece')
$bd['Two hands reaching back piece'] = 'The tattoo: two hands reaching back piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$sw['Goddess on a seashell thigh piece'] = @('Renaissance Style Large Pieces','Robed goddess on a seashell thigh piece')
$bd['Robed goddess on a seashell thigh piece'] = 'The tattoo: robed goddess on a seashell thigh piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$sw['Statue with drapery calf piece'] = @('Renaissance Style Large Pieces','Robed marble statue calf piece')
$bd['Robed marble statue calf piece'] = 'The tattoo: robed marble statue calf piece. Renaissance tattoo art inspired by Renaissance oil painting, marble sculpture and sepia master drawings, soft chiaroscuro shading, warm muted tones of sepia and ochre, classical beauty, all figures fully clothed in long robes, designed like work from a top fine art realism tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$sw['Angel falling through storm clouds into the ocean'] = @('Woodcut Big Statement Pieces','Angel flying through storm clouds over the ocean')
$bd['Angel flying through storm clouds over the ocean'] = 'The tattoo: angel flying through storm clouds over the ocean. Authentic woodcut tattoo art inspired by hand-carved relief prints, bold irregular carved lines, chunky directional gouge marks, rough handmade texture, simplified graphic forms, strong solid black shapes and untouched negative space, stark black-and-white contrast, shadows created through coarse carved marks and sparse rough hatching rather than smooth shading or delicate engraving, intentionally imperfect hand-cut appearance, visually like ink pressed from a carved wooden block, dramatic tattoo-friendly composition, black ink only, no grey wash, no fine-line illustration, no polished digital linework, no letters, no words, no watermark. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$kinds = @($sw.Values | % { $_[0] } | Select-Object -Unique)
foreach ($k in $kinds) {
  $cur = @($tt.specific.$k)
  $new = @($cur | % { $n = $_; $hit = $sw.Keys | ? { $sw[$_][0] -eq $k -and ($n -eq $_ -or $n -like ($_ + " in *")) } | Select-Object -First 1; if ($hit) { $sw[$hit][1] } else { $n } })
  if ($new.Count -ne 10) { "  " + $k + " has " + $new.Count + " - skipped" } else { RUN ("LEAVES " + $k + " :: " + ($new -join ", ")) | Out-Null; "  saved " + $k }
}
foreach ($n in $bd.Keys) { RUN ("SETKV build:" + (& $slug $n) + " " + $bd[$n]) | Out-Null }
"  15 builds saved - drawing 3 at a time"
$all = @($bd.Keys)
for ($i = 0; $i -lt $all.Count; $i += 3) { RUN ("REDO " + (($all[$i..([Math]::Min($i+2,$all.Count-1))]) -join ", ")) }
RUN "SHEET Renaissance"
RUN "SHEET Woodcut"
}
