cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Sports")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Sports before (empty = new category) =="
"  " + (@($tt.subjects."Sports") -join ", ")
$kinds = 'Sports Big Moments','Sports Epic Scenes','Sports Memories and Gear','Sports Action and Adventure','Sports Numbers and Jerseys','Sports Legends and Warriors','Sports Animal Athletes','Sports Surreal Gear','Sports Home Field','Sports Funny and Crazy'
$kh = $kinds | ? { $tk.ContainsKey((& $slug $_)) }
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
$sets = [ordered]@{}
$sets['Sports Big Moments'] = @('Basketball hoop on a neighborhood street beneath dramatic city lights','Baseball exploding apart with red stitching turning into roses','Boxer sitting exhausted in the corner between rounds','Soccer goal on a childhood field beneath a huge sunset','Surfer dropping into an enormous curling wave','Vintage football helmet surrounded by lightning','Basketball player flying toward the rim with angel wings','Baseball glove holding a bouquet of wildflowers','Hockey goalie mask covered in Gothic ornament','Skateboarder jumping over a city skyline')
$sets['Sports Epic Scenes'] = @('Championship ring floating above the city where it was won','Basketball net hanging from a crescent moon','Baseball stadium beneath a star-filled summer sky','Female boxer surrounded by roses and broken chains','Soccer ball designed like planet Earth','Golfer walking alone toward the eighteenth green at sunset','Hockey player skating through shattered ice','Football player emerging from storm clouds','Tennis player serving beneath enormous stadium lights','Dirt-bike rider jumping over desert mountains')
$sets['Sports Memories and Gear'] = @('Kids first baseball glove with the year stitched into it','Dad and child walking toward a stadium holding hands','Old neighborhood basketball hoop with weeds growing underneath','Pair of worn boxing gloves hanging from a nail','Soccer cleats covered in mud and wildflowers','Baseball breaking through a stained-glass window','Basketball on fire going through the hoop','Hockey puck cracking through frozen lake ice','Football surrounded by American Traditional roses','Tennis racket with flowers growing through the strings')
$sets['Sports Action and Adventure'] = @('Surfer sitting on board watching enormous moon rise','Skateboard with entire city landscape painted underneath it','Snowboarder flying through a forest of giant pine trees','Skier dropping from a mountain into clouds','Motocross rider jumping through a ring of fire','BMX rider flying over the moon','Rock climber hanging from an impossible floating mountain','Marathon runner following a road disappearing into sunrise','Cyclist climbing a mountain road surrounded by clouds','Wakeboarder jumping through a giant wave shaped like a dragon')
$sets['Sports Numbers and Jerseys'] = @('Basketball jersey hanging alone inside an old locker','Baseball jersey number formed from stadium lights','Football number made from cracked concrete','Soccer jersey number surrounded by hometown flowers','Hockey number frozen inside a block of ice','Athletes number formed from flames','Championship year built into a city skyline','Lucky number designed like vintage varsity lettering','Retired jersey hanging from the clouds','Athletes number surrounded by objects from their entire playing career')
$sets['Sports Legends and Warriors'] = @('Basketball court floating in outer space','Astronaut playing golf on the moon','Skeleton playing basketball','Grim Reaper skateboarding down a handrail','Skeleton surfer riding an enormous wave','Knight in full armor playing hockey','Medieval knight dunking a basketball','Samurai standing in a baseball batters box','Viking playing football with a flaming ball','Cowboy riding a motocross bike instead of a horse')
$sets['Sports Animal Athletes'] = @('Octopus boxing with eight gloves','Bear playing ice hockey','Gorilla hanging from a basketball rim','Alligator playing golf in plaid pants','Frog skateboarding down a giant staircase','Raccoon stealing a championship trophy','Pigeon wearing boxing gloves','Shark wearing a football helmet','Golden Retriever catching a baseball in midair','Black cat sitting inside a basketball hoop')
$sets['Sports Surreal Gear'] = @('Baseball turned into the moon above a city','Basketball splitting open with flowers growing from inside','Soccer ball transforming into a globe of city streets','Football containing a mountain landscape','Hockey mask with an entire frozen forest reflected inside it','Tennis ball leaving a trail of wildflowers','Golf ball sitting on top of planet Earth like a tee','Boxing glove breaking through a marble statue','Skateboard deck becoming a stained-glass cathedral window','Surfboard covered in Japanese waves and koi')
$sets['Sports Home Field'] = @('Stadium rising from inside an anatomical heart','Childhood ball field inside a Polaroid-style frame','Neighborhood court with apartment buildings surrounding it','Empty stadium seat with a ticket and date from a legendary game','Stadium lights emerging from a city map','Hometown skyline wrapped around a basketball','Baseball stitching turning into the street grid of a hometown','Football field disappearing into the horizon','Hockey rink surrounded by hometown architecture','Soccer stadium inside a snow globe')
$sets['Sports Funny and Crazy'] = @('Championship trophy being abducted by a UFO','Skeleton fan screaming from the front row','Grim Reaper holding a giant foam finger','Angel and devil arguing over opposing teams','Baseball player batting away a meteor','Basketball player dunking through Saturns rings','Surfer riding a wave through downtown skyscrapers','Golfer hitting a ball directly into outer space','Boxer fighting their own shadow','Athlete walking from a childhood playground into a giant professional stadium')
$renamed = @()
foreach ($k in @($sets.Keys)) { $sets[$k] = @($sets[$k] | % { $n = $_; if ($tk.ContainsKey((& $slug $n))) { $r = "$n in Sports Style"; $renamed += "  RENAMED: $n  ->  $r  (the first was under " + $tk[(& $slug $n)] + ")"; $r } else { $n } }) }
if ($renamed) { $renamed } else { "  no clashes" }
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:sports" ", imaginative contemporary sports tattoo artwork, explore sport through competition, fandom, personal history, hometown identity, stadium culture, athletic movement, nostalgia, victory, struggle, humor and surreal imagination rather than simply illustrating sporting equipment; freely vary between realistic illustrative tattoo art, American Traditional, Neo-Traditional, black and grey, bold color, graffiti influence, vintage sports graphics, Japanese influence, ornamental work, surrealism, cinematic scenes and playful tattoo flash depending on the concept; use dynamic movement, strong visual storytelling and tattoo-friendly composition; people, equipment, stadiums, numbers, landscapes and symbolic elements may all be used; allow lettering, jersey numbers, dates and meaningful sports-related numbers when they are integral to the concept; tattoo artwork alone, never worn on skin or a body, complete design filling the frame, isolated on a clean plain background, no watermark" --remote
RUN "CATEGORY Sports :: Sports Big Moments, Sports Epic Scenes, Sports Memories and Gear, Sports Action and Adventure, Sports Numbers and Jerseys, Sports Legends and Warriors, Sports Animal Athletes, Sports Surreal Gear, Sports Home Field, Sports Funny and Crazy"
foreach ($k in $sets.Keys) { RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) }
RUN "FACE Baseball exploding apart with red stitching turning into roses"
}
}
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Where I'm From")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Where I'm From before (empty = new category) =="
"  " + (@($tt.subjects."Where I'm From") -join ", ")
$kinds = 'Hometown Lettering','Hometown Landmarks','Hometown Street Life','Hometown Area Codes','Hometown Childhood Places','Hometown Skylines Inside Things','Hometown Local Icons','Hometown Maps and Roots','Hometown Inside Jokes','Hometown Crazy Ideas'
$kh = $kinds | ? { $tk.ContainsKey((& $slug $_)) }
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
$sets = [ordered]@{}
$sets['Hometown Lettering'] = @('NYC in huge Gothic lettering with Manhattan rising through the letters','LA script beneath palm trees and a glowing sunset','212 built from New York skyscrapers','310 surrounded by ocean waves and California palms','415 disappearing into Golden Gate fog','BROOKLYN lettering built from brownstone buildings','CHICAGO lettering beneath an elevated train','305 surrounded by Miami palms and Art Deco neon','ATL emerging through peaches skyline and flames','Hometown ZIP code designed like an old tattoo flash emblem')
$sets['Hometown Landmarks'] = @('Statue of Liberty wearing sunglasses','Golden Gate Bridge disappearing into giant clouds','Los Angeles freeway interchange transformed into ornamental linework','Chicago L train winding around skyscrapers','Miami Art Deco hotel surrounded by flamingos','Seattle Space Needle rising through storm clouds','New Orleans balcony at night surrounded by music notes and flowers','Boston brownstones beneath falling autumn leaves','Detroit muscle car beneath old industrial architecture','Las Vegas neon signs stacked into a giant glowing tower')
$sets['Hometown Street Life'] = @('Brooklyn brownstone stoop with sneakers sitting on the steps','New York bodega glowing at 2 a.m.','LA taco truck beneath palm trees','San Francisco cable car climbing an absurdly steep hill','Chicago neighborhood corner during winter','Miami lifeguard tower beneath giant tropical clouds','New Orleans streetcar surrounded by magnolias','Philadelphia row houses beneath dramatic evening sky','Seattle coffee cup with city reflected in the steam','Honolulu surfboard overlooking Diamond Head')
$sets['Hometown Area Codes'] = @('213 designed like chrome lowrider lettering','718 surrounded by Brooklyn street imagery','312 incorporated into Chicago architecture','404 made from Atlanta highway signs','702 built from Las Vegas neon tubing','617 surrounded by Boston brick and ivy','504 wrapped in New Orleans wrought iron','808 surrounded by waves and hibiscus','313 designed from Detroit automotive chrome','Persons ZIP code printed like an old postage stamp from home')
$sets['Hometown Childhood Places'] = @('Childhood street sign surrounded by flowers','Exact intersection where somebody grew up','Highway exit sign leading home','Childhood house beneath a huge moon','Apartment building where the family grew up','Local corner store turned into beautiful tattoo flash','Neighborhood basketball court beneath city lights','Hometown water tower surrounded by wildflowers','Local diner glowing alone at night','Streetlight and front stoop from childhood')
$sets['Hometown Skylines Inside Things'] = @('Manhattan skyline contained inside an anatomical heart','Los Angeles skyline reflected inside sunglasses','San Francisco inside a snow globe filled with fog','Chicago skyline growing from a deep-dish pizza','Miami skyline inside a flamingo silhouette','Seattle skyline rising from a coffee cup','New Orleans street scene inside a trumpet','Nashville skyline growing from a guitar','Detroit skyline reflected in a chrome wheel','Honolulu landscape inside a breaking wave')
$sets['Hometown Local Icons'] = @('New York subway entrance rendered as American Traditional flash','Los Angeles freeway sign surrounded by roses','San Francisco Victorian house inside an ornate frame','Chicago hot dog rendered like sacred religious iconography','Philadelphia cheesesteak presented like royal treasure','Miami cafecito cup surrounded by tropical ornament','New Orleans crawfish wearing a crown','Texas cowboy boot containing an entire hometown landscape','Seattle umbrella raining tiny Space Needles','Las Vegas slot machine filled with hometown landmarks')
$sets['Hometown Maps and Roots'] = @('City street map becoming human veins','Hometown map folded into an origami heart','City skyline growing from someones roots','Coordinates surrounded by the flowers native to home','Street grid forming a fingerprint','City map forming the shape of a heart','Hometown landscape inside the outline of the state','Road from childhood home leading into city skyline','City streets flowing out of an old Polaroid','Hometown landmarks stacked like a surreal tower')
$sets['Hometown Inside Jokes'] = @('NYC pigeon wearing a tiny gold chain','LA palm tree wearing sunglasses','San Francisco fog portrayed as a giant monster swallowing the bridge','Chicago wind literally blowing buildings sideways','Miami flamingo driving a convertible','New Orleans alligator playing trumpet','Boston lobster riding the subway','Seattle Sasquatch drinking coffee beneath the Space Needle','Las Vegas skeleton hitting a jackpot','Philadelphia cheesesteak running up famous museum steps')
$sets['Hometown Crazy Ideas'] = @('Statue of Liberty skateboarding through Manhattan','Golden Gate Bridge being abducted by a UFO','Hollywood sign surrounded by dinosaurs','Empire State Building turned into a giant rocket','Chicago train circling Saturn','Miami beach scene inside a giant martini glass','New Orleans jazz band made entirely of skeletons','Persons area code floating above their childhood street like a giant neon sign','Childhood house with hometown skyline growing impossibly behind it','Entire life journey from childhood street to hometown skyline flowing through one continuous tattoo composition')
$renamed = @()
foreach ($k in @($sets.Keys)) { $sets[$k] = @($sets[$k] | % { $n = $_; if ($tk.ContainsKey((& $slug $n))) { $r = "$n in Hometown Style"; $renamed += "  RENAMED: $n  ->  $r  (the first was under " + $tk[(& $slug $n)] + ")"; $r } else { $n } }) }
if ($renamed) { $renamed } else { "  no clashes" }
npx wrangler kv key put --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:where-i-m-from" ", imaginative contemporary hometown-pride and place-identity tattoo artwork celebrating where someone is from through cities, neighborhoods, boroughs, towns, streets, area codes, ZIP codes, coordinates, landmarks, architecture, transportation, local food, sports culture, landscapes, memories and inside jokes; freely vary between beautiful illustrative tattoo art, black and grey, American Traditional, Neo-Traditional, Chicano influence, graffiti and street-art influence, Gothic lettering, fine line, realism, vintage travel graphics, postcard imagery, ornamental work, surrealism, colorful tattoo flash and playful absurdity depending on the concept; make each design feel personal, proud and culturally connected rather than like generic tourism artwork; actual city names, neighborhood names, abbreviations, area codes, ZIP codes, street names, coordinates and meaningful place-related lettering ARE allowed and should be rendered as intentional tattoo typography when part of the concept; use strong visual storytelling and surprising combinations; tattoo artwork alone, never worn on skin or a body, complete design filling the frame, isolated on a clean plain background, no watermark" --remote
RUN "CATEGORY Where I'm From :: Hometown Lettering, Hometown Landmarks, Hometown Street Life, Hometown Area Codes, Hometown Childhood Places, Hometown Skylines Inside Things, Hometown Local Icons, Hometown Maps and Roots, Hometown Inside Jokes, Hometown Crazy Ideas"
foreach ($k in $sets.Keys) { RUN ("LEAVES " + $k + " :: " + ($sets[$k] -join ", ")) }
RUN "FACE NYC in huge Gothic lettering with Manhattan rising through the letters"
}
}