cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Surrealism")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Hot air balloon carrying a tiny island'] = 'The tattoo: hot air balloon carrying a tiny island. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Staircase climbing into pink clouds'] = 'The tattoo: staircase climbing into pink clouds. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Door opening onto the ocean in a field'] = 'The tattoo: door opening onto the ocean in a field. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Moon reflected in a teacup'] = 'The tattoo: moon reflected in a teacup. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Giant goldfish swimming through a city'] = 'The tattoo: giant goldfish swimming through a city. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Lighthouse beaming a rainbow'] = 'The tattoo: lighthouse beaming a rainbow. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Waterfall pouring out of a book'] = 'The tattoo: waterfall pouring out of a book. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Desert with a sea inside a frame'] = 'The tattoo: desert with a sea inside a frame. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Tree growing clouds instead of leaves'] = 'The tattoo: tree growing clouds instead of leaves. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Train riding across the sky'] = 'The tattoo: train riding across the sky. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Floating island with a waterfall into the sky'] = 'The tattoo: floating island with a waterfall into the sky. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['House on the back of a whale'] = 'The tattoo: house on the back of a whale. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny planet with one tree'] = 'The tattoo: tiny planet with one tree. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Island inside a lightbulb'] = 'The tattoo: island inside a lightbulb. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['City on top of a cloud'] = 'The tattoo: city on top of a cloud. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Garden inside a snow globe'] = 'The tattoo: garden inside a snow globe. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Mountain floating above a lake'] = 'The tattoo: mountain floating above a lake. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Forest inside a glass bottle'] = 'The tattoo: forest inside a glass bottle. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Ocean wave inside a jar'] = 'The tattoo: ocean wave inside a jar. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['World balanced on a teacup'] = 'The tattoo: world balanced on a teacup. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Melting clock over a branch'] = 'The tattoo: melting clock over a branch. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Umbrella raining flowers'] = 'The tattoo: umbrella raining flowers. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Piano keys turning into birds'] = 'The tattoo: piano keys turning into birds. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Mirror showing a different season'] = 'The tattoo: mirror showing a different season. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Chair with roots'] = 'The tattoo: chair with roots. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Teapot pouring a galaxy'] = 'The tattoo: teapot pouring a galaxy. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Key that opens the sky'] = 'The tattoo: key that opens the sky. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Bicycle with moon wheels'] = 'The tattoo: bicycle with moon wheels. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Paper boat sailing on a cloud'] = 'The tattoo: paper boat sailing on a cloud. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Candle with an ocean flame'] = 'The tattoo: candle with an ocean flame. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Whale flying through clouds'] = 'The tattoo: whale flying through clouds. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Fish swimming in the sky'] = 'The tattoo: fish swimming in the sky. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Elephant on stilt legs'] = 'The tattoo: elephant on stilt legs. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Butterfly with stained-glass city wings'] = 'The tattoo: butterfly with stained-glass city wings. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Turtle carrying a city'] = 'The tattoo: turtle carrying a city. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Owl with a galaxy face'] = 'The tattoo: owl with a galaxy face. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Deer with tree branch antlers in bloom'] = 'The tattoo: deer with tree branch antlers in bloom. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Jellyfish made of light floating over a field'] = 'The tattoo: jellyfish made of light floating over a field. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Cat with a night sky coat'] = 'The tattoo: cat with a night sky coat. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Bird made of leaves'] = 'The tattoo: bird made of leaves. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Face made of flowers'] = 'The tattoo: face made of flowers. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Head opening into a garden'] = 'The tattoo: head opening into a garden. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woman with clouds for hair'] = 'The tattoo: woman with clouds for hair. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Man with a birdcage head'] = 'The tattoo: man with a birdcage head. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Figure made of ocean waves'] = 'The tattoo: figure made of ocean waves. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Profile filled with a sunset'] = 'The tattoo: profile filled with a sunset. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woman wearing the moon as a hat'] = 'The tattoo: woman wearing the moon as a hat. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Hands holding a tiny sun'] = 'The tattoo: hands holding a tiny sun. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Face peeling into butterflies'] = 'The tattoo: face peeling into butterflies. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Silhouette full of stars'] = 'The tattoo: silhouette full of stars. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Rose with a sunset inside its petals'] = 'The tattoo: rose with a sunset inside its petals. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Mushroom with a tiny house inside'] = 'The tattoo: mushroom with a tiny house inside. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Cactus blooming planets'] = 'The tattoo: cactus blooming planets. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Leaf with a river running through it'] = 'The tattoo: leaf with a river running through it. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Sunflower with a clock face'] = 'The tattoo: sunflower with a clock face. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Seashell holding a whole beach'] = 'The tattoo: seashell holding a whole beach. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Apple with a forest core'] = 'The tattoo: apple with a forest core. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Feather turning into a fish'] = 'The tattoo: feather turning into a fish. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Pine cone with a city inside'] = 'The tattoo: pine cone with a city inside. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Cloud raining butterflies'] = 'The tattoo: cloud raining butterflies. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Moon on a fishing line'] = 'The tattoo: moon on a fishing line. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Planet with a swing'] = 'The tattoo: planet with a swing. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Astronaut fishing for stars'] = 'The tattoo: astronaut fishing for stars. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Saturn rings made of flowers'] = 'The tattoo: saturn rings made of flowers. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Sun inside a birdcage'] = 'The tattoo: sun inside a birdcage. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Ladder to the moon'] = 'The tattoo: ladder to the moon. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Comet made of feathers'] = 'The tattoo: comet made of feathers. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Galaxy pouring from a vase'] = 'The tattoo: galaxy pouring from a vase. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Stars in a jar'] = 'The tattoo: stars in a jar. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Moon cracked open like an egg'] = 'The tattoo: moon cracked open like an egg. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Hourglass with a beach inside'] = 'The tattoo: hourglass with a beach inside. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Pocket watch with a sky inside'] = 'The tattoo: pocket watch with a sky inside. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Clock dripping into a puddle of stars'] = 'The tattoo: clock dripping into a puddle of stars. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Calendar pages turning into birds'] = 'The tattoo: calendar pages turning into birds. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Sundial in the clouds'] = 'The tattoo: sundial in the clouds. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Clock face made of flowers'] = 'The tattoo: clock face made of flowers. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Watch gears growing vines'] = 'The tattoo: watch gears growing vines. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Clock melting over a cliff'] = 'The tattoo: clock melting over a cliff. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Hourglass sand turning into a desert'] = 'The tattoo: hourglass sand turning into a desert. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Alarm clock floating in water'] = 'The tattoo: alarm clock floating in water. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny moon in a jar'] = 'The tattoo: tiny moon in a jar. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small floating island'] = 'The tattoo: small floating island. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Little door in a tree'] = 'The tattoo: little door in a tree. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Tiny melting clock'] = 'The tattoo: tiny melting clock. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Small whale in a cloud'] = 'The tattoo: small whale in a cloud. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Little planet with a tree'] = 'The tattoo: little planet with a tree. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny umbrella raining stars'] = 'The tattoo: tiny umbrella raining stars. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small fish in a lightbulb'] = 'The tattoo: small fish in a lightbulb. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny hot air balloon island'] = 'The tattoo: tiny hot air balloon island. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Little eye in a flower'] = 'The tattoo: little eye in a flower. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Floating islands back piece'] = 'The tattoo: floating islands back piece. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Sky ocean sleeve'] = 'The tattoo: sky ocean sleeve. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Dreamscape chest piece'] = 'The tattoo: dreamscape chest piece. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Whale and clouds thigh piece'] = 'The tattoo: whale and clouds thigh piece. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Melting clocks forearm piece'] = 'The tattoo: melting clocks forearm piece. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Moon and ladder spine piece'] = 'The tattoo: moon and ladder spine piece. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Surreal garden half sleeve'] = 'The tattoo: surreal garden half sleeve. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Stairway to the sky calf piece'] = 'The tattoo: stairway to the sky calf piece. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Planets and flowers shoulder piece'] = 'The tattoo: planets and flowers shoulder piece. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Underwater sky leg sleeve'] = 'The tattoo: underwater sky leg sleeve. Surrealism tattoo art, dreamlike impossible scenes and visual twists, soft luminous colour with gentle gradients and painterly realism, light and wonder rather than dread, clean readable composition, designed like work from a top surrealist tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Surrealism Style Dreamscapes'] = @('Hot air balloon carrying a tiny island','Staircase climbing into pink clouds','Door opening onto the ocean in a field','Moon reflected in a teacup','Giant goldfish swimming through a city','Lighthouse beaming a rainbow','Waterfall pouring out of a book','Desert with a sea inside a frame','Tree growing clouds instead of leaves','Train riding across the sky')
$sets['Surrealism Style Floating Worlds'] = @('Floating island with a waterfall into the sky','House on the back of a whale','Tiny planet with one tree','Island inside a lightbulb','City on top of a cloud','Garden inside a snow globe','Mountain floating above a lake','Forest inside a glass bottle','Ocean wave inside a jar','World balanced on a teacup')
$sets['Surrealism Style Impossible Objects'] = @('Melting clock over a branch','Umbrella raining flowers','Piano keys turning into birds','Mirror showing a different season','Chair with roots','Teapot pouring a galaxy','Key that opens the sky','Bicycle with moon wheels','Paper boat sailing on a cloud','Candle with an ocean flame')
$sets['Surrealism Style Animals'] = @('Whale flying through clouds','Fish swimming in the sky','Elephant on stilt legs','Butterfly with stained-glass city wings','Turtle carrying a city','Owl with a galaxy face','Deer with tree branch antlers in bloom','Jellyfish made of light floating over a field','Cat with a night sky coat','Bird made of leaves')
$sets['Surrealism Style Faces and Figures'] = @('Face made of flowers','Head opening into a garden','Woman with clouds for hair','Man with a birdcage head','Figure made of ocean waves','Profile filled with a sunset','Woman wearing the moon as a hat','Hands holding a tiny sun','Face peeling into butterflies','Silhouette full of stars')
$sets['Surrealism Style Nature Mashups'] = @('Rose with a sunset inside its petals','Mushroom with a tiny house inside','Cactus blooming planets','Leaf with a river running through it','Sunflower with a clock face','Seashell holding a whole beach','Apple with a forest core','Feather turning into a fish','Pine cone with a city inside','Cloud raining butterflies')
$sets['Surrealism Style Sky and Space'] = @('Moon on a fishing line','Planet with a swing','Astronaut fishing for stars','Saturn rings made of flowers','Sun inside a birdcage','Ladder to the moon','Comet made of feathers','Galaxy pouring from a vase','Stars in a jar','Moon cracked open like an egg')
$sets['Surrealism Style Time'] = @('Hourglass with a beach inside','Pocket watch with a sky inside','Clock dripping into a puddle of stars','Calendar pages turning into birds','Sundial in the clouds','Clock face made of flowers','Watch gears growing vines','Clock melting over a cliff','Hourglass sand turning into a desert','Alarm clock floating in water')
$sets['Surrealism Style Small'] = @('Tiny moon in a jar','Small floating island','Little door in a tree','Tiny melting clock','Small whale in a cloud','Little planet with a tree','Tiny umbrella raining stars','Small fish in a lightbulb','Tiny hot air balloon island','Little eye in a flower')
$sets['Surrealism Style Large Pieces'] = @('Floating islands back piece','Sky ocean sleeve','Dreamscape chest piece','Whale and clouds thigh piece','Melting clocks forearm piece','Moon and ladder spine piece','Surreal garden half sleeve','Stairway to the sky calf piece','Planets and flowers shoulder piece','Underwater sky leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Surrealism Style" } else { $n } }
"== Surrealism before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:surrealism" --remote 2>$null | Out-Null
RUN "CATEGORY Surrealism :: Surrealism Style Dreamscapes, Surrealism Style Floating Worlds, Surrealism Style Impossible Objects, Surrealism Style Animals, Surrealism Style Faces and Figures, Surrealism Style Nature Mashups, Surrealism Style Sky and Space, Surrealism Style Time, Surrealism Style Small, Surrealism Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Surrealism Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Surrealism Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Whale flying through clouds"))
}
}
