cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$ns = "9c2ba111589e48c6ba5ad1b924ae8809"
function Read-Tree { for ($t = 1; $t -le 4; $t++) { $r = (npx wrangler kv key get --namespace-id $ns "card:tree" --remote 2>$null | Out-String).Trim(); if ($r.StartsWith("{")) { try { $o = $r | ConvertFrom-Json; if ($o.subjects -and $o.specific) { return @{ raw = $r; tree = $o } } } catch {} }; "  read failed (try " + $t + ") - retrying"; Start-Sleep -Seconds 5 }; return $null }
$slug = { param($x) $s = (($x.ToLower() -replace "[^a-z0-9]+","-").Trim("-")); if ($s.Length -gt 70) { $s = $s.Substring(0,70) }; $s }
$got = Read-Tree
if (-not $got) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$tt = $got.tree
$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$backup = Join-Path $env:TEMP ("card-tree-backup-" + $stamp + ".json")
[System.IO.File]::WriteAllText($backup, $got.raw, (New-Object System.Text.UTF8Encoding $false))
"  backup of the catalog saved first: " + $backup
$beforeCats = @($tt.subjects.PSObject.Properties).Count
$cats = [ordered]@{}
$cats['Cars'] = [ordered]@{}
$cats['Cars']['Cars Muscle Cars'] = @('1967 Ford Mustang Fastback black and grey realism aggressive front three-quarter view','1969 Chevrolet Camaro SS emerging through tire smoke','1970 Dodge Challenger RT beneath dramatic storm clouds','1969 Dodge Charger roaring down an empty desert highway','1967 Pontiac GTO head-on chrome grille catching the light','Shelby Cobra with American Traditional flames','Corvette Stingray reflected across wet pavement','Buick Grand National disappearing into black smoke','Plymouth Barracuda with psychedelic 1970s color','Classic Ford Mustang rendered like a vintage racing poster')
$cats['Cars']['Cars Lowriders'] = @('1964 Chevrolet Impala lowrider in black-and-grey Chicano realism','Candy-red Impala hopping on hydraulics','Lowrider Chevrolet Monte Carlo on gold wire wheels','Cadillac lowrider cruising beneath palm trees at sunset','Lowrider viewed extremely low from the front chrome towering overhead','Purple lowrider surrounded by roses and ornamental filigree','Lowrider cruising through neon-lit Los Angeles streets','Classic Impala reflected in polished chrome lettering','Lowrider with elaborate candy paint rendered in rich color realism','Three-wheel-motion lowrider with smoke curling around the tires')
$cats['Cars']['Cars JDM Legends'] = @('Nissan Skyline GT-R R34 drifting through neon rain','Toyota Supra Mk4 with glowing city reflections across the body','Mazda RX-7 FD sliding sideways through tire smoke','Honda NSX racing through a mountain tunnel','Datsun 240Z beneath a huge Japanese rising sun','Toyota AE86 drifting down a mountain pass','Mitsubishi Evo blasting through a wet nighttime street','Subaru WRX STI throwing snow through a rally corner','Nissan Silvia S15 surrounded by graffiti and tire smoke','Honda Civic Type R rendered in aggressive manga-panel style')
$cats['Cars']['Cars Supercars'] = @('Porsche 911 carving through an Alpine switchback','Classic air-cooled Porsche 911 beneath a warm sunset','Porsche 911 GT3 screaming around a racetrack','Ferrari F40 in red-and-black graphic tattoo style','Ferrari Testarossa beneath 1980s Miami neon','Lamborghini Countach in retro airbrush style','Lamborghini Aventador surrounded by shattered-glass geometry','McLaren supercar streaking through abstract watercolor speed','Mercedes AMG emerging through dark architectural shadows','BMW M3 E30 attacking a mountain road')
$cats['Cars']['Cars European Classics'] = @('Aston Martin DB5 in elegant black-and-grey realism','Jaguar E-Type surrounded by Art Nouveau ornament','Classic Mercedes 300SL with its gullwing doors raised','Porsche 356 driving along the California coast','Vintage Ferrari racing through the Italian countryside','Classic Mini Cooper tearing through a rainy London street','Volkswagen Beetle covered in colorful 1960s psychedelic flowers','Volkswagen bus loaded with surfboards beside an ocean sunset','Vintage Fiat 500 squeezed into a beautiful Italian street','Classic Rolls-Royce rendered like dark luxury Gothic artwork')
$cats['Cars']['Cars Race Cars'] = @('Formula racing car at full speed beneath exploding track lights','Le Mans prototype racing through nighttime rain','Vintage Formula One car surrounded by checkered flags','NASCAR-style stock car throwing sparks against the wall','Dragster launching with the rear tires wrinkling under power','Funny car engulfed in flames at the starting line','Rally car airborne over a forest road','Drift car sideways with a giant wall of smoke','Porsche endurance racer glowing beneath Le Mans lights','Race car cockpit reflected inside a drivers helmet visor')
$cats['Cars']['Cars Hot Rods'] = @('1932 Ford hot rod with exposed engine and traditional flames','Chopped Mercury lead sled cruising beneath streetlights','Rat rod with rusty metal texture and exposed mechanical parts','Blown hot rod engine towering through the hood','Flame-painted custom coupe in bold American Traditional style','Slammed vintage pickup with mirror-finish chrome wheels','Custom hot rod rendered in exaggerated New School style','Black hot rod emerging from red smoke','Vintage drag car with hand-painted racing graphics','Chopped custom car beneath a giant desert moon')
$cats['Cars']['Cars Off-Road and Trucks'] = @('Ford Bronco climbing through rocky desert terrain','Toyota Land Cruiser crossing a river beneath mountains','Jeep crawling over impossible boulders','Baja trophy truck flying through desert dust','Lifted pickup blasting through deep mud','Classic Chevrolet pickup in a dramatic Western desert scene','Ford Raptor jumping across desert terrain','Off-road truck beneath a giant star-filled sky','Slammed custom pickup with brilliant candy paint','Monster truck crushing a tiny row of cars in comic-book style')
$cats['Cars']['Cars Engines and Parts'] = @('V8 engine rendered like an anatomical heart','Turbocharger surrounded by Japanese clouds and lightning','Supercharger exploding through flames','Chrome wheel reflecting an entire nighttime city','Piston and connecting rod rendered like sacred mechanical ornament','Racing steering wheel surrounded by speed lines and telemetry graphics','Gearshift and tachometer at redline in black-and-grey realism','Engine bay transformed into biomechanical machinery','Brake rotor glowing red with sparks flying outward','Twin turbochargers arranged like mechanical lungs')
$cats['Cars']['Cars Surreal Dream Cars'] = @('Porsche 911 breaking through a Renaissance painting','Mustang racing alongside a wild horse','Skyline GT-R driving through a cyberpunk city','Lowrider cruising beneath an enormous moon with chrome reflections everywhere','Ferrari exploding out of a stained-glass window','Corvette Stingray surrounded by ocean waves like a Japanese composition','Lamborghini rendered entirely as liquid chrome','Classic muscle car half realistic and half blueprint drawing','Supercar dissolving into speed smoke and geometric fragments','Dream-car garage lineup disappearing into cinematic darkness')
$cats['Motorcycles'] = [ordered]@{}
$cats['Motorcycles']['Motorcycles Harley Davidson'] = @('Harley-Davidson Road Glide head-on sharknose fairing dominating the composition','Harley-Davidson Street Glide cruising through a desert sunset','Harley-Davidson Fat Boy in chrome-heavy black-and-grey realism','Harley-Davidson Sportster beneath a glowing neon motel sign','Harley-Davidson Low Rider leaned aggressively through a mountain curve','Harley-Davidson Breakout with huge rear tire and polished chrome','Vintage Harley Panhead in gritty black-and-grey realism','Vintage Harley Knucklehead rendered as bold American Traditional','Harley Shovelhead surrounded by black smoke and flames','Outrageous custom bagger with candy paint and oversized front wheel')
$cats['Motorcycles']['Motorcycles Choppers'] = @('Long-fork old-school chopper beneath an enormous desert moon','1970s chopper with tall sissy bar and psychedelic paint','Chrome chopper surrounded by American Traditional roses','Murdered-out chopper emerging through dense black smoke','Gothic chopper surrounded by cathedral architecture','Flame-painted chopper screaming across a desert highway','Chrome chopper surrounded by Japanese clouds and peonies','Chopper reflected in a pool of gasoline and rainbow oil','Vintage chopper rendered as rough woodcut artwork','Futuristic chopper rendered entirely in liquid chrome')
$cats['Motorcycles']['Motorcycles Bobbers and Cafe Racers'] = @('Stripped-down bobber with fat tires in brutal blackwork','Vintage bobber beneath an abandoned gas-station sign','Black bobber surrounded by blood-red roses','Bobber side profile using dramatic negative space','Rat-bike bobber with rust and distressed-metal texture','Cafe racer speeding through a rainy city at night','Cafe racer beneath glowing neon signs','Vintage cafe racer rendered like a 1960s racing poster','Black-and-gold cafe racer with ornamental mechanical details','Cafe racer exploding through loose watercolor brush strokes')
$cats['Motorcycles']['Motorcycles Superbikes'] = @('Ducati Panigale leaned impossibly low through a racetrack corner','BMW S1000RR accelerating beneath dramatic track lights','Yamaha R1 racing through nighttime rain','Kawasaki Ninja screaming through a tunnel','Suzuki Hayabusa rendered in hyperreal metallic detail','Honda Fireblade throwing sparks through a corner','Superbike rider fully tucked at extreme speed','Two superbikes fighting side-by-side through a corner','Superbike exploding through shattered geometric fragments','Futuristic superbike surrounded by cyberpunk neon')
$cats['Motorcycles']['Motorcycles Vintage Classics'] = @('Triumph Bonneville carving through the English countryside','Vintage Norton cafe racer in detailed engraving style','Classic BMW boxer motorcycle beneath Alpine mountains','Vintage Honda CB750 with gorgeous exposed engine detail','Classic Indian motorcycle in rich vintage color','Triumph motorcycle surrounded by faded roses and racing graphics','1960s motorcycle rendered like a weathered screen-printed poster','Vintage Grand Prix motorcycle leaned through a historic circuit','Antique motorcycle engine rendered like luxury jewelry','Barn-find motorcycle with rust peeling paint and wildflowers')
$cats['Motorcycles']['Motorcycles Cruisers'] = @('Indian Scout in dramatic black-and-grey realism','Indian Chief surrounded by storm clouds and endless highway','Modern muscle cruiser beneath nighttime city lights','Power cruiser doing a massive burnout','Blacked-out muscle bike surrounded by brutalist black shapes','Polished custom cruiser reflecting fire across its chrome','Cruiser photographed from an extreme ground-level front angle','Cruiser riding through heavy rain with headlight blazing','Sinister black cruiser surrounded by ravens and smoke','Touring motorcycle crossing an endless American desert')
$cats['Motorcycles']['Motorcycles Dirt and Adventure'] = @('Motocross rider flying over an enormous dirt jump','Dirt bike throwing a wall of mud directly toward the viewer','Motocross bike upside down during a huge backflip','Enduro motorcycle climbing an impossible rocky mountain','Adventure motorcycle blasting across a rushing river','Adventure bike beneath enormous snow-covered mountains','Desert rally motorcycle racing through giant dunes','Dirt bike exploding through watercolor splashes of mud','Motocross machine rendered in aggressive graffiti style','Dirt bike jumping through a giant ring of fire')
$cats['Motorcycles']['Motorcycles Trackers and Scramblers'] = @('Flat-track motorcycle sliding completely sideways around a dirt oval','Street tracker beneath industrial city lights','Vintage board-track racer on an old wooden racing circuit','Speedway motorcycle throwing dirt in stark blackwork','Custom tracker surrounded by bold geometric graphics','Scrambler climbing a rocky hillside','Scrambler crossing a shallow forest stream','Triumph-style scrambler beneath enormous mountain scenery','Desert scrambler surrounded by cactus beneath a blazing sun','Urban scrambler ripping through a graffiti-covered alley')
$cats['Motorcycles']['Motorcycles Engines and Parts'] = @('V-twin engine rendered like a mechanical anatomical heart','Motorcycle engine exploded into hundreds of floating mechanical pieces','Chrome exhaust pipes twisting into ornamental filigree','Spoked motorcycle wheel transforming into a sacred geometric mandala','Heavy motorcycle chain wrapped around a skull','Fuel tank covered by an elaborate Japanese dragon composition','Piston surrounded by lightning and fire','Motorcycle headlight glowing like an enormous eye','Handlebars tank and gauges viewed from the riders perspective','Polished chrome V-twin reflecting a tiny highway landscape')
$cats['Motorcycles']['Motorcycles Surreal Bikes'] = @('Harley-style chopper fighting through enormous Japanese ocean waves','Ducati-style superbike smashing through a stained-glass window','Black motorcycle emerging from an enormous Gothic cathedral doorway','Chopper surrounded by giant peonies lightning and black clouds','Cafe racer transitioning from finished motorcycle into loose sketch and blueprint lines','Superbike transformed into biomechanical muscle bone and machinery','Chrome cruiser riding across the surface of the moon','Vintage motorcycle bursting through an ornate tarot-card composition','Black chopper surrounded by flames like a 1980s heavy-metal album cover','Outrageous show bike combining engraved chrome candy paint gold leaf and jeweled mechanical details')
$cats['Sports'] = [ordered]@{}
$cats['Sports']['Sports Big Moments'] = @('Basketball hoop on a neighborhood street beneath dramatic city lights','Baseball exploding apart with red stitching turning into roses','Boxer sitting exhausted in the corner between rounds','Soccer goal on a childhood field beneath a huge sunset','Surfer dropping into an enormous curling wave','Vintage football helmet surrounded by lightning','Basketball player flying toward the rim with angel wings','Baseball glove holding a bouquet of wildflowers','Hockey goalie mask covered in Gothic ornament','Skateboarder jumping over a city skyline')
$cats['Sports']['Sports Epic Scenes'] = @('Championship ring floating above the city where it was won','Basketball net hanging from a crescent moon','Baseball stadium beneath a star-filled summer sky','Female boxer surrounded by roses and broken chains','Soccer ball designed like planet Earth','Golfer walking alone toward the eighteenth green at sunset','Hockey player skating through shattered ice','Football player emerging from storm clouds','Tennis player serving beneath enormous stadium lights','Dirt-bike rider jumping over desert mountains')
$cats['Sports']['Sports Memories and Gear'] = @('Kids first baseball glove with the year stitched into it','Dad and child walking toward a stadium holding hands','Old neighborhood basketball hoop with weeds growing underneath','Pair of worn boxing gloves hanging from a nail','Soccer cleats covered in mud and wildflowers','Baseball breaking through a stained-glass window','Basketball on fire going through the hoop','Hockey puck cracking through frozen lake ice','Football surrounded by American Traditional roses','Tennis racket with flowers growing through the strings')
$cats['Sports']['Sports Action and Adventure'] = @('Surfer sitting on board watching enormous moon rise','Skateboard with entire city landscape painted underneath it','Snowboarder flying through a forest of giant pine trees','Skier dropping from a mountain into clouds','Motocross rider jumping through a ring of fire','BMX rider flying over the moon','Rock climber hanging from an impossible floating mountain','Marathon runner following a road disappearing into sunrise','Cyclist climbing a mountain road surrounded by clouds','Wakeboarder jumping through a giant wave shaped like a dragon')
$cats['Sports']['Sports Numbers and Jerseys'] = @('Basketball jersey hanging alone inside an old locker','Baseball jersey number formed from stadium lights','Football number made from cracked concrete','Soccer jersey number surrounded by hometown flowers','Hockey number frozen inside a block of ice','Athletes number formed from flames','Championship year built into a city skyline','Lucky number designed like vintage varsity lettering','Retired jersey hanging from the clouds','Athletes number surrounded by objects from their entire playing career')
$cats['Sports']['Sports Legends and Warriors'] = @('Basketball court floating in outer space','Astronaut playing golf on the moon','Skeleton playing basketball','Grim Reaper skateboarding down a handrail','Skeleton surfer riding an enormous wave','Knight in full armor playing hockey','Medieval knight dunking a basketball','Samurai standing in a baseball batters box','Viking playing football with a flaming ball','Cowboy riding a motocross bike instead of a horse')
$cats['Sports']['Sports Animal Athletes'] = @('Octopus boxing with eight gloves','Bear playing ice hockey','Gorilla hanging from a basketball rim','Alligator playing golf in plaid pants','Frog skateboarding down a giant staircase','Raccoon stealing a championship trophy','Pigeon wearing boxing gloves','Shark wearing a football helmet','Golden Retriever catching a baseball in midair','Black cat sitting inside a basketball hoop')
$cats['Sports']['Sports Surreal Gear'] = @('Baseball turned into the moon above a city','Basketball splitting open with flowers growing from inside','Soccer ball transforming into a globe of city streets','Football containing a mountain landscape','Hockey mask with an entire frozen forest reflected inside it','Tennis ball leaving a trail of wildflowers','Golf ball sitting on top of planet Earth like a tee','Boxing glove breaking through a marble statue','Skateboard deck becoming a stained-glass cathedral window','Surfboard covered in Japanese waves and koi')
$cats['Sports']['Sports Home Field'] = @('Stadium rising from inside an anatomical heart','Childhood ball field inside a Polaroid-style frame','Neighborhood court with apartment buildings surrounding it','Empty stadium seat with a ticket and date from a legendary game','Stadium lights emerging from a city map','Hometown skyline wrapped around a basketball','Baseball stitching turning into the street grid of a hometown','Football field disappearing into the horizon','Hockey rink surrounded by hometown architecture','Soccer stadium inside a snow globe')
$cats['Sports']['Sports Funny and Crazy'] = @('Championship trophy being abducted by a UFO','Skeleton fan screaming from the front row','Grim Reaper holding a giant foam finger','Angel and devil arguing over opposing teams','Baseball player batting away a meteor','Basketball player dunking through Saturns rings','Surfer riding a wave through downtown skyscrapers','Golfer hitting a ball directly into outer space','Boxer fighting their own shadow','Athlete walking from a childhood playground into a giant professional stadium')
$cats['Where I''m From'] = [ordered]@{}
$cats['Where I''m From']['Hometown Lettering'] = @('NYC in huge Gothic lettering with Manhattan rising through the letters','LA script beneath palm trees and a glowing sunset','212 built from New York skyscrapers','310 surrounded by ocean waves and California palms','415 disappearing into Golden Gate fog','BROOKLYN lettering built from brownstone buildings','CHICAGO lettering beneath an elevated train','305 surrounded by Miami palms and Art Deco neon','ATL emerging through peaches skyline and flames','Hometown ZIP code designed like an old tattoo flash emblem')
$cats['Where I''m From']['Hometown Landmarks'] = @('Statue of Liberty wearing sunglasses','Golden Gate Bridge disappearing into giant clouds','Los Angeles freeway interchange transformed into ornamental linework','Chicago L train winding around skyscrapers','Miami Art Deco hotel surrounded by flamingos','Seattle Space Needle rising through storm clouds','New Orleans balcony at night surrounded by music notes and flowers','Boston brownstones beneath falling autumn leaves','Detroit muscle car beneath old industrial architecture','Las Vegas neon signs stacked into a giant glowing tower')
$cats['Where I''m From']['Hometown Street Life'] = @('Brooklyn brownstone stoop with sneakers sitting on the steps','New York bodega glowing at 2 a.m.','LA taco truck beneath palm trees','San Francisco cable car climbing an absurdly steep hill','Chicago neighborhood corner during winter','Miami lifeguard tower beneath giant tropical clouds','New Orleans streetcar surrounded by magnolias','Philadelphia row houses beneath dramatic evening sky','Seattle coffee cup with city reflected in the steam','Honolulu surfboard overlooking Diamond Head')
$cats['Where I''m From']['Hometown Area Codes'] = @('213 designed like chrome lowrider lettering','718 surrounded by Brooklyn street imagery','312 incorporated into Chicago architecture','404 made from Atlanta highway signs','702 built from Las Vegas neon tubing','617 surrounded by Boston brick and ivy','504 wrapped in New Orleans wrought iron','808 surrounded by waves and hibiscus','313 designed from Detroit automotive chrome','Persons ZIP code printed like an old postage stamp from home')
$cats['Where I''m From']['Hometown Childhood Places'] = @('Childhood street sign surrounded by flowers','Exact intersection where somebody grew up','Highway exit sign leading home','Childhood house beneath a huge moon','Apartment building where the family grew up','Local corner store turned into beautiful tattoo flash','Neighborhood basketball court beneath city lights','Hometown water tower surrounded by wildflowers','Local diner glowing alone at night','Streetlight and front stoop from childhood')
$cats['Where I''m From']['Hometown Skylines Inside Things'] = @('Manhattan skyline contained inside an anatomical heart','Los Angeles skyline reflected inside sunglasses','San Francisco inside a snow globe filled with fog','Chicago skyline growing from a deep-dish pizza','Miami skyline inside a flamingo silhouette','Seattle skyline rising from a coffee cup','New Orleans street scene inside a trumpet','Nashville skyline growing from a guitar','Detroit skyline reflected in a chrome wheel','Honolulu landscape inside a breaking wave')
$cats['Where I''m From']['Hometown Local Icons'] = @('New York subway entrance rendered as American Traditional flash','Los Angeles freeway sign surrounded by roses','San Francisco Victorian house inside an ornate frame','Chicago hot dog rendered like sacred religious iconography','Philadelphia cheesesteak presented like royal treasure','Miami cafecito cup surrounded by tropical ornament','New Orleans crawfish wearing a crown','Texas cowboy boot containing an entire hometown landscape','Seattle umbrella raining tiny Space Needles','Las Vegas slot machine filled with hometown landmarks')
$cats['Where I''m From']['Hometown Maps and Roots'] = @('City street map becoming human veins','Hometown map folded into an origami heart','City skyline growing from someones roots','Coordinates surrounded by the flowers native to home','Street grid forming a fingerprint','City map forming the shape of a heart','Hometown landscape inside the outline of the state','Road from childhood home leading into city skyline','City streets flowing out of an old Polaroid','Hometown landmarks stacked like a surreal tower')
$cats['Where I''m From']['Hometown Inside Jokes'] = @('NYC pigeon wearing a tiny gold chain','LA palm tree wearing sunglasses','San Francisco fog portrayed as a giant monster swallowing the bridge','Chicago wind literally blowing buildings sideways','Miami flamingo driving a convertible','New Orleans alligator playing trumpet','Boston lobster riding the subway','Seattle Sasquatch drinking coffee beneath the Space Needle','Las Vegas skeleton hitting a jackpot','Philadelphia cheesesteak running up famous museum steps')
$cats['Where I''m From']['Hometown Crazy Ideas'] = @('Statue of Liberty skateboarding through Manhattan','Golden Gate Bridge being abducted by a UFO','Hollywood sign surrounded by dinosaurs','Empire State Building turned into a giant rocket','Chicago train circling Saturn','Miami beach scene inside a giant martini glass','New Orleans jazz band made entirely of skeletons','Persons area code floating above their childhood street like a giant neon sign','Childhood house with hometown skyline growing impossibly behind it','Entire life journey from childhood street to hometown skyline flowing through one continuous tattoo composition')
$cats['Memorials'] = [ordered]@{}
$cats['Memorials']['Memorials Everyday Moments'] = @('Moms actual handwritten Love you growing into a flowering stem','Dads old fishing rod leaning against an empty dock at sunrise','Grandmas handwritten recipe surrounded by the ingredients she always used','Grandpas favorite worn cowboy boots with wildflowers growing from them','Loved ones signature beneath their favorite flower','Empty beach chair facing the ocean beneath a beautiful sunset','Their eyeglasses resting across the book they were always reading','Favorite coffee mug with steam transforming into their handwriting','Their old wristwatch stopped at a meaningful time','Favorite hat hanging from a simple wooden hook')
$cats['Memorials']['Memorials Their Belongings'] = @('Moms perfume bottle surrounded by the flowers she loved','Dads toolbox with one tool resting beside it','Grandmas sewing machine with thread becoming flowers','Grandpas pocketknife surrounded by leaves from his favorite place','Loved ones favorite sneakers with the laces becoming angel wings','Their gardening gloves lying among the flowers they grew','Favorite armchair beside a glowing lamp with nobody sitting in it','Their record player playing the album they loved','Favorite cocktail with their signature subtly worked underneath','Their camera surrounded by tiny snapshots of places they loved')
$cats['Memorials']['Memorials Animals and Signs'] = @('A cardinal perched on the persons favorite flowering branch','Hummingbird hovering beside their birth flower','Butterfly emerging from their handwritten name','Dragonfly resting on a meaningful date','Their favorite dog sitting beside an empty pair of shoes','Cat sleeping on the sweater the person always wore','Two birds on a wire with one taking flight','Elephant parent and child walking toward the horizon','Whale and calf swimming beneath stars','Their favorite animal carrying a tiny object associated with them')
$cats['Memorials']['Memorials Handwriting and Voice'] = @('Voicemail waveform transforming into wildflowers','Soundwave of their laugh wrapped around a small heart','Handwritten birthday-card message preserved exactly as written','Signature becoming the horizon of a landscape','Childs handwritten I love you Dad preserved with every imperfect letter','Grandmas handwriting becoming ribbon around a bouquet','Dads signature integrated into the road of a landscape','One sentence from an old letter surrounded by pressed flowers','Their handwriting appearing from an old fountain pen','Two peoples handwriting meeting in the middle of a heart')
$cats['Memorials']['Memorials Places They Loved'] = @('Childhood home with one upstairs window glowing','Family cabin beneath the exact mountain range they loved','Favorite beach with footprints disappearing toward the water','Their hometown street beneath a huge evening sky','Lake where the family always vacationed with an empty boat tied to the dock','Favorite hiking trail disappearing through pine trees','Lighthouse overlooking the coast where their ashes were scattered','Their favorite park bench beneath falling autumn leaves','Road leading toward the place they always called home','Coordinates of a meaningful place hidden within the landscape')
$cats['Memorials']['Memorials Their Passions'] = @('Dads motorcycle parked beneath an enormous sunset','Loved ones dream car beneath the stars','Grandpas tractor surrounded by the fields he worked','Dads fishing boat floating on completely still water','Their surfboard planted upright in the sand beside the ocean','Golf clubs resting beside an empty eighteenth green','Baseball glove holding the persons favorite flower','Old guitar leaning against an empty stool','Drumsticks crossed over a favorite record','Chefs knife surrounded by herbs from the meals they made')
$cats['Memorials']['Memorials Empty Spaces'] = @('One empty place setting at a family dinner table','Two coffee cups with steam rising from only one','Pair of hands slowly releasing one another','Parents hand holding a childs hand from an actual photograph','Silhouette of two people walking together toward the horizon','Porch swing moving beneath a tree with nobody sitting on it','Open doorway filled with warm light','Empty passenger seat during a beautiful road trip','Two footprints becoming one set as they disappear into the distance','A familiar jacket hanging beside the front door')
$cats['Memorials']['Memorials Funny and Loving'] = @('Grandmas martini with exactly three olives and her signature','Dads barbecue tongs surrounded by flames and a tiny halo','Grandpas ridiculous Hawaiian shirt hanging from a clothesline','Moms enormous sunglasses surrounded by flowers','Their favorite beer glass with angel wings and a hilariously tiny halo','Grandpas lawn chair beside a cooler under the stars','Dads remote control resting on his permanently claimed side of the couch','Grandmas rolling pin surrounded by flour flowers and her handwritten recipe','Their favorite ugly coffee mug treated like a sacred religious relic','Loved ones legendary flip-flops sitting at the gates of heaven')
$cats['Memorials']['Memorials Heavenly Humor'] = @('Fisherman skeleton peacefully fishing from a cloud','Skeleton golfer taking one final swing toward the moon','Skeleton biker riding into an enormous sunset','Grandma as a tiny angel still holding her wooden spoon','Dad as an angel unsuccessfully trying to fix something with duct tape','Loved ones favorite pet delivering their halo back to them','Grim Reaper sitting beside them at a peaceful fishing hole','Angel sitting on a barstool raising one final glass','Skeleton gardener proudly watering an absurdly enormous flower','Their favorite animal stealing the angels halo')
$cats['Memorials']['Memorials Their Whole Story'] = @('Their birth flower and death-month flower growing from the same stem','Broken clock overtaken completely by beautiful living flowers','Anatomical heart containing a tiny scene of their favorite place','Tree with roots formed from family names and one branch reaching toward the stars','Constellation built from meaningful dates rather than ordinary stars','Their favorite objects arranged inside an open locket','Polaroid photograph slowly transforming into birds and flowers','A shelf holding five tiny objects that immediately tell their whole story','A road moving through several places from their life before disappearing into the horizon','A beautiful collection of completely ordinary things only their family would recognize keys glasses coffee cup favorite snack handwriting flower and one ridiculous inside joke')
# names already used by OTHER sets - a new design with the same name would be stolen by the old set
$mine = @(); foreach ($c in $cats.Keys) { $mine += @($cats[$c].Keys) }
$taken = @{}; $tt.specific.PSObject.Properties | ? { $mine -notcontains $_.Name } | % { $_.Value | ? { $_ } | % { $taken[(& $slug $_)] = 1 } }
$renamed = 0
foreach ($c in $cats.Keys) {
  $kinds = @($cats[$c].Keys)
  if ($tt.subjects.PSObject.Properties[$c]) { $tt.subjects.$c = $kinds } else { $tt.subjects | Add-Member -NotePropertyName $c -NotePropertyValue $kinds }
  foreach ($k in $kinds) {
    $names = @($cats[$c][$k] | % { if ($taken.ContainsKey((& $slug $_))) { $script:renamed++; "  RENAMED: " + $_ + " in " + $c + " Style" | Out-Host; $_ + " in " + $c + " Style" } else { $_ } })
    if ($tt.specific.PSObject.Properties[$k]) { $tt.specific.$k = $names } else { $tt.specific | Add-Member -NotePropertyName $k -NotePropertyValue $names }
  }
}
$json = $tt | ConvertTo-Json -Depth 20 -Compress
$check = $json | ConvertFrom-Json
$afterCats = @($check.subjects.PSObject.Properties).Count
if ($afterCats -lt $beforeCats -or $json.Length -lt ($got.raw.Length * 0.9)) { "  SAFETY STOP - the new catalog looks smaller than the old one, nothing written" } else {
$tmp = Join-Path $env:TEMP "card-tree-new.json"
[System.IO.File]::WriteAllText($tmp, $json, (New-Object System.Text.UTF8Encoding $false))
npx wrangler kv key put --namespace-id $ns "card:tree" --path $tmp --remote 2>$null | Out-Null
"  catalog written in ONE save: " + $beforeCats + " categories before, " + $afterCats + " after"
npx wrangler kv key put --namespace-id $ns "frame:category:memorials" ", deeply personal contemporary memorial tattoo artwork celebrating the life, personality, memories, relationships and everyday details of someone loved rather than relying only on conventional symbols of death; make the specific object, memory, place, handwriting, animal, activity or relationship described the emotional center of the composition; freely range between beautiful, joyful, nostalgic, peaceful, funny, intimate and occasionally bittersweet imagery according to the concept; freely vary between detailed illustrative tattoo art, black-and-grey realism, color realism, fine line, American Traditional, Neo-Traditional, painterly color, botanical tattooing, ornamental work, sketch, watercolor, surrealism and other appropriate contemporary tattoo treatments; use flowers, birds, halos, wings, dates, clocks, hearts and religious symbolism only when they genuinely strengthen the individual concept rather than automatically adding them to every memorial; preserve handwriting, signatures, dates and meaningful words when specifically requested because they may be the most important part of the tattoo; favor specific human details and visual storytelling over generic RIP imagery; tattoo artwork alone, never worn on skin or a body, complete design filling the frame, isolated on a clean plain background unless an environmental scene is integral to the concept, no watermark" --remote 2>$null | Out-Null
"  waiting 70 seconds so every server sees the new catalog..."
Start-Sleep -Seconds 70
$got2 = Read-Tree
$short = 0
foreach ($c in $cats.Keys) { foreach ($k in $cats[$c].Keys) { $h = @($got2.tree.specific.$k | ? { $_ }).Count; if ($h -ne 10) { "  STILL SHORT: " + $k + " has " + $h; $short++ } } }
if ($short) { "== " + $short + " sets still short - send me this output, nothing started ==" } else {
"== all 50 sets have their 10 designs (Cars, Motorcycles, Sports, Where Im From, Memorials) =="
Start-Process powershell -WorkingDirectory (Get-Location) -ArgumentList '-NoExit','-Command','Get-Content .\draw-cars.ps1 -Raw | Invoke-Expression'
Start-Process powershell -WorkingDirectory (Get-Location) -ArgumentList '-NoExit','-Command','Get-Content .\draw-moto.ps1 -Raw | Invoke-Expression'
"  Cars and Motorcycles started in two new windows. Memorials test:"
RUN "FACE Dads old fishing rod leaning against an empty dock at sunrise"
}
}
}
