cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
RUN "REDO Tribal Spiked Armband, Tribal Wave Wrist Cuff, Tribal Calf Band, Tribal Thigh Garter Band, Tribal Chevron Armband"
RUN "REDO Tribal Ankle Band, Tribal Double Band Forearm, Tribal Upper Arm Band With Drop, Tribal Shark Tooth Band, Tribal Finger Band"
RUN "REDO Tribal Shoulder Cap Swirl, Tribal Chest Plate, Tribal Collarbone Wings, Tribal Shoulder Blade Flame, Tribal Sternum Drop"
RUN "REDO Tribal Shoulder To Bicep Flow, Tribal Shoulder Vine, Tribal Half Chest Shield, Tribal Collarbone Crescent, Tribal Sea Turtle"
RUN "REDO Tribal Manta Ray, Tribal Hammerhead Shark, Tribal Fish Hook, Tribal Ocean Wave Sleeve Piece, Tribal Dolphin Pair"
RUN "REDO Tribal Octopus, Tribal Seashell Spiral, Tribal Shark Teeth Pattern, Tribal Gecko, Tribal Wolf Head"
RUN "REDO Tribal Butterfly, Tribal Eagle Spread Wings, Tribal Scorpion, Tribal Lion Face, Tribal Serpent"
RUN "REDO Tribal Dragon, Tribal Hummingbird, Tribal Tiger Stripes Head, Tribal Swallow Pair, Tribal Sun Burst"
RUN "REDO Tribal Crescent Moon, Tribal Sun And Moon Joined, Tribal Star Burst, Tribal Eclipse, Tribal Sun On The Spine"
RUN "REDO Tribal Compass Star, Tribal Moon Phases Band, Tribal Sun On The Calf, Tribal Shooting Star, Tribal Lower Back Wings"
RUN "REDO Tribal Barbed Wire Armband, Tribal Flame Wrap, Tribal Heart With Points, Tribal Butterfly Y2K, Tribal Neck Flare"
RUN "REDO Tribal Spiked Heart Ankle, Tribal Flame Forearm, Tribal Hip Swirl, Tribal Dagger Points, Tribal Mandala Fusion"
RUN "REDO Tribal Geometric Fusion, Tribal Biomech Fusion, Tribal Floral Fusion, Tribal Dotwork Fusion, Tribal Lace Fusion"
RUN "REDO Tribal Negative Space Panel, Tribal Feather Fusion, Tribal Skull Fusion, Tribal Rose Fusion, Tribal Hand Accent"
RUN "REDO Tribal Behind The Ear, Tribal Wrist Point, Tribal Finger Swirl, Tribal Neck Accent, Tribal Ankle Curl"
RUN "REDO Tribal Small Forearm Mark, Tribal Nape Of Neck, Tribal Finger Points, Tribal Wrist Swirl, Tribal Full Back Piece"
RUN "REDO Tribal Spine Line, Tribal Shoulder Blade Wings, Tribal Spine Vine, Tribal Back Totem, Tribal Upper Back Crown"
RUN "REDO Tribal Spine Blades, Tribal Lower Back Flow, Tribal Side Torso Flow, Tribal Back Butterfly, Tribal Full Sleeve"
RUN "REDO Tribal Half Sleeve Swirls, Tribal Polynesian-Inspired Half Sleeve, Tribal Leg Wrap, Tribal Full Leg Sleeve, Tribal Thigh Piece"
RUN "REDO Tribal Forearm Sleeve, Tribal Full Sleeve Flow, Tribal Calf Sleeve, Tribal Hip To Thigh Piece"
RUN "WALK Tribal"
RUN "SHEET Tribal"
