cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Tribal")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$tt.specific.PSObject.Properties | ? { $mineK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
"== Tribal before (these sets get replaced) =="
"  " + (@($tt.subjects."Tribal") -join ", ")
$new = 'Tribal Bands','Tribal Shoulder and Chest','Tribal Ocean Motifs','Tribal Animals','Tribal Sun Moon and Stars','Tribal Y2K Revival','Tribal Fusion','Tribal Small Pieces','Tribal Spine and Back','Tribal Sleeves and Legs','Tribal Spiked Armband','Tribal Wave Wrist Cuff','Tribal Calf Band','Tribal Thigh Garter Band','Tribal Chevron Armband','Tribal Ankle Band','Tribal Double Band Forearm','Tribal Upper Arm Band With Drop','Tribal Shark Tooth Band','Tribal Finger Band','Tribal Pec And Shoulder Piece','Tribal Shoulder Cap Swirl','Tribal Chest Plate','Tribal Collarbone Wings','Tribal Shoulder Blade Flame','Tribal Sternum Drop','Tribal Shoulder To Bicep Flow','Tribal Shoulder Vine','Tribal Half Chest Shield','Tribal Collarbone Crescent','Tribal Sea Turtle','Tribal Manta Ray','Tribal Hammerhead Shark','Tribal Fish Hook','Tribal Ocean Wave Sleeve Piece','Tribal Dolphin Pair','Tribal Octopus','Tribal Seashell Spiral','Tribal Shark Teeth Pattern','Tribal Gecko','Tribal Wolf Head','Tribal Butterfly','Tribal Eagle Spread Wings','Tribal Scorpion','Tribal Lion Face','Tribal Serpent','Tribal Dragon','Tribal Hummingbird','Tribal Tiger Stripes Head','Tribal Swallow Pair','Tribal Sun Burst','Tribal Crescent Moon','Tribal Sun And Moon Joined','Tribal Star Burst','Tribal Eclipse','Tribal Sun On The Spine','Tribal Compass Star','Tribal Moon Phases Band','Tribal Sun On The Calf','Tribal Shooting Star','Tribal Lower Back Wings','Tribal Barbed Wire Armband','Tribal Flame Wrap','Tribal Heart With Points','Tribal Butterfly Y2K','Tribal Neck Flare','Tribal Spiked Heart Ankle','Tribal Flame Forearm','Tribal Hip Swirl','Tribal Dagger Points','Tribal Mandala Fusion','Tribal Geometric Fusion','Tribal Biomech Fusion','Tribal Floral Fusion','Tribal Dotwork Fusion','Tribal Lace Fusion','Tribal Negative Space Panel','Tribal Feather Fusion','Tribal Skull Fusion','Tribal Rose Fusion','Tribal Hand Accent','Tribal Behind The Ear','Tribal Wrist Point','Tribal Finger Swirl','Tribal Neck Accent','Tribal Ankle Curl','Tribal Small Forearm Mark','Tribal Nape Of Neck','Tribal Finger Points','Tribal Wrist Swirl','Tribal Full Back Piece','Tribal Spine Line','Tribal Shoulder Blade Wings','Tribal Spine Vine','Tribal Back Totem','Tribal Upper Back Crown','Tribal Spine Blades','Tribal Lower Back Flow','Tribal Side Torso Flow','Tribal Back Butterfly','Tribal Full Sleeve','Tribal Half Sleeve Swirls','Tribal Polynesian-Inspired Half Sleeve','Tribal Leg Wrap','Tribal Full Leg Sleeve','Tribal Thigh Piece','Tribal Forearm Sleeve','Tribal Full Sleeve Flow','Tribal Calf Sleeve','Tribal Hip To Thigh Piece'
$hits = $new | ? { $tk.ContainsKey((& $slug $_)) } | % { "  CLASH: $_  (already under " + $tk[(& $slug $_)] + ")" }
if ($hits) { $hits; "  STOPPED - nothing written or drawn" } else {
"  no clashes - building Tribal as split cards"
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:tribal" --remote 2>$null | Out-Null
RUN "CATEGORY Tribal :: Tribal Bands, Tribal Shoulder and Chest, Tribal Ocean Motifs, Tribal Animals, Tribal Sun Moon and Stars, Tribal Y2K Revival, Tribal Fusion, Tribal Small Pieces, Tribal Spine and Back, Tribal Sleeves and Legs"
RUN "LEAVES Tribal Bands :: Tribal Spiked Armband, Tribal Wave Wrist Cuff, Tribal Calf Band, Tribal Thigh Garter Band, Tribal Chevron Armband, Tribal Ankle Band, Tribal Double Band Forearm, Tribal Upper Arm Band With Drop, Tribal Shark Tooth Band, Tribal Finger Band" | Out-Null
RUN "LEAVES Tribal Shoulder and Chest :: Tribal Pec And Shoulder Piece, Tribal Shoulder Cap Swirl, Tribal Chest Plate, Tribal Collarbone Wings, Tribal Shoulder Blade Flame, Tribal Sternum Drop, Tribal Shoulder To Bicep Flow, Tribal Shoulder Vine, Tribal Half Chest Shield, Tribal Collarbone Crescent" | Out-Null
RUN "LEAVES Tribal Ocean Motifs :: Tribal Sea Turtle, Tribal Manta Ray, Tribal Hammerhead Shark, Tribal Fish Hook, Tribal Ocean Wave Sleeve Piece, Tribal Dolphin Pair, Tribal Octopus, Tribal Seashell Spiral, Tribal Shark Teeth Pattern, Tribal Gecko" | Out-Null
RUN "LEAVES Tribal Animals :: Tribal Wolf Head, Tribal Butterfly, Tribal Eagle Spread Wings, Tribal Scorpion, Tribal Lion Face, Tribal Serpent, Tribal Dragon, Tribal Hummingbird, Tribal Tiger Stripes Head, Tribal Swallow Pair" | Out-Null
RUN "LEAVES Tribal Sun Moon and Stars :: Tribal Sun Burst, Tribal Crescent Moon, Tribal Sun And Moon Joined, Tribal Star Burst, Tribal Eclipse, Tribal Sun On The Spine, Tribal Compass Star, Tribal Moon Phases Band, Tribal Sun On The Calf, Tribal Shooting Star" | Out-Null
RUN "LEAVES Tribal Y2K Revival :: Tribal Lower Back Wings, Tribal Barbed Wire Armband, Tribal Flame Wrap, Tribal Heart With Points, Tribal Butterfly Y2K, Tribal Neck Flare, Tribal Spiked Heart Ankle, Tribal Flame Forearm, Tribal Hip Swirl, Tribal Dagger Points" | Out-Null
RUN "LEAVES Tribal Fusion :: Tribal Mandala Fusion, Tribal Geometric Fusion, Tribal Biomech Fusion, Tribal Floral Fusion, Tribal Dotwork Fusion, Tribal Lace Fusion, Tribal Negative Space Panel, Tribal Feather Fusion, Tribal Skull Fusion, Tribal Rose Fusion" | Out-Null
RUN "LEAVES Tribal Small Pieces :: Tribal Hand Accent, Tribal Behind The Ear, Tribal Wrist Point, Tribal Finger Swirl, Tribal Neck Accent, Tribal Ankle Curl, Tribal Small Forearm Mark, Tribal Nape Of Neck, Tribal Finger Points, Tribal Wrist Swirl" | Out-Null
RUN "LEAVES Tribal Spine and Back :: Tribal Full Back Piece, Tribal Spine Line, Tribal Shoulder Blade Wings, Tribal Spine Vine, Tribal Back Totem, Tribal Upper Back Crown, Tribal Spine Blades, Tribal Lower Back Flow, Tribal Side Torso Flow, Tribal Back Butterfly" | Out-Null
RUN "LEAVES Tribal Sleeves and Legs :: Tribal Full Sleeve, Tribal Half Sleeve Swirls, Tribal Polynesian-Inspired Half Sleeve, Tribal Leg Wrap, Tribal Full Leg Sleeve, Tribal Thigh Piece, Tribal Forearm Sleeve, Tribal Full Sleeve Flow, Tribal Calf Sleeve, Tribal Hip To Thigh Piece" | Out-Null
"  100 leaves saved in 10 sets"
RUN "SETKV render:tribal-bands Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-bands 3:2" | Out-Null
RUN "SETKV split:tribal-bands yes" | Out-Null
RUN "SETKV render:tribal-shoulder-and-chest Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-shoulder-and-chest 3:2" | Out-Null
RUN "SETKV split:tribal-shoulder-and-chest yes" | Out-Null
RUN "SETKV render:tribal-ocean-motifs Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-ocean-motifs 3:2" | Out-Null
RUN "SETKV split:tribal-ocean-motifs yes" | Out-Null
RUN "SETKV render:tribal-animals Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-animals 3:2" | Out-Null
RUN "SETKV split:tribal-animals yes" | Out-Null
RUN "SETKV render:tribal-sun-moon-and-stars Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-sun-moon-and-stars 3:2" | Out-Null
RUN "SETKV split:tribal-sun-moon-and-stars yes" | Out-Null
RUN "SETKV render:tribal-y2k-revival Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-y2k-revival 3:2" | Out-Null
RUN "SETKV split:tribal-y2k-revival yes" | Out-Null
RUN "SETKV render:tribal-fusion Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-fusion 3:2" | Out-Null
RUN "SETKV split:tribal-fusion yes" | Out-Null
RUN "SETKV render:tribal-small-pieces Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-small-pieces 3:2" | Out-Null
RUN "SETKV split:tribal-small-pieces yes" | Out-Null
RUN "SETKV render:tribal-spine-and-back Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-spine-and-back 3:2" | Out-Null
RUN "SETKV split:tribal-spine-and-back yes" | Out-Null
RUN "SETKV render:tribal-sleeves-and-legs Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical." | Out-Null
RUN "SETKV shape:tribal-sleeves-and-legs 3:2" | Out-Null
RUN "SETKV split:tribal-sleeves-and-legs yes" | Out-Null
"  10 sets set to split cards"
RUN "SETKV build:tribal-spiked-armband The tattoo: tribal spiked armband - a bold band of interlocking black spikes wrapping the upper arm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is wrapping around his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-wave-wrist-cuff The tattoo: tribal wave wrist cuff - a slim band of flowing black waves wrapping the wrist. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her wrist, a close-up of her hand and forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-calf-band The tattoo: tribal calf band - a wide band of hooked black blades wrapping the calf. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is wrapping around his calf, wearing shorts" | Out-Null
RUN "SETKV build:tribal-thigh-garter-band The tattoo: tribal thigh garter band - a curving band of tapered black points wrapping the thigh. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is wrapping around her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:tribal-chevron-armband The tattoo: tribal chevron armband - stacked black chevrons forming a band around the arm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is wrapping around his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-ankle-band The tattoo: tribal ankle band - a thin band of small black points and curves wrapping the ankle. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her ankle, a close-up of her lower leg and foot" | Out-Null
RUN "SETKV build:tribal-double-band-forearm The tattoo: tribal double band forearm - two parallel black bands linked by small tribal points. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-upper-arm-band-with-drop The tattoo: tribal upper arm band with drop - a sleek armband with a single pointed drop hanging below it. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is wrapping around her upper arm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-shark-tooth-band The tattoo: tribal shark tooth band - a band of black triangular shark teeth wrapping the wrist. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around his wrist, a close-up of his hand and forearm, wearing a plain short-sleeve shirt" | Out-Null
RUN "SETKV build:tribal-finger-band The tattoo: tribal finger band - a tiny band of black points wrapping the finger. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her finger, a close-up of her hand" | Out-Null
RUN "SETKV build:tribal-pec-and-shoulder-piece The tattoo: tribal pec and shoulder piece - bold black blades sweeping from the chest up over the shoulder. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on one side of his chest running up over the shoulder, shirtless" | Out-Null
RUN "SETKV build:tribal-shoulder-cap-swirl The tattoo: tribal shoulder cap swirl - black curves spiralling around the top of the shoulder. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:tribal-chest-plate The tattoo: tribal chest plate - a symmetrical black design spreading across both sides of the chest. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:tribal-collarbone-wings The tattoo: tribal collarbone wings - two black wing-like tribal shapes following the collarbones. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along her collarbones and shoulders, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:tribal-shoulder-blade-flame The tattoo: tribal shoulder blade flame - black flame-like blades rising over the shoulder. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-sternum-drop The tattoo: tribal sternum drop - a symmetrical tribal ornament with a pointed drop at the centre of the chest. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:tribal-shoulder-to-bicep-flow The tattoo: tribal shoulder to bicep flow - one flowing black form running from the shoulder down the bicep. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-shoulder-vine The tattoo: tribal shoulder vine - curling black tribal tendrils wrapping the shoulder cap. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:tribal-half-chest-shield The tattoo: tribal half chest shield - a shield-shaped tribal pattern on one side of the chest. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on one side of his chest running up over the shoulder, shirtless" | Out-Null
RUN "SETKV build:tribal-collarbone-crescent The tattoo: tribal collarbone crescent - a black crescent of tribal points along the collarbones. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along her collarbones and shoulders, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:tribal-sea-turtle The tattoo: tribal sea turtle - a Polynesian-inspired sea turtle built from bold black patterns. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-manta-ray The tattoo: tribal manta ray - a Polynesian-inspired manta ray with patterned wings. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:tribal-hammerhead-shark The tattoo: tribal hammerhead shark - a hammerhead shark made of black tribal shapes. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:tribal-fish-hook The tattoo: tribal fish hook - a Polynesian-inspired fish hook filled with tribal pattern. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her ankle, a close-up of her lower leg and foot" | Out-Null
RUN "SETKV build:tribal-ocean-wave-sleeve-piece The tattoo: tribal ocean wave sleeve piece - rolling black waves in tribal pattern. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-dolphin-pair The tattoo: tribal dolphin pair - two dolphins in tribal black curves circling each other. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:tribal-octopus The tattoo: tribal octopus - an octopus with curling tribal tentacles. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts" | Out-Null
RUN "SETKV build:tribal-seashell-spiral The tattoo: tribal seashell spiral - a spiral seashell in bold tribal pattern. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:tribal-shark-teeth-pattern The tattoo: tribal shark teeth pattern - rows of black triangular shark teeth forming a shoulder piece. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-gecko The tattoo: tribal gecko - a gecko made of black tribal pattern. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-wolf-head The tattoo: tribal wolf head - a wolf head built from sharp black tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-butterfly The tattoo: tribal butterfly - a butterfly with wings made of curving black tribal shapes. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her lower back just above the waistband of simple jeans, seen from behind, wearing a short top" | Out-Null
RUN "SETKV build:tribal-eagle-spread-wings The tattoo: tribal eagle spread wings - an eagle with spread wings of black tribal feathers. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:tribal-scorpion The tattoo: tribal scorpion - a scorpion formed from tapered black tribal points. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt" | Out-Null
RUN "SETKV build:tribal-lion-face The tattoo: tribal lion face - a lion face built from bold black tribal flames. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:tribal-serpent The tattoo: tribal serpent - a serpent curling in black tribal curves. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:tribal-dragon The tattoo: tribal dragon - a dragon whose body is made of flowing black tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of his ribs, shirtless, seen from the side" | Out-Null
RUN "SETKV build:tribal-hummingbird The tattoo: tribal hummingbird - a hummingbird made of fine black tribal shapes. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:tribal-tiger-stripes-head The tattoo: tribal tiger stripes head - a tiger head shaped from black tribal stripes. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-swallow-pair The tattoo: tribal swallow pair - two swallows in black tribal curves. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along her collarbones and shoulders, wearing a simple black strapless top" | Out-Null
RUN "SETKV build:tribal-sun-burst The tattoo: tribal sun burst - a sun with sharp curving black tribal rays. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-crescent-moon The tattoo: tribal crescent moon - a crescent moon edged with tribal points. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is just behind her ear with her hair tucked back, a close-up of the side of her head and neck" | Out-Null
RUN "SETKV build:tribal-sun-and-moon-joined The tattoo: tribal sun and moon joined - a sun and moon joined into one tribal circle. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-star-burst The tattoo: tribal star burst - a star made of curved black tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her wrist, a close-up of her hand and forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-eclipse The tattoo: tribal eclipse - a black eclipse ringed with tribal flames. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his chest, shirtless" | Out-Null
RUN "SETKV build:tribal-sun-on-the-spine The tattoo: tribal sun on the spine - a small tribal sun at the top of the spine. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of her neck with her hair up, seen from behind, wearing a simple top" | Out-Null
RUN "SETKV build:tribal-compass-star The tattoo: tribal compass star - a compass star with tribal points. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-moon-phases-band The tattoo: tribal moon phases band - moon phases linked by tribal curves. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is down her spine, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:tribal-sun-on-the-calf The tattoo: tribal sun on the calf - a large tribal sun with long curling rays. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:tribal-shooting-star The tattoo: tribal shooting star - a shooting star with a tribal tail. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her ankle, a close-up of her lower leg and foot" | Out-Null
RUN "SETKV build:tribal-lower-back-wings The tattoo: tribal lower back wings - a symmetrical Y2K tribal design spreading like wings. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her lower back just above the waistband of simple jeans, seen from behind, wearing a short top" | Out-Null
RUN "SETKV build:tribal-barbed-wire-armband The tattoo: tribal barbed wire armband - barbed wire twisted with sharp tribal points around the arm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is wrapping around his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-flame-wrap The tattoo: tribal flame wrap - Y2K tribal flames curling up the arm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-heart-with-points The tattoo: tribal heart with points - a heart edged with sharp Y2K tribal points. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his hand, wearing a plain long-sleeve shirt" | Out-Null
RUN "SETKV build:tribal-butterfly-y2k The tattoo: tribal butterfly y2k - a symmetrical Y2K tribal butterfly. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:tribal-neck-flare The tattoo: tribal neck flare - a sharp Y2K tribal flare on the side of the neck. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his neck, wearing a plain crew-neck shirt" | Out-Null
RUN "SETKV build:tribal-spiked-heart-ankle The tattoo: tribal spiked heart ankle - a small spiked tribal heart. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her ankle, a close-up of her lower leg and foot" | Out-Null
RUN "SETKV build:tribal-flame-forearm The tattoo: tribal flame forearm - long Y2K tribal flames running along the forearm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-hip-swirl The tattoo: tribal hip swirl - Y2K tribal swirls curling over the hip. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:tribal-dagger-points The tattoo: tribal dagger points - a dagger shape made of sharp tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:tribal-mandala-fusion The tattoo: tribal mandala fusion - a mandala circle with tribal blades radiating outward. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:tribal-geometric-fusion The tattoo: tribal geometric fusion - tribal curves locked into triangles and straight lines. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-biomech-fusion The tattoo: tribal biomech fusion - tribal blades merging with mechanical plates and joints. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-floral-fusion The tattoo: tribal floral fusion - a flower whose petals are sharp tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:tribal-dotwork-fusion The tattoo: tribal dotwork fusion - tribal shapes filled with fine black dotwork shading. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:tribal-lace-fusion The tattoo: tribal lace fusion - tribal curves edged with delicate lace patterns. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top" | Out-Null
RUN "SETKV build:tribal-negative-space-panel The tattoo: tribal negative space panel - a solid black panel with tribal shapes cut out as bare skin. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-feather-fusion The tattoo: tribal feather fusion - a long feather built from tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is down her spine, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:tribal-skull-fusion The tattoo: tribal skull fusion - a skull framed by sweeping tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-rose-fusion The tattoo: tribal rose fusion - a rose wrapped in curling tribal tendrils. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-hand-accent The tattoo: tribal hand accent - a small sharp tribal accent on the hand. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his hand, wearing a plain long-sleeve shirt" | Out-Null
RUN "SETKV build:tribal-behind-the-ear The tattoo: tribal behind the ear - a tiny curling tribal mark. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is just behind her ear with her hair tucked back, a close-up of the side of her head and neck" | Out-Null
RUN "SETKV build:tribal-wrist-point The tattoo: tribal wrist point - a small tribal point on the wrist. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around his wrist, a close-up of his hand and forearm, wearing a plain short-sleeve shirt" | Out-Null
RUN "SETKV build:tribal-finger-swirl The tattoo: tribal finger swirl - a tiny tribal swirl on the finger. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her finger, a close-up of her hand" | Out-Null
RUN "SETKV build:tribal-neck-accent The tattoo: tribal neck accent - a small tribal accent on the side of the neck. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his neck, wearing a plain crew-neck shirt" | Out-Null
RUN "SETKV build:tribal-ankle-curl The tattoo: tribal ankle curl - a small tribal curl on the ankle. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her ankle, a close-up of her lower leg and foot" | Out-Null
RUN "SETKV build:tribal-small-forearm-mark The tattoo: tribal small forearm mark - a compact tribal mark on the forearm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-nape-of-neck The tattoo: tribal nape of neck - a small symmetrical tribal mark. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of her neck with her hair up, seen from behind, wearing a simple top" | Out-Null
RUN "SETKV build:tribal-finger-points The tattoo: tribal finger points - a tiny row of tribal points. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of his finger, a close-up of his hand" | Out-Null
RUN "SETKV build:tribal-wrist-swirl The tattoo: tribal wrist swirl - a small curling tribal swirl. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is around her wrist, a close-up of her hand and forearm, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-full-back-piece The tattoo: tribal full back piece - a large symmetrical tribal design covering the whole back. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:tribal-spine-line The tattoo: tribal spine line - a long tribal line of points running down the spine. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is down her spine, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:tribal-shoulder-blade-wings The tattoo: tribal shoulder blade wings - tribal wings spreading across both shoulder blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:tribal-spine-vine The tattoo: tribal spine vine - curling tribal tendrils climbing the spine. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is down her spine, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:tribal-back-totem The tattoo: tribal back totem - a stacked tribal totem running down the centre of the back. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across his back, shirtless, seen from behind" | Out-Null
RUN "SETKV build:tribal-upper-back-crown The tattoo: tribal upper back crown - a symmetrical tribal crown across the upper back. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top" | Out-Null
RUN "SETKV build:tribal-spine-blades The tattoo: tribal spine blades - sharp tribal blades fanning out from the spine. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind" | Out-Null
RUN "SETKV build:tribal-lower-back-flow The tattoo: tribal lower back flow - a flowing tribal design across the lower back. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her lower back just above the waistband of simple jeans, seen from behind, wearing a short top" | Out-Null
RUN "SETKV build:tribal-side-torso-flow The tattoo: tribal side torso flow - tribal blades running up the side of the ribs. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is along the side of his ribs, shirtless, seen from the side" | Out-Null
RUN "SETKV build:tribal-back-butterfly The tattoo: tribal back butterfly - a large tribal butterfly across the back. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top" | Out-Null
RUN "SETKV build:tribal-full-sleeve The tattoo: tribal full sleeve - a full arm of interlocking bold tribal blades. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-half-sleeve-swirls The tattoo: tribal half sleeve swirls - sweeping tribal swirls covering the upper arm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-polynesian-inspired-half-sleeve The tattoo: tribal polynesian-inspired half sleeve - bands of Polynesian-inspired tribal pattern covering the upper arm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering his upper arm from shoulder to elbow, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-leg-wrap The tattoo: tribal leg wrap - tribal blades spiralling up the whole leg. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering her whole leg, wearing mid-length shorts" | Out-Null
RUN "SETKV build:tribal-full-leg-sleeve The tattoo: tribal full leg sleeve - a full leg of bold tribal pattern. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering his whole leg, wearing shorts" | Out-Null
RUN "SETKV build:tribal-thigh-piece The tattoo: tribal thigh piece - a large tribal design on the thigh. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts" | Out-Null
RUN "SETKV build:tribal-forearm-sleeve The tattoo: tribal forearm sleeve - bold tribal pattern covering the whole forearm. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on his forearm, wearing a plain sleeveless shirt" | Out-Null
RUN "SETKV build:tribal-full-sleeve-flow The tattoo: tribal full sleeve flow - a full arm of flowing tribal curves. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is covering her whole arm from shoulder to wrist, wearing a sleeveless top" | Out-Null
RUN "SETKV build:tribal-calf-sleeve The tattoo: tribal calf sleeve - tribal blades wrapping the whole calf. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the back of his calf, wearing shorts" | Out-Null
RUN "SETKV build:tribal-hip-to-thigh-piece The tattoo: tribal hip to thigh piece - a tribal design flowing from the hip down the thigh. Modern tribal tattoo art, bold solid black shapes with sharp tapered points and sweeping curves, clean crisp negative space between the forms, composed to follow the muscles and the natural flow of the body, symmetrical where it suits the placement, designed like work from a contemporary tribal and blackwork tattoo artist rather than clip art or a logo, black ink only, no grey wash, no colour, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts" | Out-Null
"  100 builds saved"
RUN "REDO Tribal Pec And Shoulder Piece"
}
}
