cd "C:\Users\Aaron Karacas\aura-worker\aura\aura-workers\aura-core"
$slug = { param($x) (($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-')) }
$raw = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote | Select-Object -Last 1
$tt = $raw | ConvertFrom-Json
if (-not $tt.subjects) { "COULD NOT READ THE CATALOG - nothing written, run the block again" } else {
$mineK = @($tt.subjects."Woodcut")
$tk = @{}
$tt.subjects.PSObject.Properties | % { $_.Value | ? { $mineK -notcontains $_ } | % { $tk[(& $slug $_)] = "a set name" } }
$newK = @('Woodcut Style Animals','Woodcut Style Botanicals','Woodcut Style Nature Scenes','Woodcut Style Mythology','Woodcut Style Nautical','Woodcut Style Skulls and Death','Woodcut Style Folk','Woodcut Style Celestial','Woodcut Style Small','Woodcut Style Large Pieces')
$tt.specific.PSObject.Properties | ? { $newK -notcontains $_.Name } | % { $k = $_.Name; $_.Value | % { $tk[(& $slug $_)] = $k } }
$b = @{}
$b['Woodcut stag in a forest'] = 'The tattoo: woodcut stag in a forest. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut wolf howling'] = 'The tattoo: woodcut wolf howling. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut bear standing'] = 'The tattoo: woodcut bear standing. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut fox curled up'] = 'The tattoo: woodcut fox curled up. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut owl on a branch'] = 'The tattoo: woodcut owl on a branch. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Woodcut raven'] = 'The tattoo: woodcut raven. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut hare leaping'] = 'The tattoo: woodcut hare leaping. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Woodcut boar'] = 'The tattoo: woodcut boar. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut horse rearing'] = 'The tattoo: woodcut horse rearing. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woodcut snake coiled'] = 'The tattoo: woodcut snake coiled. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut rose'] = 'The tattoo: woodcut rose. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woodcut thistle'] = 'The tattoo: woodcut thistle. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut fern'] = 'The tattoo: woodcut fern. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Woodcut mushrooms'] = 'The tattoo: woodcut mushrooms. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Woodcut oak branch with acorns'] = 'The tattoo: woodcut oak branch with acorns. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut wheat sheaf'] = 'The tattoo: woodcut wheat sheaf. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Woodcut poppy'] = 'The tattoo: woodcut poppy. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut lily'] = 'The tattoo: woodcut lily. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut pine cone'] = 'The tattoo: woodcut pine cone. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Woodcut sunflower'] = 'The tattoo: woodcut sunflower. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut mountain range'] = 'The tattoo: woodcut mountain range. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut ocean wave'] = 'The tattoo: woodcut ocean wave. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut forest path'] = 'The tattoo: woodcut forest path. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Woodcut waterfall'] = 'The tattoo: woodcut waterfall. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut lone tree'] = 'The tattoo: woodcut lone tree. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Woodcut volcano'] = 'The tattoo: woodcut volcano. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut desert sun'] = 'The tattoo: woodcut desert sun. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woodcut river valley'] = 'The tattoo: woodcut river valley. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut storm clouds'] = 'The tattoo: woodcut storm clouds. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut lake with reeds'] = 'The tattoo: woodcut lake with reeds. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut dragon'] = 'The tattoo: woodcut dragon. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Woodcut sea serpent'] = 'The tattoo: woodcut sea serpent. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Woodcut griffin'] = 'The tattoo: woodcut griffin. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut phoenix'] = 'The tattoo: woodcut phoenix. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Woodcut unicorn'] = 'The tattoo: woodcut unicorn. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut kraken'] = 'The tattoo: woodcut kraken. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut minotaur'] = 'The tattoo: woodcut minotaur. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Woodcut mermaid in a shell top'] = 'The tattoo: woodcut mermaid in a shell top. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut cerberus'] = 'The tattoo: woodcut cerberus. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut basilisk'] = 'The tattoo: woodcut basilisk. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut sailing ship'] = 'The tattoo: woodcut sailing ship. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Woodcut lighthouse'] = 'The tattoo: woodcut lighthouse. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut anchor and rope'] = 'The tattoo: woodcut anchor and rope. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Woodcut whale'] = 'The tattoo: woodcut whale. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut octopus'] = 'The tattoo: woodcut octopus. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woodcut compass rose'] = 'The tattoo: woodcut compass rose. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut ship in a storm'] = 'The tattoo: woodcut ship in a storm. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut swallow'] = 'The tattoo: woodcut swallow. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut shark'] = 'The tattoo: woodcut shark. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woodcut diving helmet'] = 'The tattoo: woodcut diving helmet. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut skull'] = 'The tattoo: woodcut skull. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut skeleton dancing'] = 'The tattoo: woodcut skeleton dancing. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Woodcut grim reaper'] = 'The tattoo: woodcut grim reaper. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut skull with roses'] = 'The tattoo: woodcut skull with roses. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut hourglass'] = 'The tattoo: woodcut hourglass. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Woodcut coffin'] = 'The tattoo: woodcut coffin. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut raven on a skull'] = 'The tattoo: woodcut raven on a skull. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut plague doctor'] = 'The tattoo: woodcut plague doctor. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut dagger and skull'] = 'The tattoo: woodcut dagger and skull. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut candle and skull'] = 'The tattoo: woodcut candle and skull. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut folk bird'] = 'The tattoo: woodcut folk bird. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across her upper back, seen from behind in an open-back top'
$b['Woodcut farmer with a scythe'] = 'The tattoo: woodcut farmer with a scythe. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut sun face'] = 'The tattoo: woodcut sun face. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woodcut moon face'] = 'The tattoo: woodcut moon face. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut heart with flowers'] = 'The tattoo: woodcut heart with flowers. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut tree of life'] = 'The tattoo: woodcut tree of life. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut rooster'] = 'The tattoo: woodcut rooster. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Woodcut horse and cart'] = 'The tattoo: woodcut horse and cart. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut cottage'] = 'The tattoo: woodcut cottage. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Woodcut witch on a broom'] = 'The tattoo: woodcut witch on a broom. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Woodcut crescent moon with a face'] = 'The tattoo: woodcut crescent moon with a face. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut sun with rays'] = 'The tattoo: woodcut sun with rays. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut comet'] = 'The tattoo: woodcut comet. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her upper thigh just below the hip, below the hem of mid-length shorts'
$b['Woodcut eclipse'] = 'The tattoo: woodcut eclipse. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Woodcut stars and moon'] = 'The tattoo: woodcut stars and moon. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut planet with rings'] = 'The tattoo: woodcut planet with rings. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of his upper arm, wearing a plain sleeveless shirt'
$b['Woodcut constellation'] = 'The tattoo: woodcut constellation. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of her calf, below a knee-length skirt'
$b['Woodcut sun and moon together'] = 'The tattoo: woodcut sun and moon together. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut falling star'] = 'The tattoo: woodcut falling star. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Woodcut astronomer'] = 'The tattoo: woodcut astronomer. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny woodcut moon'] = 'The tattoo: tiny woodcut moon. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small woodcut rose'] = 'The tattoo: small woodcut rose. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Tiny woodcut skull'] = 'The tattoo: tiny woodcut skull. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small woodcut mushroom'] = 'The tattoo: small woodcut mushroom. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of his forearm, wearing a plain short-sleeve shirt'
$b['Tiny woodcut swallow'] = 'The tattoo: tiny woodcut swallow. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the outside of her upper arm, wearing a sleeveless top'
$b['Small woodcut wave'] = 'The tattoo: small woodcut wave. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Tiny woodcut star'] = 'The tattoo: tiny woodcut star. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of her thigh, below the hem of mid-length shorts'
$b['Small woodcut key'] = 'The tattoo: small woodcut key. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on his shoulder cap, wearing a plain sleeveless shirt'
$b['Tiny woodcut bee'] = 'The tattoo: tiny woodcut bee. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Small woodcut leaf'] = 'The tattoo: small woodcut leaf. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across his upper back, shirtless, seen from behind'
$b['Woodcut forest back piece'] = 'The tattoo: woodcut forest back piece. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is across her back, seen from behind in a low open-back top'
$b['Woodcut ocean sleeve'] = 'The tattoo: woodcut ocean sleeve. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is covering his whole arm from shoulder to wrist, wearing a plain sleeveless shirt'
$b['Woodcut stag chest piece'] = 'The tattoo: woodcut stag chest piece. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on her upper chest just below her collarbones, above a simple scoop-neck top'
$b['Woodcut dragon thigh piece'] = 'The tattoo: woodcut dragon thigh piece. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the side of his thigh, wearing shorts'
$b['Woodcut mountain forearm piece'] = 'The tattoo: woodcut mountain forearm piece. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the inside of her forearm, wearing a sleeveless top'
$b['Woodcut snake spine piece'] = 'The tattoo: woodcut snake spine piece. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is down his spine, shirtless, seen from behind'
$b['Woodcut sea monster half sleeve'] = 'The tattoo: woodcut sea monster half sleeve. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is covering her upper arm from shoulder to elbow, wearing a sleeveless top'
$b['Woodcut wolf calf piece'] = 'The tattoo: woodcut wolf calf piece. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on the back of his calf, wearing shorts'
$b['Woodcut sun shoulder piece'] = 'The tattoo: woodcut sun shoulder piece. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is on her shoulder cap, wearing a simple black strapless top'
$b['Woodcut forest leg sleeve'] = 'The tattoo: woodcut forest leg sleeve. Woodcut tattoo art in the style of old woodblock and linocut prints, bold black carved lines with parallel hatching and gouge marks, high contrast black ink with no grey shading, rough hand-carved texture, designed like work from a top woodcut and engraving tattoo artist, no letters, no words. In the right panel it is covering his whole leg, wearing shorts'
$sets = [ordered]@{}
$sets['Woodcut Style Animals'] = @('Woodcut stag in a forest','Woodcut wolf howling','Woodcut bear standing','Woodcut fox curled up','Woodcut owl on a branch','Woodcut raven','Woodcut hare leaping','Woodcut boar','Woodcut horse rearing','Woodcut snake coiled')
$sets['Woodcut Style Botanicals'] = @('Woodcut rose','Woodcut thistle','Woodcut fern','Woodcut mushrooms','Woodcut oak branch with acorns','Woodcut wheat sheaf','Woodcut poppy','Woodcut lily','Woodcut pine cone','Woodcut sunflower')
$sets['Woodcut Style Nature Scenes'] = @('Woodcut mountain range','Woodcut ocean wave','Woodcut forest path','Woodcut waterfall','Woodcut lone tree','Woodcut volcano','Woodcut desert sun','Woodcut river valley','Woodcut storm clouds','Woodcut lake with reeds')
$sets['Woodcut Style Mythology'] = @('Woodcut dragon','Woodcut sea serpent','Woodcut griffin','Woodcut phoenix','Woodcut unicorn','Woodcut kraken','Woodcut minotaur','Woodcut mermaid in a shell top','Woodcut cerberus','Woodcut basilisk')
$sets['Woodcut Style Nautical'] = @('Woodcut sailing ship','Woodcut lighthouse','Woodcut anchor and rope','Woodcut whale','Woodcut octopus','Woodcut compass rose','Woodcut ship in a storm','Woodcut swallow','Woodcut shark','Woodcut diving helmet')
$sets['Woodcut Style Skulls and Death'] = @('Woodcut skull','Woodcut skeleton dancing','Woodcut grim reaper','Woodcut skull with roses','Woodcut hourglass','Woodcut coffin','Woodcut raven on a skull','Woodcut plague doctor','Woodcut dagger and skull','Woodcut candle and skull')
$sets['Woodcut Style Folk'] = @('Woodcut folk bird','Woodcut farmer with a scythe','Woodcut sun face','Woodcut moon face','Woodcut heart with flowers','Woodcut tree of life','Woodcut rooster','Woodcut horse and cart','Woodcut cottage','Woodcut witch on a broom')
$sets['Woodcut Style Celestial'] = @('Woodcut crescent moon with a face','Woodcut sun with rays','Woodcut comet','Woodcut eclipse','Woodcut stars and moon','Woodcut planet with rings','Woodcut constellation','Woodcut sun and moon together','Woodcut falling star','Woodcut astronomer')
$sets['Woodcut Style Small'] = @('Tiny woodcut moon','Small woodcut rose','Tiny woodcut skull','Small woodcut mushroom','Tiny woodcut swallow','Small woodcut wave','Tiny woodcut star','Small woodcut key','Tiny woodcut bee','Small woodcut leaf')
$sets['Woodcut Style Large Pieces'] = @('Woodcut forest back piece','Woodcut ocean sleeve','Woodcut stag chest piece','Woodcut dragon thigh piece','Woodcut mountain forearm piece','Woodcut snake spine piece','Woodcut sea monster half sleeve','Woodcut wolf calf piece','Woodcut sun shoulder piece','Woodcut forest leg sleeve')
$fix = { param($n) if ($tk.ContainsKey((& $slug $n))) { "$n in Woodcut Style" } else { $n } }
"== Woodcut before (these get replaced) =="
"  " + ($mineK -join ", ")
$kh = @($sets.Keys | ? { $tk.ContainsKey((& $slug $_)) })
if ($kh) { $kh | % { "  SET NAME CLASH: $_" }; "  STOPPED - nothing written or drawn" } else {
npx wrangler kv key delete --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "frame:category:woodcut" --remote 2>$null | Out-Null
RUN "CATEGORY Woodcut :: Woodcut Style Animals, Woodcut Style Botanicals, Woodcut Style Nature Scenes, Woodcut Style Mythology, Woodcut Style Nautical, Woodcut Style Skulls and Death, Woodcut Style Folk, Woodcut Style Celestial, Woodcut Style Small, Woodcut Style Large Pieces" | Out-Null
$n = 0
foreach ($k in $sets.Keys) {
  $names = @($sets[$k] | % { & $fix $_ })
  $names | ? { $_ -match " in Woodcut Style$" } | % { "  RENAMED: $_" }
  RUN ("LEAVES " + $k + " :: " + ($names -join ", ")) | Out-Null
  $ks = & $slug $k
  RUN ("SETKV render:" + $ks + " Two panels side by side on one image, divided down the middle. LEFT PANEL: the tattoo design alone on a plain white background, shown flat exactly as described, no body, drawn large so it fills most of the panel. RIGHT PANEL: Studio photograph of a real person's body showing the same exact tattoo where described, healed tattoo on real skin in soft even light, the rest of the body modestly covered by simple plain clothing, only the tattooed area bare, plain seamless light grey studio backdrop - no room, no furniture, no scenery. The tattoo in both panels is identical.") | Out-Null
  RUN ("SETKV shape:" + $ks + " 3:2") | Out-Null
  RUN ("SETKV split:" + $ks + " yes") | Out-Null
  foreach ($leaf in $names) { $base = $leaf -replace ' in Woodcut Style$',''; RUN ("SETKV build:" + (& $slug $leaf) + " " + $b[$base]) | Out-Null; $n++ }
}
"  10 sets saved as split cards, " + $n + " builds saved"
RUN ("REDO " + (& $fix "Woodcut stag in a forest"))
}
}
