$t = npx wrangler kv key get --namespace-id 9c2ba111589e48c6ba5ad1b924ae8809 "card:tree" --remote
$j = $t | ConvertFrom-Json
$slug = { param($x) ($x.ToLower() -replace '[^a-z0-9]+','-').Trim('-') }
$all = @{}; foreach ($c in $j.subjects.PSObject.Properties) { $all[(& $slug $c.Name)] = "category $($c.Name)"; foreach ($k in $c.Value) { $all[(& $slug $k)] = "kind $k in $($c.Name)"; foreach ($l in @($j.specific.$k)) { if ($l) { $all[(& $slug $l)] = "design $l in $k" } } } }
$new = 'Y2K Butterfly Clip','Y2K Digital Pet','Y2K MP3 Player','Y2K Portable CD Player','Y2K Pager','Y2K CRT Computer','Y2K Computer Mouse','Y2K Instant Messenger Window','Y2K Loading Bar','Y2K Cursor','Y2K Floppy Disk','Y2K Digital Camera','Y2K Camcorder','Y2K Wired Earbuds','Y2K Boombox','Y2K Mini TV','Y2K Game Controller','Y2K Pixel Angel','Y2K Pixel Devil','Y2K Pixel Flower','Y2K Pixel Cherry','Y2K Pixel Flame','Y2K Pixel Star','Y2K Error Heart','Y2K Broken Screen Heart','Y2K Chrome Butterfly','Y2K Chrome Heart','Y2K Chrome Cross','Y2K Chrome Angel','Y2K Chrome Flame','Y2K Chrome Tribal','Y2K Chrome Dragon','Y2K Chrome Scorpion','Y2K Chrome Spider','Y2K Chrome Dolphin','Y2K Chrome Heart With Wings','Y2K Barbed-Wire Heart','Y2K Tribal Butterfly','Y2K Tribal Dragon','Y2K Tribal Bat','Y2K Tribal Cross','Y2K Tribal Star','Y2K Tribal Butterfly Heart','Y2K Cyber Heart','Y2K Cyber Butterfly','Y2K Cyber Star','Y2K Cyber Angel','Y2K Cyber Cross','Y2K Cyber Flame','Y2K Cyber Sigil','Y2K Thorn Heart','Y2K Digital Thorns','Y2K Halo Heart','Y2K Angel Heart','Y2K Devil Cherries','Y2K Angel Cherries','Y2K Devil Butterfly','Y2K Angel Butterfly','Y2K Angel Number','Y2K Baby Angel','Y2K Tiara','Y2K Rhinestone Cross','Y2K Rhinestone Butterfly','Y2K Rhinestone Cherries','Y2K Rhinestone Star','Y2K Heart Locket','Y2K Charm Bracelet','Y2K Nameplate','Y2K Princess Lettering','Y2K Bubble Lettering','Y2K Flame Lettering','Y2K Graffiti Heart','Y2K Airbrush Cloud','Y2K Rainbow','Y2K Magic Wand','Y2K Lollipop','Y2K Platform Shoe','Y2K Mini Handbag','Y2K Sunglasses','Y2K Everything'
$hits = $new | Where-Object { $all.ContainsKey((& $slug $_)) } | ForEach-Object { "CLASH: $_ -> " + $all[(& $slug $_)] }
if ($hits) { $hits; "STOPPED - nothing saved or drawn" } else {
"no clashes - building"
RUN "LEAVES Y2K Ideas :: Y2K Butterfly, Y2K Cherries, Y2K Bow, Y2K Tribal Heart, Y2K Tribal Sun, Y2K Lower-Back Tribal, Y2K Flame Heart, Y2K Chrome Star, Y2K Shooting Star, Y2K Dice, Y2K 8-Ball, Y2K Angel Wings, Y2K Devil Heart, Y2K Rhinestone Heart, Y2K Flip Phone, Y2K CD, Y2K Headphones, Y2K Pixel Heart, Y2K Acid Smiley, Y2K Sparkly Lettering, Y2K Butterfly Clip, Y2K Digital Pet, Y2K MP3 Player, Y2K Portable CD Player, Y2K Pager, Y2K CRT Computer, Y2K Computer Mouse, Y2K Instant Messenger Window, Y2K Loading Bar, Y2K Cursor, Y2K Floppy Disk, Y2K Digital Camera, Y2K Camcorder, Y2K Wired Earbuds, Y2K Boombox, Y2K Mini TV, Y2K Game Controller, Y2K Pixel Angel, Y2K Pixel Devil, Y2K Pixel Flower, Y2K Pixel Cherry, Y2K Pixel Flame, Y2K Pixel Star, Y2K Error Heart, Y2K Broken Screen Heart, Y2K Chrome Butterfly, Y2K Chrome Heart, Y2K Chrome Cross, Y2K Chrome Angel, Y2K Chrome Flame, Y2K Chrome Tribal, Y2K Chrome Dragon, Y2K Chrome Scorpion, Y2K Chrome Spider, Y2K Chrome Dolphin, Y2K Chrome Heart With Wings, Y2K Barbed-Wire Heart, Y2K Tribal Butterfly, Y2K Tribal Dragon, Y2K Tribal Bat, Y2K Tribal Cross, Y2K Tribal Star, Y2K Tribal Butterfly Heart, Y2K Cyber Heart, Y2K Cyber Butterfly, Y2K Cyber Star, Y2K Cyber Angel, Y2K Cyber Cross, Y2K Cyber Flame, Y2K Cyber Sigil, Y2K Thorn Heart, Y2K Digital Thorns, Y2K Halo Heart, Y2K Angel Heart, Y2K Devil Cherries, Y2K Angel Cherries, Y2K Devil Butterfly, Y2K Angel Butterfly, Y2K Angel Number, Y2K Baby Angel, Y2K Tiara, Y2K Rhinestone Cross, Y2K Rhinestone Butterfly, Y2K Rhinestone Cherries, Y2K Rhinestone Star, Y2K Heart Locket, Y2K Charm Bracelet, Y2K Nameplate, Y2K Princess Lettering, Y2K Bubble Lettering, Y2K Flame Lettering, Y2K Graffiti Heart, Y2K Airbrush Cloud, Y2K Rainbow, Y2K Magic Wand, Y2K Lollipop, Y2K Platform Shoe, Y2K Mini Handbag, Y2K Sunglasses, Y2K Everything"
RUN "SETKV build:y2k-butterfly-clip a Y2K butterfly clip - translucent glitter butterfly hair clip"
RUN "SETKV build:y2k-digital-pet a Y2K digital pet - an original egg-shaped virtual pet device with pixel creature"
RUN "SETKV build:y2k-mp3-player a Y2K MP3 player - tiny metallic early-digital music player with wired earbuds"
RUN "SETKV build:y2k-portable-cd-player a Y2K portable CD player - round chrome portable CD player with wired headphones"
RUN "SETKV build:y2k-pager a Y2K pager - transparent or chrome pager with tiny digital message"
RUN "SETKV build:y2k-crt-computer a Y2K CRT computer - chunky translucent desktop computer with smiling screen"
RUN "SETKV build:y2k-computer-mouse a Y2K computer mouse - translucent colored computer mouse with long cord"
RUN "SETKV build:y2k-instant-messenger-window a Y2K instant messenger window - retro computer chat window with tiny heart message"
RUN "SETKV build:y2k-loading-bar a Y2K loading bar - retro pixel loading bar nearly complete"
RUN "SETKV build:y2k-cursor a Y2K cursor - chunky pixel mouse cursor surrounded by sparkles"
RUN "SETKV build:y2k-floppy-disk a Y2K floppy disk - chrome or translucent floppy disk with heart label"
RUN "SETKV build:y2k-digital-camera a Y2K digital camera - tiny silver early-2000s point-and-shoot camera"
RUN "SETKV build:y2k-camcorder a Y2K camcorder - mini silver handheld camcorder with star accents"
RUN "SETKV build:y2k-wired-earbuds a Y2K wired earbuds - tangled wired earbuds forming a heart"
RUN "SETKV build:y2k-boombox a Y2K boombox - silver or chrome boombox with pink details"
RUN "SETKV build:y2k-mini-tv a Y2K mini TV - tiny bubble-screen television showing a heart"
RUN "SETKV build:y2k-game-controller a Y2K game controller - original translucent retro-style controller with chrome details"
RUN "SETKV build:y2k-pixel-angel a Y2K pixel angel - tiny pixelated angel with halo"
RUN "SETKV build:y2k-pixel-devil a Y2K pixel devil - tiny pixel devil with horns and tail"
RUN "SETKV build:y2k-pixel-flower a Y2K pixel flower - bright pixelated flower with smiley center"
RUN "SETKV build:y2k-pixel-cherry a Y2K pixel cherry - pair of pixel cherries"
RUN "SETKV build:y2k-pixel-flame a Y2K pixel flame - retro computer-game flame"
RUN "SETKV build:y2k-pixel-star a Y2K pixel star - glowing pixel star with tiny sparkles"
RUN "SETKV build:y2k-error-heart a Y2K error heart - pixel heart with an original ERROR style digital message"
RUN "SETKV build:y2k-broken-screen-heart a Y2K broken screen heart - digital heart appearing cracked or glitched"
RUN "SETKV build:y2k-chrome-butterfly a Y2K chrome butterfly - liquid-metal butterfly"
RUN "SETKV build:y2k-chrome-heart a Y2K chrome heart - puffy liquid-chrome heart"
RUN "SETKV build:y2k-chrome-cross a Y2K chrome cross - rounded metallic cross with sparkle highlights"
RUN "SETKV build:y2k-chrome-angel a Y2K chrome angel - tiny metallic angel figure with reflective highlights"
RUN "SETKV build:y2k-chrome-flame a Y2K chrome flame - liquid-metal flame shape"
RUN "SETKV build:y2k-chrome-tribal a Y2K chrome tribal - sharp symmetrical metallic tribal ornament"
RUN "SETKV build:y2k-chrome-dragon a Y2K chrome dragon - small metallic dragon with exaggerated chrome highlights"
RUN "SETKV build:y2k-chrome-scorpion a Y2K chrome scorpion - liquid-metal scorpion"
RUN "SETKV build:y2k-chrome-spider a Y2K chrome spider - metallic spider with jewel-like body"
RUN "SETKV build:y2k-chrome-dolphin a Y2K chrome dolphin - shiny metallic jumping dolphin with sparkles"
RUN "SETKV build:y2k-chrome-heart-with-wings a Y2K chrome heart with wings - puffy chrome heart with angel wings"
RUN "SETKV build:y2k-barbed-wire-heart a Y2K barbed-wire heart - heart formed from polished barbed wire"
RUN "SETKV build:y2k-tribal-butterfly a Y2K tribal butterfly - butterfly constructed from sharp tribal shapes"
RUN "SETKV build:y2k-tribal-dragon a Y2K tribal dragon - compact dragon formed from flowing tribal curves"
RUN "SETKV build:y2k-tribal-bat a Y2K tribal bat - sharp symmetrical tribal bat"
RUN "SETKV build:y2k-tribal-cross a Y2K tribal cross - sharp decorative cross with neo-tribal extensions"
RUN "SETKV build:y2k-tribal-star a Y2K tribal star - five-point star surrounded by sharp tribal flourishes"
RUN "SETKV build:y2k-tribal-butterfly-heart a Y2K tribal butterfly heart - heart and butterfly merged into one symmetrical tribal emblem"
RUN "SETKV build:y2k-cyber-heart a Y2K cyber heart - futuristic heart formed from sharp digital or tribal lines"
RUN "SETKV build:y2k-cyber-butterfly a Y2K cyber butterfly - butterfly built from thin thorny cyber linework"
RUN "SETKV build:y2k-cyber-star a Y2K cyber star - sharp symmetrical futuristic star glyph"
RUN "SETKV build:y2k-cyber-angel a Y2K cyber angel - angel-wing motif translated into cyber linework"
RUN "SETKV build:y2k-cyber-cross a Y2K cyber cross - futuristic ornamental cross with pointed extensions"
RUN "SETKV build:y2k-cyber-flame a Y2K cyber flame - flame reconstructed as sharp digital tribal linework"
RUN "SETKV build:y2k-cyber-sigil a Y2K cyber sigil - original abstract symmetrical digital sigil"
RUN "SETKV build:y2k-thorn-heart a Y2K thorn heart - heart formed from thin futuristic thorns"
RUN "SETKV build:y2k-digital-thorns a Y2K digital thorns - abstract thorn-like cyber ornament"
RUN "SETKV build:y2k-halo-heart a Y2K halo heart - pink heart floating beneath chrome halo"
RUN "SETKV build:y2k-angel-heart a Y2K angel heart - puffy heart with tiny halo and wings"
RUN "SETKV build:y2k-devil-cherries a Y2K devil cherries - pair of cherries with tiny devil horns and tails"
RUN "SETKV build:y2k-angel-cherries a Y2K angel cherries - cherries with tiny halos and wings"
RUN "SETKV build:y2k-devil-butterfly a Y2K devil butterfly - butterfly with subtle horns and pointed tail elements"
RUN "SETKV build:y2k-angel-butterfly a Y2K angel butterfly - butterfly with halo and sparkle accents"
RUN "SETKV build:y2k-angel-number a Y2K angel number - sparkly original number treatment with halo or wings"
RUN "SETKV build:y2k-baby-angel a Y2K baby angel - cute original cherub-like angel with glitter accents"
RUN "SETKV build:y2k-tiara a Y2K tiara - pink rhinestone princess tiara"
RUN "SETKV build:y2k-rhinestone-cross a Y2K rhinestone cross - cross constructed from jewel-like stones"
RUN "SETKV build:y2k-rhinestone-butterfly a Y2K rhinestone butterfly - butterfly covered in gem-like details"
RUN "SETKV build:y2k-rhinestone-cherries a Y2K rhinestone cherries - jewel-covered cherries with chrome stems"
RUN "SETKV build:y2k-rhinestone-star a Y2K rhinestone star - large gem-covered star"
RUN "SETKV build:y2k-heart-locket a Y2K heart locket - chrome heart locket with pink rhinestones"
RUN "SETKV build:y2k-charm-bracelet a Y2K charm bracelet - tiny chain with heart, star, butterfly and cherry charms"
RUN "SETKV build:y2k-nameplate a Y2K nameplate - original chrome script nameplate aesthetic"
RUN "SETKV build:y2k-princess-lettering a Y2K princess lettering - sparkly pink or chrome decorative word treatment"
RUN "SETKV build:y2k-bubble-lettering a Y2K bubble lettering - puffy airbrushed bubble-letter word treatment"
RUN "SETKV build:y2k-flame-lettering a Y2K flame lettering - original word surrounded by tribal flames"
RUN "SETKV build:y2k-graffiti-heart a Y2K graffiti heart - airbrushed heart with graffiti-style flourishes"
RUN "SETKV build:y2k-airbrush-cloud a Y2K airbrush cloud - dreamy airbrushed cloud with stars and tiny heart"
RUN "SETKV build:y2k-rainbow a Y2K rainbow - metallic pastel rainbow with chrome clouds"
RUN "SETKV build:y2k-magic-wand a Y2K magic wand - rhinestone star wand with sparkly trail"
RUN "SETKV build:y2k-lollipop a Y2K lollipop - heart-shaped translucent pink lollipop"
RUN "SETKV build:y2k-platform-shoe a Y2K platform shoe - chunky platform shoe with chrome or pink details"
RUN "SETKV build:y2k-mini-handbag a Y2K mini handbag - tiny sparkly early-2000s-style handbag with heart charm"
RUN "SETKV build:y2k-sunglasses a Y2K sunglasses - tiny tinted wraparound sunglasses with rhinestone accents"
RUN "SETKV build:y2k-everything a Y2K everything - chrome heart, butterfly wings, tribal flames, rhinestones, sparkles, tiny pixel details - a deliberately ridiculous maximum-Y2K emblem"
Start-Sleep -Seconds 60
RUN "LEAVES Y2K Ideas :: Y2K Butterfly, Y2K Cherries, Y2K Bow, Y2K Tribal Heart, Y2K Tribal Sun, Y2K Lower-Back Tribal, Y2K Flame Heart, Y2K Chrome Star, Y2K Shooting Star, Y2K Dice, Y2K 8-Ball, Y2K Angel Wings, Y2K Devil Heart, Y2K Rhinestone Heart, Y2K Flip Phone, Y2K CD, Y2K Headphones, Y2K Pixel Heart, Y2K Acid Smiley, Y2K Sparkly Lettering, Y2K Butterfly Clip, Y2K Digital Pet, Y2K MP3 Player, Y2K Portable CD Player, Y2K Pager, Y2K CRT Computer, Y2K Computer Mouse, Y2K Instant Messenger Window, Y2K Loading Bar, Y2K Cursor, Y2K Floppy Disk, Y2K Digital Camera, Y2K Camcorder, Y2K Wired Earbuds, Y2K Boombox, Y2K Mini TV, Y2K Game Controller, Y2K Pixel Angel, Y2K Pixel Devil, Y2K Pixel Flower, Y2K Pixel Cherry, Y2K Pixel Flame, Y2K Pixel Star, Y2K Error Heart, Y2K Broken Screen Heart, Y2K Chrome Butterfly, Y2K Chrome Heart, Y2K Chrome Cross, Y2K Chrome Angel, Y2K Chrome Flame, Y2K Chrome Tribal, Y2K Chrome Dragon, Y2K Chrome Scorpion, Y2K Chrome Spider, Y2K Chrome Dolphin, Y2K Chrome Heart With Wings, Y2K Barbed-Wire Heart, Y2K Tribal Butterfly, Y2K Tribal Dragon, Y2K Tribal Bat, Y2K Tribal Cross, Y2K Tribal Star, Y2K Tribal Butterfly Heart, Y2K Cyber Heart, Y2K Cyber Butterfly, Y2K Cyber Star, Y2K Cyber Angel, Y2K Cyber Cross, Y2K Cyber Flame, Y2K Cyber Sigil, Y2K Thorn Heart, Y2K Digital Thorns, Y2K Halo Heart, Y2K Angel Heart, Y2K Devil Cherries, Y2K Angel Cherries, Y2K Devil Butterfly, Y2K Angel Butterfly, Y2K Angel Number, Y2K Baby Angel, Y2K Tiara, Y2K Rhinestone Cross, Y2K Rhinestone Butterfly, Y2K Rhinestone Cherries, Y2K Rhinestone Star, Y2K Heart Locket, Y2K Charm Bracelet, Y2K Nameplate, Y2K Princess Lettering, Y2K Bubble Lettering, Y2K Flame Lettering, Y2K Graffiti Heart, Y2K Airbrush Cloud, Y2K Rainbow, Y2K Magic Wand, Y2K Lollipop, Y2K Platform Shoe, Y2K Mini Handbag, Y2K Sunglasses, Y2K Everything"
Start-Sleep -Seconds 60
RUN "LEAVES Y2K Ideas"
RUN "REDO Y2K Butterfly Clip, Y2K Digital Pet, Y2K MP3 Player, Y2K Portable CD Player, Y2K Pager"
RUN "REDO Y2K CRT Computer, Y2K Computer Mouse, Y2K Instant Messenger Window, Y2K Loading Bar, Y2K Cursor"
RUN "REDO Y2K Floppy Disk, Y2K Digital Camera, Y2K Camcorder, Y2K Wired Earbuds, Y2K Boombox"
RUN "REDO Y2K Mini TV, Y2K Game Controller, Y2K Pixel Angel, Y2K Pixel Devil, Y2K Pixel Flower"
RUN "REDO Y2K Pixel Cherry, Y2K Pixel Flame, Y2K Pixel Star, Y2K Error Heart, Y2K Broken Screen Heart"
RUN "REDO Y2K Chrome Butterfly, Y2K Chrome Heart, Y2K Chrome Cross, Y2K Chrome Angel, Y2K Chrome Flame"
RUN "REDO Y2K Chrome Tribal, Y2K Chrome Dragon, Y2K Chrome Scorpion, Y2K Chrome Spider, Y2K Chrome Dolphin"
RUN "REDO Y2K Chrome Heart With Wings, Y2K Barbed-Wire Heart, Y2K Tribal Butterfly, Y2K Tribal Dragon, Y2K Tribal Bat"
RUN "REDO Y2K Tribal Cross, Y2K Tribal Star, Y2K Tribal Butterfly Heart, Y2K Cyber Heart, Y2K Cyber Butterfly"
RUN "REDO Y2K Cyber Star, Y2K Cyber Angel, Y2K Cyber Cross, Y2K Cyber Flame, Y2K Cyber Sigil"
RUN "REDO Y2K Thorn Heart, Y2K Digital Thorns, Y2K Halo Heart, Y2K Angel Heart, Y2K Devil Cherries"
RUN "REDO Y2K Angel Cherries, Y2K Devil Butterfly, Y2K Angel Butterfly, Y2K Angel Number, Y2K Baby Angel"
RUN "REDO Y2K Tiara, Y2K Rhinestone Cross, Y2K Rhinestone Butterfly, Y2K Rhinestone Cherries, Y2K Rhinestone Star"
RUN "REDO Y2K Heart Locket, Y2K Charm Bracelet, Y2K Nameplate, Y2K Princess Lettering, Y2K Bubble Lettering"
RUN "REDO Y2K Flame Lettering, Y2K Graffiti Heart, Y2K Airbrush Cloud, Y2K Rainbow, Y2K Magic Wand"
RUN "REDO Y2K Lollipop, Y2K Platform Shoe, Y2K Mini Handbag, Y2K Sunglasses, Y2K Everything"
Start-Sleep -Seconds 30
RUN "SHEET Y2K Ideas"
RUN "SHEET Y2K Nostalgia"
RUN "BROWSE"
}
